// RustBro-RustSla
const phenotypeMapping11 = {
  // RUSTY BROWN
"BB ee Rr": "Rusty Brown",
"BB ee Nn Rr": "Rusty Brown",
"BB ee Rr Slsl": "Rusty Brown",
"BB ee Pnpn Rr": "Rusty Brown",
"BB ee pnpn Rr": "Rusty Brown",
"BB ee Pnpn Rr Slsl": "Rusty Brown",
"BB ee pnpn Rr Slsl": "Rusty Brown",
"BB ee Nn Rr Slsl": "Rusty Brown",
"BB ee Nn Pnpn Rr": "Rusty Brown",
"BB ee Nn pnpn Rr": "Rusty Brown",
"BB ee Nn Pnpn Rr Slsl": "Rusty Brown",
"BB ee Nn pnpn Rr Slsl": "Rusty Brown",
"BB Ccg ee Rr": "Rusty Brown",
"BB Ccg ee Nn Rr": "Rusty Brown",
"BB Ccg ee Rr Slsl": "Rusty Brown",
"BB Ccg ee Pnpn Rr": "Rusty Brown",
"BB Ccg ee pnpn Rr": "Rusty Brown",
"BB Ccg ee Pnpn Rr Slsl": "Rusty Brown",
"BB Ccg ee pnpn Rr Slsl": "Rusty Brown",
"BB Ccg ee Nn Rr Slsl": "Rusty Brown",
"BB Ccg ee Nn Pnpn Rr": "Rusty Brown",
"BB Ccg ee Nn pnpn Rr": "Rusty Brown",
"BB Ccg ee Nn Pnpn Rr Slsl": "Rusty Brown",
"BB Ccg ee Nn pnpn Rr Slsl": "Rusty Brown",
"BB Ccm ee Rr": "Rusty Brown",
"BB Ccm ee Nn Rr": "Rusty Brown",
"BB Ccm ee Rr Slsl": "Rusty Brown",
"BB Ccm ee Pnpn Rr": "Rusty Brown",
"BB Ccm ee pnpn Rr Slsl": "Rusty Brown",
"BB Ccm ee Pnpn Rr Slsl": "Rusty Brown",
"BB Ccm ee pnpn Rr": "Rusty Brown",
"BB Ccm ee Nn Rr Slsl": "Rusty Brown",
"BB Ccm ee Nn Pnpn Rr": "Rusty Brown",
"BB Ccm ee Nn pnpn Rr": "Rusty Brown",
"BB Ccm ee Nn Pnpn Rr Slsl": "Rusty Brown",
"BB Ccm ee Nn pnpn Rr Slsl": "Rusty Brown",
"BB Cc ee Rr": "Rusty Brown",
"BB Cc ee Nn Rr": "Rusty Brown",
"BB Cc ee Rr Slsl": "Rusty Brown",
"BB Cc ee Pnpn Rr": "Rusty Brown",
"BB Cc ee pnpn Rr Slsl": "Rusty Brown",
"BB Cc ee Pnpn Rr Slsl": "Rusty Brown",
"BB Cc ee pnpn Rr": "Rusty Brown",
"BB Cc ee Nn Rr Slsl": "Rusty Brown",
"BB Cc ee Nn Pnpn Rr": "Rusty Brown",
"BB Cc ee Nn pnpn Rr": "Rusty Brown",
"BB Cc ee Nn Pnpn Rr Slsl": "Rusty Brown",
"BB Cc ee Nn pnpn Rr Slsl": "Rusty Brown",
"BB cgcg ee Rr": "Rusty Brown",
"BB cgcg ee Nn Rr": "Rusty Brown",
"BB cgcg ee Rr Slsl": "Rusty Brown",
"BB cgcg ee Pnpn Rr": "Rusty Brown",
"BB cgcg ee pnpn Rr": "Rusty Brown",
"BB cgcg ee Pnpn Rr Slsl": "Rusty Brown",
"BB cgcg ee pnpn Rr Slsl": "Rusty Brown",
"BB cgcg ee Nn Rr Slsl": "Rusty Brown",
"BB cgcg ee Nn Pnpn Rr": "Rusty Brown",
"BB cgcg ee Nn pnpn Rr": "Rusty Brown",
"BB cgcg ee Nn Pnpn Rr Slsl": "Rusty Brown",
"BB cgcg ee Nn pnpn Rr Slsl": "Rusty Brown",
"BB cgcm ee Rr": "Rusty Brown",
"BB cgcm ee Nn Rr": "Rusty Brown",
"BB cgcm ee Rr Slsl": "Rusty Brown",
"BB cgcm ee Pnpn Rr": "Rusty Brown",
"BB cgcm ee pnpn Rr": "Rusty Brown",
"BB cgcm ee Pnpn Rr Slsl": "Rusty Brown",
"BB cgcm ee pnpn Rr Slsl": "Rusty Brown",
"BB cgcm ee Nn Rr Slsl": "Rusty Brown",
"BB cgcm ee Nn Pnpn Rr": "Rusty Brown",
"BB cgcm ee Nn pnpn Rr": "Rusty Brown",
"BB cgcm ee Nn Pnpn Rr Slsl": "Rusty Brown",
"BB cgcm ee Nn pnpn Rr Slsl": "Rusty Brown",
"BB cgc ee Rr": "Rusty Brown",
"BB cgc ee Nn Rr": "Rusty Brown",
"BB cgc ee Rr Slsl": "Rusty Brown",
"BB cgc ee Pnpn Rr": "Rusty Brown",
"BB cgc ee pnpn Rr": "Rusty Brown",
"BB cgc ee Pnpn Rr Slsl": "Rusty Brown",
"BB cgc ee pnpn Rr Slsl": "Rusty Brown",
"BB cgc ee Nn Rr Slsl": "Rusty Brown",
"BB cgc ee Nn Pnpn Rr": "Rusty Brown",
"BB cgc ee Nn pnpn Rr": "Rusty Brown",
"BB cgc ee Nn Pnpn Rr Slsl": "Rusty Brown",
"BB cgc ee Nn pnpn Rr Slsl": "Rusty Brown",
// FEMALES
"BB e- Rr": "Rusty Brown",
"BB e-  Rr Slsl": "Rusty Brown",
"BB e- Pnpn Rr": "Rusty Brown",
"BB e- pnpn Rr": "Rusty Brown",
"BB e- Pnpn Rr Slsl": "Rusty Brown",
"BB e- pnpn Rr Slsl": "Rusty Brown",
"BB Ccg e- Rr": "Rusty Brown",
"BB Ccg e- Rr Slsl": "Rusty Brown",
"BB Ccg e- Pnpn Rr": "Rusty Brown",
"BB Ccg e- pnpn Rr": "Rusty Brown",
"BB Ccg e- Pnpn Rr Slsl": "Rusty Brown",
"BB Ccg e- pnpn Rr Slsl": "Rusty Brown",
"BB Ccm e- Rr": "Rusty Brown",
"BB Ccm e- Rr Slsl": "Rusty Brown",
"BB Ccm e- Pnpn Rr": "Rusty Brown",
"BB Ccm e- pnpn Rr Slsl": "Rusty Brown",
"BB Ccm e- Pnpn Rr Slsl": "Rusty Brown",
"BB Ccm e- pnpn Rr": "Rusty Brown",
"BB Cc e- Rr": "Rusty Brown",
"BB Cc e- Rr Slsl": "Rusty Brown",
"BB Cc e- Pnpn Rr": "Rusty Brown",
"BB Cc e- pnpn Rr": "Rusty Brown",
"BB Cc e- Pnpn Rr Slsl": "Rusty Brown",
"BB Cc e- pnpn Rr Slsl": "Rusty Brown",
"BB cgcg e- Rr": "Rusty Brown",
"BB cgcg e- Rr Slsl": "Rusty Brown",
"BB cgcg e- Pnpn Rr": "Rusty Brown",
"BB cgcg e- pnpn Rr": "Rusty Brown",
"BB cgcg e- Pnpn Rr Slsl": "Rusty Brown",
"BB cgcg e- pnpn Rr Slsl": "Rusty Brown",
"BB cgcm e- Rr": "Rusty Brown",
"BB cgcm e- Rr Slsl": "Rusty Brown",
"BB cgcm e- Pnpn Rr": "Rusty Brown",
"BB cgcm e- pnpn Rr": "Rusty Brown",
"BB cgcm e- Pnpn Rr Slsl": "Rusty Brown",
"BB cgcm e- pnpn Rr Slsl": "Rusty Brown",
"BB cgc e- Rr": "Rusty Brown",
"BB cgc e- Rr Slsl": "Rusty Brown",
"BB cgc e- Pnpn Rr": "Rusty Brown",
"BB cgc e- pnpn Rr": "Rusty Brown",
"BB cgc e- Pnpn Rr Slsl": "Rusty Brown",
"BB cgc e- pnpn Rr Slsl": "Rusty Brown",
// Bb RUSTY BROWN
"Bb ee Rr": "Rusty Brown",
"Bb ee Nn Rr": "Rusty Brown",
"Bb ee Rr Slsl": "Rusty Brown",
"Bb ee Pnpn Rr": "Rusty Brown",
"Bb ee pnpn Rr": "Rusty Brown",
"Bb ee Pnpn Rr Slsl": "Rusty Brown",
"Bb ee pnpn Rr Slsl": "Rusty Brown",
"Bb ee Nn Rr Slsl": "Rusty Brown",
"Bb ee Nn Pnpn Rr": "Rusty Brown",
"Bb ee Nn pnpn Rr": "Rusty Brown",
"Bb ee Nn Pnpn Rr Slsl": "Rusty Brown",
"Bb ee Nn pnpn Rr Slsl": "Rusty Brown",
"Bb Ccg ee Rr": "Rusty Brown",
"Bb Ccg ee Nn Rr": "Rusty Brown",
"Bb Ccg ee Rr Slsl": "Rusty Brown",
"Bb Ccg ee Pnpn Rr": "Rusty Brown",
"Bb Ccg ee pnpn Rr": "Rusty Brown",
"Bb Ccg ee Pnpn Rr Slsl": "Rusty Brown",
"Bb Ccg ee pnpn Rr Slsl": "Rusty Brown",
"Bb Ccg ee Nn Rr Slsl": "Rusty Brown",
"Bb Ccg ee Nn Pnpn Rr": "Rusty Brown",
"Bb Ccg ee Nn pnpn Rr": "Rusty Brown",
"Bb Ccg ee Nn Pnpn Rr Slsl": "Rusty Brown",
"Bb Ccg ee Nn pnpn Rr Slsl": "Rusty Brown",
"Bb Ccm ee Rr": "Rusty Brown",
"Bb Ccm ee Nn Rr": "Rusty Brown",
"Bb Ccm ee Rr Slsl": "Rusty Brown",
"Bb Ccm ee Pnpn Rr": "Rusty Brown",
"Bb Ccm ee pnpn Rr Slsl": "Rusty Brown",
"Bb Ccm ee Pnpn Rr Slsl": "Rusty Brown",
"Bb Ccm ee pnpn Rr": "Rusty Brown",
"Bb Ccm ee Nn Rr Slsl": "Rusty Brown",
"Bb Ccm ee Nn Pnpn Rr": "Rusty Brown",
"Bb Ccm ee Nn pnpn Rr": "Rusty Brown",
"Bb Ccm ee Nn Pnpn Rr Slsl": "Rusty Brown",
"Bb Ccm ee Nn pnpn Rr Slsl": "Rusty Brown",
"Bb Cc ee Rr": "Rusty Brown",
"Bb Cc ee Nn Rr": "Rusty Brown",
"Bb Cc ee Rr Slsl": "Rusty Brown",
"Bb Cc ee Pnpn Rr": "Rusty Brown",
"Bb Cc ee pnpn Rr Slsl": "Rusty Brown",
"Bb Cc ee Pnpn Rr Slsl": "Rusty Brown",
"Bb Cc ee pnpn Rr": "Rusty Brown",
"Bb Cc ee Nn Rr Slsl": "Rusty Brown",
"Bb Cc ee Nn Pnpn Rr": "Rusty Brown",
"Bb Cc ee Nn pnpn Rr": "Rusty Brown",
"Bb Cc ee Nn Pnpn Rr Slsl": "Rusty Brown",
"Bb Cc ee Nn pnpn Rr Slsl": "Rusty Brown",
"Bb cgcg ee Rr": "Rusty Brown",
"Bb cgcg ee Nn Rr": "Rusty Brown",
"Bb cgcg ee Rr Slsl": "Rusty Brown",
"Bb cgcg ee Pnpn Rr": "Rusty Brown",
"Bb cgcg ee pnpn Rr": "Rusty Brown",
"Bb cgcg ee Pnpn Rr Slsl": "Rusty Brown",
"Bb cgcg ee pnpn Rr Slsl": "Rusty Brown",
"Bb cgcg ee Nn Rr Slsl": "Rusty Brown",
"Bb cgcg ee Nn Pnpn Rr": "Rusty Brown",
"Bb cgcg ee Nn pnpn Rr": "Rusty Brown",
"Bb cgcg ee Nn Pnpn Rr Slsl": "Rusty Brown",
"Bb cgcg ee Nn pnpn Rr Slsl": "Rusty Brown",
"Bb cgcm ee Rr": "Rusty Brown",
"Bb cgcm ee Nn Rr": "Rusty Brown",
"Bb cgcm ee Rr Slsl": "Rusty Brown",
"Bb cgcm ee Pnpn Rr": "Rusty Brown",
"Bb cgcm ee pnpn Rr": "Rusty Brown",
"Bb cgcm ee Pnpn Rr Slsl": "Rusty Brown",
"Bb cgcm ee pnpn Rr Slsl": "Rusty Brown",
"Bb cgcm ee Nn Rr Slsl": "Rusty Brown",
"Bb cgcm ee Nn Pnpn Rr": "Rusty Brown",
"Bb cgcm ee Nn pnpn Rr": "Rusty Brown",
"Bb cgcm ee Nn Pnpn Rr Slsl": "Rusty Brown",
"Bb cgcm ee Nn pnpn Rr Slsl": "Rusty Brown",
"Bb cgc ee Rr": "Rusty Brown",
"Bb cgc ee Nn Rr": "Rusty Brown",
"Bb cgc ee Rr Slsl": "Rusty Brown",
"Bb cgc ee Pnpn Rr": "Rusty Brown",
"Bb cgc ee pnpn Rr": "Rusty Brown",
"Bb cgc ee Pnpn Rr Slsl": "Rusty Brown",
"Bb cgc ee pnpn Rr Slsl": "Rusty Brown",
"Bb cgc ee Nn Rr Slsl": "Rusty Brown",
"Bb cgc ee Nn Pnpn Rr": "Rusty Brown",
"Bb cgc ee Nn pnpn Rr": "Rusty Brown",
"Bb cgc ee Nn Pnpn Rr Slsl": "Rusty Brown",
"Bb cgc ee Nn pnpn Rr Slsl": "Rusty Brown",
 // FEMALES
"Bb e- Rr": "Rusty Brown",
"Bb e- Rr Slsl": "Rusty Brown",
"Bb e- Pnpn Rr": "Rusty Brown",
"Bb e- pnpn Rr": "Rusty Brown",
"Bb e- Pnpn Rr Slsl": "Rusty Brown",
"Bb e- pnpn Rr Slsl": "Rusty Brown",
"Bb Ccg e- Rr": "Rusty Brown",
"Bb Ccg e- Rr Slsl": "Rusty Brown",
"Bb Ccg e- Pnpn Rr": "Rusty Brown",
"Bb Ccg e- pnpn Rr": "Rusty Brown",
"Bb Ccg e- Pnpn Rr Slsl": "Rusty Brown",
"Bb Ccg e- pnpn Rr Slsl": "Rusty Brown",
"Bb Ccm e- Rr": "Rusty Brown",
"Bb Ccm e- Rr Slsl": "Rusty Brown",
"Bb Ccm e- Pnpn Rr": "Rusty Brown",
"Bb Ccm e- pnpn Rr Slsl": "Rusty Brown",
"Bb Ccm e- Pnpn Rr Slsl": "Rusty Brown",
"Bb Ccm e- pnpn Rr": "Rusty Brown",
"Bb Cc e- Rr": "Rusty Brown",
"Bb Cc e- Rr Slsl": "Rusty Brown",
"Bb Cc e- Pnpn Rr": "Rusty Brown",
"Bb Cc e- pnpn Rr": "Rusty Brown",
"Bb Cc e- Pnpn Rr Slsl": "Rusty Brown",
"Bb Cc e- pnpn Rr Slsl": "Rusty Brown",
"Bb cgcg e- Rr": "Rusty Brown",
"Bb cgcg e- Rr Slsl": "Rusty Brown",
"Bb cgcg e- Pnpn Rr": "Rusty Brown",
"Bb cgcg e- pnpn Rr": "Rusty Brown",
"Bb cgcg e- Pnpn Rr Slsl": "Rusty Brown",
"Bb cgcg e- pnpn Rr Slsl": "Rusty Brown",
"Bb cgcm e- Rr": "Rusty Brown",
"Bb cgcm e- Rr Slsl": "Rusty Brown",
"Bb cgcm e- Pnpn Rr": "Rusty Brown",
"Bb cgcm e- pnpn Rr": "Rusty Brown",
"Bb cgcm e- Pnpn Rr Slsl": "Rusty Brown",
"Bb cgcm e- pnpn Rr Slsl": "Rusty Brown",
"Bb cgc e- Rr": "Rusty Brown",
"Bb cgc e- Rr Slsl": "Rusty Brown",
"Bb cgc e- Pnpn Rr": "Rusty Brown",
"Bb cgc e- pnpn Rr": "Rusty Brown",
"Bb cgc e- Pnpn Rr Slsl": "Rusty Brown",
"Bb cgc e- pnpn Rr Slsl": "Rusty Brown",
// Bb1 RUSTY BROWN
"Bb1 ee Rr": "Rusty Brown",
"Bb1 ee Nn Rr": "Rusty Brown",
"Bb1 ee Rr Slsl": "Rusty Brown",
"Bb1 ee Pnpn Rr": "Rusty Brown",
"Bb1 ee pnpn Rr": "Rusty Brown",
"Bb1 ee Pnpn Rr Slsl": "Rusty Brown",
"Bb1 ee pnpn Rr Slsl": "Rusty Brown",
"Bb1 ee Nn Rr Slsl": "Rusty Brown",
"Bb1 ee Nn Pnpn Rr": "Rusty Brown",
"Bb1 ee Nn pnpn Rr": "Rusty Brown",
"Bb1 ee Nn Pnpn Rr Slsl": "Rusty Brown",
"Bb1 ee Nn pnpn Rr Slsl": "Rusty Brown",
"Bb1 Ccm ee Rr": "Rusty Brown",
"Bb1 Ccm ee Nn Rr": "Rusty Brown",
"Bb1 Ccm ee Rr Slsl": "Rusty Brown",
"Bb1 Ccm ee Pnpn Rr": "Rusty Brown",
"Bb1 Ccm ee pnpn Rr Slsl": "Rusty Brown",
"Bb1 Ccm ee Pnpn Rr Slsl": "Rusty Brown",
"Bb1 Ccm ee pnpn Rr": "Rusty Brown",
"Bb1 Ccm ee Nn Rr Slsl": "Rusty Brown",
"Bb1 Ccm ee Nn Pnpn Rr": "Rusty Brown",
"Bb1 Ccm ee Nn pnpn Rr": "Rusty Brown",
"Bb1 Ccm ee Nn Pnpn Rr Slsl": "Rusty Brown",
"Bb1 Ccm ee Nn pnpn Rr Slsl": "Rusty Brown",
"Bb1 Cc ee Rr": "Rusty Brown",
"Bb1 Cc ee Nn Rr": "Rusty Brown",
"Bb1 Cc ee Rr Slsl": "Rusty Brown",
"Bb1 Cc ee Pnpn Rr": "Rusty Brown",
"Bb1 Cc ee pnpn Rr Slsl": "Rusty Brown",
"Bb1 Cc ee Pnpn Rr Slsl": "Rusty Brown",
"Bb1 Cc ee pnpn Rr": "Rusty Brown",
"Bb1 Cc ee Nn Rr Slsl": "Rusty Brown",
"Bb1 Cc ee Nn Pnpn Rr": "Rusty Brown",
"Bb1 Cc ee Nn pnpn Rr": "Rusty Brown",
"Bb1 Cc ee Nn Pnpn Rr Slsl": "Rusty Brown",
"Bb1 Cc ee Nn pnpn Rr Slsl": "Rusty Brown",
"Bb1 e- Rr": "Rusty Brown",
"Bb1 e-  Rr Slsl": "Rusty Brown",
"Bb1 e- Pnpn Rr": "Rusty Brown",
"Bb1 e- pnpn Rr": "Rusty Brown",
"Bb1 e- Pnpn Rr Slsl": "Rusty Brown",
"Bb1 e- pnpn Rr Slsl": "Rusty Brown",
"Bb1 Ccm e- Rr": "Rusty Brown",
"Bb1 Ccm e- Rr Slsl": "Rusty Brown",
"Bb1 Ccm e- Pnpn Rr": "Rusty Brown",
"Bb1 Ccm e- pnpn Rr Slsl": "Rusty Brown",
"Bb1 Ccm e- Pnpn Rr Slsl": "Rusty Brown",
"Bb1 Ccm e- pnpn Rr": "Rusty Brown",
"Bb1 Cc e- Rr": "Rusty Brown",
"Bb1 Cc e- Rr Slsl": "Rusty Brown",
"Bb1 Cc e- Pnpn Rr": "Rusty Brown",
"Bb1 Cc e- pnpn Rr": "Rusty Brown",
"Bb1 Cc e- Pnpn Rr Slsl": "Rusty Brown",
"Bb1 Cc e- pnpn Rr Slsl": "Rusty Brown",

// RUSTY BROWN SLATE
"BB Dd ee Rr": "Rusty Brown Slate",
"BB Dd ee Nn Rr": "Rusty Brown Slate",
"BB Dd ee Rr Slsl": "Rusty Brown Slate",
"BB Dd ee Pnpn Rr": "Rusty Brown Slate",
"BB Dd ee pnpn Rr": "Rusty Brown Slate",
"BB Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"BB Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"BB Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"BB Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"BB Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"BB Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"BB Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
"BB Ccg Dd ee Rr": "Rusty Brown Slate",
"BB Ccg Dd ee Nn Rr": "Rusty Brown Slate",
"BB Ccg Dd ee Rr Slsl": "Rusty Brown Slate",
"BB Ccg Dd ee Pnpn Rr": "Rusty Brown Slate",
"BB Ccg Dd ee pnpn Rr": "Rusty Brown Slate",
"BB Ccg Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"BB Ccg Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"BB Ccg Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"BB Ccg Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"BB Ccg Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"BB Ccg Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"BB Ccg Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
"BB Ccm Dd ee Rr": "Rusty Brown Slate",
"BB Ccm Dd ee Nn Rr": "Rusty Brown Slate",
"BB Ccm Dd ee Rr Slsl": "Rusty Brown Slate",
"BB Ccm Dd ee Pnpn Rr": "Rusty Brown Slate",
"BB Ccm Dd ee pnpn Rr": "Rusty Brown Slate",
"BB Ccm Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"BB Ccm Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"BB Ccm Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"BB Ccm Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"BB Ccm Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"BB Ccm Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"BB Ccm Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
"BB Cc Dd ee Rr": "Rusty Brown Slate",
"BB Cc Dd ee Nn Rr": "Rusty Brown Slate",
"BB Cc Dd ee Rr Slsl": "Rusty Brown Slate",
"BB Cc Dd ee Pnpn Rr": "Rusty Brown Slate",
"BB Cc Dd ee pnpn Rr": "Rusty Brown Slate",
"BB Cc Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"BB Cc Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"BB Cc Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"BB Cc Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"BB Cc Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"BB Cc Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"BB Cc Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgcg Dd ee Rr": "Rusty Brown Slate",
"BB cgcg Dd ee Nn Rr": "Rusty Brown Slate",
"BB cgcg Dd ee Rr Slsl": "Rusty Brown Slate",
"BB cgcg Dd ee Pnpn Rr": "Rusty Brown Slate",
"BB cgcg Dd ee pnpn Rr": "Rusty Brown Slate",
"BB cgcg Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"BB cgcg Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"BB cgcg Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"BB cgcg Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgcg Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgcg Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgcg Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgcm Dd ee Rr": "Rusty Brown Slate",
"BB cgcm Dd ee Nn Rr": "Rusty Brown Slate",
"BB cgcm Dd ee Rr Slsl": "Rusty Brown Slate",
"BB cgcm Dd ee Pnpn Rr": "Rusty Brown Slate",
"BB cgcm Dd ee pnpn Rr": "Rusty Brown Slate",
"BB cgcm Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"BB cgcm Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"BB cgcm Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"BB cgcm Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgcm Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgcm Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgcm Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgc Dd ee Rr": "Rusty Brown Slate",
"BB cgc Dd ee Nn Rr": "Rusty Brown Slate",
"BB cgc Dd ee Rr Slsl": "Rusty Brown Slate",
"BB cgc Dd ee Pnpn Rr": "Rusty Brown Slate",
"BB cgc Dd ee pnpn Rr": "Rusty Brown Slate",
"BB cgc Dd ee ee Nn Rr": "Rusty Brown Slate",
"BB cgc Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"BB cgc Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"BB cgc Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"BB cgc Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgc Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgc Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgc Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
// Bb
"Bb Dd ee Rr": "Rusty Brown Slate",
"Bb Dd ee Nn Rr": "Rusty Brown Slate",
"Bb Dd ee Rr Slsl": "Rusty Brown Slate",
"Bb Dd ee Pnpn Rr": "Rusty Brown Slate",
"Bb Dd ee pnpn Rr": "Rusty Brown Slate",
"Bb Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"Bb Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"Bb Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"Bb Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Ccg Dd ee Rr": "Rusty Brown Slate",
"Bb Ccg Dd ee Nn Rr": "Rusty Brown Slate",
"Bb Ccg Dd ee Rr Slsl": "Rusty Brown Slate",
"Bb Ccg Dd ee Pnpn Rr": "Rusty Brown Slate",
"Bb Ccg Dd ee pnpn Rr": "Rusty Brown Slate",
"Bb Ccg Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"Bb Ccg Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"Bb Ccg Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"Bb Ccg Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Ccg Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Ccg Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Ccg Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Ccm Dd ee Rr": "Rusty Brown Slate",
"Bb Ccm Dd ee Nn Rr": "Rusty Brown Slate",
"Bb Ccm Dd ee Rr Slsl": "Rusty Brown Slate",
"Bb Ccm Dd ee Pnpn Rr": "Rusty Brown Slate",
"Bb Ccm Dd ee pnpn Rr": "Rusty Brown Slate",
"Bb Ccm Dd ee  Nn Rr": "Rusty Brown Slate",
"Bb Ccm Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"Bb Ccm Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"Bb Ccm Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"Bb Ccm Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Ccm Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Ccm Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Ccm Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Cc Dd ee Rr": "Rusty Brown Slate",
"Bb Cc Dd ee Nn Rr": "Rusty Brown Slate",
"Bb Cc Dd ee Rr Slsl": "Rusty Brown Slate",
"Bb Cc Dd ee Pnpn Rr": "Rusty Brown Slate",
"Bb Cc Dd ee pnpn Rr": "Rusty Brown Slate",
"Bb Cc Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"Bb Cc Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"Bb Cc Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"Bb Cc Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Cc Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Cc Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Cc Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgcg Dd ee Rr": "Rusty Brown Slate",
"Bb cgcg Dd ee Nn Rr": "Rusty Brown Slate",
"Bb cgcg Dd ee Rr Slsl": "Rusty Brown Slate",
"Bb cgcg Dd ee Pnpn Rr": "Rusty Brown Slate",
"Bb cgcg Dd ee pnpn Rr": "Rusty Brown Slate",
"Bb cgcg Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"Bb cgcg Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"Bb cgcg Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"Bb cgcg Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgcg Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgcg Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgcg Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgcm Dd ee Rr": "Rusty Brown Slate",
"Bb cgcm Dd ee Nn Rr": "Rusty Brown Slate",
"Bb cgcm Dd ee Rr Slsl": "Rusty Brown Slate",
"Bb cgcm Dd ee Pnpn Rr": "Rusty Brown Slate",
"Bb cgcm Dd ee pnpn Rr": "Rusty Brown Slate",
"Bb cgcm Dd ee ee Nn Rr": "Rusty Brown Slate",
"Bb cgcm Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"Bb cgcm Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"Bb cgcm Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"Bb cgcm Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgcm Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgcm Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgcm Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgc Dd ee Rr": "Rusty Brown Slate",
"Bb cgc Dd ee Nn Rr": "Rusty Brown Slate",
"Bb cgc Dd ee Rr Slsl": "Rusty Brown Slate",
"Bb cgc Dd ee Pnpn Rr": "Rusty Brown Slate",
"Bb cgc Dd ee pnpn Rr": "Rusty Brown Slate",
"Bb cgc Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"Bb cgc Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"Bb cgc Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"Bb cgc Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgc Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgc Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgc Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
// Bb1
"Bb1 Dd ee Rr": "Rusty Brown Slate",
"Bb1 Dd ee Nn Rr": "Rusty Brown Slate",
"Bb1 Dd ee Rr Slsl": "Rusty Brown Slate",
"Bb1 Dd ee Pnpn Rr": "Rusty Brown Slate",
"Bb1 Dd ee pnpn Rr": "Rusty Brown Slate",
"Bb1 Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"Bb1 Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"Bb1 Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"Bb1 Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Ccm Dd ee Rr": "Rusty Brown Slate",
"Bb1 Ccm Dd ee Nn Rr": "Rusty Brown Slate",
"Bb1 Ccm Dd ee Rr Slsl": "Rusty Brown Slate",
"Bb1 Ccm Dd ee Pnpn Rr": "Rusty Brown Slate",
"Bb1 Ccm Dd ee pnpn Rr": "Rusty Brown Slate",
"Bb1 Ccm Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"Bb1 Ccm Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"Bb1 Ccm Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"Bb1 Ccm Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Ccm Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Ccm Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Ccm Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Cc Dd ee Rr": "Rusty Brown Slate",
"Bb1 Cc Dd ee Nn Rr": "Rusty Brown Slate",
"Bb1 Cc Dd ee Rr Slsl": "Rusty Brown Slate",
"Bb1 Cc Dd ee Pnpn Rr": "Rusty Brown Slate",
"Bb1 Cc Dd ee pnpn Rr": "Rusty Brown Slate",
"Bb1 Cc Dd ee Nn Rr Slsl": "Rusty Brown Slate",
"Bb1 Cc Dd ee Nn Pnpn Rr": "Rusty Brown Slate",
"Bb1 Cc Dd ee Nn pnpn Rr": "Rusty Brown Slate",
"Bb1 Cc Dd ee Nn Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Cc Dd ee Nn pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Cc Dd ee Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Cc Dd ee pnpn Rr Slsl": "Rusty Brown Slate",
// RUSTY BROWN SLATE FEMALES
"BB Dd e- Rr": "Rusty Brown Slate",
"BB Dd e- Rr Slsl": "Rusty Brown Slate",
"BB Dd e- Pnpn Rr": "Rusty Brown Slate",
"BB Dd e- pnpn Rr": "Rusty Brown Slate",
"BB Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"BB Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
"BB Ccg Dd e- Rr": "Rusty Brown Slate",
"BB Ccg Dd e- Rr Slsl": "Rusty Brown Slate",
"BB Ccg Dd e- Pnpn Rr": "Rusty Brown Slate",
"BB Ccg Dd e- pnpn Rr": "Rusty Brown Slate",
"BB Ccg Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"BB Ccg Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
"BB Ccm Dd e- Rr": "Rusty Brown Slate",
"BB Ccm Dd e- Rr Slsl": "Rusty Brown Slate",
"BB Ccm Dd e- Pnpn Rr": "Rusty Brown Slate",
"BB Ccm Dd e- pnpn Rr": "Rusty Brown Slate",
"BB Ccm Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"BB Ccm Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
"BB Cc Dd e- Rr": "Rusty Brown Slate",
"BB Cc Dd e- Rr Slsl": "Rusty Brown Slate",
"BB Cc Dd e- Pnpn Rr": "Rusty Brown Slate",
"BB Cc Dd e- pnpn Rr": "Rusty Brown Slate",
"BB Cc Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"BB Cc Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgcg Dd e- Rr": "Rusty Brown Slate",
"BB cgcg Dd e- Rr Slsl": "Rusty Brown Slate",
"BB cgcg Dd e- Pnpn Rr": "Rusty Brown Slate",
"BB cgcg Dd e- pnpn Rr": "Rusty Brown Slate",
"BB cgcg Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgcg Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgcm Dd e- Rr": "Rusty Brown Slate",
"BB cgcm Dd e- Rr Slsl": "Rusty Brown Slate",
"BB cgcm Dd e- Pnpn Rr": "Rusty Brown Slate",
"BB cgcm Dd e- pnpn Rr": "Rusty Brown Slate",
"BB cgcm Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgcm Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgc Dd e- Rr": "Rusty Brown Slate",
"BB cgc Dd e- Rr Slsl": "Rusty Brown Slate",
"BB cgc Dd e- Pnpn Rr": "Rusty Brown Slate",
"BB cgc Dd e- pnpn Rr": "Rusty Brown Slate",
"BB cgc Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"BB cgc Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
// Bb
"Bb Dd e- Rr": "Rusty Brown Slate",
"Bb Dd e- Rr Slsl": "Rusty Brown Slate",
"Bb Dd e- Pnpn Rr": "Rusty Brown Slate",
"Bb Dd e- pnpn Rr": "Rusty Brown Slate",
"Bb Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Ccg Dd e- Rr": "Rusty Brown Slate",
"Bb Ccg Dd e- Rr Slsl": "Rusty Brown Slate",
"Bb Ccg Dd e- Pnpn Rr": "Rusty Brown Slate",
"Bb Ccg Dd e- pnpn Rr": "Rusty Brown Slate",
"Bb Ccg Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Ccg Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Ccm Dd e- Rr": "Rusty Brown Slate",
"Bb Ccm Dd e- Rr Slsl": "Rusty Brown Slate",
"Bb Ccm Dd e- Pnpn Rr": "Rusty Brown Slate",
"Bb Ccm Dd e- pnpn Rr": "Rusty Brown Slate",
"Bb Ccm Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Ccm Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Cc Dd e- Rr": "Rusty Brown Slate",
"Bb Cc Dd e- Rr Slsl": "Rusty Brown Slate",
"Bb Cc Dd e- Pnpn Rr": "Rusty Brown Slate",
"Bb Cc Dd e- pnpn Rr": "Rusty Brown Slate",
"Bb Cc Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb Cc Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgcg Dd e- Rr": "Rusty Brown Slate",
"Bb cgcg Dd e- Rr Slsl": "Rusty Brown Slate",
"Bb cgcg Dd e- Pnpn Rr": "Rusty Brown Slate",
"Bb cgcg Dd e- pnpn Rr": "Rusty Brown Slate",
"Bb cgcg Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgcg Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgcm Dd e- Rr": "Rusty Brown Slate",
"Bb cgcm Dd e- Rr Slsl": "Rusty Brown Slate",
"Bb cgcm Dd e- Pnpn Rr": "Rusty Brown Slate",
"Bb cgcm Dd e- pnpn Rr": "Rusty Brown Slate",
"Bb cgcm Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgcm Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgc Dd e- Rr": "Rusty Brown Slate",
"Bb cgc Dd e- Rr Slsl": "Rusty Brown Slate",
"Bb cgc Dd e- Pnpn Rr": "Rusty Brown Slate",
"Bb cgc Dd e- pnpn Rr": "Rusty Brown Slate",
"Bb cgc Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb cgc Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
// Bb1
"Bb1 Dd e- Rr": "Rusty Brown Slate",
"Bb1 Dd e- Rr Slsl": "Rusty Brown Slate",
"Bb1 Dd e- Pnpn Rr": "Rusty Brown Slate",
"Bb1 Dd e- pnpn Rr": "Rusty Brown Slate",
"Bb1 Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Ccm Dd e- Rr": "Rusty Brown Slate",
"Bb1 Ccm Dd e- Rr Slsl": "Rusty Brown Slate",
"Bb1 Ccm Dd e- Pnpn Rr": "Rusty Brown Slate",
"Bb1 Ccm Dd e- pnpn Rr": "Rusty Brown Slate",
"Bb1 Ccm Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Ccm Dd e- pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Cc Dd e- Rr": "Rusty Brown Slate",
"Bb1 Cc Dd e- Rr Slsl": "Rusty Brown Slate",
"Bb1 Cc Dd e- Pnpn Rr": "Rusty Brown Slate",
"Bb1 Cc Dd e- pnpn Rr": "Rusty Brown Slate",
"Bb1 Cc Dd e- Pnpn Rr Slsl": "Rusty Brown Slate",
"Bb1 Cc Dd e- pnpn Rr Slsl": "Rusty Brown Slate",

// RUSTY DAPPLE
"Bb cgc nn Rr": "Rusty Dapple",
"Bb cgc Ee nn Rr": "Rusty Dapple",
"Bb cgc nn Rr Slsl": "Rusty Dapple",
"Bb cgc nn Pnpn Rr Slsl": "Rusty Dapple",
"Bb cgc nn pnpn Rr Slsl": "Rusty Dapple",
"Bb cgc Ee nn Rr Slsl": "Rusty Dapple",
"Bb cgc Ee nn Pnpn Rr Slsl": "Rusty Dapple",
"Bb cgc n- Rr": "Rusty Dapple",
"Bb cgc n- Pnpn Rr": "Rusty Dapple",
"Bb cgc n- pnpn Rr": "Rusty Dapple",
"Bb cgc n- Rr Slsl": "Rusty Dapple",
"Bb cgc n- Pnpn Rr Slsl": "Rusty Dapple",
"Bb cgc n- pnpn Rr Slsl": "Rusty Dapple",
// RUSTY DAPPLE SLATE
"Bb cgc Dd nn Rr": "Rusty Dapple Slate",
"Bb cgc Dd Ee nn Rr": "Rusty Dapple Slate",
"Bb cgc Dd nn Rr Slsl": "Rusty Dapple Slate",
"Bb cgc Dd nn Pnpn Rr Slsl": "Rusty Dapple Slate",
"Bb cgc Dd nn pnpn Rr Slsl": "Rusty Dapple Slate",
"Bb cgc Dd Ee nn Rr Slsl": "Rusty Dapple Slate",
"Bb cgc Dd Ee nn Pnpn Rr Slsl": "Rusty Dapple Slate",
"Bb cgc Dd n- Rr": "Rusty Dapple Slate",
"Bb cgc Dd n- Pnpn Rr": "Rusty Dapple Slate",
"Bb cgc Dd n- pnpn Rr": "Rusty Dapple Slate",
"Bb cgc Dd n- Rr Slsl": "Rusty Dapple Slate",
"Bb cgc Dd n- Pnpn Rr Slsl": "Rusty Dapple Slate",
"Bb cgc Dd n- pnpn Rr Slsl": "Rusty Dapple Slate",
//  BB RUSTY LAVENDER
"BB DD Rr": "Rusty Lavender",
"BB DD Ee Rr": "Rusty Lavender",
"BB DD Nn Rr": "Rusty Lavender",
"BB DD Rr Slsl": "Rusty Lavender",
"BB DD Pnpn Rr Slsl": "Rusty Lavender",
"BB DD pnpn Rr Slsl": "Rusty Lavender",
"BB DD Ee Nn Rr Slsl": "Rusty Lavender",
"BB DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"BB DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
"BB Ccg DD Rr": "Rusty Lavender",
"BB Ccg DD Ee Rr": "Rusty Lavender",
"BB Ccg DD Nn Rr": "Rusty Lavender",
"BB Ccg DD Rr Slsl": "Rusty Lavender",
"BB Ccg DD Pnpn Rr Slsl": "Rusty Lavender",
"BB Ccg DD pnpn Rr Slsl": "Rusty Lavender",
"BB Ccg DD Ee Nn Rr Slsl": "Rusty Lavender",
"BB Ccg DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"BB Ccg DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
"BB Ccm DD Rr": "Rusty Lavender",
"BB Ccm DD Ee Rr": "Rusty Lavender",
"BB Ccm DD Nn Rr": "Rusty Lavender",
"BB Ccm DD Slsl Rr": "Rusty Lavender",
"BB Ccm DD Pnpn Rr Slsl": "Rusty Lavender",
"BB Ccm DD pnpn Rr Slsl": "Rusty Lavender",
"BB Ccm DD Ee Nn Rr Slsl": "Rusty Lavender",
"BB Ccm DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"BB Ccm DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
"BB Cc DD Rr": "Rusty Lavender",
"BB Cc DD Ee Rr": "Rusty Lavender",
"BB Cc DD Nn Rr": "Rusty Lavender",
"BB Cc DD Rr Slsl": "Rusty Lavender",
"BB Cc DD Pnpn Rr Slsl": "Rusty Lavender",
"BB Cc DD pnpn Rr Slsl": "Rusty Lavender",
"BB Cc DD Ee Nn Rr Slsl": "Rusty Lavender",
"BB Cc DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"BB Cc DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
"BB cgcg DD Rr": "Rusty Lavender",
"BB cgcg DD Ee Rr": "Rusty Lavender",
"BB cgcg DD Nn Rr": "Rusty Lavender",
"BB cgcg DD Rr Slsl": "Rusty Lavender",
"BB cgcg DD Pnpn Rr Slsl": "Rusty Lavender",
"BB cgcg DD pnpn Rr Slsl": "Rusty Lavender",
"BB cgcg DD Ee Nn Rr Slsl": "Rusty Lavender",
"BB cgcg DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"BB cgcg DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
"BB cgcm DD Rr": "Rusty Lavender",
"BB cgcm DD Ee Rr": "Rusty Lavender",
"BB cgcm DD Nn Rr": "Rusty Lavender",
"BB cgcm DD Rr Slsl": "Rusty Lavender",
"BB cgcm DD Pnpn Rr Slsl": "Rusty Lavender",
"BB cgcm DD pnpn Rr Slsl": "Rusty Lavender",
"BB cgcm DD Ee Nn Rr Slsl": "Rusty Lavender",
"BB cgcm DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"BB cgcm DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
"BB cgc DD Rr": "Rusty Lavender",
"BB cgc DD Ee Rr": "Rusty Lavender",
"BB cgc DD Nn Rr": "Rusty Lavender",
"BB cgc DD Rr Slsl": "Rusty Lavender",
"BB cgc DD Pnpn Rr Slsl": "Rusty Lavender",
"BB cgc DD pnpn Rr Slsl": "Rusty Lavender",
"BB cgc DD Ee Nn Rr Slsl": "Rusty Lavender",
"BB cgc DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"BB cgc DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
 // Bb RUSTY LAVENDER
"Bb DD Rr": "Rusty Lavender",
"Bb DD Ee Rr": "Rusty Lavender",
"Bb DD Nn Rr": "Rusty Lavender",
"Bb DD Rr Slsl": "Rusty Lavender",
"Bb DD Pnpn Rr Slsl": "Rusty Lavender",
"Bb DD pnpn Rr Slsl": "Rusty Lavender",
"Bb DD Ee Nn Rr Slsl": "Rusty Lavender",
"Bb DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb Ccg DD Rr": "Rusty Lavender",
"Bb Ccg DD Ee Rr": "Rusty Lavender",
"Bb Ccg DD Nn Rr": "Rusty Lavender",
"Bb Ccg DD Slsl Rr": "Rusty Lavender",
"Bb Ccg DD Pnpn Rr Slsl": "Rusty Lavender",
"Bb Ccg DD pnpn Rr Slsl": "Rusty Lavender",
"Bb Ccg DD Ee Nn Rr Slsl": "Rusty Lavender",
"Bb Ccg DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb Ccg DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb Ccm DD Rr": "Rusty Lavender",
"Bb Ccm DD Ee Rr": "Rusty Lavender",
"Bb Ccm DD Nn Rr": "Rusty Lavender",
"Bb Ccm DD Slsl Rr": "Rusty Lavender",
"Bb Ccm DD Pnpn Rr Slsl": "Rusty Lavender",
"Bb Ccm DD pnpn Rr Slsl": "Rusty Lavender",
"Bb Ccm DD Ee Nn Rr Slsl": "Rusty Lavender",
"Bb Ccm DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb Ccm DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb Cc DD Rr": "Rusty Lavender",
"Bb Cc DD Ee Rr": "Rusty Lavender",
"Bb Cc DD Nn Rr": "Rusty Lavender",
"Bb Cc DD Slsl Rr": "Rusty Lavender",
"Bb Cc DD Pnpn Rr Slsl": "Rusty Lavender",
"Bb Cc DD pnpn Rr Slsl": "Rusty Lavender",
"Bb Cc DD Ee Nn Rr Slsl": "Rusty Lavender",
"Bb Cc DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb Cc DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb cgcg DD Rr": "Rusty Lavender",
"Bb cgcg DD Ee Rr": "Rusty Lavender",
"Bb cgcg DD Nn Rr": "Rusty Lavender",
"Bb cgcg DD Slsl Rr": "Rusty Lavender",
"Bb cgcg DD Pnpn Rr Slsl": "Rusty Lavender",
"Bb cgcg DD pnpn Rr Slsl": "Rusty Lavender",
"Bb cgcg DD Ee Nn Rr Slsl": "Rusty Lavender",
"Bb cgcg DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb cgcg DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb cgcm DD Rr": "Rusty Lavender",
"Bb cgcm DD Ee Rr": "Rusty Lavender",
"Bb cgcm DD Nn Rr": "Rusty Lavender",
"Bb cgcm DD Rr Slsl": "Rusty Lavender",
"Bb cgcm DD Pnpn Rr Slsl": "Rusty Lavender",
"Bb cgcm DD pnpn Rr Slsl": "Rusty Lavender",
"Bb cgcm DD Ee Nn Rr Slsl": "Rusty Lavender",
"Bb cgcm DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb cgcm DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb cgc DD Rr": "Rusty Lavender",
"Bb cgc DD Ee Rr": "Rusty Lavender",
"Bb cgc DD Nn Rr": "Rusty Lavender",
"Bb cgc DD Rr Slsl": "Rusty Lavender",
"Bb cgc DD Pnpn Rr Slsl": "Rusty Lavender",
"Bb cgc DD pnpn Rr Slsl": "Rusty Lavender",
"Bb cgc DD Ee Nn Rr Slsl": "Rusty Lavender",
"Bb cgc DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb cgc DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
 // Bb1 RUSTY LAVENDER
"Bb1 DD Rr": "Rusty Lavender",
"Bb1 DD Ee Rr": "Rusty Lavender",
"Bb1 DD Nn Rr": "Rusty Lavender",
"Bb1 DD Rr Slsl": "Rusty Lavender",
"Bb1 DD Pnpn Rr Slsl": "Rusty Lavender",
"Bb1 DD pnpn Rr Slsl": "Rusty Lavender",
"Bb1 DD Ee Nn Rr Slsl": "Rusty Lavender",
"Bb1 DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb1 DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb1 Ccm DD Rr": "Rusty Lavender",
"Bb1 Ccm DD Ee Rr": "Rusty Lavender",
"Bb1 Ccm DD Nn Rr": "Rusty Lavender",
"Bb1 Ccm DD Rr Slsl": "Rusty Lavender",
"Bb1 Ccm DD Pnpn Rr Slsl": "Rusty Lavender",
"Bb1 Ccm DD pnpn Rr Slsl": "Rusty Lavender",
"Bb1 Ccm DD Ee Nn Rr Slsl": "Rusty Lavender",
"Bb1 Ccm DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb1 Ccm DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb1 Cc DD Rr": "Rusty Lavender",
"Bb1 Cc DD Ee Rr": "Rusty Lavender",
"Bb1 Cc DD Nn Rr": "Rusty Lavender",
"Bb1 Cc DD Rr Slsl": "Rusty Lavender",
"Bb1 Cc DD Pnpn Rr Slsl": "Rusty Lavender",
"Bb1 Cc DD pnpn Rr Slsl": "Rusty Lavender",
"Bb1 Cc DD Ee Nn Rr Slsl": "Rusty Lavender",
"Bb1 Cc DD Nn Pnpn Rr Slsl": "Rusty Lavender",
"Bb1 Cc DD Ee Nn Pnpn Rr Slsl": "Rusty Lavender",
// RUSTY RECESSIVE BLUE
"BB Rr slsl": "Rusty Recessive Blue",
"BB Ee Rr slsl": "Rusty Recessive Blue",
"BB Nn Rr slsl": "Rusty Recessive Blue",
"BB Pnpn Rr slsl": "Rusty Recessive Blue",
"BB pnpn Rr slsl": "Rusty Recessive Blue",
"BB Ee Nn Rr slsl": "Rusty Recessive Blue",
"BB Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"BB Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"BB Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"BB Nn pnpn Rr slsl": "Rusty Recessive Blue",
"BB Ccg Rr slsl": "Rusty Recessive Blue",
"BB Ccg Ee Rr slsl": "Rusty Recessive Blue",
"BB Ccg Nn Rr slsl": "Rusty Recessive Blue",
"BB Ccg Pnpn Rr slsl": "Rusty Recessive Blue",
"BB Ccg pnpn Rr slsl": "Rusty Recessive Blue",
"BB Ccg Ee Nn Rr slsl": "Rusty Recessive Blue",
"BB Ccg Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"BB Ccg Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"BB Ccg Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"BB Ccg Nn pnpn Rr slsl": "Rusty Recessive Blue",
"BB Ccm Rr slsl": "Rusty Recessive Blue",
"BB Ccm Ee Rr slsl": "Rusty Recessive Blue",
"BB Ccm Nn Rr slsl": "Rusty Recessive Blue",
"BB Ccm Pnpn Rr slsl": "Rusty Recessive Blue",
"BB Ccm pnpn Rr slsl": "Rusty Recessive Blue",
"BB Ccm Ee Nn Rr slsl": "Rusty Recessive Blue",
"BB Ccm Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"BB Ccm Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"BB Ccm Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"BB Ccm Nn pnpn Rr slsl": "Rusty Recessive Blue",
"BB Cc Rr slsl": "Rusty Recessive Blue",
"BB Cc Ee Rr slsl": "Rusty Recessive Blue",
"BB Cc Nn Rr slsl": "Rusty Recessive Blue",
"BB Cc Pnpn Rr slsl": "Rusty Recessive Blue",
"BB Cc pnpn Rr slsl": "Rusty Recessive Blue",
"BB Cc Ee Nn Rr slsl": "Rusty Recessive Blue",
"BB Cc Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"BB Cc Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"BB Cc Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"BB Cc Nn pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgcg Rr slsl": "Rusty Recessive Blue",
"BB cgcg Ee Rr slsl": "Rusty Recessive Blue",
"BB cgcg Nn Rr slsl": "Rusty Recessive Blue",
"BB cgcg Pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgcg pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgcg Ee Nn Rr slsl": "Rusty Recessive Blue",
"BB cgcg Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgcg Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgcg Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgcg Nn pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgcm Rr slsl": "Rusty Recessive Blue",
"BB cgcm Ee Rr slsl": "Rusty Recessive Blue",
"BB cgcm Nn Rr slsl": "Rusty Recessive Blue",
"BB cgcm Pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgcm pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgcm Ee Nn Rr slsl": "Rusty Recessive Blue",
"BB cgcm Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgcm Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgcm Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgcm Nn pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgc Rr slsl": "Rusty Recessive Blue",
"BB cgc Ee Rr slsl": "Rusty Recessive Blue",
"BB cgc Nn Rr slsl": "Rusty Recessive Blue",
"BB cgc Pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgc pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgc Ee Nn Rr slsl": "Rusty Recessive Blue",
"BB cgc Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgc Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgc Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"BB cgc Nn pnpn Rr slsl": "Rusty Recessive Blue",
// Bb RUSTY RECESSIVE BLUE
"Bb Rr slsl": "Rusty Recessive Blue",
"Bb Ee Rr slsl": "Rusty Recessive Blue",
"Bb Nn Rr slsl": "Rusty Recessive Blue",
"Bb Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Ee Nn Rr slsl": "Rusty Recessive Blue",
"Bb Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Ccg Rr slsl": "Rusty Recessive Blue",
"Bb Ccg Ee Rr slsl": "Rusty Recessive Blue",
"Bb Ccg Nn Rr slsl": "Rusty Recessive Blue",
"Bb Ccg Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Ccg pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Ccg Ee Nn Rr slsl": "Rusty Recessive Blue",
"Bb Ccg Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Ccg Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Ccg Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Ccg Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Ccm Rr slsl": "Rusty Recessive Blue",
"Bb Ccm Ee Rr slsl": "Rusty Recessive Blue",
"Bb Ccm Nn Rr slsl": "Rusty Recessive Blue",
"Bb Ccm Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Ccm pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Ccm Ee Nn Rr slsl": "Rusty Recessive Blue",
"Bb Ccm Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Ccm Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Ccm Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Ccm Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Cc Rr slsl": "Rusty Recessive Blue",
"Bb Cc Ee Rr slsl": "Rusty Recessive Blue",
"Bb Cc Nn Rr slsl": "Rusty Recessive Blue",
"Bb Cc Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Cc pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Cc Ee Nn Rr slsl": "Rusty Recessive Blue",
"Bb Cc Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Cc Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Cc Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb Cc Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgcg Rr slsl": "Rusty Recessive Blue",
"Bb cgcg Ee Rr slsl": "Rusty Recessive Blue",
"Bb cgcg Nn Rr slsl": "Rusty Recessive Blue",
"Bb cgcg Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgcg pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgcg Ee Nn Rr slsl": "Rusty Recessive Blue",
"Bb cgcg Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgcg Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgcg Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgcg Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgcm Rr slsl": "Rusty Recessive Blue",
"Bb cgcm Ee Rr slsl": "Rusty Recessive Blue",
"Bb cgcm Nn Rr slsl": "Rusty Recessive Blue",
"Bb cgcm Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgcm pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgcm Ee Nn Rr slsl": "Rusty Recessive Blue",
"Bb cgcm Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgcm Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgcm Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgcm Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgc Rr slsl": "Rusty Recessive Blue",
"Bb cgc Ee Rr slsl": "Rusty Recessive Blue",
"Bb cgc Nn Rr slsl": "Rusty Recessive Blue",
"Bb cgc Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgc pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgc Ee Nn Rr slsl": "Rusty Recessive Blue",
"Bb cgc Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgc Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgc Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb cgc Nn pnpn Rr slsl": "Rusty Recessive Blue",
// Bb1 RUSTY RECESSIVE BLUE
"Bb1 Rr slsl": "Rusty Recessive Blue",
"Bb1 Ee Rr slsl": "Rusty Recessive Blue",
"Bb1 Nn Rr slsl": "Rusty Recessive Blue",
"Bb1 Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Ee Nn Rr slsl": "Rusty Recessive Blue",
"Bb1 Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Ccm Rr slsl": "Rusty Recessive Blue",
"Bb1 Ccm Ee Rr slsl": "Rusty Recessive Blue",
"Bb1 Ccm Nn Rr slsl": "Rusty Recessive Blue",
"Bb1 Ccm Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Ccm pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Ccm Ee Nn Rr slsl": "Rusty Recessive Blue",
"Bb1 Ccm Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Ccm Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Ccm Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Ccm Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Cc Rr slsl": "Rusty Recessive Blue",
"Bb1 Cc Ee Rr slsl": "Rusty Recessive Blue",
"Bb1 Cc Nn Rr slsl": "Rusty Recessive Blue",
"Bb1 Cc Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Cc pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Cc Ee Nn Rr slsl": "Rusty Recessive Blue",
"Bb1 Cc Ee Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Cc Ee Nn pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Cc Nn Pnpn Rr slsl": "Rusty Recessive Blue",
"Bb1 Cc Nn pnpn Rr slsl": "Rusty Recessive Blue",

 // Bb RUSTY SLATE
"Bb Dd Rr": "Rusty Slate",
"Bb Dd Ee Rr": "Rusty Slate",
"Bb Dd Nn Rr": "Rusty Slate",
"Bb Dd Ee Nn Rr": "Rusty Slate",
"Bb Dd Rr Slsl": "Rusty Slate",
"Bb Dd Pnpn Rr Slsl": "Rusty Slate",
"Bb Dd pnpn Rr Slsl": "Rusty Slate",
"Bb Dd Ee Nn Rr Slsl": "Rusty Slate",
"Bb Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb Ccg Dd Rr": "Rusty Slate",
"Bb Ccg Dd Ee Rr": "Rusty Slate",
"Bb Ccg Dd Nn Rr": "Rusty Slate",
"Bb Ccg Dd Ee Nn Rr": "Rusty Slate",
"Bb Ccg Dd Rr Slsl": "Rusty Slate",
"Bb Ccg Dd Pnpn Rr Slsl": "Rusty Slate",
"Bb Ccg Dd pnpn Rr Slsl": "Rusty Slate",
"Bb Ccg Dd Ee Nn Rr Slsl": "Rusty Slate",
"Bb Ccg Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb Ccg Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb Ccm Dd Rr": "Rusty Slate",
"Bb Ccm Dd Ee Rr": "Rusty Slate",
"Bb Ccm Dd Nn Rr": "Rusty Slate",
"Bb Ccm Dd Ee Nn Rr": "Rusty Slate",
"Bb Ccm Dd Rr Slsl": "Rusty Slate",
"Bb Ccm Dd Pnpn Rr Slsl": "Rusty Slate",
"Bb Ccm Dd pnpn Rr Slsl": "Rusty Slate",
"Bb Ccm Dd Ee Nn Rr Slsl": "Rusty Slate",
"Bb Ccm Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb Ccm Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb Cc Dd Rr": "Rusty Slate",
"Bb Cc Dd Ee Rr": "Rusty Slate",
"Bb Cc Dd Nn Rr": "Rusty Slate",
"Bb Cc Dd Ee Nn Rr": "Rusty Slate",
"Bb Cc Dd Rr Slsl": "Rusty Slate",
"Bb Cc Dd Pnpn Rr Slsl": "Rusty Slate",
"Bb Cc Dd pnpn Rr Slsl": "Rusty Slate",
"Bb Cc Dd Ee Nn Rr Slsl": "Rusty Slate",
"Bb Cc Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb Cc Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb cgcg Dd Rr": "Rusty Slate",
"Bb cgcg Dd Ee Rr": "Rusty Slate",
"Bb cgcg Dd Nn Rr": "Rusty Slate",
"Bb cgcg Dd Ee Nn Rr": "Rusty Slate",
"Bb cgcg Dd Rr Slsl": "Rusty Slate",
"Bb cgcg Dd Pnpn Rr Slsl": "Rusty Slate",
"Bb cgcg Dd pnpn Rr Slsl": "Rusty Slate",
"Bb cgcg Dd Ee Nn Rr Slsl": "Rusty Slate",
"Bb cgcg Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb cgcg Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb cgcm Dd Rr": "Rusty Slate",
"Bb cgcm Dd Ee Rr": "Rusty Slate",
"Bb cgcm Dd Nn Rr": "Rusty Slate",
"Bb cgcm Dd Ee Nn Rr": "Rusty Slate",
"Bb cgcm Dd Rr Slsl": "Rusty Slate",
"Bb cgcm Dd Pnpn Rr Slsl": "Rusty Slate",
"Bb cgcm Dd pnpn Rr Slsl": "Rusty Slate",
"Bb cgcm Dd Ee Nn Rr Slsl": "Rusty Slate",
"Bb cgcm Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb cgcm Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb cgc Dd Rr": "Rusty Slate",
"Bb cgc Dd Ee Rr": "Rusty Slate",
"Bb cgc Dd Nn Rr": "Rusty Slate",
"Bb cgc Dd Ee Nn Rr": "Rusty Slate",
"Bb cgc Dd Rr Slsl": "Rusty Slate",
"Bb cgc Dd Pnpn Rr Slsl": "Rusty Slate",
"Bb cgc Dd pnpn Rr Slsl": "Rusty Slate",
"Bb cgc Dd Ee Nn Rr Slsl": "Rusty Slate",
"Bb cgc Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb cgc Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
 // Bb1 RUSTY SLATE
"Bb1 Dd Rr": "Rusty Slate",
"Bb1 Dd Ee Rr": "Rusty Slate",
"Bb1 Dd Nn Rr": "Rusty Slate",
"Bb1 Dd Ee Nn Rr Slsl": "Rusty Slate",
"Bb1 Dd Rr Slsl": "Rusty Slate",
"Bb1 Dd Pnpn Rr Slsl": "Rusty Slate",
"Bb1 Dd pnpn Rr Slsl": "Rusty Slate",
"Bb1 Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb1 Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb1 Ccm Dd Rr": "Rusty Slate",
"Bb1 Ccm Dd Ee Rr": "Rusty Slate",
"Bb1 Ccm Dd Nn Rr": "Rusty Slate",
"Bb1 Ccm Dd Ee Nn Rr Slsl": "Rusty Slate",
"Bb1 Ccm Dd Rr Slsl": "Rusty Slate",
"Bb1 Ccm Dd Pnpn Rr Slsl": "Rusty Slate",
"Bb1 Ccm Dd pnpn Rr Slsl": "Rusty Slate",
"Bb1 Ccm Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb1 Ccm Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb1 Cc Dd Rr": "Rusty Slate",
"Bb1 Cc Dd Ee Rr": "Rusty Slate",
"Bb1 Cc Dd Nn Rr": "Rusty Slate",
"Bb1 Cc Dd Rr Slsl": "Rusty Slate",
"Bb1 Cc Dd Pnpn Rr Slsl": "Rusty Slate",
"Bb1 Cc Dd pnpn Rr Slsl": "Rusty Slate",
"Bb1 Cc Dd Ee Nn Rr Slsl": "Rusty Slate",
"Bb1 Cc Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"Bb1 Cc Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
  
//  BB RUSTY SLATE
"BB Dd Rr": "Rusty Slate",
"BB Dd Ee Rr": "Rusty Slate",
"BB Dd Nn Rr": "Rusty Slate",
"BB Dd Ee Nn Rr": "Rusty Slate",
"BB Dd Rr Slsl": "Rusty Slate",
"BB Dd Pnpn Rr Slsl": "Rusty Slate",
"BB Dd pnpn Rr Slsl": "Rusty Slate",
"BB Dd Ee Nn Rr Slsl": "Rusty Slate",
"BB Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"BB Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
"BB Ccg Dd Rr": "Rusty Slate",
"BB Ccg Dd Ee Rr": "Rusty Slate",
"BB Ccg Dd Nn Rr": "Rusty Slate",
"BB Ccg Dd Ee Nn Rr": "Rusty Slate",
"BB Ccg Dd Rr Slsl": "Rusty Slate",
"BB Ccg Dd Pnpn Rr Slsl": "Rusty Slate",
"BB Ccg Dd pnpn Rr Slsl": "Rusty Slate",
"BB Ccg Dd Ee Nn Rr Slsl": "Rusty Slate",
"BB Ccg Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"BB Ccg Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
"BB Ccm Dd Rr": "Rusty Slate",
"BB Ccm Dd Ee Rr": "Rusty Slate",
"BB Ccm Dd Nn Rr": "Rusty Slate",
"BB Ccm Dd Ee Nn Rr": "Rusty Slate",
"BB Ccm Dd Rr Slsl": "Rusty Slate",
"BB Ccm Dd Pnpn Rr Slsl": "Rusty Slate",
"BB Ccm Dd pnpn Rr Slsl": "Rusty Slate",
"BB Ccm Dd Ee Nn Rr Slsl": "Rusty Slate",
"BB Ccm Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"BB Ccm Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
"BB Cc Dd Rr": "Rusty Slate",
"BB Cc Dd Ee Rr": "Rusty Slate",
"BB Cc Dd Nn Rr": "Rusty Slate",
"BB Cc Dd Ee Nn Rr": "Rusty Slate",
"BB Cc Dd Rr Slsl": "Rusty Slate",
"BB Cc Dd Pnpn Rr Slsl": "Rusty Slate",
"BB Cc Dd pnpn Rr Slsl": "Rusty Slate",
"BB Cc Dd Ee Nn Rr Slsl": "Rusty Slate",
"BB Cc Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"BB Cc Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
"BB cgcg Dd Rr": "Rusty Slate",
"BB cgcg Dd Ee Rr": "Rusty Slate",
"BB cgcg Dd Nn Rr": "Rusty Slate",
"BB cgcg Dd Ee Nn Rr": "Rusty Slate",
"BB cgcg Dd Rr Slsl": "Rusty Slate",
"BB cgcg Dd Pnpn Rr Slsl": "Rusty Slate",
"BB cgcg Dd pnpn Rr Slsl": "Rusty Slate",
"BB cgcg Dd Ee Nn Rr Slsl": "Rusty Slate",
"BB cgcg Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"BB cgcg Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
"BB cgcm Dd Rr": "Rusty Slate",
"BB cgcm Dd Ee Rr": "Rusty Slate",
"BB cgcm Dd Nn Rr": "Rusty Slate",
"BB cgcm Dd Ee Nn Rr": "Rusty Slate",
"BB cgcm Dd Rr Slsl": "Rusty Slate",
"BB cgcm Dd Pnpn Rr Slsl": "Rusty Slate",
"BB cgcm Dd pnpn Rr Slsl": "Rusty Slate",
"BB cgcm Dd Ee Nn Rr Slsl": "Rusty Slate",
"BB cgcm Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"BB cgcm Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",
"BB cgc Dd Rr": "Rusty Slate",
"BB cgc Dd Ee Rr": "Rusty Slate",
"BB cgc Dd Nn Rr": "Rusty Slate",
"BB cgc Dd Ee Nn Rr": "Rusty Slate",
"BB cgc Dd Rr Slsl": "Rusty Slate",
"BB cgc Dd Pnpn Rr Slsl": "Rusty Slate",
"BB cgc Dd pnpn Rr Slsl": "Rusty Slate",
"BB cgc Dd Ee Nn Rr Slsl": "Rusty Slate",
"BB cgc Dd Nn Pnpn Rr Slsl": "Rusty Slate",
"BB cgc Dd Ee Nn Pnpn Rr Slsl": "Rusty Slate",  
  
  
  
 
  
};
