// Dilute Rusty Black- Frosted Oregon Lav Blue 
const phenotypeMapping3A = {
  //  BB DILUTE RUSTY BLACK
"BB nn Rr": "Dilute Rusty Black",
"BB Ee nn Rr": "Dilute Rusty Black",
"BB nn Rr Slsl": "Dilute Rusty Black",
"BB nn Pnpn Rr Slsl": "Dilute Rusty Black",
"BB nn pnpn Rr Slsl": "Dilute Rusty Black",
"BB Ee nn Rr Slsl": "Dilute Rusty Black",
"BB Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
"BB Ccg nn Rr": "Dilute Rusty Black",
"BB Ccg Ee nn Rr": "Dilute Rusty Black",
"BB Ccg nn Rr Slsl": "Dilute Rusty Black",
"BB Ccg nn Pnpn Rr Slsl": "Dilute Rusty Black",
"BB Ccg nn pnpn Rr Slsl": "Dilute Rusty Black",
"BB Ccg Ee nn Rr Slsl": "Dilute Rusty Black",
"BB Ccg Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
"BB Ccm nn Rr": "Dilute Rusty Black",
"BB Ccm Ee nn Rr": "Dilute Rusty Black",
"BB Ccm nn Rr Slsl": "Dilute Rusty Black",
"BB Ccm nn Pnpn Rr Slsl": "Dilute Rusty Black",
"BB Ccm nn pnpn Rr Slsl": "Dilute Rusty Black",
"BB Ccm Ee nn Rr Slsl": "Dilute Rusty Black",
"BB Ccm Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
"BB Cc nn Rr": "Dilute Rusty Black",
"BB Cc Ee nn Rr": "Dilute Rusty Black",
"BB Cc nn Rr Slsl": "Dilute Rusty Black",
"BB Cc nn Pnpn Rr Slsl": "Dilute Rusty Black",
"BB Cc nn pnpn Rr Slsl": "Dilute Rusty Black",
"BB Cc Ee nn Rr Slsl": "Dilute Rusty Black",
"BB Cc Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgcg nn Rr": "Dilute Rusty Black",
"BB cgcg Ee nn Rr": "Dilute Rusty Black",
"BB cgcg nn Rr Slsl": "Dilute Rusty Black",
"BB cgcg nn Pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgcg nn pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgcg Ee nn Rr Slsl": "Dilute Rusty Black",
"BB cgcg Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgcm nn Rr": "Dilute Rusty Black",
"BB cgcm Ee nn Rr": "Dilute Rusty Black",
"BB cgcm nn Rr Slsl": "Dilute Rusty Black",
"BB cgcm nn Pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgcm nn pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgcm Ee nn Rr Slsl": "Dilute Rusty Black",
"BB cgcm Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgc nn Rr": "Dilute Rusty Black",
"BB cgc Ee nn Rr": "Dilute Rusty Black",
"BB cgc nn Rr Slsl": "Dilute Rusty Black",
"BB cgc nn Pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgc nn pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgc Ee nn Rr Slsl": "Dilute Rusty Black",
"BB cgc Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
// BB DILUTE RUSTY BLACK FEMALES
"BB n- Rr": "Dilute Rusty Black",
"BB n- Pnpn Rr": "Dilute Rusty Black",
"BB n- pnpn Rr": "Dilute Rusty Black",
"BB n- Rr Slsl": "Dilute Rusty Black",
"BB n- Pnpn Rr Slsl": "Dilute Rusty Black",
"BB n- pnpn Rr Slsl": "Dilute Rusty Black",
"BB Ccg n- Rr": "Dilute Rusty Black",
"BB Ccg n- Pnpn Rr": "Dilute Rusty Black",
"BB Ccg n- pnpn Rr": "Dilute Rusty Black",
"BB Ccg n- Rr Slsl": "Dilute Rusty Black",
"BB Ccg n- Pnpn Rr Slsl": "Dilute Rusty Black",
"BB Ccg n- pnpn Rr Slsl": "Dilute Rusty Black",
"BB Ccm n- Rr": "Dilute Rusty Black",
"BB Ccm n- Pnpn Rr": "Dilute Rusty Black",
"BB Ccm n- pnpn Rr": "Dilute Rusty Black",
"BB Ccm n- Rr Slsl": "Dilute Rusty Black",
"BB Ccm n- Pnpn Rr Slsl": "Dilute Rusty Black",
"BB Ccm n- pnpn Rr Slsl": "Dilute Rusty Black",
"BB Cc n- Rr": "Dilute Rusty Black",
"BB Cc n- Pnpn Rr": "Dilute Rusty Black",
"BB Cc n- pnpn Rr": "Dilute Rusty Black",
"BB Cc n- Rr Slsl": "Dilute Rusty Black",
"BB Cc n- Pnpn Rr Slsl": "Dilute Rusty Black",
"BB Cc n- pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgcg n- Rr": "Dilute Rusty Black",
"BB cgcg n- Pnpn Rr": "Dilute Rusty Black",
"BB cgcg n- pnpn Rr": "Dilute Rusty Black",
"BB cgcg n- Rr Slsl": "Dilute Rusty Black",
"BB cgcg n- Pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgcg n- pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgcm n- Rr": "Dilute Rusty Black",
"BB cgcm n- Pnpn Rr": "Dilute Rusty Black",
"BB cgcm n- pnpn Rr": "Dilute Rusty Black",
"BB cgcm n- Rr Slsl": "Dilute Rusty Black",
"BB cgcm n- Pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgcm n- pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgc n- Rr": "Dilute Rusty Black",
"BB cgc n- Pnpn Rr": "Dilute Rusty Black",
"BB cgc n- pnpn Rr": "Dilute Rusty Black",
"BB cgc n- Rr Slsl": "Dilute Rusty Black",
"BB cgc n- Pnpn Rr Slsl": "Dilute Rusty Black",
"BB cgc n- pnpn Rr Slsl": "Dilute Rusty Black",
//  Bb DILUTE RUSTY BLACK
"Bb nn Rr": "Dilute Rusty Black",
"Bb Ee nn Rr": "Dilute Rusty Black",
"Bb nn Rr Slsl": "Dilute Rusty Black",
"Bb nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb nn pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Ee nn Rr Slsl": "Dilute Rusty Black",
"Bb Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Ccg nn Rr": "Dilute Rusty Black",
"Bb Ccg Ee nn Rr": "Dilute Rusty Black",
"Bb Ccg nn Rr Slsl": "Dilute Rusty Black",
"Bb Ccg nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Ccg nn pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Ccg Ee nn Rr Slsl": "Dilute Rusty Black",
"Bb Ccg Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Ccm nn Rr": "Dilute Rusty Black",
"Bb Ccm Ee nn Rr": "Dilute Rusty Black",
"Bb Ccm nn Rr Slsl": "Dilute Rusty Black",
"Bb Ccm nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Ccm nn pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Ccm Ee nn Rr Slsl": "Dilute Rusty Black",
"Bb Ccm Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Cc nn Rr": "Dilute Rusty Black",
"Bb Cc Ee nn Rr": "Dilute Rusty Black",
"Bb Cc nn Rr Slsl": "Dilute Rusty Black",
"Bb Cc nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Cc nn pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Cc Ee nn Rr Slsl": "Dilute Rusty Black",
"Bb Cc Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb cgcg nn Rr": "Dilute Rusty Black",
"Bb cgcg Ee nn Rr": "Dilute Rusty Black",
"Bb cgcg nn Rr Slsl": "Dilute Rusty Black",
"Bb cgcg nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb cgcg nn pnpn Rr Slsl": "Dilute Rusty Black",
"Bb cgcg Ee nn Rr Slsl": "Dilute Rusty Black",
"Bb cgcg Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb cgcm nn Rr": "Dilute Rusty Black",
"Bb cgcm Ee nn Rr": "Dilute Rusty Black",
"Bb cgcm nn Rr Slsl": "Dilute Rusty Black",
"Bb cgcm nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb cgcm nn pnpn Rr Slsl": "Dilute Rusty Black",
"Bb cgcm Ee nn Rr Slsl": "Dilute Rusty Black",
"Bb cgcm Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
// Bb DILUTE RUSTY BLACK FEMALES
"Bb n- Rr": "Dilute Rusty Black",
"Bb n- Pnpn Rr": "Dilute Rusty Black",
"Bb n- pnpn Rr": "Dilute Rusty Black",
"Bb n- Rr Slsl": "Dilute Rusty Black",
"Bb n- Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb n- pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Ccg n- Rr": "Dilute Rusty Black",
"Bb Ccg n- Pnpn Rr": "Dilute Rusty Black",
"Bb Ccg n- pnpn Rr": "Dilute Rusty Black",
"Bb Ccg n- Rr Slsl": "Dilute Rusty Black",
"Bb Ccg n- Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Ccg n- pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Ccm n- Rr": "Dilute Rusty Black",
"Bb Ccm n- Pnpn Rr": "Dilute Rusty Black",
"Bb Ccm n- pnpn Rr": "Dilute Rusty Black",
"Bb Ccm n- Rr Slsl": "Dilute Rusty Black",
"Bb Ccm n- Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Ccm n- pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Cc n- Rr": "Dilute Rusty Black",
"Bb Cc n- Pnpn Rr": "Dilute Rusty Black",
"Bb Cc n- pnpn Rr": "Dilute Rusty Black",
"Bb Cc n- Rr Slsl": "Dilute Rusty Black",
"Bb Cc n- Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb Cc n- pnpn Rr Slsl": "Dilute Rusty Black",
"Bb cgcg n- Rr": "Dilute Rusty Black",
"Bb cgcg n- Pnpn Rr": "Dilute Rusty Black",
"Bb cgcg n- pnpn Rr": "Dilute Rusty Black",
"Bb cgcg n- Rr Slsl": "Dilute Rusty Black",
"Bb cgcg n- Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb cgcg n- pnpn Rr Slsl": "Dilute Rusty Black",
"Bb cgcm n- Rr": "Dilute Rusty Black",
"Bb cgcm n- Pnpn Rr": "Dilute Rusty Black",
"Bb cgcm n- pnpn Rr": "Dilute Rusty Black",
"Bb cgcm n- Rr Slsl": "Dilute Rusty Black",
"Bb cgcm n- Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb cgcm n- pnpn Rr Slsl": "Dilute Rusty Black",
// Bb1 DILUTE RUSTY BLACK
"Bb1 nn Rr": "Dilute Rusty Black",
"Bb1 Ee nn Rr": "Dilute Rusty Black",
"Bb1 nn Rr Slsl": "Dilute Rusty Black",
"Bb1 nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb1 nn pnpn Rr Slsl": "Dilute Rusty Black",
"Bb1 Ee nn Rr Slsl": "Dilute Rusty Black",
"Bb1 Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb1 Ccm nn Rr": "Dilute Rusty Black",
"Bb1 Ccm Ee nn Rr": "Dilute Rusty Black",
"Bb1 Ccm nn Rr Slsl": "Dilute Rusty Black",
"Bb1 Ccm nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb1 Ccm nn pnpn Rr Slsl": "Dilute Rusty Black",
"Bb1 Ccm Ee nn Rr Slsl": "Dilute Rusty Black",
"Bb1 Ccm Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb1 Cc nn Rr": "Dilute Rusty Black",
"Bb1 Cc Ee nn Rr": "Dilute Rusty Black",
"Bb1 Cc nn Rr Slsl": "Dilute Rusty Black",
"Bb1 Cc nn Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb1 Cc nn pnpn Rr Slsl": "Dilute Rusty Black",
"Bb1 Cc Ee nn Rr Slsl": "Dilute Rusty Black",
"Bb1 Cc Ee nn Pnpn Rr Slsl": "Dilute Rusty Black",
// Bb1 DILUTE RUSTY BLACK FEMALES
"Bb1 n- Rr": "Dilute Rusty Black",
"Bb1 n- Pnpn Rr": "Dilute Rusty Black",
"Bb1 n- pnpn Rr": "Dilute Rusty Black",
"Bb1 n- Rr Slsl": "Dilute Rusty Black",
"Bb1 n- Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb1 n- pnpn Rr Slsl": "Dilute Rusty Black",
"Bb1 Ccm n- Rr": "Dilute Rusty Black",
"Bb1 Ccm n- Pnpn Rr": "Dilute Rusty Black",
"Bb1 Ccm n- pnpn Rr": "Dilute Rusty Black",
"Bb1 Ccm n- Rr Slsl": "Dilute Rusty Black",
"Bb1 Ccm n- Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb1 Ccm n- pnpn Rr Slsl": "Dilute Rusty Black",
"Bb1 Cc n- Rr": "Dilute Rusty Black",
"Bb1 Cc n- Pnpn Rr": "Dilute Rusty Black",
"Bb1 Cc n- pnpn Rr": "Dilute Rusty Black",
"Bb1 Cc n- Rr Slsl": "Dilute Rusty Black",
"Bb1 Cc n- Pnpn Rr Slsl": "Dilute Rusty Black",
"Bb1 Cc n- pnpn Rr Slsl": "Dilute Rusty Black",
 //DILUTE RUSTY BROWN
"BB ee nn Rr": "Dilute Rusty Brown",
"BB ee nn Pnpn Rr": "Dilute Rusty Brown",
"BB ee nn pnpn Rr": "Dilute Rusty Brown",
"BB ee nn Rr Slsl": "Dilute Rusty Brown",
"BB ee nn Pnpn Rr Slsl": "Dilute Rusty Brown",
"BB ee nn pnpn Rr Slsl": "Dilute Rusty Brown",
"BB Ccg ee nn Rr": "Dilute Rusty Brown",
"BB Ccg ee nn Pnpn Rr": "Dilute Rusty Brown",
"BB Ccg ee nn pnpn Rr": "Dilute Rusty Brown",
"BB Ccg ee nn Rr Slsl": "Dilute Rusty Brown",
"BB Ccg ee nn Pnpn Rr Slsl": "Dilute Rusty Brown",
"BB Ccg ee nn pnpn Rr Slsl": "Dilute Rusty Brown",
"BB Ccm ee nn Rr": "Dilute Rusty Brown",
"BB Ccm ee nn Pnpn Rr": "Dilute Rusty Brown",
"BB Ccm ee nn pnpn Rr": "Dilute Rusty Brown",
"BB Ccm ee nn Rr Slsl": "Dilute Rusty Brown",
"BB Ccm ee nn Pnpn Rr Slsl": "Dilute Rusty Brown",
"BB Ccm ee nn pnpn Rr Slsl": "Dilute Rusty Brown",
"BB Cc ee nn Rr": "Dilute Rusty Brown",
"BB Cc ee nn Pnpn Rr": "Dilute Rusty Brown",
"BB Cc ee nn pnpn Rr": "Dilute Rusty Brown",
"BB Cc ee nn Rr Slsl": "Dilute Rusty Brown",
"BB Cc ee nn Pnpn Rr Slsl": "Dilute Rusty Brown",
"BB Cc ee nn pnpn Rr Slsl": "Dilute Rusty Brown",
 // DILUTE RUSTY BROWN FEMALES
"BB e- n- Rr": "Dilute Rusty Brown",
"BB e- n- Pnpn Rr": "Dilute Rusty Brown",
"BB e- n- pnpn Rr": "Dilute Rusty Brown",
"BB e- n- Rr Slsl": "Dilute Rusty Brown",
"BB e- n- Pnpn Rr Slsl": "Dilute Rusty Brown",
"BB e- n- pnpn Rr Slsl": "Dilute Rusty Brown",
"BB Ccg e- n- Rr": "Dilute Rusty Brown",
"BB Ccg e- n- Pnpn Rr": "Dilute Rusty Brown",
"BB Ccg e- n- pnpn Rr": "Dilute Rusty Brown",
"BB Ccg e- n- Rr Slsl": "Dilute Rusty Brown",
"BB Ccg e- n- Pnpn Rr Slsl": "Dilute Rusty Brown",
"BB Ccg e- n- pnpn Rr Slsl": "Dilute Rusty Brown",
"BB Ccm e- n- Rr": "Dilute Rusty Brown",
"BB Ccm e- n- Pnpn Rr": "Dilute Rusty Brown",
"BB Ccm e- n- pnpn Rr": "Dilute Rusty Brown",
"BB Ccm e- n- Rr Slsl": "Dilute Rusty Brown",
"BB Ccm e- n- Pnpn Rr Slsl": "Dilute Rusty Brown",
"BB Ccm e- n- pnpn Rr Slsl": "Dilute Rusty Brown",
"BB Cc e- n- Rr": "Dilute Rusty Brown",
"BB Cc e- n- Pnpn Rr": "Dilute Rusty Brown",
"BB Cc e- n- pnpn Rr": "Dilute Rusty Brown",
"BB Cc e- n- Rr Slsl": "Dilute Rusty Brown",
"BB Cc e- n- Pnpn Rr Slsl": "Dilute Rusty Brown",
"BB Cc e- n- pnpn Rr Slsl": "Dilute Rusty Brown",
 // Bb DILUTE RUSTY BROWN
"Bb ee nn Rr": "Dilute Rusty Brown",
"Bb ee nn Pnpn Rr": "Dilute Rusty Brown",
"Bb ee nn pnpn Rr": "Dilute Rusty Brown",
"Bb ee nn Rr Slsl": "Dilute Rusty Brown",
"Bb ee nn Pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb ee nn pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb Ccg ee nn Rr": "Dilute Rusty Brown",
"Bb Ccg ee nn Pnpn Rr": "Dilute Rusty Brown",
"Bb Ccg ee nn pnpn Rr": "Dilute Rusty Brown",
"Bb Ccg ee nn Rr Slsl": "Dilute Rusty Brown",
"Bb Ccg ee nn Pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb Ccg ee nn pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb Ccm ee nn Rr": "Dilute Rusty Brown",
"Bb Ccm ee nn Pnpn Rr": "Dilute Rusty Brown",
"Bb Ccm ee nn pnpn Rr": "Dilute Rusty Brown",
"Bb Ccm ee nn Rr Slsl": "Dilute Rusty Brown",
"Bb Ccm ee nn Pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb Ccm ee nn pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb Cc ee nn Rr": "Dilute Rusty Brown",
"Bb Cc ee nn Pnpn Rr": "Dilute Rusty Brown",
"Bb Cc ee nn pnpn Rr": "Dilute Rusty Brown",
"Bb Cc ee nn Rr Slsl": "Dilute Rusty Brown",
"Bb Cc ee nn Pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb Cc ee nn pnpn Rr Slsl": "Dilute Rusty Brown",
 // Bb DILUTE RUSTY BROWN FEMALES
"Bb e- n- Rr": "Dilute Rusty Brown",
"Bb e- n- Pnpn Rr": "Dilute Rusty Brown",
"Bb e- n- pnpn Rr": "Dilute Rusty Brown",
"Bb e- n- Rr Slsl": "Dilute Rusty Brown",
"Bb e- n- Pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb e- n- pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb Ccg e- n- Rr": "Dilute Rusty Brown",
"Bb Ccg e- n- Pnpn Rr": "Dilute Rusty Brown",
"Bb Ccg e- n- pnpn Rr": "Dilute Rusty Brown",
"Bb Ccg e- n- Rr Slsl": "Dilute Rusty Brown",
"Bb Ccg e- n- Pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb Ccg e- n- pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb Ccm e- n- Rr": "Dilute Rusty Brown",
"Bb Ccm e- n- Pnpn Rr": "Dilute Rusty Brown",
"Bb Ccm e- n- pnpn Rr": "Dilute Rusty Brown",
"Bb Ccm e- n- Rr Slsl": "Dilute Rusty Brown",
"Bb Ccm e- n- Pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb Ccm e- n- pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb Cc e- n- Rr": "Dilute Rusty Brown",
"Bb Cc e- n- Pnpn Rr": "Dilute Rusty Brown",
"Bb Cc e- n- pnpn Rr": "Dilute Rusty Brown",
"Bb Cc e- n- Rr Slsl": "Dilute Rusty Brown",
"Bb Cc e- n- Pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb Cc e- n- pnpn Rr Slsl": "Dilute Rusty Brown",
 // Bb1 DILUTE RUSTY BROWN
"Bb1 ee nn Rr": "Dilute Rusty Brown",
"Bb1 ee nn Pnpn Rr": "Dilute Rusty Brown",
"Bb1 ee nn pnpn Rr": "Dilute Rusty Brown",
"Bb1 ee nn Rr Slsl": "Dilute Rusty Brown",
"Bb1 ee nn Pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb1 ee nn pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb1 Ccm ee nn Rr": "Dilute Rusty Brown",
"Bb1 Ccm ee nn Pnpn Rr": "Dilute Rusty Brown",
"Bb1 Ccm ee nn pnpn Rr": "Dilute Rusty Brown",
"Bb1 Ccm ee nn Rr Slsl": "Dilute Rusty Brown",
"Bb1 Ccm ee nn Pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb1 Ccm ee nn pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb1 Cc ee nn Rr": "Dilute Rusty Brown",
"Bb1 Cc ee nn Pnpn Rr": "Dilute Rusty Brown",
"Bb1 Cc ee nn pnpn Rr": "Dilute Rusty Brown",
"Bb1 Cc ee nn Rr Slsl": "Dilute Rusty Brown",
"Bb1 Cc ee nn Pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb1 Cc ee nn pnpn Rr Slsl": "Dilute Rusty Brown",
 // Bb1 DILUTE RUSTY BROWN FEMALES
"Bb1 e- n- Rr": "Dilute Rusty Brown",
"Bb1 e- n- Pnpn Rr": "Dilute Rusty Brown",
"Bb1 e- n- pnpn Rr": "Dilute Rusty Brown",
"Bb1 e- n- Rr Slsl": "Dilute Rusty Brown",
"Bb1 e- n- Pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb1 e- n- pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb1 Ccm e- n- Rr": "Dilute Rusty Brown",
"Bb1 Ccm e- n- Pnpn Rr": "Dilute Rusty Brown",
"Bb1 Ccm e- n- pnpn Rr": "Dilute Rusty Brown",
"Bb1 Ccm e- n- Rr Slsl": "Dilute Rusty Brown",
"Bb1 Ccm e- n- Pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb1 Ccm e- n- pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb1 Cc e- n- Rr": "Dilute Rusty Brown",
"Bb1 Cc e- n- Pnpn Rr": "Dilute Rusty Brown",
"Bb1 Cc e- n- pnpn Rr": "Dilute Rusty Brown",
"Bb1 Cc e- n- Rr Slsl": "Dilute Rusty Brown",
"Bb1 Cc e- n- Pnpn Rr Slsl": "Dilute Rusty Brown",
"Bb1 Cc e- n- pnpn Rr Slsl": "Dilute Rusty Brown",
// DILUTE MOTTLED RUSTY LAVENDER
"Bb1 Ccg DD nn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 Ccg DD Ee nn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 Ccg DD nn  Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 Ccg DD nn Pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 Ccg DD nn pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 Ccg DD Ee nn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 Ccg DD Ee nn Pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcg DD nn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgcg DD Ee nn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgcg DD nn  Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcg DD nn Pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcg DD nn pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcg DD Ee nn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcg DD Ee nn Pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcm DD nn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgcm DD Ee nn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgcm DD nn  Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcm DD nn Pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcm DD nn pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcm DD Ee nn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcm DD Ee nn Pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgc DD nn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgc DD Ee nn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgc DD nn  Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgc DD nn Pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgc DD nn pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgc DD Ee nn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgc DD Ee nn Pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 Ccg DD n- Rr": "Dilute Mottled Rusty Lavender",
"Bb1 Ccg DD n- Pnpn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 Ccg DD n- pnpn  Rr": "Dilute Mottled Rusty Lavender",
"Bb1 Ccg DD n-  Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 Ccg DD n- Pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 Ccg DD n- pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcg DD n- Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgcg DD n- Pnpn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgcg DD n- pnpn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgcg DD n- Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcg DD n- Pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcg DD n- pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcm DD n- Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgcm DD n- Pnpn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgcm DD n- pnpn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgcm DD n- Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcm DD n- Pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgcm DD n- pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgc DD n- Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgc DD n- Pnpn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgc DD n- pnpn Rr": "Dilute Mottled Rusty Lavender",
"Bb1 cgc DD n- Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgc DD n- Pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
"Bb1 cgc DD n- pnpn Rr Slsl": "Dilute Mottled Rusty Lavender",
// DILUTE RUSTY LAVENDER
"BB DD nn Rr": "Dilute Rusty Lavender",
"BB DD Ee nn Rr": "Dilute Rusty Lavender",
"BB DD nn  Rr Slsl": "Dilute Rusty Lavender",
"BB DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"BB DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Ccg DD nn Rr": "Dilute Rusty Lavender",
"BB Ccg DD Ee nn Rr": "Dilute Rusty Lavender",
"BB Ccg DD nn  Rr Slsl": "Dilute Rusty Lavender",
"BB Ccg DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Ccg DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Ccg DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"BB Ccg DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Ccm DD nn Rr": "Dilute Rusty Lavender",
"BB Ccm DD Ee nn Rr": "Dilute Rusty Lavender",
"BB Ccm DD nn  Rr Slsl": "Dilute Rusty Lavender",
"BB Ccm DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Ccm DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Ccm DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"BB Ccm DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Cc DD nn Rr": "Dilute Rusty Lavender",
"BB Cc DD Ee nn Rr": "Dilute Rusty Lavender",
"BB Cc DD nn  Rr Slsl": "Dilute Rusty Lavender",
"BB Cc DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Cc DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Cc DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"BB Cc DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgcg DD nn Rr": "Dilute Rusty Lavender",
"BB cgcg DD Ee nn Rr": "Dilute Rusty Lavender",
"BB cgcg DD nn  Rr Slsl": "Dilute Rusty Lavender",
"BB cgcg DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgcg DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgcg DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"BB cgcg DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgcm DD nn Rr": "Dilute Rusty Lavender",
"BB cgcm DD Ee nn Rr": "Dilute Rusty Lavender",
"BB cgcm DD nn  Rr Slsl": "Dilute Rusty Lavender",
"BB cgcm DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgcm DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgcm DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"BB cgcm DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgc DD nn Rr": "Dilute Rusty Lavender",
"BB cgc DD Ee nn Rr": "Dilute Rusty Lavender",
"BB cgc DD nn  Rr Slsl": "Dilute Rusty Lavender",
"BB cgc DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgc DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgc DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"BB cgc DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
// DILUTE RUSTY LAVENDER FEMALES
"BB DD n- Rr": "Dilute Rusty Lavender",
"BB DD n- Pnpn Rr": "Dilute Rusty Lavender",
"BB DD n- pnpn Rr": "Dilute Rusty Lavender",
"BB DD n- Rr Slsl": "Dilute Rusty Lavender",
"BB DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Ccg DD n- Rr": "Dilute Rusty Lavender",
"BB Ccg DD n- Pnpn Rr": "Dilute Rusty Lavender",
"BB Ccg DD n- pnpn  Rr": "Dilute Rusty Lavender",
"BB Ccg DD n-  Rr Slsl": "Dilute Rusty Lavender",
"BB Ccg DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Ccg DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Ccm DD n- Rr": "Dilute Rusty Lavender",
"BB Ccm DD n- Pnpn Rr": "Dilute Rusty Lavender",
"BB Ccm DD n- pnpn Rr": "Dilute Rusty Lavender",
"BB Ccm DD n- Rr Slsl": "Dilute Rusty Lavender",
"BB Ccm DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Ccm DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Cc DD n- Rr": "Dilute Rusty Lavender",
"BB Cc DD n- Pnpn Rr": "Dilute Rusty Lavender",
"BB Cc DD n- pnpn Rr": "Dilute Rusty Lavender",
"BB Cc DD n- Rr Slsl": "Dilute Rusty Lavender",
"BB Cc DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB Cc DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgcg DD n- Rr": "Dilute Rusty Lavender",
"BB cgcg DD n- Pnpn Rr": "Dilute Rusty Lavender",
"BB cgcg DD n- pnpn Rr": "Dilute Rusty Lavender",
"BB cgcg DD n- Rr Slsl": "Dilute Rusty Lavender",
"BB cgcg DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgcg DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgcm DD n- Rr": "Dilute Rusty Lavender",
"BB cgcm DD n- Pnpn Rr": "Dilute Rusty Lavender",
"BB cgcm DD n- pnpn Rr": "Dilute Rusty Lavender",
"BB cgcm DD n- Rr Slsl": "Dilute Rusty Lavender",
"BB cgcm DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgcm DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgc DD n- Rr": "Dilute Rusty Lavender",
"BB cgc DD n- Pnpn Rr": "Dilute Rusty Lavender",
"BB cgc DD n- pnpn Rr": "Dilute Rusty Lavender",
"BB cgc DD n- Rr Slsl": "Dilute Rusty Lavender",
"BB cgc DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"BB cgc DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
// Bb
"Bb DD nn Rr": "Dilute Rusty Lavender",
"Bb DD Ee nn Rr": "Dilute Rusty Lavender",
"Bb DD nn  Rr Slsl": "Dilute Rusty Lavender",
"Bb DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"Bb DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccg DD nn Rr": "Dilute Rusty Lavender",
"Bb Ccg DD Ee nn Rr": "Dilute Rusty Lavender",
"Bb Ccg DD nn  Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccg DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccg DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccg DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccg DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccm DD nn Rr": "Dilute Rusty Lavender",
"Bb Ccm DD Ee nn Rr": "Dilute Rusty Lavender",
"Bb Ccm DD nn  Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccm DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccm DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccm DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccm DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Cc DD nn Rr": "Dilute Rusty Lavender",
"Bb Cc DD Ee nn Rr": "Dilute Rusty Lavender",
"Bb Cc DD nn  Rr Slsl": "Dilute Rusty Lavender",
"Bb Cc DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Cc DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Cc DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"Bb Cc DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcg DD nn Rr": "Dilute Rusty Lavender",
"Bb cgcg DD Ee nn Rr": "Dilute Rusty Lavender",
"Bb cgcg DD nn  Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcg DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcg DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcg DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcg DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcm DD nn Rr": "Dilute Rusty Lavender",
"Bb cgcm DD Ee nn Rr": "Dilute Rusty Lavender",
"Bb cgcm DD nn  Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcm DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcm DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcm DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcm DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgc DD nn Rr": "Dilute Rusty Lavender",
"Bb cgc DD Ee nn Rr": "Dilute Rusty Lavender",
"Bb cgc DD nn  Rr Slsl": "Dilute Rusty Lavender",
"Bb cgc DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgc DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgc DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgc DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb DD n- Rr": "Dilute Rusty Lavender",
"Bb DD n- Pnpn Rr": "Dilute Rusty Lavender",
"Bb DD n- pnpn Rr": "Dilute Rusty Lavender",
"Bb DD n- Rr Slsl": "Dilute Rusty Lavender",
"Bb DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccg DD n- Rr": "Dilute Rusty Lavender",
"Bb Ccg DD n- Pnpn Rr": "Dilute Rusty Lavender",
"Bb Ccg DD n- pnpn  Rr": "Dilute Rusty Lavender",
"Bb Ccg DD n-  Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccg DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccg DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccm DD n- Rr": "Dilute Rusty Lavender",
"Bb Ccm DD n- Pnpn Rr": "Dilute Rusty Lavender",
"Bb Ccm DD n- pnpn Rr": "Dilute Rusty Lavender",
"Bb Ccm DD n- Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccm DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Ccm DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Cc DD n- Rr": "Dilute Rusty Lavender",
"Bb Cc DD n- Pnpn Rr": "Dilute Rusty Lavender",
"Bb Cc DD n- pnpn Rr": "Dilute Rusty Lavender",
"Bb Cc DD n- Rr Slsl": "Dilute Rusty Lavender",
"Bb Cc DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb Cc DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcg DD n- Rr": "Dilute Rusty Lavender",
"Bb cgcg DD n- Pnpn Rr": "Dilute Rusty Lavender",
"Bb cgcg DD n- pnpn Rr": "Dilute Rusty Lavender",
"Bb cgcg DD n- Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcg DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcg DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcm DD n- Rr": "Dilute Rusty Lavender",
"Bb cgcm DD n- Pnpn Rr": "Dilute Rusty Lavender",
"Bb cgcm DD n- pnpn Rr": "Dilute Rusty Lavender",
"Bb cgcm DD n- Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcm DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgcm DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgc DD n- Rr": "Dilute Rusty Lavender",
"Bb cgc DD n- Pnpn Rr": "Dilute Rusty Lavender",
"Bb cgc DD n- pnpn Rr": "Dilute Rusty Lavender",
"Bb cgc DD n- Rr Slsl": "Dilute Rusty Lavender",
"Bb cgc DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb cgc DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
// Bb1
"Bb1 DD nn Rr": "Dilute Rusty Lavender",
"Bb1 DD Ee nn Rr": "Dilute Rusty Lavender",
"Bb1 DD nn  Rr Slsl": "Dilute Rusty Lavender",
"Bb1 DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Ccm DD nn Rr": "Dilute Rusty Lavender",
"Bb1 Ccm DD Ee nn Rr": "Dilute Rusty Lavender",
"Bb1 Ccm DD nn  Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Ccm DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Ccm DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Ccm DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Ccm DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Cc DD nn Rr": "Dilute Rusty Lavender",
"Bb1 Cc DD Ee nn Rr": "Dilute Rusty Lavender",
"Bb1 Cc DD nn  Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Cc DD nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Cc DD nn pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Cc DD Ee nn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Cc DD Ee nn Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 DD n- Rr": "Dilute Rusty Lavender",
"Bb1 DD n- Pnpn Rr": "Dilute Rusty Lavender",
"Bb1 DD n- pnpn Rr": "Dilute Rusty Lavender",
"Bb1 DD n- Rr Slsl": "Dilute Rusty Lavender",
"Bb1 DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Ccm DD n- Rr": "Dilute Rusty Lavender",
"Bb1 Ccm DD n- Pnpn Rr": "Dilute Rusty Lavender",
"Bb1 Ccm DD n- pnpn Rr": "Dilute Rusty Lavender",
"Bb1 Ccm DD n- Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Ccm DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Ccm DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Cc DD n- Rr": "Dilute Rusty Lavender",
"Bb1 Cc DD n- Pnpn Rr": "Dilute Rusty Lavender",
"Bb1 Cc DD n- pnpn Rr": "Dilute Rusty Lavender",
"Bb1 Cc DD n- Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Cc DD n- Pnpn Rr Slsl": "Dilute Rusty Lavender",
"Bb1 Cc DD n- pnpn Rr Slsl": "Dilute Rusty Lavender",
// DILUTE RUSTY SLATE
"BB Dd nn Rr": "Dilute Rusty Slate",
"BB Dd Ee nn Rr": "Dilute Rusty Slate",
"BB Dd nn  Rr Slsl": "Dilute Rusty Slate",
"BB Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"BB Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Ccg Dd nn Rr": "Dilute Rusty Slate",
"BB Ccg Dd Ee nn Rr": "Dilute Rusty Slate",
"BB Ccg Dd nn  Rr Slsl": "Dilute Rusty Slate",
"BB Ccg Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Ccg Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Ccg Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"BB Ccg Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Ccm Dd nn Rr": "Dilute Rusty Slate",
"BB Ccm Dd Ee nn Rr": "Dilute Rusty Slate",
"BB Ccm Dd nn  Rr Slsl": "Dilute Rusty Slate",
"BB Ccm Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Ccm Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Ccm Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"BB Ccm Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Cc Dd nn Rr": "Dilute Rusty Slate",
"BB Cc Dd Ee nn Rr": "Dilute Rusty Slate",
"BB Cc Dd nn  Rr Slsl": "Dilute Rusty Slate",
"BB Cc Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Cc Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Cc Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"BB Cc Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgcg Dd nn Rr": "Dilute Rusty Slate",
"BB cgcg Dd Ee nn Rr": "Dilute Rusty Slate",
"BB cgcg Dd nn  Rr Slsl": "Dilute Rusty Slate",
"BB cgcg Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgcg Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgcg Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"BB cgcg Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgcm Dd nn Rr": "Dilute Rusty Slate",
"BB cgcm Dd Ee nn Rr": "Dilute Rusty Slate",
"BB cgcm Dd nn  Rr Slsl": "Dilute Rusty Slate",
"BB cgcm Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgcm Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgcm Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"BB cgcm Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgc Dd nn Rr": "Dilute Rusty Slate",
"BB cgc Dd Ee nn Rr": "Dilute Rusty Slate",
"BB cgc Dd nn  Rr Slsl": "Dilute Rusty Slate",
"BB cgc Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgc Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgc Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"BB cgc Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
// DILUTE RUSTY SLATE FEMALES
"BB Dd n- Rr": "Dilute Rusty Slate",
"BB Dd n- Pnpn Rr": "Dilute Rusty Slate",
"BB Dd n- pnpn Rr": "Dilute Rusty Slate",
"BB Dd n- Rr Slsl": "Dilute Rusty Slate",
"BB Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Ccg Dd n- Rr": "Dilute Rusty Slate",
"BB Ccg Dd n- Pnpn Rr": "Dilute Rusty Slate",  
"BB Ccg Dd n- pnpn  Rr": "Dilute Rusty Slate",                                                                                              
"BB Ccg Dd n-  Rr Slsl": "Dilute Rusty Slate",
"BB Ccg Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Ccg Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Ccm Dd n- Rr": "Dilute Rusty Slate",
"BB Ccm Dd n- Pnpn Rr": "Dilute Rusty Slate",
"BB Ccm Dd n- pnpn Rr": "Dilute Rusty Slate",
"BB Ccm Dd n- Rr Slsl": "Dilute Rusty Slate",
"BB Ccm Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Ccm Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Cc Dd n- Rr": "Dilute Rusty Slate",
"BB Cc Dd n- Pnpn Rr": "Dilute Rusty Slate",
"BB Cc Dd n- pnpn Rr": "Dilute Rusty Slate",
"BB Cc Dd n- Rr Slsl": "Dilute Rusty Slate",
"BB Cc Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB Cc Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgcg Dd n- Rr": "Dilute Rusty Slate",
"BB cgcg Dd n- Pnpn Rr": "Dilute Rusty Slate",
"BB cgcg Dd n- pnpn Rr": "Dilute Rusty Slate",
"BB cgcg Dd n- Rr Slsl": "Dilute Rusty Slate",
"BB cgcg Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgcg Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgcm Dd n- Rr": "Dilute Rusty Slate",
"BB cgcm Dd n- Pnpn Rr": "Dilute Rusty Slate",
"BB cgcm Dd n- pnpn Rr": "Dilute Rusty Slate",
"BB cgcm Dd n- Rr Slsl": "Dilute Rusty Slate",
"BB cgcm Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgcm Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgc Dd n- Rr": "Dilute Rusty Slate",
"BB cgc Dd n- Pnpn Rr": "Dilute Rusty Slate",
"BB cgc Dd n- pnpn Rr": "Dilute Rusty Slate",
"BB cgc Dd n- Rr Slsl": "Dilute Rusty Slate",
"BB cgc Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"BB cgc Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
// Bb
"Bb Dd nn Rr": "Dilute Rusty Slate",
"Bb Dd Ee nn Rr": "Dilute Rusty Slate",
"Bb Dd nn  Rr Slsl": "Dilute Rusty Slate",
"Bb Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"Bb Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Ccg Dd nn Rr": "Dilute Rusty Slate",
"Bb Ccg Dd Ee nn Rr": "Dilute Rusty Slate",
"Bb Ccg Dd nn  Rr Slsl": "Dilute Rusty Slate",
"Bb Ccg Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Ccg Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Ccg Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"Bb Ccg Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Ccm Dd nn Rr": "Dilute Rusty Slate",
"Bb Ccm Dd Ee nn Rr": "Dilute Rusty Slate",
"Bb Ccm Dd nn  Rr Slsl": "Dilute Rusty Slate",
"Bb Ccm Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Ccm Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Ccm Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"Bb Ccm Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Cc Dd nn Rr": "Dilute Rusty Slate",
"Bb Cc Dd Ee nn Rr": "Dilute Rusty Slate",
"Bb Cc Dd nn  Rr Slsl": "Dilute Rusty Slate",
"Bb Cc Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Cc Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Cc Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"Bb Cc Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb cgcg Dd nn Rr": "Dilute Rusty Slate",
"Bb cgcg Dd Ee nn Rr": "Dilute Rusty Slate",
"Bb cgcg Dd nn  Rr Slsl": "Dilute Rusty Slate",
"Bb cgcg Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb cgcg Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb cgcg Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"Bb cgcg Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb cgcm Dd nn Rr": "Dilute Rusty Slate",
"Bb cgcm Dd Ee nn Rr": "Dilute Rusty Slate",
"Bb cgcm Dd nn  Rr Slsl": "Dilute Rusty Slate",
"Bb cgcm Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb cgcm Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb cgcm Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"Bb cgcm Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Dd n- Rr": "Dilute Rusty Slate",
"Bb Dd n- Pnpn Rr": "Dilute Rusty Slate",
"Bb Dd n- pnpn Rr": "Dilute Rusty Slate",
"Bb Dd n- Rr Slsl": "Dilute Rusty Slate",
"Bb Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Ccg Dd n- Rr": "Dilute Rusty Slate",
"Bb Ccg Dd n- Pnpn Rr": "Dilute Rusty Slate",
"Bb Ccg Dd n- pnpn  Rr": "Dilute Rusty Slate",
"Bb Ccg Dd n-  Rr Slsl": "Dilute Rusty Slate",
"Bb Ccg Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Ccg Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Ccm Dd n- Rr": "Dilute Rusty Slate",
"Bb Ccm Dd n- Pnpn Rr": "Dilute Rusty Slate",
"Bb Ccm Dd n- pnpn Rr": "Dilute Rusty Slate",
"Bb Ccm Dd n- Rr Slsl": "Dilute Rusty Slate",
"Bb Ccm Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Ccm Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Cc Dd n- Rr": "Dilute Rusty Slate",
"Bb Cc Dd n- Pnpn Rr": "Dilute Rusty Slate",
"Bb Cc Dd n- pnpn Rr": "Dilute Rusty Slate",
"Bb Cc Dd n- Rr Slsl": "Dilute Rusty Slate",
"Bb Cc Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb Cc Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb cgcg Dd n- Rr": "Dilute Rusty Slate",
"Bb cgcg Dd n- Pnpn Rr": "Dilute Rusty Slate",
"Bb cgcg Dd n- pnpn Rr": "Dilute Rusty Slate",
"Bb cgcg Dd n- Rr Slsl": "Dilute Rusty Slate",
"Bb cgcg Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb cgcg Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb cgcm Dd n- Rr": "Dilute Rusty Slate",
"Bb cgcm Dd n- Pnpn Rr": "Dilute Rusty Slate",
"Bb cgcm Dd n- pnpn Rr": "Dilute Rusty Slate",
"Bb cgcm Dd n- Rr Slsl": "Dilute Rusty Slate",
"Bb cgcm Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb cgcm Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
// Bb1
"Bb1 Dd nn Rr": "Dilute Rusty Slate",
"Bb1 Dd Ee nn Rr": "Dilute Rusty Slate",
"Bb1 Dd nn  Rr Slsl": "Dilute Rusty Slate",
"Bb1 Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Ccm Dd nn Rr": "Dilute Rusty Slate",
"Bb1 Ccm Dd Ee nn Rr": "Dilute Rusty Slate",
"Bb1 Ccm Dd nn  Rr Slsl": "Dilute Rusty Slate",
"Bb1 Ccm Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Ccm Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Ccm Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Ccm Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Cc Dd nn Rr": "Dilute Rusty Slate",
"Bb1 Cc Dd Ee nn Rr": "Dilute Rusty Slate",
"Bb1 Cc Dd nn  Rr Slsl": "Dilute Rusty Slate",
"Bb1 Cc Dd nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Cc Dd nn pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Cc Dd Ee nn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Cc Dd Ee nn Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Dd n- Rr": "Dilute Rusty Slate",
"Bb1 Dd n- Pnpn Rr": "Dilute Rusty Slate",
"Bb1 Dd n- pnpn Rr": "Dilute Rusty Slate",
"Bb1 Dd n- Rr Slsl": "Dilute Rusty Slate",
"Bb1 Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Ccm Dd n- Rr": "Dilute Rusty Slate",
"Bb1 Ccm Dd n- Pnpn Rr": "Dilute Rusty Slate",
"Bb1 Ccm Dd n- pnpn Rr": "Dilute Rusty Slate",
"Bb1 Ccm Dd n- Rr Slsl": "Dilute Rusty Slate",
"Bb1 Ccm Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Ccm Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Cc Dd n- Rr": "Dilute Rusty Slate",
"Bb1 Cc Dd n- Pnpn Rr": "Dilute Rusty Slate",
"Bb1 Cc Dd n- pnpn Rr": "Dilute Rusty Slate",
"Bb1 Cc Dd n- Rr Slsl": "Dilute Rusty Slate",
"Bb1 Cc Dd n- Pnpn Rr Slsl": "Dilute Rusty Slate",
"Bb1 Cc Dd n- pnpn Rr Slsl": "Dilute Rusty Slate",
// FALL FIRE
"b1b1 cgcg Rr": "Fall Fire",
"b1b1 cgcg Ee Rr": "Fall Fire",
"b1b1 cgcg Nn Rr": "Fall Fire",
"b1b1 cgcg Rr Slsl": "Fall Fire",
"b1b1 cgcg Ee Nn Rr": "Fall Fire",
"b1b1 cgcg Nn Rr Slsl": "Fall Fire",
"b1b1 cgcg Ee Nn Rr Slsl": "Fall Fire",
"b1b1 cgcm Rr": "Fall Fire",
"b1b1 cgcm Ee Rr": "Fall Fire",
"b1b1 cgcm Nn Rr": "Fall Fire",
"b1b1 cgcm Rr Slsl": "Fall Fire",
"b1b1 cgcm Ee Nn Rr": "Fall Fire",
"b1b1 cgcm Nn Rr Slsl": "Fall Fire",
"b1b1 cgcm Ee Nn Rr Slsl": "Fall Fire",
"b1b1 cgc Rr": "Fall Fire",
"b1b1 cgc Ee Rr": "Fall Fire",
"b1b1 cgc Nn Rr": "Fall Fire",
"b1b1 cgc Rr Slsl": "Fall Fire",
"b1b1 cgc Ee Nn Rr": "Fall Fire",
"b1b1 cgc Nn Rr Slsl": "Fall Fire",
"b1b1 cgc Ee Nn Rr Slsl": "Fall Fire",
// FROSTED DARK BLUE
"bb cgcg Dd nn Rr": "Frosted Dark Blue",
"bb cgcg Dd Ee nn Rr": "Frosted Dark Blue",
"bb cgcg Dd nn  Rr Slsl": "Frosted Dark Blue",
"bb cgcg Dd nn Pnpn Rr Slsl": "Frosted Dark Blue",
"bb cgcg Dd nn pnpn Rr Slsl": "Frosted Dark Blue",
"bb cgcg Dd nn Pnpn Rr": "Frosted Dark Blue",
"bb cgcg Dd nn pnpn Rr": "Frosted Dark Blue",
"bb cgcg Dd Ee nn Rr Slsl": "Frosted Dark Blue",
"bb cgcg Dd Ee nn Pnpn Rr Slsl": "Frosted Dark Blue",
"bb cgcm Dd nn Rr": "Frosted Dark Blue",
"bb cgcm Dd Ee nn Rr": "Frosted Dark Blue",
"bb cgcm Dd nn  Rr Slsl": "Frosted Dark Blue",
"bb cgcm Dd nn Pnpn Rr Slsl": "Frosted Dark Blue",
"bb cgcm Dd nn pnpn Rr Slsl": "Frosted Dark Blue",
"bb cgcm Dd Ee nn Rr Slsl": "Frosted Dark Blue",
"bb cgcm Dd Ee nn Pnpn Rr Slsl": "Frosted Dark Blue",
// FEMALES
"bb cgcg Dd n- Rr": "Frosted Dark Blue",
"bb cgcg Dd n- Pnpn Rr": "Frosted Dark Blue",
"bb cgcg Dd n- pnpn Rr": "Frosted Dark Blue",
"bb cgcg Dd n- Rr Slsl": "Frosted Dark Blue",
"bb cgcg Dd n- Pnpn Rr Slsl": "Frosted Dark Blue",
"bb cgcg Dd n- pnpn Rr Slsl": "Frosted Dark Blue",
"bb cgcm Dd n- Rr": "Frosted Dark Blue",
"bb cgcm Dd n- Pnpn Rr": "Frosted Dark Blue",
"bb cgcm Dd n- pnpn Rr": "Frosted Dark Blue",
"bb cgcm Dd n- Rr Slsl": "Frosted Dark Blue",
"bb cgcm Dd n- Pnpn Rr Slsl": "Frosted Dark Blue",
"bb cgcm Dd n- pnpn Rr Slsl": "Frosted Dark Blue",

// bb1
"bb1 cgcg Dd nn Rr": "Frosted Dark Blue",
"bb1 cgcg Dd Ee nn Rr": "Frosted Dark Blue",
"bb1 cgcg Dd nn  Rr Slsl": "Frosted Dark Blue",
"bb1 cgcg Dd nn Pnpn Rr Slsl": "Frosted Dark Blue",
"bb1 cgcg Dd nn pnpn Rr Slsl": "Frosted Dark Blue",
"bb1 cgcg Dd nn Pnpn Rr": "Frosted Dark Blue",
"bb1 cgcg Dd nn pnpn Rr": "Frosted Dark Blue",
"bb1 cgcg Dd Ee nn Rr Slsl": "Frosted Dark Blue",
"bb1 cgcg Dd Ee nn Pnpn Rr Slsl": "Frosted Dark Blue",
"bb1 cgcm Dd nn Rr": "Frosted Dark Blue",
"bb1 cgcm Dd Ee nn Rr": "Frosted Dark Blue",
"bb1 cgcm Dd nn  Rr Slsl": "Frosted Dark Blue",
"bb1 cgcm Dd nn Pnpn Rr Slsl": "Frosted Dark Blue",
"bb1 cgcm Dd nn pnpn Rr Slsl": "Frosted Dark Blue",
"bb1 cgcm Dd Ee nn Rr Slsl": "Frosted Dark Blue",
"bb1 cgcm Dd Ee nn Pnpn Rr Slsl": "Frosted Dark Blue",

// FEMALES
"bb1 cgcg Dd n- Rr": "Frosted Dark Blue",
"bb1 cgcg Dd n- Pnpn Rr": "Frosted Dark Blue",
"bb1 cgcg Dd n- pnpn Rr": "Frosted Dark Blue",
"bb1 cgcg Dd n- Rr Slsl": "Frosted Dark Blue",
"bb1 cgcg Dd n- Pnpn Rr Slsl": "Frosted Dark Blue",
"bb1 cgcg Dd n- pnpn Rr Slsl": "Frosted Dark Blue",
"bb1 cgcm Dd n- Rr": "Frosted Dark Blue",
"bb1 cgcm Dd n- Pnpn Rr": "Frosted Dark Blue",
"bb1 cgcm Dd n- pnpn Rr": "Frosted Dark Blue",
"bb1 cgcm Dd n- Rr Slsl": "Frosted Dark Blue",
"bb1 cgcm Dd n- Pnpn Rr Slsl": "Frosted Dark Blue",
"bb1 cgcm Dd n- pnpn Rr Slsl": "Frosted Dark Blue",


// FROSTED DARK BROWN
"bb cgcg ee nn Rr": "Frosted Dark Brown",
"bb cgcg ee nn Pnpn Rr": "Frosted Dark Brown",
"bb cgcg ee nn pnpn Rr": "Frosted Dark Brown",
"bb cgcg ee nn Rr Slsl": "Frosted Dark Brown",
"bb cgcg ee nn Pnpn Rr Slsl": "Frosted Dark Brown",
"bb cgcg ee nn pnpn Rr Slsl": "Frosted Dark Brown",
"bb cgcm ee nn Rr": "Frosted Dark Brown",
"bb cgcm ee nn Pnpn Rr": "Frosted Dark Brown",
"bb cgcm ee nn pnpn Rr": "Frosted Dark Brown",
"bb cgcm ee nn Rr Slsl": "Frosted Dark Brown",
"bb cgcm ee nn Pnpn Rr Slsl": "Frosted Dark Brown",
"bb cgcm ee nn pnpn Rr Slsl": "Frosted Dark Brown",
"bb cgcg e- n- Rr": "Frosted Dark Brown",
"bb cgcg e- n- Pnpn Rr": "Frosted Dark Brown",
"bb cgcg e- n- pnpn Rr": "Frosted Dark Brown",
"bb cgcg e- n- Rr Slsl": "Frosted Dark Brown",
"bb cgcg e- n- Pnpn Rr Slsl": "Frosted Dark Brown",
"bb cgcg e- n- pnpn Rr Slsl": "Frosted Dark Brown",
"bb cgcm e- n- Rr": "Frosted Dark Brown",
"bb cgcm e- n- Pnpn Rr": "Frosted Dark Brown",
"bb cgcm e- n- pnpn Rr": "Frosted Dark Brown",
"bb cgcm e- n- Rr Slsl": "Frosted Dark Brown",
"bb cgcm e- n- Pnpn Rr Slsl": "Frosted Dark Brown",
"bb cgcm e- n- pnpn Rr Slsl": "Frosted Dark Brown",
 // bb1 FROSTED DARK BROWN
"bb1 cgcg ee nn Rr": "Frosted Dark Brown",
"bb1 cgcg ee nn Pnpn Rr": "Frosted Dark Brown",
"bb1 cgcg ee nn pnpn Rr": "Frosted Dark Brown",
"bb1 cgcg ee nn Rr Slsl": "Frosted Dark Brown",
"bb1 cgcg ee nn Pnpn Rr Slsl": "Frosted Dark Brown",
"bb1 cgcg ee nn pnpn Rr Slsl": "Frosted Dark Brown",
"bb1 cgcm ee nn Rr": "Frosted Dark Brown",
"bb1 cgcm ee nn Pnpn Rr": "Frosted Dark Brown",
"bb1 cgcm ee nn pnpn Rr": "Frosted Dark Brown",
"bb1 cgcm ee nn Rr Slsl": "Frosted Dark Brown",
"bb1 cgcm ee nn Pnpn Rr Slsl": "Frosted Dark Brown",
"bb1 cgcm ee nn pnpn Rr Slsl": "Frosted Dark Brown",
"bb1 cgcg e- n- Rr": "Frosted Dark Brown",
"bb1 cgcg e- n- Pnpn Rr": "Frosted Dark Brown",
"bb1 cgcg e- n- pnpn Rr": "Frosted Dark Brown",
"bb1 cgcg e- n- Rr Slsl": "Frosted Dark Brown",
"bb1 cgcg e- n- Pnpn Rr Slsl": "Frosted Dark Brown",
"bb1 cgcg e- n- pnpn Rr Slsl": "Frosted Dark Brown",
"bb1 cgcm e- n- Rr": "Frosted Dark Brown",
"bb1 cgcm e- n- Pnpn Rr": "Frosted Dark Brown",
"bb1 cgcm e- n- pnpn Rr": "Frosted Dark Brown",
"bb1 cgcm e- n- Rr Slsl": "Frosted Dark Brown",
"bb1 cgcm e- n- Pnpn Rr Slsl": "Frosted Dark Brown",
"bb1 cgcm e- n- pnpn Rr Slsl": "Frosted Dark Brown",
 // FROSTED DARK GRAY
"bb cgcg nn Rr": "Frosted Dark Gray",
"bb cgcg Ee nn Rr": "Frosted Dark Gray",
"bb cgcg nn Rr Slsl": "Frosted Dark Gray",
"bb cgcg nn Pnpn Rr": "Frosted Dark Gray",
"bb cgcg nn pnpn Rr": "Frosted Dark Gray",
"bb cgcg Ee nn Rr Slsl": "Frosted Dark Gray",
"bb cgcg Ee nn Pnpn Rr": "Frosted Dark Gray",
"bb cgcg Ee nn pnpn Rr": "Frosted Dark Gray",
"bb cgcg Ee nn Pnpn Rr Slsl": "Frosted Dark Gray",
"bb cgcg Ee nn pnpn Rr Slsl": "Frosted Dark Gray",
"bb cgcg nn Pnpn Rr Slsl": "Frosted Dark Gray",
"bb cgcg nn pnpn Rr Slsl": "Frosted Dark Gray",
"bb cgcg n- Rr": "Frosted Dark Gray",
"bb cgcg n- Rr Slsl": "Frosted Dark Gray",
"bb cgcg n- Pnpn Rr": "Frosted Dark Gray",
"bb cgcg n- pnpn Rr": "Frosted Dark Gray",
"bb cgcg n- Pnpn Rr Slsl": "Frosted Dark Gray",
"bb cgcg n- pnpn Rr Slsl": "Frosted Dark Gray",
"bb cgcm nn Rr": "Frosted Dark Gray",
"bb cgcm Ee nn Rr": "Frosted Dark Gray",
"bb cgcm nn Rr Slsl": "Frosted Dark Gray",
"bb cgcm nn Pnpn Rr": "Frosted Dark Gray",
"bb cgcm nn pnpn Rr": "Frosted Dark Gray",
"bb cgcm Ee nn Rr Slsl": "Frosted Dark Gray",
"bb cgcm Ee nn Pnpn Rr": "Frosted Dark Gray",
"bb cgcm Ee nn pnpn Rr": "Frosted Dark Gray",
"bb cgcm Ee nn Pnpn Rr Slsl": "Frosted Dark Gray",
"bb cgcm Ee nn pnpn Rr Slsl": "Frosted Dark Gray",
"bb cgcm nn Pnpn Rr Slsl": "Frosted Dark Gray",
"bb cgcm nn pnpn Rr Slsl": "Frosted Dark Gray",
"bb cgcm n- Rr": "Frosted Dark Gray",
"bb cgcm n- Rr Slsl": "Frosted Dark Gray",
"bb cgcm n- Pnpn Rr": "Frosted Dark Gray",
"bb cgcm n- pnpn Rr": "Frosted Dark Gray",
"bb cgcm n- Pnpn Rr Slsl": "Frosted Dark Gray",
"bb cgcm n- pnpn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcg nn Rr": "Frosted Dark Gray",
"bb1 cgcg Ee nn Rr": "Frosted Dark Gray",
"bb1 cgcg nn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcg nn Pnpn Rr": "Frosted Dark Gray",
"bb1 cgcg nn pnpn Rr": "Frosted Dark Gray",
"bb1 cgcg Ee nn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcg Ee nn Pnpn Rr": "Frosted Dark Gray",
"bb1 cgcg Ee nn pnpn Rr": "Frosted Dark Gray",
"bb1 cgcg Ee nn Pnpn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcg Ee nn pnpn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcg nn Pnpn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcg nn pnpn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcg n- Rr": "Frosted Dark Gray",
"bb1 cgcg n- Rr Slsl": "Frosted Dark Gray",
"bb1 cgcg n- Pnpn Rr": "Frosted Dark Gray",
"bb1 cgcg n- pnpn Rr": "Frosted Dark Gray",
"bb1 cgcg n- Pnpn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcg n- pnpn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcm nn Rr": "Frosted Dark Gray",
"bb1 cgcm Ee nn Rr": "Frosted Dark Gray",
"bb1 cgcm nn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcm nn Pnpn Rr": "Frosted Dark Gray",
"bb1 cgcm nn pnpn Rr": "Frosted Dark Gray",
"bb1 cgcm Ee nn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcm Ee nn Pnpn Rr": "Frosted Dark Gray",
"bb1 cgcm Ee nn pnpn Rr": "Frosted Dark Gray",
"bb1 cgcm Ee nn Pnpn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcm Ee nn pnpn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcm nn Pnpn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcm nn pnpn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcm n- Rr": "Frosted Dark Gray",
"bb1 cgcm n- Rr Slsl": "Frosted Dark Gray",
"bb1 cgcm n- Pnpn Rr": "Frosted Dark Gray",
"bb1 cgcm n- pnpn Rr": "Frosted Dark Gray",
"bb1 cgcm n- Pnpn Rr Slsl": "Frosted Dark Gray",
"bb1 cgcm n- pnpn Rr Slsl": "Frosted Dark Gray",

// FROSTED DARK LAVENDER BLUE
"bb cgcg DD nn Rr": "Frosted Dark Lavender Blue",
"bb cgcg DD Ee nn Rr": "Frosted Dark Lavender Blue",
"bb cgcg DD nn  Rr Slsl": "Frosted Dark Lavender Blue",
"bb cgcg DD nn Pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb cgcg DD nn pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb cgcg DD Ee nn Rr Slsl": "Frosted Dark Lavender Blue",
"bb cgcg DD Ee nn Pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb cgcm DD nn Rr": "Frosted Dark Lavender Blue",
"bb cgcm DD Ee nn Rr": "Frosted Dark Lavender Blue",
"bb cgcm DD nn  Rr Slsl": "Frosted Dark Lavender Blue",
"bb cgcm DD nn Pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb cgcm DD nn pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb cgcm DD Ee nn Rr Slsl": "Frosted Dark Lavender Blue",
"bb cgcm DD Ee nn Pnpn Rr Slsl": "Frosted Dark Lavender Blue",

// FEMALES
"bb cgcg DD n- Rr": "Frosted Dark Lavender Blue",
"bb cgcg DD n- Pnpn Rr": "Frosted Dark Lavender Blue",
"bb cgcg DD n- pnpn Rr": "Frosted Dark Lavender Blue",
"bb cgcg DD n- Rr Slsl": "Frosted Dark Lavender Blue",
"bb cgcg DD n- Pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb cgcg DD n- pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb cgcm DD n- Rr": "Frosted Dark Lavender Blue",
"bb cgcm DD n- Pnpn Rr": "Frosted Dark Lavender Blue",
"bb cgcm DD n- pnpn Rr": "Frosted Dark Lavender Blue",
"bb cgcm DD n- Rr Slsl": "Frosted Dark Lavender Blue",
"bb cgcm DD n- Pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb cgcm DD n- pnpn Rr Slsl": "Frosted Dark Lavender Blue",

// bb1
"bb1 cgcg DD nn Rr": "Frosted Dark Lavender Blue",
"bb1 cgcg DD Ee nn Rr": "Frosted Dark Lavender Blue",
"bb1 cgcg DD nn  Rr Slsl": "Frosted Dark Lavender Blue",
"bb1 cgcg DD nn Pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb1 cgcg DD nn pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb1 cgcg DD Ee nn Rr Slsl": "Frosted Dark Lavender Blue",
"bb1 cgcg DD Ee nn Pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb1 cgcm DD nn Rr": "Frosted Dark Lavender Blue",
"bb1 cgcm DD Ee nn Rr": "Frosted Dark Lavender Blue",
"bb1 cgcm DD nn  Rr Slsl": "Frosted Dark Lavender Blue",
"bb1 cgcm DD nn Pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb1 cgcm DD nn pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb1 cgcm DD Ee nn Rr Slsl": "Frosted Dark Lavender Blue",
"bb1 cgcm DD Ee nn Pnpn Rr Slsl": "Frosted Dark Lavender Blue",

// FEMALES
"bb1 cgcg DD n- Rr": "Frosted Dark Lavender Blue",
"bb1 cgcg DD n- Pnpn Rr": "Frosted Dark Lavender Blue",
"bb1 cgcg DD n- pnpn Rr": "Frosted Dark Lavender Blue",
"bb1 cgcg DD n- Rr Slsl": "Frosted Dark Lavender Blue",
"bb1 cgcg DD n- Pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb1 cgcg DD n- pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb1 cgcm DD n- Rr": "Frosted Dark Lavender Blue",
"bb1 cgcm DD n- Pnpn Rr": "Frosted Dark Lavender Blue",
"bb1 cgcm DD n- pnpn Rr": "Frosted Dark Lavender Blue",
"bb1 cgcm DD n- Rr Slsl": "Frosted Dark Lavender Blue",
"bb1 cgcm DD n- Pnpn Rr Slsl": "Frosted Dark Lavender Blue",
"bb1 cgcm DD n- pnpn Rr Slsl": "Frosted Dark Lavender Blue",


// FROSTED OREGON BLUE
"bb cgc Dd nn Rr": "Frosted Oregon Blue",
"bb cgc Dd Ee nn Rr": "Frosted Oregon Blue",
"bb cgc Dd nn  Rr Slsl": "Frosted Oregon Blue",
"bb cgc Dd nn Pnpn Rr Slsl": "Frosted Oregon Blue",
"bb cgc Dd nn pnpn Rr Slsl": "Frosted Oregon Blue",
"bb cgc Dd nn Pnpn Rr": "Frosted Oregon Blue",
"bb cgc Dd nn pnpn Rr": "Frosted Oregon Blue",
"bb cgc Dd Ee nn Rr Slsl": "Frosted Oregon Blue",
"bb cgc Dd Ee nn Pnpn Rr Slsl": "Frosted Oregon Blue",
// FEMALES
"bb cgc Dd n- Rr": "Frosted Oregon Blue",
"bb cgc Dd n- Pnpn Rr": "Frosted Oregon Blue",
"bb cgc Dd n- pnpn Rr": "Frosted Oregon Blue",
"bb cgc Dd n- Rr Slsl": "Frosted Oregon Blue",
"bb cgc Dd n- Pnpn Rr Slsl": "Frosted Oregon Blue",
"bb cgc Dd n- pnpn Rr Slsl": "Frosted Oregon Blue",

// bb1
"bb1 cgc Dd nn Rr": "Frosted Oregon Blue",
"bb1 cgc Dd Ee nn Rr": "Frosted Oregon Blue",
"bb1 cgc Dd nn  Rr Slsl": "Frosted Oregon Blue",
"bb1 cgc Dd nn Pnpn Rr Slsl": "Frosted Oregon Blue",
"bb1 cgc Dd nn pnpn Rr Slsl": "Frosted Oregon Blue",
"bb1 cgc Dd nn Pnpn Rr": "Frosted Oregon Blue",
"bb1 cgc Dd nn pnpn Rr": "Frosted Oregon Blue",
"bb1 cgc Dd Ee nn Rr Slsl": "Frosted Oregon Blue",
"bb1 cgc Dd Ee nn Pnpn Rr Slsl": "Frosted Oregon Blue",

// FEMALES
"bb1 cgc Dd n- Rr": "Frosted Oregon Blue",
"bb1 cgc Dd n- Pnpn Rr": "Frosted Oregon Blue",
"bb1 cgc Dd n- pnpn Rr": "Frosted Oregon Blue",
"bb1 cgc Dd n- Rr Slsl": "Frosted Oregon Blue",
"bb1 cgc Dd n- Pnpn Rr Slsl": "Frosted Oregon Blue",
"bb1 cgc Dd n- pnpn Rr Slsl": "Frosted Oregon Blue",

// FROSTED OREGON BROWN
"bb cgc ee nn Rr": "Frosted Oregon Brown",
"bb cgc ee nn Pnpn Rr": "Frosted Oregon Brown",
"bb cgc ee nn pnpn Rr": "Frosted Oregon Brown",
"bb cgc ee nn Rr Slsl": "Frosted Oregon Brown",
"bb cgc ee nn Pnpn Rr Slsl": "Frosted Oregon Brown",
"bb cgc ee nn pnpn Rr Slsl": "Frosted Oregon Brown",
"bb cgc e- n- Rr": "Frosted Oregon Brown",
"bb cgc e- n- Pnpn Rr": "Frosted Oregon Brown",
"bb cgc e- n- pnpn Rr": "Frosted Oregon Brown",
"bb cgc e- n- Rr Slsl": "Frosted Oregon Brown",
"bb cgc e- n- Pnpn Rr Slsl": "Frosted Oregon Brown",
"bb cgc e- n- pnpn Rr Slsl": "Frosted Oregon Brown",
"bb1 cgc ee nn Rr": "Frosted Oregon Brown",
"bb1 cgc ee nn Pnpn Rr": "Frosted Oregon Brown",
"bb1 cgc ee nn pnpn Rr": "Frosted Oregon Brown",
"bb1 cgc ee nn Rr Slsl": "Frosted Oregon Brown",
"bb1 cgc ee nn Pnpn Rr Slsl": "Frosted Oregon Brown",
"bb1 cgc ee nn pnpn Rr Slsl": "Frosted Oregon Brown",
"bb1 cgc e- n- Rr": "Frosted Oregon Brown",
"bb1 cgc e- n- Pnpn Rr": "Frosted Oregon Brown",
"bb1 cgc e- n- pnpn Rr": "Frosted Oregon Brown",
"bb1 cgc e- n- Rr Slsl": "Frosted Oregon Brown",
"bb1 cgc e- n- Pnpn Rr Slsl": "Frosted Oregon Brown",
"bb1 cgc e- n- pnpn Rr Slsl": "Frosted Oregon Brown",
 // FROSTED OREGON GRAY
"bb cgc nn Rr": "Frosted Oregon Gray",
"bb cgc Ee nn Rr": "Frosted Oregon Gray",
"bb cgc nn Rr Slsl": "Frosted Oregon Gray",
"bb cgc nn Pnpn Rr": "Frosted Oregon Gray",
"bb cgc nn pnpn Rr": "Frosted Oregon Gray",
"bb cgc Ee nn Rr Slsl": "Frosted Oregon Gray",
"bb cgc Ee nn Pnpn Rr": "Frosted Oregon Gray",
"bb cgc Ee nn pnpn Rr": "Frosted Oregon Gray",
"bb cgc Ee nn Pnpn Rr Slsl": "Frosted Oregon Gray",
"bb cgc Ee nn pnpn Rr Slsl": "Frosted Oregon Gray",
"bb cgc nn Pnpn Rr Slsl": "Frosted Oregon Gray",
"bb cgc nn pnpn Rr Slsl": "Frosted Oregon Gray",
"bb cgc n- Rr": "Frosted Oregon Gray",
"bb cgc n- Rr Slsl": "Frosted Oregon Gray",
"bb cgc n- Pnpn Rr": "Frosted Oregon Gray",
"bb cgc n- pnpn Rr": "Frosted Oregon Gray",
"bb cgc n- Pnpn Rr Slsl": "Frosted Oregon Gray",
"bb cgc n- pnpn Rr Slsl": "Frosted Oregon Gray",
"bb1 cgc nn Rr": "Frosted Oregon Gray",
"bb1 cgc Ee nn Rr": "Frosted Oregon Gray",
"bb1 cgc nn Rr Slsl": "Frosted Oregon Gray",
"bb1 cgc nn Pnpn Rr": "Frosted Oregon Gray",
"bb1 cgc nn pnpn Rr": "Frosted Oregon Gray",
"bb1 cgc Ee nn Rr Slsl": "Frosted Oregon Gray",
"bb1 cgc Ee nn Pnpn Rr": "Frosted Oregon Gray",
"bb1 cgc Ee nn pnpn Rr": "Frosted Oregon Gray",
"bb1 cgc Ee nn Pnpn Rr Slsl": "Frosted Oregon Gray",
"bb1 cgc Ee nn pnpn Rr Slsl": "Frosted Oregon Gray",
"bb1 cgc nn Pnpn Rr Slsl": "Frosted Oregon Gray",
"bb1 cgc nn pnpn Rr Slsl": "Frosted Oregon Gray",
"bb1 cgc n- Rr": "Frosted Oregon Gray",
"bb1 cgc n- Rr Slsl": "Frosted Oregon Gray",
"bb1 cgc n- Pnpn Rr": "Frosted Oregon Gray",
"bb1 cgc n- pnpn Rr": "Frosted Oregon Gray",
"bb1 cgc n- Pnpn Rr Slsl": "Frosted Oregon Gray",
"bb1 cgc n- pnpn Rr Slsl": "Frosted Oregon Gray",

// FROSTED OREGON LAVENDER BLUE
"bb cgc DD nn Rr": "Frosted Oregon Lavender Blue",
"bb cgc DD Ee nn Rr": "Frosted Oregon Lavender Blue",
"bb cgc DD nn  Rr Slsl": "Frosted Oregon Lavender Blue",
"bb cgc DD nn Pnpn Rr Slsl": "Frosted Oregon Lavender Blue",
"bb cgc DD nn pnpn Rr Slsl": "Frosted Oregon Lavender Blue",
"bb cgc DD Ee nn Rr Slsl": "Frosted Oregon Lavender Blue",
"bb cgc DD Ee nn Pnpn Rr Slsl": "Frosted Oregon Lavender Blue",

// FEMALES
"bb cgc DD n- Rr": "Frosted Oregon Lavender Blue",
"bb cgc DD n- Pnpn Rr": "Frosted Oregon Lavender Blue",
"bb cgc DD n- pnpn Rr": "Frosted Oregon Lavender Blue",
"bb cgc DD n- Rr Slsl": "Frosted Oregon Lavender Blue",
"bb cgc DD n- Pnpn Rr Slsl": "Frosted Oregon Lavender Blue",
"bb cgc DD n- pnpn Rr Slsl": "Frosted Oregon Lavender Blue",

// bb1
"bb1 cgc DD nn Rr": "Frosted Oregon Lavender Blue",
"bb1 cgc DD Ee nn Rr": "Frosted Oregon Lavender Blue",
"bb1 cgc DD nn  Rr Slsl": "Frosted Oregon Lavender Blue",
"bb1 cgc DD nn Pnpn Rr Slsl": "Frosted Oregon Lavender Blue",
"bb1 cgc DD nn pnpn Rr Slsl": "Frosted Oregon Lavender Blue",
"bb1 cgc DD Ee nn Rr Slsl": "Frosted Oregon Lavender Blue",
"bb1 cgc DD Ee nn Pnpn Rr Slsl": "Frosted Oregon Lavender Blue",

// FEMALES
"bb1 cgc DD n- Rr": "Frosted Oregon Lavender Blue",
"bb1 cgc DD n- Pnpn Rr": "Frosted Oregon Lavender Blue",
"bb1 cgc DD n- pnpn Rr": "Frosted Oregon Lavender Blue",
"bb1 cgc DD n- Rr Slsl": "Frosted Oregon Lavender Blue",
"bb1 cgc DD n- Pnpn Rr Slsl": "Frosted Oregon Lavender Blue",
"bb1 cgc DD n- pnpn Rr Slsl": "Frosted Oregon Lavender Blue",






};
