 // bb HARVEY SPECKLED, done ***
const phenotypeMapping99 = {
"bb cc fdfd rr": "Harvey Speckled",
"bb cc Ee fdfd rr": "Harvey Speckled",
"bb cc fdfd Nn rr": "Harvey Speckled",
"bb cc fdfd rr Slsl": "Harvey Speckled",
"bb cc fdfd Pnpn rr": "Harvey Speckled",
"bb cc fdfd pnpn rr": "Harvey Speckled",
"bb cc Ee fdfd Nn rr": "Harvey Speckled",
"bb cc Ee fdfd rr Slsl": "Harvey Speckled",
"bb cc Ee fdfd Pnpn rr": "Harvey Speckled",
"bb cc Ee fdfd pnpn rr": "Harvey Speckled",
"bb cc fdfd Nn Pnpn rr": "Harvey Speckled",
"bb cc fdfd Nn pnpn rr": "Harvey Speckled",
"bb cc fdfd Nn rr Slsl": "Harvey Speckled",
"bb cc fdfd Nn Pnpn rr Slsl": "Harvey Speckled",
"bb cc fdfd Nn pnpn rr Slsl": "Harvey Speckled",
"bb cc Ee fdfd Nn Pnpn rr": "Harvey Speckled",
"bb cc Ee fdfd Nn rr Slsl": "Harvey Speckled",
"bb cc Ee fdfd Nn Pnpn rr Slsl": "Harvey Speckled",
"bb cc Ee fdfd Nn pnpn rr Slsl": "Harvey Speckled",
"bb cc fdfd Pnpn rr Slsl": "Harvey Speckled",
"bb cc fdfd pnpn rr Slsl": "Harvey Speckled",
"bb cc fdfd rr Spsp": "Harvey Speckled",
"bb cc Ee fdfd rr Spsp": "Harvey Speckled",
"bb cc fdfd Nn rr Spsp": "Harvey Speckled",
"bb cc fdfd rr Slsl Spsp": "Harvey Speckled",
"bb cc fdfd Pnpn rr Spsp": "Harvey Speckled",
"bb cc fdfd pnpn rr Spsp": "Harvey Speckled",
"bb cc Ee fdfd Nn rr Spsp": "Harvey Speckled",
"bb cc Ee fdfd rr Slsl Spsp": "Harvey Speckled",
"bb cc Ee fdfd Pnpn rr Spsp": "Harvey Speckled",
"bb cc Ee fdfd pnpn rr Spsp": "Harvey Speckled",
"bb cc fdfd Nn Pnpn rr Spsp": "Harvey Speckled",
"bb cc fdfd Nn pnpn rr Spsp": "Harvey Speckled",
"bb cc fdfd Nn rr Slsl Spsp": "Harvey Speckled",
"bb cc fdfd Nn Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc fdfd Nn pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc Ee fdfd Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc Ee fdfd pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc fdfd Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc fdfd pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc Ee fdfd Nn Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc Ee fdfd Nn pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc Ee fdfd Nn Pnpn rr Spsp": "Harvey Speckled",
"bb cc Ee fdfd Nn pnpn rr Spsp": "Harvey Speckled",
"bb cc Ee fdfd Nn rr Slsl Spsp": "Harvey Speckled",
"bb cc Ee fdfd Pnpn rr Slsl": "Harvey Speckled",
"bb cc Ee fdfd pnpn rr Slsl": "Harvey Speckled",


// spsp HARVEY SPECKLED, done***
"bb cc fdfd rr spsp": "Harvey Speckled",
"bb cc Ee fdfd rr spsp": "Harvey Speckled",
"bb cc fdfd Nn rr spsp": "Harvey Speckled",
"bb cc fdfd rr Slsl spsp": "Harvey Speckled",
"bb cc fdfd Pnpn rr spsp": "Harvey Speckled",
"bb cc fdfd pnpn rr spsp": "Harvey Speckled",
"bb cc Ee fdfd Nn rr spsp": "Harvey Speckled",
"bb cc Ee fdfd rr Slsl spsp": "Harvey Speckled",
"bb cc Ee fdfd Pnpn rr spsp": "Harvey Speckled",
"bb cc Ee fdfd pnpn rr spsp": "Harvey Speckled",
"bb cc fdfd Nn Pnpn rr spsp": "Harvey Speckled",
"bb cc fdfd Nn pnpn rr spsp": "Harvey Speckled",
"bb cc fdfd Nn rr Slsl spsp": "Harvey Speckled",
"bb cc fdfd Nn Pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc fdfd Nn pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc Ee fdfd Nn Pnpn rr spsp": "Harvey Speckled",
"bb cc Ee fdfd Nn rr Slsl spsp": "Harvey Speckled",
"bb cc Ee fdfd Nn Pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc Ee fdfd Nn pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc fdfd Pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc fdfd pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc Ee fdfd Pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc Ee fdfd pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc Ee fdfd Nn pnpn rr spsp": "Harvey Speckled",



// bb1 HARVEY SPECKLED, done ***
"bb1 cc fdfd rr": "Harvey Speckled",
"bb1 cc Ee fdfd rr": "Harvey Speckled",
"bb1 cc fdfd Nn rr": "Harvey Speckled",
"bb1 cc fdfd rr Slsl": "Harvey Speckled",
"bb1 cc fdfd Pnpn rr": "Harvey Speckled",
"bb1 cc fdfd pnpn rr": "Harvey Speckled",
"bb1 cc Ee fdfd Nn rr": "Harvey Speckled",
"bb1 cc Ee fdfd rr Slsl": "Harvey Speckled",
"bb1 cc Ee fdfd Pnpn rr": "Harvey Speckled",
"bb1 cc Ee fdfd pnpn rr": "Harvey Speckled",
"bb1 cc fdfd Nn Pnpn rr": "Harvey Speckled",
"bb1 cc fdfd Nn pnpn rr": "Harvey Speckled",
"bb1 cc fdfd Nn rr Slsl": "Harvey Speckled",
"bb1 cc fdfd Nn Pnpn rr Slsl": "Harvey Speckled",
"bb1 cc fdfd Nn pnpn rr Slsl": "Harvey Speckled",
"bb1 cc Ee fdfd Nn Pnpn rr": "Harvey Speckled",
"bb1 cc Ee fdfd Nn rr Slsl": "Harvey Speckled",
"bb1 cc Ee fdfd Nn Pnpn rr Slsl": "Harvey Speckled",
"bb1 cc Ee fdfd Nn pnpn rr Slsl": "Harvey Speckled",
"bb1 cc fdfd Pnpn rr Slsl": "Harvey Speckled",
"bb1 cc fdfd pnpn rr Slsl": "Harvey Speckled",
"bb1 cc fdfd rr Spsp": "Harvey Speckled",
"bb1 cc Ee fdfd rr Spsp": "Harvey Speckled",
"bb1 cc fdfd Nn rr Spsp": "Harvey Speckled",
"bb1 cc fdfd rr Slsl Spsp": "Harvey Speckled",
"bb1 cc fdfd Pnpn rr Spsp": "Harvey Speckled",
"bb1 cc fdfd pnpn rr Spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Nn rr Spsp": "Harvey Speckled",
"bb1 cc Ee fdfd rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Pnpn rr Spsp": "Harvey Speckled",
"bb1 cc Ee fdfd pnpn rr Spsp": "Harvey Speckled",
"bb1 cc fdfd Nn Pnpn rr Spsp": "Harvey Speckled",
"bb1 cc fdfd Nn pnpn rr Spsp": "Harvey Speckled",
"bb1 cc fdfd Nn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc fdfd Nn Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc fdfd Nn pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Ee fdfd pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc fdfd Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc fdfd pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Nn Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Nn pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Nn Pnpn rr Spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Nn pnpn rr Spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Nn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Pnpn rr Slsl": "Harvey Speckled",
"bb1 cc Ee fdfd pnpn rr Slsl": "Harvey Speckled",


// spsp HARVEY SPECKLED, done***
"bb1 cc fdfd rr spsp": "Harvey Speckled",
"bb1 cc Ee fdfd rr spsp": "Harvey Speckled",
"bb1 cc fdfd Nn rr spsp": "Harvey Speckled",
"bb1 cc fdfd rr Slsl spsp": "Harvey Speckled",
"bb1 cc fdfd Pnpn rr spsp": "Harvey Speckled",
"bb1 cc fdfd pnpn rr spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Nn rr spsp": "Harvey Speckled",
"bb1 cc Ee fdfd rr Slsl spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Pnpn rr spsp": "Harvey Speckled",
"bb1 cc Ee fdfd pnpn rr spsp": "Harvey Speckled",
"bb1 cc fdfd Nn Pnpn rr spsp": "Harvey Speckled",
"bb1 cc fdfd Nn pnpn rr spsp": "Harvey Speckled",
"bb1 cc fdfd Nn rr Slsl spsp": "Harvey Speckled",
"bb1 cc fdfd Nn Pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc fdfd Nn pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Nn Pnpn rr spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Nn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Nn Pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Nn pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc fdfd Pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc fdfd pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Ee fdfd pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Ee fdfd Nn pnpn rr spsp": "Harvey Speckled",
  
  
  // bb Fdfd HARVEY SPECKLED, done ***
"bb cc Fdfd rr": "Harvey Speckled",
"bb cc Ee Fdfd rr": "Harvey Speckled",
"bb cc Fdfd Nn rr": "Harvey Speckled",
"bb cc Fdfd rr Slsl": "Harvey Speckled",
"bb cc Fdfd Pnpn rr": "Harvey Speckled",
"bb cc Fdfd pnpn rr": "Harvey Speckled",
"bb cc Ee Fdfd Nn rr": "Harvey Speckled",
"bb cc Ee Fdfd rr Slsl": "Harvey Speckled",
"bb cc Ee Fdfd Pnpn rr": "Harvey Speckled",
"bb cc Ee Fdfd pnpn rr": "Harvey Speckled",
"bb cc Fdfd Nn Pnpn rr": "Harvey Speckled",
"bb cc Fdfd Nn pnpn rr": "Harvey Speckled",
"bb cc Fdfd Nn rr Slsl": "Harvey Speckled",
"bb cc Fdfd Nn Pnpn rr Slsl": "Harvey Speckled",
"bb cc Fdfd Nn pnpn rr Slsl": "Harvey Speckled",
"bb cc Ee Fdfd Nn Pnpn rr": "Harvey Speckled",
"bb cc Ee Fdfd Nn rr Slsl": "Harvey Speckled",
"bb cc Ee Fdfd Nn Pnpn rr Slsl": "Harvey Speckled",
"bb cc Ee Fdfd Nn pnpn rr Slsl": "Harvey Speckled",
"bb cc Fdfd Pnpn rr Slsl": "Harvey Speckled",
"bb cc Fdfd pnpn rr Slsl": "Harvey Speckled",
"bb cc Fdfd rr Spsp": "Harvey Speckled",
"bb cc Ee Fdfd rr Spsp": "Harvey Speckled",
"bb cc Fdfd Nn rr Spsp": "Harvey Speckled",
"bb cc Fdfd rr Slsl Spsp": "Harvey Speckled",
"bb cc Fdfd Pnpn rr Spsp": "Harvey Speckled",
"bb cc Fdfd pnpn rr Spsp": "Harvey Speckled",
"bb cc Ee Fdfd Nn rr Spsp": "Harvey Speckled",
"bb cc Ee Fdfd rr Slsl Spsp": "Harvey Speckled",
"bb cc Ee Fdfd Pnpn rr Spsp": "Harvey Speckled",
"bb cc Ee Fdfd pnpn rr Spsp": "Harvey Speckled",
"bb cc Fdfd Nn Pnpn rr Spsp": "Harvey Speckled",
"bb cc Fdfd Nn pnpn rr Spsp": "Harvey Speckled",
"bb cc Fdfd Nn rr Slsl Spsp": "Harvey Speckled",
"bb cc Fdfd Nn Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc Fdfd Nn pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc Ee Fdfd Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc Ee Fdfd pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc Fdfd Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc Fdfd pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc Ee Fdfd Nn Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc Ee Fdfd Nn pnpn rr Slsl Spsp": "Harvey Speckled",
"bb cc Ee Fdfd Nn Pnpn rr Spsp": "Harvey Speckled",
"bb cc Ee Fdfd Nn pnpn rr Spsp": "Harvey Speckled",
"bb cc Ee Fdfd Nn rr Slsl Spsp": "Harvey Speckled",
"bb cc Ee Fdfd Pnpn rr Slsl": "Harvey Speckled",
"bb cc Ee Fdfd pnpn rr Slsl": "Harvey Speckled",


//bb Fdfd spsp HARVEY SPECKLED, done***
"bb cc Fdfd rr spsp": "Harvey Speckled",
"bb cc Ee Fdfd rr spsp": "Harvey Speckled",
"bb cc Fdfd Nn rr spsp": "Harvey Speckled",
"bb cc Fdfd rr Slsl spsp": "Harvey Speckled",
"bb cc Fdfd Pnpn rr spsp": "Harvey Speckled",
"bb cc Fdfd pnpn rr spsp": "Harvey Speckled",
"bb cc Ee Fdfd Nn rr spsp": "Harvey Speckled",
"bb cc Ee Fdfd rr Slsl spsp": "Harvey Speckled",
"bb cc Ee Fdfd Pnpn rr spsp": "Harvey Speckled",
"bb cc Ee Fdfd pnpn rr spsp": "Harvey Speckled",
"bb cc Fdfd Nn Pnpn rr spsp": "Harvey Speckled",
"bb cc Fdfd Nn pnpn rr spsp": "Harvey Speckled",
"bb cc Fdfd Nn rr Slsl spsp": "Harvey Speckled",
"bb cc Fdfd Nn Pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc Fdfd Nn pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc Ee Fdfd Nn Pnpn rr spsp": "Harvey Speckled",
"bb cc Ee Fdfd Nn rr Slsl spsp": "Harvey Speckled",
"bb cc Ee Fdfd Nn Pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc Ee Fdfd Nn pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc Fdfd Pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc Fdfd pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc Ee Fdfd Pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc Ee Fdfd pnpn rr Slsl spsp": "Harvey Speckled",
"bb cc Ee Fdfd Nn pnpn rr spsp": "Harvey Speckled",

  // bb1 Fdfd HARVEY SPECKLED, done ***
"bb1 cc Fdfd rr": "Harvey Speckled",
"bb1 cc Ee Fdfd rr": "Harvey Speckled",
"bb1 cc Fdfd Nn rr": "Harvey Speckled",
"bb1 cc Fdfd rr Slsl": "Harvey Speckled",
"bb1 cc Fdfd Pnpn rr": "Harvey Speckled",
"bb1 cc Fdfd pnpn rr": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn rr": "Harvey Speckled",
"bb1 cc Ee Fdfd rr Slsl": "Harvey Speckled",
"bb1 cc Ee Fdfd Pnpn rr": "Harvey Speckled",
"bb1 cc Ee Fdfd pnpn rr": "Harvey Speckled",
"bb1 cc Fdfd Nn Pnpn rr": "Harvey Speckled",
"bb1 cc Fdfd Nn pnpn rr": "Harvey Speckled",
"bb1 cc Fdfd Nn rr Slsl": "Harvey Speckled",
"bb1 cc Fdfd Nn Pnpn rr Slsl": "Harvey Speckled",
"bb1 cc Fdfd Nn pnpn rr Slsl": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn Pnpn rr": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn rr Slsl": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn Pnpn rr Slsl": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn pnpn rr Slsl": "Harvey Speckled",
"bb1 cc Fdfd Pnpn rr Slsl": "Harvey Speckled",
"bb1 cc Fdfd pnpn rr Slsl": "Harvey Speckled",
"bb1 cc Fdfd rr Spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd rr Spsp": "Harvey Speckled",
"bb1 cc Fdfd Nn rr Spsp": "Harvey Speckled",
"bb1 cc Fdfd rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Fdfd Pnpn rr Spsp": "Harvey Speckled",
"bb1 cc Fdfd pnpn rr Spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn rr Spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Pnpn rr Spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd pnpn rr Spsp": "Harvey Speckled",
"bb1 cc Fdfd Nn Pnpn rr Spsp": "Harvey Speckled",
"bb1 cc Fdfd Nn pnpn rr Spsp": "Harvey Speckled",
"bb1 cc Fdfd Nn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Fdfd Nn Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Fdfd Nn pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Fdfd Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Fdfd pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn Pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn pnpn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn Pnpn rr Spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn pnpn rr Spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn rr Slsl Spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Pnpn rr Slsl": "Harvey Speckled",
"bb1 cc Ee Fdfd pnpn rr Slsl": "Harvey Speckled",


//  bb1 Fdfd spsp HARVEY SPECKLED, done***
"bb1 cc Fdfd rr spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd rr spsp": "Harvey Speckled",
"bb1 cc Fdfd Nn rr spsp": "Harvey Speckled",
"bb1 cc Fdfd rr Slsl spsp": "Harvey Speckled",
"bb1 cc Fdfd Pnpn rr spsp": "Harvey Speckled",
"bb1 cc Fdfd pnpn rr spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn rr spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd rr Slsl spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Pnpn rr spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd pnpn rr spsp": "Harvey Speckled",
"bb1 cc Fdfd Nn Pnpn rr spsp": "Harvey Speckled",
"bb1 cc Fdfd Nn pnpn rr spsp": "Harvey Speckled",
"bb1 cc Fdfd Nn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Fdfd Nn Pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Fdfd Nn pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn Pnpn rr spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn Pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Fdfd Pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Fdfd pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd pnpn rr Slsl spsp": "Harvey Speckled",
"bb1 cc Ee Fdfd Nn pnpn rr spsp": "Harvey Speckled",

 // RECESSIVE BLUE HARVEY SPECKLED
"bb cc fdfd rr slsl": "Recessive Blue Harvey Speckled",
"bb cc Ee fdfd rr slsl": "Recessive Blue Harvey Speckled",
"bb cc fdfd Nn rr slsl": "Recessive Blue Harvey Speckled",
"bb cc fdfd Pnpn rr slsl": "Recessive Blue Harvey Speckled",
"bb cc fdfd pnpn rr slsl": "Recessive Blue Harvey Speckled",
"bb cc Ee fdfd Nn rr slsl": "Recessive Blue Harvey Speckled",
"bb cc Ee fdfd Pnpn rr slsl": "Recessive Blue Harvey Speckled",
"bb cc Ee fdfd pnpn rr slsl": "Recessive Blue Harvey Speckled",
"bb cc fdfd Nn Pnpn rr slsl": "Recessive Blue Harvey Speckled",
"bb cc fdfd Nn pnpn rr slsl": "Recessive Blue Harvey Speckled",
"bb cc Ee fdfd Nn Pnpn rr slsl": "Recessive Blue Harvey Speckled",
"bb cc Ee fdfd Nn pnpn rr slsl": "Recessive Blue Harvey Speckled",
"bb cc fdfd rr slsl Spsp": "Recessive Blue Harvey Speckled",
"bb cc Ee fdfd rr slsl Spsp": "Recessive Blue Harvey Speckled",
"bb cc fdfd Nn rr slsl Spsp": "Recessive Blue Harvey Speckled",
"bb cc fdfd Pnpn rr slsl Spsp": "Recessive Blue Harvey Speckled",
"bb cc fdfd pnpn rr slsl Spsp": "Recessive Blue Harvey Speckled",
"bb cc Ee fdfd Nn rr slsl Spsp": "Recessive Blue Harvey Speckled",
"bb cc Ee fdfd Pnpn rr slsl Spsp": "Recessive Blue Harvey Speckled",
"bb cc Ee fdfd pnpn rr slsl Spsp": "Recessive Blue Harvey Speckled",
"bb cc fdfd Nn Pnpn rr slsl Spsp": "Recessive Blue Harvey Speckled",
"bb cc fdfd Nn pnpn rr slsl Spsp": "Recessive Blue Harvey Speckled",
"bb cc Ee fdfd Nn Pnpn rr slsl Spsp": "Recessive Blue Harvey Speckled",
"bb cc Ee fdfd Nn pnpn rr slsl Spsp": "Recessive Blue Harvey Speckled",




};
