// Misc
const phenotypeMapping13 = {

// BARRED CHOCOLATE SLATE
"Bb Dd ee": "Barred Chocolate Slate",
"Bb Dd ee Nn": "Barred Chocolate Slate",
"Bb Dd ee Nn Pnpn": "Barred Chocolate Slate",
"Bb Dd ee Nn Slsl": "Barred Chocolate Slate",
"Bb Dd ee Nn pnpn": "Barred Chocolate Slate",
"Bb Dd ee Pnpn": "Barred Chocolate Slate",
"Bb Dd ee Pnpn Slsl": "Barred Chocolate Slate",
"Bb Dd ee pnpn": "Barred Chocolate Slate",
"Bb Dd ee pnpn Slsl": "Barred Chocolate Slate",
"Bb Ccg Dd ee": "Barred Chocolate Slate",
"Bb Ccg Dd ee Nn": "Barred Chocolate Slate",
"Bb Ccg Dd ee Nn Pnpn": "Barred Chocolate Slate",
"Bb Ccg Dd ee Nn Slsl": "Barred Chocolate Slate",
"Bb Ccg Dd ee Nn pnpn": "Barred Chocolate Slate",
"Bb Ccg Dd ee Pnpn": "Barred Chocolate Slate",
"Bb Ccg Dd ee Pnpn Slsl": "Barred Chocolate Slate",
"Bb Ccg Dd ee pnpn": "Barred Chocolate Slate",
"Bb Ccg Dd ee pnpn Slsl": "Barred Chocolate Slate",
"Bb Ccm Dd ee": "Barred Chocolate Slate",
"Bb Ccm Dd ee Nn": "Barred Chocolate Slate",
"Bb Ccm Dd ee Nn Pnpn": "Barred Chocolate Slate",
"Bb Ccm Dd ee Nn Slsl": "Barred Chocolate Slate",
"Bb Ccm Dd ee Nn pnpn": "Barred Chocolate Slate",
"Bb Ccm Dd ee Pnpn": "Barred Chocolate Slate",
"Bb Ccm Dd ee Pnpn Slsl": "Barred Chocolate Slate",
"Bb Ccm Dd ee pnpn": "Barred Chocolate Slate",
"Bb Ccm Dd ee pnpn Slsl": "Barred Chocolate Slate",
"Bb Cc Dd ee": "Barred Chocolate Slate",
"Bb Cc Dd ee Nn": "Barred Chocolate Slate",
"Bb Cc Dd ee Nn Pnpn": "Barred Chocolate Slate",
"Bb Cc Dd ee Nn Slsl": "Barred Chocolate Slate",
"Bb Cc Dd ee Nn pnpn": "Barred Chocolate Slate",
"Bb Cc Dd ee Pnpn": "Barred Chocolate Slate",
"Bb Cc Dd ee Pnpn Slsl": "Barred Chocolate Slate",
"Bb Cc Dd ee pnpn": "Barred Chocolate Slate",
"Bb Cc Dd ee pnpn Slsl": "Barred Chocolate Slate",
"Bb cgcg Dd ee": "Barred Chocolate Slate",
"Bb cgcg Dd ee Nn": "Barred Chocolate Slate",
"Bb cgcg Dd ee Nn Pnpn": "Barred Chocolate Slate",
"Bb cgcg Dd ee Nn Slsl": "Barred Chocolate Slate",
"Bb cgcg Dd ee Nn pnpn": "Barred Chocolate Slate",
"Bb cgcg Dd ee Pnpn": "Barred Chocolate Slate",
"Bb cgcg Dd ee Pnpn Slsl": "Barred Chocolate Slate",
"Bb cgcg Dd ee pnpn": "Barred Chocolate Slate",
"Bb cgcg Dd ee pnpn Slsl": "Barred Chocolate Slate",
"Bb cgcm Dd ee": "Barred Chocolate Slate",
"Bb cgcm Dd ee Nn": "Barred Chocolate Slate",
"Bb cgcm Dd ee Nn Pnpn": "Barred Chocolate Slate",
"Bb cgcm Dd ee Nn Slsl": "Barred Chocolate Slate",
"Bb cgcm Dd ee Nn pnpn": "Barred Chocolate Slate",
"Bb cgcm Dd ee Pnpn": "Barred Chocolate Slate",
"Bb cgcm Dd ee Pnpn Slsl": "Barred Chocolate Slate",
"Bb cgcm Dd ee pnpn": "Barred Chocolate Slate",
"Bb cgcm Dd ee pnpn Slsl": "Barred Chocolate Slate",
"Bb cgc Dd ee": "Barred Chocolate Slate",
"Bb cgc Dd ee Nn": "Barred Chocolate Slate",
"Bb cgc Dd ee Nn Pnpn": "Barred Chocolate Slate",
"Bb cgc Dd ee Nn Slsl": "Barred Chocolate Slate",
"Bb cgc Dd ee Nn pnpn": "Barred Chocolate Slate",
"Bb cgc Dd ee Pnpn": "Barred Chocolate Slate",
"Bb cgc Dd ee Pnpn Slsl": "Barred Chocolate Slate",
"Bb cgc Dd ee pnpn": "Barred Chocolate Slate",
"Bb cgc Dd ee pnpn Slsl": "Barred Chocolate Slate",
"Bb Dd e-": "Barred Chocolate Slate",
"Bb Dd e- Slsl": "Barred Chocolate Slate",
"Bb Dd e- Pnpn": "Barred Chocolate Slate",
"Bb Dd e- pnpn": "Barred Chocolate Slate",
"Bb Dd e- Pnpn Slsl": "Barred Chocolate Slate",
"Bb Dd e- pnpn Slsl": "Barred Chocolate Slate",
"Bb Ccg Dd e-": "Barred Chocolate Slate",
"Bb Ccg Dd e- Slsl": "Barred Chocolate Slate",
"Bb Ccg Dd e- Pnpn": "Barred Chocolate Slate",
"Bb Ccg Dd e- pnpn": "Barred Chocolate Slate",
"Bb Ccg Dd e- Pnpn Slsl": "Barred Chocolate Slate",
"Bb Ccg Dd e- pnpn Slsl": "Barred Chocolate Slate",
"Bb Ccm Dd e-": "Barred Chocolate Slate",
"Bb Ccm Dd e- Slsl": "Barred Chocolate Slate",
"Bb Ccm Dd e- Pnpn": "Barred Chocolate Slate",
"Bb Ccm Dd e- pnpn": "Barred Chocolate Slate",
"Bb Ccm Dd e- pnpn Slsl": "Barred Chocolate Slate",
"Bb Ccm Dd e- Pnpn Slsl": "Barred Chocolate Slate",
"Bb Cc Dd e-": "Barred Chocolate Slate",
"Bb Cc Dd e- Slsl": "Barred Chocolate Slate",
"Bb Cc Dd e- Pnpn": "Barred Chocolate Slate",
"Bb Cc Dd e- pnpn": "Barred Chocolate Slate",
"Bb Cc Dd e- Pnpn Slsl": "Barred Chocolate Slate",
"Bb Cc Dd e- pnpn Slsl": "Barred Chocolate Slate",
"Bb cgcg Dd e-": "Barred Chocolate Slate",
"Bb cgcg Dd e- Slsl": "Barred Chocolate Slate",
"Bb cgcg Dd e- Pnpn": "Barred Chocolate Slate",
"Bb cgcg Dd e- pnpn": "Barred Chocolate Slate",
"Bb cgcg Dd e- Pnpn Slsl": "Barred Chocolate Slate",
"Bb cgcg Dd e- pnpn Slsl": "Barred Chocolate Slate",
"Bb cgcm Dd e-": "Barred Chocolate Slate",
"Bb cgcm Dd e- Slsl": "Barred Chocolate Slate",
"Bb cgcm Dd e- Pnpn": "Barred Chocolate Slate",
"Bb cgcm Dd e- pnpn": "Barred Chocolate Slate",
"Bb cgcm Dd e- Pnpn Slsl": "Barred Chocolate Slate",
"Bb cgcm Dd e- pnpn Slsl": "Barred Chocolate Slate",
"Bb cgc Dd e-": "Barred Chocolate Slate",
"Bb cgc Dd e- Slsl": "Barred Chocolate Slate",
"Bb cgc Dd e- Pnpn": "Barred Chocolate Slate",
"Bb cgc Dd e- pnpn": "Barred Chocolate Slate",
"Bb cgc Dd e- Pnpn Slsl": "Barred Chocolate Slate",
"Bb cgc Dd e- pnpn Slsl": "Barred Chocolate Slate",
"Bb1 Dd ee": "Barred Chocolate Slate",
"Bb1 Dd ee Nn": "Barred Chocolate Slate",
"Bb1 Dd ee Nn Pnpn": "Barred Chocolate Slate",
"Bb1 Dd ee Nn Slsl": "Barred Chocolate Slate",
"Bb1 Dd ee Nn pnpn": "Barred Chocolate Slate",
"Bb1 Dd ee Pnpn": "Barred Chocolate Slate",
"Bb1 Dd ee Pnpn Slsl": "Barred Chocolate Slate",
"Bb1 Dd ee pnpn": "Barred Chocolate Slate",
"Bb1 Dd ee pnpn Slsl": "Barred Chocolate Slate",
"Bb1 Ccm Dd ee": "Barred Chocolate Slate",
"Bb1 Ccm Dd ee Nn": "Barred Chocolate Slate",
"Bb1 Ccm Dd ee Nn Pnpn": "Barred Chocolate Slate",
"Bb1 Ccm Dd ee Nn Slsl": "Barred Chocolate Slate",
"Bb1 Ccm Dd ee Nn pnpn": "Barred Chocolate Slate",
"Bb1 Ccm Dd ee Pnpn": "Barred Chocolate Slate",
"Bb1 Ccm Dd ee Pnpn Slsl": "Barred Chocolate Slate",
"Bb1 Ccm Dd ee pnpn": "Barred Chocolate Slate",
"Bb1 Ccm Dd ee pnpn Slsl": "Barred Chocolate Slate",
"Bb1 Cc Dd ee": "Barred Chocolate Slate",
"Bb1 Cc Dd ee Nn": "Barred Chocolate Slate",
"Bb1 Cc Dd ee Nn Pnpn": "Barred Chocolate Slate",
"Bb1 Cc Dd ee Nn Slsl": "Barred Chocolate Slate",
"Bb1 Cc Dd ee Nn pnpn": "Barred Chocolate Slate",
"Bb1 Cc Dd ee Pnpn": "Barred Chocolate Slate",
"Bb1 Cc Dd ee Pnpn Slsl": "Barred Chocolate Slate",
"Bb1 Cc Dd ee pnpn": "Barred Chocolate Slate",
"Bb1 Cc Dd ee pnpn Slsl": "Barred Chocolate Slate",
"Bb1 Dd e-": "Barred Chocolate Slate",
"Bb1 Dd e- Slsl": "Barred Chocolate Slate",
"Bb1 Dd e- Pnpn": "Barred Chocolate Slate",
"Bb1 Dd e- pnpn": "Barred Chocolate Slate",
"Bb1 Dd e- Pnpn Slsl": "Barred Chocolate Slate",
"Bb1 Dd e- pnpn Slsl": "Barred Chocolate Slate",
"Bb1 Ccm Dd e-": "Barred Chocolate Slate",
"Bb1 Ccm Dd e- Slsl": "Barred Chocolate Slate",
"Bb1 Ccm Dd e- Pnpn": "Barred Chocolate Slate",
"Bb1 Ccm Dd e- pnpn": "Barred Chocolate Slate",
"Bb1 Ccm Dd e- pnpn Slsl": "Barred Chocolate Slate",
"Bb1 Ccm Dd e- Pnpn Slsl": "Barred Chocolate Slate",
"Bb1 Cc Dd e-": "Barred Chocolate Slate",
"Bb1 Cc Dd e- Slsl": "Barred Chocolate Slate",
"Bb1 Cc Dd e- Pnpn": "Barred Chocolate Slate",
"Bb1 Cc Dd e- pnpn": "Barred Chocolate Slate",
"Bb1 Cc Dd e- Pnpn Slsl": "Barred Chocolate Slate",
"Bb1 Cc Dd e- pnpn Slsl": "Barred Chocolate Slate",
// BARRED RED LILAC
"Bb rr slsl": "Barred Red Lilac",
"Bb Ee rr slsl": "Barred Red Lilac",
"Bb Nn rr slsl": "Barred Red Lilac",
"Bb Pnpn rr slsl": "Barred Red Lilac",
"Bb pnpn rr slsl": "Barred Red Lilac",
"Bb Ee Nn rr slsl": "Barred Red Lilac",
"Bb Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb Nn pnpn rr slsl": "Barred Red Lilac",
"Bb Ee Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb Ee Nn pnpn rr slsl": "Barred Red Lilac",
"Bb Ccg rr slsl": "Barred Red Lilac",
"Bb Ccg Ee rr slsl": "Barred Red Lilac",
"Bb Ccg Nn rr slsl": "Barred Red Lilac",
"Bb Ccg Pnpn rr slsl": "Barred Red Lilac",
"Bb Ccg pnpn rr slsl": "Barred Red Lilac",
"Bb Ccg Ee Nn rr slsl": "Barred Red Lilac",
"Bb Ccg Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb Ccg Nn pnpn rr slsl": "Barred Red Lilac",
"Bb Ccg Ee Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb Ccg Ee Nn pnpn rr slsl": "Barred Red Lilac",
"Bb Ccm rr slsl": "Barred Red Lilac",
"Bb Ccm Ee rr slsl": "Barred Red Lilac",
"Bb Ccm Nn rr slsl": "Barred Red Lilac",
"Bb Ccm Pnpn rr slsl": "Barred Red Lilac",
"Bb Ccm pnpn rr slsl": "Barred Red Lilac",
"Bb Ccm Ee Nn rr slsl": "Barred Red Lilac",
"Bb Ccm Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb Ccm Nn pnpn rr slsl": "Barred Red Lilac",
"Bb Ccm Ee Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb Ccm Ee Nn pnpn rr slsl": "Barred Red Lilac",
"Bb Cc rr slsl": "Barred Red Lilac",
"Bb Cc Ee rr slsl": "Barred Red Lilac",
"Bb Cc Nn rr slsl": "Barred Red Lilac",
"Bb Cc Pnpn rr slsl": "Barred Red Lilac",
"Bb Cc pnpn rr slsl": "Barred Red Lilac",
"Bb Cc Ee Nn rr slsl": "Barred Red Lilac",
"Bb Cc Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb Cc Nn pnpn rr slsl": "Barred Red Lilac",
"Bb Cc Ee Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb Cc Ee Nn pnpn rr slsl": "Barred Red Lilac",
"Bb cgcg rr slsl": "Barred Red Lilac",
"Bb cgcg Ee rr slsl": "Barred Red Lilac",
"Bb cgcg Nn rr slsl": "Barred Red Lilac",
"Bb cgcg Pnpn rr slsl": "Barred Red Lilac",
"Bb cgcg pnpn rr slsl": "Barred Red Lilac",
"Bb cgcg Ee Nn rr slsl": "Barred Red Lilac",
"Bb cgcg Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb cgcg Nn pnpn rr slsl": "Barred Red Lilac",
"Bb cgcg Ee Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb cgcg Ee Nn pnpn rr slsl": "Barred Red Lilac",
"Bb cgcm rr slsl": "Barred Red Lilac",
"Bb cgcm Ee rr slsl": "Barred Red Lilac",
"Bb cgcm Nn rr slsl": "Barred Red Lilac",
"Bb cgcm Pnpn rr slsl": "Barred Red Lilac",
"Bb cgcm pnpn rr slsl": "Barred Red Lilac",
"Bb cgcm Ee Nn rr slsl": "Barred Red Lilac",
"Bb cgcm Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb cgcm Nn pnpn rr slsl": "Barred Red Lilac",
"Bb cgcm Ee Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb cgcm Ee Nn pnpn rr slsl": "Barred Red Lilac",
"Bb cgc rr slsl": "Barred Red Lilac",
"Bb cgc Ee rr slsl": "Barred Red Lilac",
"Bb cgc Nn rr slsl": "Barred Red Lilac",
"Bb cgc Pnpn rr slsl": "Barred Red Lilac",
"Bb cgc pnpn rr slsl": "Barred Red Lilac",
"Bb cgc Ee Nn rr slsl": "Barred Red Lilac",
"Bb cgc Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb cgc Nn pnpn rr slsl": "Barred Red Lilac",
"Bb cgc Ee Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb cgc Ee Nn pnpn rr slsl": "Barred Red Lilac",
// Bb1 BARRED LILAC
"Bb1 rr slsl": "Barred Red Lilac",
"Bb1 Ee rr slsl": "Barred Red Lilac",
"Bb1 Nn rr slsl": "Barred Red Lilac",
"Bb1 Pnpn rr slsl": "Barred Red Lilac",
"Bb1 pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ee Nn rr slsl": "Barred Red Lilac",
"Bb1 Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb1 Nn pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ee Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ee Nn pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ccg rr slsl": "Barred Red Lilac",
"Bb1 Ccg Ee rr slsl": "Barred Red Lilac",
"Bb1 Ccg Nn rr slsl": "Barred Red Lilac",
"Bb1 Ccg Pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ccg pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ccg Ee Nn rr slsl": "Barred Red Lilac",
"Bb1 Ccg Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ccg Nn pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ccg Ee Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ccg Ee Nn pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ccm rr slsl": "Barred Red Lilac",
"Bb1 Ccm Ee rr slsl": "Barred Red Lilac",
"Bb1 Ccm Nn rr slsl": "Barred Red Lilac",
"Bb1 Ccm Pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ccm pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ccm Ee Nn rr slsl": "Barred Red Lilac",
"Bb1 Ccm Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ccm Nn pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ccm Ee Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb1 Ccm Ee Nn pnpn rr slsl": "Barred Red Lilac",
"Bb1 Cc rr slsl": "Barred Red Lilac",
"Bb1 Cc Ee rr slsl": "Barred Red Lilac",
"Bb1 Cc Nn rr slsl": "Barred Red Lilac",
"Bb1 Cc Pnpn rr slsl": "Barred Red Lilac",
"Bb1 Cc pnpn rr slsl": "Barred Red Lilac",
"Bb1 Cc Ee Nn rr slsl": "Barred Red Lilac",
"Bb1 Cc Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb1 Cc Nn pnpn rr slsl": "Barred Red Lilac",
"Bb1 Cc Ee Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb1 Cc Ee Nn pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgcg rr slsl": "Barred Red Lilac",
"Bb1 cgcg Ee rr slsl": "Barred Red Lilac",
"Bb1 cgcg Nn rr slsl": "Barred Red Lilac",
"Bb1 cgcg Pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgcg pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgcg Ee Nn rr slsl": "Barred Red Lilac",
"Bb1 cgcg Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgcg Nn pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgcg Ee Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgcg Ee Nn pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgcm rr slsl": "Barred Red Lilac",
"Bb1 cgcm Ee rr slsl": "Barred Red Lilac",
"Bb1 cgcm Nn rr slsl": "Barred Red Lilac",
"Bb1 cgcm Pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgcm pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgcm Ee Nn rr slsl": "Barred Red Lilac",
"Bb1 cgcm Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgcm Nn pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgcm Ee Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgcm Ee Nn pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgc rr slsl": "Barred Red Lilac",
"Bb1 cgc Ee rr slsl": "Barred Red Lilac",
"Bb1 cgc Nn rr slsl": "Barred Red Lilac",
"Bb1 cgc Pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgc pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgc Ee Nn rr slsl": "Barred Red Lilac",
"Bb1 cgc Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgc Nn pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgc Ee Nn Pnpn rr slsl": "Barred Red Lilac",
"Bb1 cgc Ee Nn pnpn rr slsl": "Barred Red Lilac",

// b1b1 BLUE WINGED LAVENDER RED NARRAGANSETT, done
"b1b1 DD nn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee nn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD nn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD nn Pnpn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD nn pnpn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee nn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee nn Pnpn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee nn pnpn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD nn Pnpn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD nn pnpn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee nn Pnpn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee nn pnpn Rr Slsl": "Blue Winged Lavender Red Narragansett",

// b1b1 Spsp BLUE WINGED LAVENDER RED NARRAGANSETT
"b1b1 DD nn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee nn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD nn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD nn Pnpn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD nn pnpn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee nn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee nn Pnpn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee nn pnpn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD nn Pnpn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD nn pnpn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee nn Pnpn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee nn pnpn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",

// b1b1 Fdfd BLUE WINGED LAVENDER RED NARRAGANSETT
"b1b1 DD Fdfd nn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee Fdfd nn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Fdfd nn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Fdfd nn Pnpn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Fdfd nn pnpn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee Fdfd nn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee Fdfd nn Pnpn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee Fdfd nn pnpn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Fdfd nn Pnpn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Fdfd nn pnpn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee Fdfd nn Pnpn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee Fdfd nn pnpn Rr Slsl": "Blue Winged Lavender Red Narragansett",

// b1b1 fdfd BLUE WINGED LAVENDER RED NARRAGANSETT
"b1b1 DD fdfd nn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee fdfd nn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD fdfd nn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD fdfd nn Pnpn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD fdfd nn pnpn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee fdfd nn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee fdfd nn Pnpn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee fdfd nn pnpn Rr": "Blue Winged Lavender Red Narragansett",
"b1b1 DD fdfd nn Pnpn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD fdfd nn pnpn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee fdfd nn Pnpn Rr Slsl": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee fdfd nn pnpn Rr Slsl": "Blue Winged Lavender Red Narragansett",

// b1b1 Fdfd Spsp BLUE WINGED LAVENDER RED NARRAGANSETT
"b1b1 DD Fdfd nn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee Fdfd nn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Fdfd nn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Fdfd nn Pnpn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Fdfd nn pnpn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee Fdfd nn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee Fdfd nn Pnpn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee Fdfd nn pnpn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Fdfd nn Pnpn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Fdfd nn pnpn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee Fdfd nn Pnpn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee Fdfd nn pnpn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",

// b1b1 fdfd Spsp BLUE WINGED LAVENDER RED NARRAGANSETT
"b1b1 DD fdfd nn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee fdfd nn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD fdfd nn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD fdfd nn Pnpn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD fdfd nn pnpn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee fdfd nn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee fdfd nn Pnpn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee fdfd nn pnpn Rr Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD fdfd nn Pnpn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD fdfd nn pnpn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee fdfd nn Pnpn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",
"b1b1 DD Ee fdfd nn pnpn Rr Slsl Spsp": "Blue Winged Lavender Red Narragansett",


     
    // NEBRASKAN, DONE ***
    
   // bb NEBRASKAN
"bb spsp": "Nebraskan",
"bb Ee spsp": "Nebraskan",
"bb Nn spsp": "Nebraskan",
"bb Slsl spsp": "Nebraskan",
"bb Pnpn spsp": "Nebraskan",
"bb pnpn spsp": "Nebraskan",
"bb Ee Nn spsp": "Nebraskan",
"bb Ee Slsl spsp": "Nebraskan",
"bb Ee Pnpn spsp": "Nebraskan",
"bb Ee pnpn spsp": "Nebraskan",
"bb Nn Slsl spsp": "Nebraskan",
"bb Nn Pnpn spsp": "Nebraskan",
"bb Nn pnpn spsp": "Nebraskan",
"bb Nn Pnpn Slsl spsp": "Nebraskan",
"bb Nn pnpn Slsl spsp": "Nebraskan",
"bb Pnpn Slsl spsp": "Nebraskan",
"bb pnpn Slsl spsp": "Nebraskan",
"bb Ee Nn Slsl spsp": "Nebraskan",
"bb Ee Nn Pnpn spsp": "Nebraskan",
"bb Ee Nn pnpn spsp": "Nebraskan",
"bb Ee Nn Pnpn Slsl spsp": "Nebraskan",
"bb Ee Nn pnpn Slsl spsp": "Nebraskan",
"bb Ee Pnpn Slsl spsp": "Nebraskan",
"bb Ee pnpn Slsl spsp": "Nebraskan",

// bb fdfd NEBRASKAN
"bb fdfd spsp": "Nebraskan",
"bb Ee fdfd spsp": "Nebraskan",
"bb fdfd Nn spsp": "Nebraskan",
"bb fdfd Slsl spsp": "Nebraskan",
"bb fdfd Pnpn spsp": "Nebraskan",
"bb fdfd pnpn spsp": "Nebraskan",
"bb Ee fdfd Nn spsp": "Nebraskan",
"bb Ee fdfd Slsl spsp": "Nebraskan",
"bb Ee fdfd Pnpn spsp": "Nebraskan",
"bb Ee fdfd pnpn spsp": "Nebraskan",
"bb fdfd Nn Slsl spsp": "Nebraskan",
"bb fdfd Nn Pnpn spsp": "Nebraskan",
"bb fdfd Nn pnpn spsp": "Nebraskan",
"bb fdfd Nn Pnpn Slsl spsp": "Nebraskan",
"bb fdfd Nn pnpn Slsl spsp": "Nebraskan",
"bb fdfd Pnpn Slsl spsp": "Nebraskan",
"bb fdfd pnpn Slsl spsp": "Nebraskan",
"bb Ee fdfd Nn Slsl spsp": "Nebraskan",
"bb Ee fdfd Nn Pnpn spsp": "Nebraskan",
"bb Ee fdfd Nn pnpn spsp": "Nebraskan",
"bb Ee fdfd Nn Pnpn Slsl spsp": "Nebraskan",
"bb Ee fdfd Nn pnpn Slsl spsp": "Nebraskan",
"bb Ee fdfd Pnpn Slsl spsp": "Nebraskan",
"bb Ee fdfd pnpn Slsl spsp": "Nebraskan",

// bb Fdfd NEBRASKAN
"bb Fdfd spsp": "Nebraskan",
"bb Ee Fdfd spsp": "Nebraskan",
"bb Fdfd Nn spsp": "Nebraskan",
"bb Fdfd Slsl spsp": "Nebraskan",
"bb Fdfd Pnpn spsp": "Nebraskan",
"bb Fdfd pnpn spsp": "Nebraskan",
"bb Ee Fdfd Nn spsp": "Nebraskan",
"bb Ee Fdfd Slsl spsp": "Nebraskan",
"bb Ee Fdfd Pnpn spsp": "Nebraskan",
"bb Ee Fdfd pnpn spsp": "Nebraskan",
"bb Fdfd Nn Slsl spsp": "Nebraskan",
"bb Fdfd Nn Pnpn spsp": "Nebraskan",
"bb Fdfd Nn pnpn spsp": "Nebraskan",
"bb Fdfd Nn Pnpn Slsl spsp": "Nebraskan",
"bb Fdfd Nn pnpn Slsl spsp": "Nebraskan",
"bb Fdfd Pnpn Slsl spsp": "Nebraskan",
"bb Fdfd pnpn Slsl spsp": "Nebraskan",
"bb Ee Fdfd Nn Slsl spsp": "Nebraskan",
"bb Ee Fdfd Nn Pnpn spsp": "Nebraskan",
"bb Ee Fdfd Nn pnpn spsp": "Nebraskan",
"bb Ee Fdfd Nn Pnpn Slsl spsp": "Nebraskan",
"bb Ee Fdfd Nn pnpn Slsl spsp": "Nebraskan",
"bb Ee Fdfd Pnpn Slsl spsp": "Nebraskan",
"bb Ee Fdfd pnpn Slsl spsp": "Nebraskan",



// C loci variations
"bb Ccg spsp": "Nebraskan",
"bb Ccg Ee spsp": "Nebraskan",
"bb Ccg Nn spsp": "Nebraskan",
"bb Ccg Slsl spsp": "Nebraskan",
"bb Ccg Pnpn spsp": "Nebraskan",
"bb Ccg pnpn spsp": "Nebraskan",
"bb Ccg Ee Nn spsp": "Nebraskan",
"bb Ccg Ee Slsl spsp": "Nebraskan",
"bb Ccg Ee Pnpn spsp": "Nebraskan",
"bb Ccg Ee pnpn spsp": "Nebraskan",
"bb Ccg Nn Slsl spsp": "Nebraskan",
"bb Ccg Nn Pnpn spsp": "Nebraskan",
"bb Ccg Nn pnpn spsp": "Nebraskan",
"bb Ccg Nn Pnpn Slsl spsp": "Nebraskan",
"bb Ccg Nn pnpn Slsl spsp": "Nebraskan",
"bb Ccg Pnpn Slsl spsp": "Nebraskan",
"bb Ccg pnpn Slsl spsp": "Nebraskan",
"bb Ccg Ee Nn Slsl spsp": "Nebraskan",
"bb Ccg Ee Nn Pnpn spsp": "Nebraskan",
"bb Ccg Ee Nn pnpn spsp": "Nebraskan",
"bb Ccg Ee Nn Pnpn Slsl spsp": "Nebraskan",
"bb Ccg Ee Nn pnpn Slsl spsp": "Nebraskan",
"bb Ccg Ee Pnpn Slsl spsp": "Nebraskan",
"bb Ccg Ee pnpn Slsl spsp": "Nebraskan",


"bb Ccm spsp": "Nebraskan",
"bb Ccm Ee spsp": "Nebraskan",
"bb Ccm Nn spsp": "Nebraskan",
"bb Ccm Slsl spsp": "Nebraskan",
"bb Ccm Pnpn spsp": "Nebraskan",
"bb Ccm pnpn spsp": "Nebraskan",
"bb Ccm Ee Nn spsp": "Nebraskan",
"bb Ccm Ee Slsl spsp": "Nebraskan",
"bb Ccm Ee Pnpn spsp": "Nebraskan",
"bb Ccm Ee pnpn spsp": "Nebraskan",
"bb Ccm Nn Slsl spsp": "Nebraskan",
"bb Ccm Nn Pnpn spsp": "Nebraskan",
"bb Ccm Nn pnpn spsp": "Nebraskan",
"bb Ccm Nn Pnpn Slsl spsp": "Nebraskan",
"bb Ccm Nn pnpn Slsl spsp": "Nebraskan",
"bb Ccm Pnpn Slsl spsp": "Nebraskan",
"bb Ccm pnpn Slsl spsp": "Nebraskan",
"bb Ccm Ee Nn Slsl spsp": "Nebraskan",
"bb Ccm Ee Nn Pnpn spsp": "Nebraskan",
"bb Ccm Ee Nn pnpn spsp": "Nebraskan",
"bb Ccm Ee Nn Pnpn Slsl spsp": "Nebraskan",
"bb Ccm Ee Nn pnpn Slsl spsp": "Nebraskan",
"bb Ccm Ee Pnpn Slsl spsp": "Nebraskan",
"bb Ccm Ee pnpn Slsl spsp": "Nebraskan",


"bb Cc spsp": "Nebraskan",
"bb Cc Ee spsp": "Nebraskan",
"bb Cc Nn spsp": "Nebraskan",
"bb Cc Slsl spsp": "Nebraskan",
"bb Cc Pnpn spsp": "Nebraskan",
"bb Cc pnpn spsp": "Nebraskan",
"bb Cc Ee Nn spsp": "Nebraskan",
"bb Cc Ee Slsl spsp": "Nebraskan",
"bb Cc Ee Pnpn spsp": "Nebraskan",
"bb Cc Ee pnpn spsp": "Nebraskan",
"bb Cc Nn Slsl spsp": "Nebraskan",
"bb Cc Nn Pnpn spsp": "Nebraskan",
"bb Cc Nn pnpn spsp": "Nebraskan",
"bb Cc Nn Pnpn Slsl spsp": "Nebraskan",
"bb Cc Nn pnpn Slsl spsp": "Nebraskan",
"bb Cc Pnpn Slsl spsp": "Nebraskan",
"bb Cc pnpn Slsl spsp": "Nebraskan",
"bb Cc Ee Nn Slsl spsp": "Nebraskan",
"bb Cc Ee Nn Pnpn spsp": "Nebraskan",
"bb Cc Ee Nn pnpn spsp": "Nebraskan",
"bb Cc Ee Nn Pnpn Slsl spsp": "Nebraskan",
"bb Cc Ee Nn pnpn Slsl spsp": "Nebraskan",
"bb Cc Ee Pnpn Slsl spsp": "Nebraskan",
"bb Cc Ee pnpn Slsl spsp": "Nebraskan",


"bb cgcg spsp": "Nebraskan",
"bb cgcg Ee spsp": "Nebraskan",
"bb cgcg Nn spsp": "Nebraskan",
"bb cgcg Slsl spsp": "Nebraskan",
"bb cgcg Pnpn spsp": "Nebraskan",
"bb cgcg pnpn spsp": "Nebraskan",
"bb cgcg Ee Nn spsp": "Nebraskan",
"bb cgcg Ee Slsl spsp": "Nebraskan",
"bb cgcg Ee Pnpn spsp": "Nebraskan",
"bb cgcg Ee pnpn spsp": "Nebraskan",
"bb cgcg Nn Slsl spsp": "Nebraskan",
"bb cgcg Nn Pnpn spsp": "Nebraskan",
"bb cgcg Nn pnpn spsp": "Nebraskan",
"bb cgcg Nn Pnpn Slsl spsp": "Nebraskan",
"bb cgcg Nn pnpn Slsl spsp": "Nebraskan",
"bb cgcg Pnpn Slsl spsp": "Nebraskan",
"bb cgcg pnpn Slsl spsp": "Nebraskan",
"bb cgcg Ee Nn Slsl spsp": "Nebraskan",
"bb cgcg Ee Nn Pnpn spsp": "Nebraskan",
"bb cgcg Ee Nn pnpn spsp": "Nebraskan",
"bb cgcg Ee Nn Pnpn Slsl spsp": "Nebraskan",
"bb cgcg Ee Nn pnpn Slsl spsp": "Nebraskan",
"bb cgcg Ee Pnpn Slsl spsp": "Nebraskan",
"bb cgcg Ee pnpn Slsl spsp": "Nebraskan",



"bb cgcm spsp": "Nebraskan",
"bb cgcm Ee spsp": "Nebraskan",
"bb cgcm Nn spsp": "Nebraskan",
"bb cgcm Slsl spsp": "Nebraskan",
"bb cgcm Pnpn spsp": "Nebraskan",
"bb cgcm pnpn spsp": "Nebraskan",
"bb cgcm Ee Nn spsp": "Nebraskan",
"bb cgcm Ee Slsl spsp": "Nebraskan",
"bb cgcm Ee Pnpn spsp": "Nebraskan",
"bb cgcm Ee pnpn spsp": "Nebraskan",
"bb cgcm Nn Slsl spsp": "Nebraskan",
"bb cgcm Nn Pnpn spsp": "Nebraskan",
"bb cgcm Nn pnpn spsp": "Nebraskan",
"bb cgcm Nn Pnpn Slsl spsp": "Nebraskan",
"bb cgcm Nn pnpn Slsl spsp": "Nebraskan",
"bb cgcm Pnpn Slsl spsp": "Nebraskan",
"bb cgcm pnpn Slsl spsp": "Nebraskan",
"bb cgcm Ee Nn Slsl spsp": "Nebraskan",
"bb cgcm Ee Nn Pnpn spsp": "Nebraskan",
"bb cgcm Ee Nn pnpn spsp": "Nebraskan",
"bb cgcm Ee Nn Pnpn Slsl spsp": "Nebraskan",
"bb cgcm Ee Nn pnpn Slsl spsp": "Nebraskan",
"bb cgcm Ee Pnpn Slsl spsp": "Nebraskan",
"bb cgcm Ee pnpn Slsl spsp": "Nebraskan",


"bb cgc spsp": "Nebraskan",
"bb cgc Ee spsp": "Nebraskan",
"bb cgc Nn spsp": "Nebraskan",
"bb cgc Slsl spsp": "Nebraskan",
"bb cgc Pnpn spsp": "Nebraskan",
"bb cgc pnpn spsp": "Nebraskan",
"bb cgc Ee Nn spsp": "Nebraskan",
"bb cgc Ee Slsl spsp": "Nebraskan",
"bb cgc Ee Pnpn spsp": "Nebraskan",
"bb cgc Ee pnpn spsp": "Nebraskan",
"bb cgc Nn Slsl spsp": "Nebraskan",
"bb cgc Nn Pnpn spsp": "Nebraskan",
"bb cgc Nn pnpn spsp": "Nebraskan",
"bb cgc Nn Pnpn Slsl spsp": "Nebraskan",
"bb cgc Nn pnpn Slsl spsp": "Nebraskan",
"bb cgc Pnpn Slsl spsp": "Nebraskan",
"bb cgc pnpn Slsl spsp": "Nebraskan",
"bb cgc Ee Nn Slsl spsp": "Nebraskan",
"bb cgc Ee Nn Pnpn spsp": "Nebraskan",
"bb cgc Ee Nn pnpn spsp": "Nebraskan",
"bb cgc Ee Nn Pnpn Slsl spsp": "Nebraskan",
"bb cgc Ee Nn pnpn Slsl spsp": "Nebraskan",
"bb cgc Ee Pnpn Slsl spsp": "Nebraskan",
"bb cgc Ee pnpn Slsl spsp": "Nebraskan",

    
    
// bb1 NEBRASKAN
"bb1 spsp": "Nebraskan (Split Black Winged Bronze)",
"bb1 Ee spsp": "Nebraskan",
"bb1 Nn spsp": "Nebraskan",
"bb1 Slsl spsp": "Nebraskan",
"bb1 Pnpn spsp": "Nebraskan",
"bb1 pnpn spsp": "Nebraskan",
"bb1 Ee Nn spsp": "Nebraskan",
"bb1 Ee Slsl spsp": "Nebraskan",
"bb1 Ee Pnpn spsp": "Nebraskan",
"bb1 Ee pnpn spsp": "Nebraskan",
"bb1 Nn Slsl spsp": "Nebraskan",
"bb1 Nn Pnpn spsp": "Nebraskan",
"bb1 Nn pnpn spsp": "Nebraskan",
"bb1 Nn Pnpn Slsl spsp": "Nebraskan",
"bb1 Nn pnpn Slsl spsp": "Nebraskan",
"bb1 Pnpn Slsl spsp": "Nebraskan",
"bb1 pnpn Slsl spsp": "Nebraskan",
"bb1 Ee Nn Slsl spsp": "Nebraskan",
"bb1 Ee Nn Pnpn spsp": "Nebraskan",
"bb1 Ee Nn pnpn spsp": "Nebraskan",
"bb1 Ee Nn Pnpn Slsl spsp": "Nebraskan",
"bb1 Ee Nn pnpn Slsl spsp": "Nebraskan",
"bb1 Ee Pnpn Slsl spsp": "Nebraskan",
"bb1 Ee pnpn Slsl spsp": "Nebraskan",

// C loci variations
"bb1 Ccg spsp": "Nebraskan",
"bb1 Ccg Ee spsp": "Nebraskan",
"bb1 Ccg Nn spsp": "Nebraskan",
"bb1 Ccg Slsl spsp": "Nebraskan",
"bb1 Ccg Pnpn spsp": "Nebraskan",
"bb1 Ccg pnpn spsp": "Nebraskan",
"bb1 Ccg Ee Nn spsp": "Nebraskan",
"bb1 Ccg Ee Slsl spsp": "Nebraskan",
"bb1 Ccg Ee Pnpn spsp": "Nebraskan",
"bb1 Ccg Ee pnpn spsp": "Nebraskan",
"bb1 Ccg Nn Slsl spsp": "Nebraskan",
"bb1 Ccg Nn Pnpn spsp": "Nebraskan",
"bb1 Ccg Nn pnpn spsp": "Nebraskan",
"bb1 Ccg Nn Pnpn Slsl spsp": "Nebraskan",
"bb1 Ccg Nn pnpn Slsl spsp": "Nebraskan",
"bb1 Ccg Pnpn Slsl spsp": "Nebraskan",
"bb1 Ccg pnpn Slsl spsp": "Nebraskan",
"bb1 Ccg Ee Nn Slsl spsp": "Nebraskan",
"bb1 Ccg Ee Nn Pnpn spsp": "Nebraskan",
"bb1 Ccg Ee Nn pnpn spsp": "Nebraskan",
"bb1 Ccg Ee Nn Pnpn Slsl spsp": "Nebraskan",
"bb1 Ccg Ee Nn pnpn Slsl spsp": "Nebraskan",
"bb1 Ccg Ee Pnpn Slsl spsp": "Nebraskan",
"bb1 Ccg Ee pnpn Slsl spsp": "Nebraskan",

  
"bb1 Ccm spsp": "Nebraskan",
"bb1 Ccm Ee spsp": "Nebraskan",
"bb1 Ccm Nn spsp": "Nebraskan",
"bb1 Ccm Slsl spsp": "Nebraskan",
"bb1 Ccm Pnpn spsp": "Nebraskan",
"bb1 Ccm pnpn spsp": "Nebraskan",
"bb1 Ccm Ee Nn spsp": "Nebraskan",
"bb1 Ccm Ee Slsl spsp": "Nebraskan",
"bb1 Ccm Ee Pnpn spsp": "Nebraskan",
"bb1 Ccm Ee pnpn spsp": "Nebraskan",
"bb1 Ccm Nn Slsl spsp": "Nebraskan",
"bb1 Ccm Nn Pnpn spsp": "Nebraskan",
"bb1 Ccm Nn pnpn spsp": "Nebraskan",
"bb1 Ccm Nn Pnpn Slsl spsp": "Nebraskan",
"bb1 Ccm Nn pnpn Slsl spsp": "Nebraskan",
"bb1 Ccm Pnpn Slsl spsp": "Nebraskan",
"bb1 Ccm pnpn Slsl spsp": "Nebraskan",
"bb1 Ccm Ee Nn Slsl spsp": "Nebraskan",
"bb1 Ccm Ee Nn Pnpn spsp": "Nebraskan",
"bb1 Ccm Ee Nn pnpn spsp": "Nebraskan",
"bb1 Ccm Ee Nn Pnpn Slsl spsp": "Nebraskan",
"bb1 Ccm Ee Nn pnpn Slsl spsp": "Nebraskan",
"bb1 Ccm Ee Pnpn Slsl spsp": "Nebraskan",
"bb1 Ccm Ee pnpn Slsl spsp": "Nebraskan",

"bb1 Cc spsp": "Nebraskan",
"bb1 Cc Ee spsp": "Nebraskan",
"bb1 Cc Nn spsp": "Nebraskan",
"bb1 Cc Slsl spsp": "Nebraskan",
"bb1 Cc Pnpn spsp": "Nebraskan",
"bb1 Cc pnpn spsp": "Nebraskan",
"bb1 Cc Ee Nn spsp": "Nebraskan",
"bb1 Cc Ee Slsl spsp": "Nebraskan",
"bb1 Cc Ee Pnpn spsp": "Nebraskan",
"bb1 Cc Ee pnpn spsp": "Nebraskan",
"bb1 Cc Nn Slsl spsp": "Nebraskan",
"bb1 Cc Nn Pnpn spsp": "Nebraskan",
"bb1 Cc Nn pnpn spsp": "Nebraskan",
"bb1 Cc Nn Pnpn Slsl spsp": "Nebraskan",
"bb1 Cc Nn pnpn Slsl spsp": "Nebraskan",
"bb1 Cc Pnpn Slsl spsp": "Nebraskan",
"bb1 Cc pnpn Slsl spsp": "Nebraskan",
"bb1 Cc Ee Nn Slsl spsp": "Nebraskan",
"bb1 Cc Ee Nn Pnpn spsp": "Nebraskan",
"bb1 Cc Ee Nn pnpn spsp": "Nebraskan",
"bb1 Cc Ee Nn Pnpn Slsl spsp": "Nebraskan",
"bb1 Cc Ee Nn pnpn Slsl spsp": "Nebraskan",
"bb1 Cc Ee Pnpn Slsl spsp": "Nebraskan",
"bb1 Cc Ee pnpn Slsl spsp": "Nebraskan",

  
"bb1 cgcg spsp": "Nebraskan",
"bb1 cgcg Ee spsp": "Nebraskan",
"bb1 cgcg Nn spsp": "Nebraskan",
"bb1 cgcg Slsl spsp": "Nebraskan",
"bb1 cgcg Pnpn spsp": "Nebraskan",
"bb1 cgcg pnpn spsp": "Nebraskan",
"bb1 cgcg Ee Nn spsp": "Nebraskan",
"bb1 cgcg Ee Slsl spsp": "Nebraskan",
"bb1 cgcg Ee Pnpn spsp": "Nebraskan",
"bb1 cgcg Ee pnpn spsp": "Nebraskan",
"bb1 cgcg Nn Slsl spsp": "Nebraskan",
"bb1 cgcg Nn Pnpn spsp": "Nebraskan",
"bb1 cgcg Nn pnpn spsp": "Nebraskan",
"bb1 cgcg Nn Pnpn Slsl spsp": "Nebraskan",
"bb1 cgcg Nn pnpn Slsl spsp": "Nebraskan",
"bb1 cgcg Pnpn Slsl spsp": "Nebraskan",
"bb1 cgcg pnpn Slsl spsp": "Nebraskan",
"bb1 cgcg Ee Nn Slsl spsp": "Nebraskan",
"bb1 cgcg Ee Nn Pnpn spsp": "Nebraskan",
"bb1 cgcg Ee Nn pnpn spsp": "Nebraskan",
"bb1 cgcg Ee Nn Pnpn Slsl spsp": "Nebraskan",
"bb1 cgcg Ee Nn pnpn Slsl spsp": "Nebraskan",
"bb1 cgcg Ee Pnpn Slsl spsp": "Nebraskan",
"bb1 cgcg Ee pnpn Slsl spsp": "Nebraskan",

"bb1 cgcm spsp": "Nebraskan",
"bb1 cgcm Ee spsp": "Nebraskan",
"bb1 cgcm Nn spsp": "Nebraskan",
"bb1 cgcm Slsl spsp": "Nebraskan",
"bb1 cgcm Pnpn spsp": "Nebraskan",
"bb1 cgcm pnpn spsp": "Nebraskan",
"bb1 cgcm Ee Nn spsp": "Nebraskan",
"bb1 cgcm Ee Slsl spsp": "Nebraskan",
"bb1 cgcm Ee Pnpn spsp": "Nebraskan",
"bb1 cgcm Ee pnpn spsp": "Nebraskan",
"bb1 cgcm Nn Slsl spsp": "Nebraskan",
"bb1 cgcm Nn Pnpn spsp": "Nebraskan",
"bb1 cgcm Nn pnpn spsp": "Nebraskan",
"bb1 cgcm Nn Pnpn Slsl spsp": "Nebraskan",
"bb1 cgcm Nn pnpn Slsl spsp": "Nebraskan",
"bb1 cgcm Pnpn Slsl spsp": "Nebraskan",
"bb1 cgcm pnpn Slsl spsp": "Nebraskan",
"bb1 cgcm Ee Nn Slsl spsp": "Nebraskan",
"bb1 cgcm Ee Nn Pnpn spsp": "Nebraskan",
"bb1 cgcm Ee Nn pnpn spsp": "Nebraskan",
"bb1 cgcm Ee Nn Pnpn Slsl spsp": "Nebraskan",
"bb1 cgcm Ee Nn pnpn Slsl spsp": "Nebraskan",
"bb1 cgcm Ee Pnpn Slsl spsp": "Nebraskan",
"bb1 cgcm Ee pnpn Slsl spsp": "Nebraskan",

"bb1 cgc spsp": "Nebraskan",
"bb1 cgc Ee spsp": "Nebraskan",
"bb1 cgc Nn spsp": "Nebraskan",
"bb1 cgc Slsl spsp": "Nebraskan",
"bb1 cgc Pnpn spsp": "Nebraskan",
"bb1 cgc pnpn spsp": "Nebraskan",
"bb1 cgc Ee Nn spsp": "Nebraskan",
"bb1 cgc Ee Slsl spsp": "Nebraskan",
"bb1 cgc Ee Pnpn spsp": "Nebraskan",
"bb1 cgc Ee pnpn spsp": "Nebraskan",
"bb1 cgc Nn Slsl spsp": "Nebraskan",
"bb1 cgc Nn Pnpn spsp": "Nebraskan",
"bb1 cgc Nn pnpn spsp": "Nebraskan",
"bb1 cgc Nn Pnpn Slsl spsp": "Nebraskan",
"bb1 cgc Nn pnpn Slsl spsp": "Nebraskan",
"bb1 cgc Pnpn Slsl spsp": "Nebraskan",
"bb1 cgc pnpn Slsl spsp": "Nebraskan",
"bb1 cgc Ee Nn Slsl spsp": "Nebraskan",
"bb1 cgc Ee Nn Pnpn spsp": "Nebraskan",
"bb1 cgc Ee Nn pnpn spsp": "Nebraskan",
"bb1 cgc Ee Nn Pnpn Slsl spsp": "Nebraskan",
"bb1 cgc Ee Nn pnpn Slsl spsp": "Nebraskan",
"bb1 cgc Ee Pnpn Slsl spsp": "Nebraskan",
"bb1 cgc Ee pnpn Slsl spsp": "Nebraskan",

  
 // bb Dd BLUE NEBRASKAN
"bb Dd spsp": "Blue Nebraskan",
"bb Dd Ee spsp": "Blue Nebraskan",
"bb Dd Nn spsp": "Blue Nebraskan",
"bb Dd Slsl spsp": "Blue Nebraskan",
"bb Dd Pnpn spsp": "Blue Nebraskan",
"bb Dd pnpn spsp": "Blue Nebraskan",
"bb Dd Ee Nn spsp": "Blue Nebraskan",
"bb Dd Ee Slsl spsp": "Blue Nebraskan",
"bb Dd Ee Pnpn spsp": "Blue Nebraskan",
"bb Dd Ee pnpn spsp": "Blue Nebraskan",
"bb Dd Nn Slsl spsp": "Blue Nebraskan",
"bb Dd Nn Pnpn spsp": "Blue Nebraskan",
"bb Dd Nn pnpn spsp": "Blue Nebraskan",
"bb Dd Nn Pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Nn pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee Nn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee Nn Pnpn spsp": "Blue Nebraskan",
"bb Dd Ee Nn pnpn spsp": "Blue Nebraskan",
"bb Dd Ee Nn Pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee Nn pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee Pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee pnpn Slsl spsp": "Blue Nebraskan",

// bb Dd fdfd BLUE NEBRASKAN
"bb Dd fdfd spsp": "Blue Nebraskan",
"bb Dd Ee fdfd spsp": "Blue Nebraskan",
"bb Dd fdfd Nn spsp": "Blue Nebraskan",
"bb Dd fdfd Slsl spsp": "Blue Nebraskan",
"bb Dd fdfd Pnpn spsp": "Blue Nebraskan",
"bb Dd fdfd pnpn spsp": "Blue Nebraskan",
"bb Dd Ee fdfd Nn spsp": "Blue Nebraskan",
"bb Dd Ee fdfd Slsl spsp": "Blue Nebraskan",
"bb Dd Ee fdfd Pnpn spsp": "Blue Nebraskan",
"bb Dd Ee fdfd pnpn spsp": "Blue Nebraskan",
"bb Dd fdfd Nn Slsl spsp": "Blue Nebraskan",
"bb Dd fdfd Nn Pnpn spsp": "Blue Nebraskan",
"bb Dd fdfd Nn pnpn spsp": "Blue Nebraskan",
"bb Dd fdfd Nn Pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd fdfd Nn pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd fdfd Pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd fdfd pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee fdfd Nn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee fdfd Nn Pnpn spsp": "Blue Nebraskan",
"bb Dd Ee fdfd Nn pnpn spsp": "Blue Nebraskan",
"bb Dd Ee fdfd Nn Pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee fdfd Nn pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee fdfd Pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee fdfd pnpn Slsl spsp": "Blue Nebraskan",


// bb Dd Fdfd BLUE NEBRASKAN
"bb Dd Fdfd spsp": "Blue Nebraskan",
"bb Dd Ee Fdfd spsp": "Blue Nebraskan",
"bb Dd Fdfd Nn spsp": "Blue Nebraskan",
"bb Dd Fdfd Slsl spsp": "Blue Nebraskan",
"bb Dd Fdfd Pnpn spsp": "Blue Nebraskan",
"bb Dd Fdfd pnpn spsp": "Blue Nebraskan",
"bb Dd Ee Fdfd Nn spsp": "Blue Nebraskan",
"bb Dd Ee Fdfd Slsl spsp": "Blue Nebraskan",
"bb Dd Ee Fdfd Pnpn spsp": "Blue Nebraskan",
"bb Dd Ee Fdfd pnpn spsp": "Blue Nebraskan",
"bb Dd Fdfd Nn Slsl spsp": "Blue Nebraskan",
"bb Dd Fdfd Nn Pnpn spsp": "Blue Nebraskan",
"bb Dd Fdfd Nn pnpn spsp": "Blue Nebraskan",
"bb Dd Fdfd Nn Pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Fdfd Nn pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Fdfd Pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Fdfd pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee Fdfd Nn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee Fdfd Nn Pnpn spsp": "Blue Nebraskan",
"bb Dd Ee Fdfd Nn pnpn spsp": "Blue Nebraskan",
"bb Dd Ee Fdfd Nn Pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee Fdfd Nn pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee Fdfd Pnpn Slsl spsp": "Blue Nebraskan",
"bb Dd Ee Fdfd pnpn Slsl spsp": "Blue Nebraskan",

 
  
  
  // bb RED NEBRASKAN
"bb rr spsp": "Red Nebraskan",
"bb Ee rr spsp": "Red Nebraskan",
"bb Nn rr spsp": "Red Nebraskan",
"bb rr Slsl spsp": "Red Nebraskan",
"bb Pnpn rr spsp": "Red Nebraskan",
"bb pnpn rr spsp": "Red Nebraskan",
"bb Ee Nn rr spsp": "Red Nebraskan",
"bb Ee rr Slsl spsp": "Red Nebraskan",
"bb Ee Pnpn rr spsp": "Red Nebraskan",
"bb Ee pnpn rr spsp": "Red Nebraskan",
"bb Nn rr Slsl spsp": "Red Nebraskan",
"bb Nn Pnpn rr spsp": "Red Nebraskan",
"bb Nn pnpn rr spsp": "Red Nebraskan",
"bb Nn Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Nn pnpn rr Slsl spsp": "Red Nebraskan",
"bb Pnpn rr Slsl spsp": "Red Nebraskan",
"bb pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ee Nn rr Slsl spsp": "Red Nebraskan",
"bb Ee Nn Pnpn rr spsp": "Red Nebraskan",
"bb Ee Nn pnpn rr spsp": "Red Nebraskan",
"bb Ee Nn Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ee Nn pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ee Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ee pnpn rr Slsl spsp": "Red Nebraskan",

  
 // bb Ccg RED NEBRASKAN
"bb Ccg rr spsp": "Red Nebraskan",
"bb Ccg Ee rr spsp": "Red Nebraskan",
"bb Ccg Nn rr spsp": "Red Nebraskan",
"bb Ccg rr Slsl spsp": "Red Nebraskan",
"bb Ccg Pnpn rr spsp": "Red Nebraskan",
"bb Ccg pnpn rr spsp": "Red Nebraskan",
"bb Ccg Ee Nn rr spsp": "Red Nebraskan",
"bb Ccg Ee rr Slsl spsp": "Red Nebraskan",
"bb Ccg Ee Pnpn rr spsp": "Red Nebraskan",
"bb Ccg Ee pnpn rr spsp": "Red Nebraskan",
"bb Ccg Nn rr Slsl spsp": "Red Nebraskan",
"bb Ccg Nn Pnpn rr spsp": "Red Nebraskan",
"bb Ccg Nn pnpn rr spsp": "Red Nebraskan",
"bb Ccg Nn Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ccg Nn pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ccg Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ccg pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ccg Ee Nn rr Slsl spsp": "Red Nebraskan",
"bb Ccg Ee Nn Pnpn rr spsp": "Red Nebraskan",
"bb Ccg Ee Nn pnpn rr spsp": "Red Nebraskan",
"bb Ccg Ee Nn Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ccg Ee Nn pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ccg Ee Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ccg Ee pnpn rr Slsl spsp": "Red Nebraskan",

  
  // bb Ccm RED NEBRASKAN
"bb Ccm rr spsp": "Red Nebraskan",
"bb Ccm Ee rr spsp": "Red Nebraskan",
"bb Ccm Nn rr spsp": "Red Nebraskan",
"bb Ccm rr Slsl spsp": "Red Nebraskan",
"bb Ccm Pnpn rr spsp": "Red Nebraskan",
"bb Ccm pnpn rr spsp": "Red Nebraskan",
"bb Ccm Ee Nn rr spsp": "Red Nebraskan",
"bb Ccm Ee rr Slsl spsp": "Red Nebraskan",
"bb Ccm Ee Pnpn rr spsp": "Red Nebraskan",
"bb Ccm Ee pnpn rr spsp": "Red Nebraskan",
"bb Ccm Nn rr Slsl spsp": "Red Nebraskan",
"bb Ccm Nn Pnpn rr spsp": "Red Nebraskan",
"bb Ccm Nn pnpn rr spsp": "Red Nebraskan",
"bb Ccm Nn Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ccm Nn pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ccm Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ccm pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ccm Ee Nn rr Slsl spsp": "Red Nebraskan",
"bb Ccm Ee Nn Pnpn rr spsp": "Red Nebraskan",
"bb Ccm Ee Nn pnpn rr spsp": "Red Nebraskan",
"bb Ccm Ee Nn Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ccm Ee Nn pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ccm Ee Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Ccm Ee pnpn rr Slsl spsp": "Red Nebraskan",

  
  
  // bb Cc RED NEBRASKAN
"bb Cc rr spsp": "Red Nebraskan",
"bb Cc Ee rr spsp": "Red Nebraskan",
"bb Cc Nn rr spsp": "Red Nebraskan",
"bb Cc rr Slsl spsp": "Red Nebraskan",
"bb Cc Pnpn rr spsp": "Red Nebraskan",
"bb Cc pnpn rr spsp": "Red Nebraskan",
"bb Cc Ee Nn rr spsp": "Red Nebraskan",
"bb Cc Ee rr Slsl spsp": "Red Nebraskan",
"bb Cc Ee Pnpn rr spsp": "Red Nebraskan",
"bb Cc Ee pnpn rr spsp": "Red Nebraskan",
"bb Cc Nn rr Slsl spsp": "Red Nebraskan",
"bb Cc Nn Pnpn rr spsp": "Red Nebraskan",
"bb Cc Nn pnpn rr spsp": "Red Nebraskan",
"bb Cc Nn Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Cc Nn pnpn rr Slsl spsp": "Red Nebraskan",
"bb Cc Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Cc pnpn rr Slsl spsp": "Red Nebraskan",
"bb Cc Ee Nn rr Slsl spsp": "Red Nebraskan",
"bb Cc Ee Nn Pnpn rr spsp": "Red Nebraskan",
"bb Cc Ee Nn pnpn rr spsp": "Red Nebraskan",
"bb Cc Ee Nn Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Cc Ee Nn pnpn rr Slsl spsp": "Red Nebraskan",
"bb Cc Ee Pnpn rr Slsl spsp": "Red Nebraskan",
"bb Cc Ee pnpn rr Slsl spsp": "Red Nebraskan",

  
  
  // bb cgcg RED NEBRASKAN
"bb cgcg rr spsp": "Red Nebraskan",
"bb cgcg Ee rr spsp": "Red Nebraskan",
"bb cgcg Nn rr spsp": "Red Nebraskan",
"bb cgcg rr Slsl spsp": "Red Nebraskan",
"bb cgcg Pnpn rr spsp": "Red Nebraskan",
"bb cgcg pnpn rr spsp": "Red Nebraskan",
"bb cgcg Ee Nn rr spsp": "Red Nebraskan",
"bb cgcg Ee rr Slsl spsp": "Red Nebraskan",
"bb cgcg Ee Pnpn rr spsp": "Red Nebraskan",
"bb cgcg Ee pnpn rr spsp": "Red Nebraskan",
"bb cgcg Nn rr Slsl spsp": "Red Nebraskan",
"bb cgcg Nn Pnpn rr spsp": "Red Nebraskan",
"bb cgcg Nn pnpn rr spsp": "Red Nebraskan",
"bb cgcg Nn Pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgcg Nn pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgcg Pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgcg pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgcg Ee Nn rr Slsl spsp": "Red Nebraskan",
"bb cgcg Ee Nn Pnpn rr spsp": "Red Nebraskan",
"bb cgcg Ee Nn pnpn rr spsp": "Red Nebraskan",
"bb cgcg Ee Nn Pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgcg Ee Nn pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgcg Ee Pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgcg Ee pnpn rr Slsl spsp": "Red Nebraskan",

  
  // bb cgcm RED NEBRASKAN
"bb cgcm rr spsp": "Red Nebraskan",
"bb cgcm Ee rr spsp": "Red Nebraskan",
"bb cgcm Nn rr spsp": "Red Nebraskan",
"bb cgcm rr Slsl spsp": "Red Nebraskan",
"bb cgcm Pnpn rr spsp": "Red Nebraskan",
"bb cgcm pnpn rr spsp": "Red Nebraskan",
"bb cgcm Ee Nn rr spsp": "Red Nebraskan",
"bb cgcm Ee rr Slsl spsp": "Red Nebraskan",
"bb cgcm Ee Pnpn rr spsp": "Red Nebraskan",
"bb cgcm Ee pnpn rr spsp": "Red Nebraskan",
"bb cgcm Nn rr Slsl spsp": "Red Nebraskan",
"bb cgcm Nn Pnpn rr spsp": "Red Nebraskan",
"bb cgcm Nn pnpn rr spsp": "Red Nebraskan",
"bb cgcm Nn Pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgcm Nn pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgcm Pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgcm pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgcm Ee Nn rr Slsl spsp": "Red Nebraskan",
"bb cgcm Ee Nn Pnpn rr spsp": "Red Nebraskan",
"bb cgcm Ee Nn pnpn rr spsp": "Red Nebraskan",
"bb cgcm Ee Nn Pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgcm Ee Nn pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgcm Ee Pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgcm Ee pnpn rr Slsl spsp": "Red Nebraskan",

  
  
  // bb cgc RED NEBRASKAN
"bb cgc rr spsp": "Red Nebraskan",
"bb cgc Ee rr spsp": "Red Nebraskan",
"bb cgc Nn rr spsp": "Red Nebraskan",
"bb cgc rr Slsl spsp": "Red Nebraskan",
"bb cgc Pnpn rr spsp": "Red Nebraskan",
"bb cgc pnpn rr spsp": "Red Nebraskan",
"bb cgc Ee Nn rr spsp": "Red Nebraskan",
"bb cgc Ee rr Slsl spsp": "Red Nebraskan",
"bb cgc Ee Pnpn rr spsp": "Red Nebraskan",
"bb cgc Ee pnpn rr spsp": "Red Nebraskan",
"bb cgc Nn rr Slsl spsp": "Red Nebraskan",
"bb cgc Nn Pnpn rr spsp": "Red Nebraskan",
"bb cgc Nn pnpn rr spsp": "Red Nebraskan",
"bb cgc Nn Pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgc Nn pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgc Pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgc pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgc Ee Nn rr Slsl spsp": "Red Nebraskan",
"bb cgc Ee Nn Pnpn rr spsp": "Red Nebraskan",
"bb cgc Ee Nn pnpn rr spsp": "Red Nebraskan",
"bb cgc Ee Nn Pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgc Ee Nn pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgc Ee Pnpn rr Slsl spsp": "Red Nebraskan",
"bb cgc Ee pnpn rr Slsl spsp": "Red Nebraskan",

  
  
  
// Wild subspecies

"bb..": "Eastern Wild",
"bb...": "Gould's Wild",
"bb....": "Merriam's Wild",
"bb.....": "Osceola Wild",
"bb......": "Rio Grande Wild",


//Broad Breasted Bronze
"bb.": "Broad Breasted Bronze",



   // special case pheno search for white varieties
   


"bb cc": "White (Dark Brown Eyes)",
"BB cc": "White (Blue Eyes)",
"b1b1 cc": "White (Light Brown Eyes)",





   
   


"bb cc..": "White Holland",
"bb cc...": "Beltsville Small White",
"bb cc....": "Midget White",
"bb cc.....": "Holland White",
"bb cc......": "White Beltsville",
"bb cc.......": "White Midget",
"bb cc........": "Broad Breasted White", 
"bb cc..........": "Beltsville White",
    

"bb cc.........": "White (Dark Brown Eyes)",
"BB cc.": "White (Blue Eyes)",
"b1b1 cc.": "White (Light Brown Eyes)", 



//BROWN EDGED REGAL RED
"b1b1 ee rr": "Brown Edged Regal Red",
"b1b1 ee rr Slsl": "Brown Edged Regal Red",
"b1b1 Ccm ee rr": "Brown Edged Regal Red",
"b1b1 Ccm ee rr Slsl": "Brown Edged Regal Red",
"b1b1 Cc ee rr": "Brown Edged Regal Red",
"b1b1 Cc ee rr Slsl": "Brown Edged Regal Red",
"b1b1 e- rr": "Brown Edged Regal Red",
"b1b1 e- rr Slsl": "Brown Edged Regal Red",
"b1b1 Ccm e- rr": "Brown Edged Regal Red",
"b1b1 Ccm e- rr Slsl": "Brown Edged Regal Red",
"b1b1 Cc e- rr": "Brown Edged Regal Red",
"b1b1 Cc e- rr Slsl": "Brown Edged Regal Red",








};
