const phenotypeMapping1C = {
 // Bb1 SLATE EDGED BARRED DILUTE JERSEY BUFF, done
"Bb1 Dd nn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee nn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd nn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd nn Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd nn pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee nn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee nn Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee nn pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd nn Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd nn pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee nn Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee nn pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 Spsp SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 Dd nn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee nn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd nn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd nn Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd nn pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee nn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee nn Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee nn pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd nn Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd nn pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee nn Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee nn pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 Fdfd SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 Dd Fdfd nn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee Fdfd nn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Fdfd nn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Fdfd nn Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Fdfd nn pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee Fdfd nn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee Fdfd nn Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee Fdfd nn pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Fdfd nn Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Fdfd nn pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee Fdfd nn Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee Fdfd nn pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
 
  
 // Bb1 fdfd SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 Dd fdfd nn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee fdfd nn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd fdfd nn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd fdfd nn Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd fdfd nn pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee fdfd nn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee fdfd nn Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee fdfd nn pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd fdfd nn Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd fdfd nn pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee fdfd nn Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee fdfd nn pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 Fdfd Spsp SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 Dd Fdfd nn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee Fdfd nn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Fdfd nn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Fdfd nn Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Fdfd nn pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee Fdfd nn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee Fdfd nn Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee Fdfd nn pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Fdfd nn Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Fdfd nn pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee Fdfd nn Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee Fdfd nn pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 fdfd Spsp SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 Dd fdfd nn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee fdfd nn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd fdfd nn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd fdfd nn Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd fdfd nn pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee fdfd nn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee fdfd nn Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee fdfd nn pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd fdfd nn Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd fdfd nn pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee fdfd nn Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 Dd Ee fdfd nn pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 cgcg SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 cgcg Dd nn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee nn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd nn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd nn Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd nn pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee nn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee nn Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee nn pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd nn Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd nn pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee nn Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee nn pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 cgcg Spsp SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 cgcg Dd nn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee nn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd nn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd nn Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd nn pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee nn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee nn Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee nn pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd nn Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd nn pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee nn Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee nn pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 cgcg Fdfd SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 cgcg Dd Fdfd nn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee Fdfd nn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd nn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd nn Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd nn pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee Fdfd nn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee Fdfd nn Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee Fdfd nn pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd nn Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd nn pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee Fdfd nn Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee Fdfd nn pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 cgcg fdfd SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 cgcg Dd fdfd nn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee fdfd nn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd nn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd nn Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd nn pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee fdfd nn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee fdfd nn Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee fdfd nn pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd nn Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd nn pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee fdfd nn Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee fdfd nn pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 cgcg Fdfd Spsp SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 cgcg Dd Fdfd nn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee Fdfd nn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd nn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd nn Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd nn pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee Fdfd nn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee Fdfd nn Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee Fdfd nn pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd nn Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd nn pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee Fdfd nn Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee Fdfd nn pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 cgcg fdfd Spsp SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 cgcg Dd fdfd nn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee fdfd nn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd nn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd nn Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd nn pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee fdfd nn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee fdfd nn Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee fdfd nn pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd nn Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd nn pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee fdfd nn Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Ee fdfd nn pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 cgcg SLATE EDGED BARRED DILUTE JERSEY BUFF females
"Bb1 cgcg Dd n- rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd n- rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd n- Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd n- pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd n- Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd n- pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 cgcg Spsp SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 cgcg Dd n- rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd n- rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd n- Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd n- pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd n- Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd n- pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 cgcg Fdfd SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 cgcg Dd Fdfd n- rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd n- rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd n- Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd n- pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd n- Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd n- pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 cgcg fdfd SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 cgcg Dd fdfd n- rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd n- rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd n- Pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd n- pnpn rr": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd n- Pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd n- pnpn rr Slsl": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 cgcg Fdfd Spsp SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 cgcg Dd Fdfd n- rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd n- rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd n- Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd n- pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd n- Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd Fdfd n- pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",

// Bb1 cgcg fdfd Spsp SLATE EDGED BARRED DILUTE JERSEY BUFF
"Bb1 cgcg Dd fdfd n- rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd n- rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd n- Pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd n- pnpn rr Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd n- Pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",
"Bb1 cgcg Dd fdfd n- pnpn rr Slsl Spsp": "Slate Edged Barred Dilute Jersey Buff",



 
  
// SLATE EDGED CHESTNUT RED
"bb1 Dd rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee rr": "Slate Edged Chestnut Red",
"bb1 Dd Nn rr": "Slate Edged Chestnut Red",
"bb1 Dd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee Nn rr": "Slate Edged Chestnut Red",
"bb1 Dd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Spsp
"bb1 Dd rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Fdfd
"bb1 Dd Fdfd rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd rr": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Fdfd and Spsp
"bb1 Dd Fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee Fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with fdfd
"bb1 Dd fdfd rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd rr": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Dd fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with fdfd and Spsp
"bb1 Dd fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd Ee fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Dd fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// Ccg SLATE EDGED CHESTNUT RED
"bb1 Ccg Dd rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Nn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Nn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Spsp
"bb1 Ccg Dd rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Fdfd
"bb1 Ccg Dd Fdfd rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Fdfd and Spsp
"bb1 Ccg Dd Fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee Fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with fdfd
"bb1 Ccg Dd fdfd rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee fdfd rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee fdfd Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd Ee fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccg Dd fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccg Dd fdfd Nn pnpn rr": "Slate Edged Chestnut Red",

// Ccm SLATE EDGED CHESTNUT RED
"bb1 Ccm Dd rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Nn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Nn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Spsp
"bb1 Ccm Dd rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Fdfd
"bb1 Ccm Dd Fdfd rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Fdfd and Spsp
"bb1 Ccm Dd Fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee Fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with fdfd
"bb1 Ccm Dd fdfd rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee fdfd rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee fdfd Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd Ee fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Ccm Dd fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Ccm Dd fdfd Nn pnpn rr": "Slate Edged Chestnut Red",

// Cc SLATE EDGED CHESTNUT RED
"bb1 Cc Dd rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Nn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Nn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Spsp
"bb1 Cc Dd rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Fdfd
"bb1 Cc Dd Fdfd rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Fdfd and Spsp
"bb1 Cc Dd Fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee Fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 Cc Dd Fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with fdfd
"bb1 Cc Dd fdfd rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee fdfd rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee fdfd Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd Ee fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 Cc Dd fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 Cc Dd fdfd Nn pnpn rr": "Slate Edged Chestnut Red",

// cgcg SLATE EDGED CHESTNUT RED
"bb1 cgcg Dd rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Nn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Spsp
"bb1 cgcg Dd rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Fdfd
"bb1 cgcg Dd Fdfd rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Fdfd and Spsp
"bb1 cgcg Dd Fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee Fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with fdfd
"bb1 cgcg Dd fdfd rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee fdfd rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee fdfd Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd Ee fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcg Dd fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcg Dd fdfd Nn pnpn rr": "Slate Edged Chestnut Red",

// cgcm SLATE EDGED CHESTNUT RED
"bb1 cgcm Dd rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Nn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Spsp
"bb1 cgcm Dd rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Fdfd
"bb1 cgcm Dd Fdfd rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Fdfd and Spsp
"bb1 cgcm Dd Fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee Fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with fdfd
"bb1 cgcm Dd fdfd rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee fdfd rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee fdfd Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd Ee fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgcm Dd fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgcm Dd fdfd Nn pnpn rr": "Slate Edged Chestnut Red",

// cgc SLATE EDGED CHESTNUT RED
"bb1 cgc Dd rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Nn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Spsp
"bb1 cgc Dd rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Fdfd
"bb1 cgc Dd Fdfd rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Nn pnpn rr": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with Fdfd and Spsp
"bb1 cgc Dd Fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Nn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Nn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Nn Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Nn pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd pnpn rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee Fdfd rr Slsl Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Nn Pnpn rr Spsp": "Slate Edged Chestnut Red",
"bb1 cgc Dd Fdfd Nn pnpn rr Spsp": "Slate Edged Chestnut Red",

// SLATE EDGED CHESTNUT RED with fdfd
"bb1 cgc Dd fdfd rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee fdfd rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee fdfd Nn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee fdfd Nn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee fdfd Nn pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee fdfd Nn Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee fdfd Nn pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee fdfd Pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee fdfd Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee fdfd pnpn rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee fdfd pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd Ee fdfd rr Slsl": "Slate Edged Chestnut Red",
"bb1 cgc Dd fdfd Nn Pnpn rr": "Slate Edged Chestnut Red",
"bb1 cgc Dd fdfd Nn pnpn rr": "Slate Edged Chestnut Red",




// SLATE EDGED JERSEY BUFF
"BB Dd rr": "Slate Edged Jersey Buff",
"BB Dd Ee rr": "Slate Edged Jersey Buff",
"BB Dd Nn rr": "Slate Edged Jersey Buff",
"BB Dd rr Slsl": "Slate Edged Jersey Buff",
"BB Dd Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Dd pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Dd Ee Nn rr Slsl": "Slate Edged Jersey Buff",
"BB Dd Nn Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Dd Nn pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Dd Ee Nn Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Dd Ee Nn pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Ccg Dd rr": "Slate Edged Jersey Buff",
"BB Ccg Dd Ee rr": "Slate Edged Jersey Buff",
"BB Ccg Dd Nn rr": "Slate Edged Jersey Buff",
"BB Ccg Dd rr Slsl": "Slate Edged Jersey Buff",
"BB Ccg Dd Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Ccg Dd pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Ccg Dd Ee Nn rr Slsl": "Slate Edged Jersey Buff",
"BB Ccg Dd Nn Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Ccg Dd Nn pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Ccg Dd Ee Nn Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Ccg Dd Ee Nn pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Ccm Dd rr": "Slate Edged Jersey Buff",
"BB Ccm Dd Ee rr": "Slate Edged Jersey Buff",
"BB Ccm Dd Nn rr": "Slate Edged Jersey Buff",
"BB Ccm Dd rr Slsl": "Slate Edged Jersey Buff",
"BB Ccm Dd Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Ccm Dd pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Ccm Dd Ee Nn rr Slsl": "Slate Edged Jersey Buff",
"BB Ccm Dd Nn Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Ccm Dd Nn pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Ccm Dd Ee Nn Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Ccm Dd Ee Nn pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Cc Dd rr": "Slate Edged Jersey Buff",
"BB Cc Dd Ee rr": "Slate Edged Jersey Buff",
"BB Cc Dd Nn rr": "Slate Edged Jersey Buff",
"BB Cc Dd rr Slsl": "Slate Edged Jersey Buff",
"BB Cc Dd Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Cc Dd pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Cc Dd Ee Nn rr Slsl": "Slate Edged Jersey Buff",
"BB Cc Dd Nn Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Cc Dd Nn pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Cc Dd Ee Nn Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB Cc Dd Ee Nn pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgcg Dd rr": "Slate Edged Jersey Buff",
"BB cgcg Dd Ee rr": "Slate Edged Jersey Buff",
"BB cgcg Dd Nn rr": "Slate Edged Jersey Buff",
"BB cgcg Dd rr Slsl": "Slate Edged Jersey Buff",
"BB cgcg Dd Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgcg Dd pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgcg Dd Ee Nn rr Slsl": "Slate Edged Jersey Buff",
"BB cgcg Dd Nn Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgcg Dd Nn pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgcg Dd Ee Nn Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgcg Dd Ee Nn pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgcm Dd rr": "Slate Edged Jersey Buff",
"BB cgcm Dd Ee rr": "Slate Edged Jersey Buff",
"BB cgcm Dd Nn rr": "Slate Edged Jersey Buff",
"BB cgcm Dd rr Slsl": "Slate Edged Jersey Buff",
"BB cgcm Dd Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgcm Dd pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgcm Dd Ee Nn rr Slsl": "Slate Edged Jersey Buff",
"BB cgcm Dd Nn Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgcm Dd Nn pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgcm Dd Ee Nn Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgcm Dd Ee Nn pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgc Dd rr": "Slate Edged Jersey Buff",
"BB cgc Dd Ee rr": "Slate Edged Jersey Buff",
"BB cgc Dd Nn rr": "Slate Edged Jersey Buff",
"BB cgc Dd rr Slsl": "Slate Edged Jersey Buff",
"BB cgc Dd Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgc Dd pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgc Dd Ee Nn rr Slsl": "Slate Edged Jersey Buff",
"BB cgc Dd Nn Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgc Dd Nn pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgc Dd Ee Nn Pnpn rr Slsl": "Slate Edged Jersey Buff",
"BB cgc Dd Ee Nn pnpn rr Slsl": "Slate Edged Jersey Buff",









// SLATE EDGED LIGHT RED
"b1b1 Ccg Dd rr": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee rr": "Slate Edged Light Red",
"b1b1 Ccg Dd Nn rr": "Slate Edged Light Red",
"b1b1 Ccg Dd rr Slsl": "Slate Edged Light Red",
"b1b1 Ccg Dd Pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Nn rr": "Slate Edged Light Red",
"b1b1 Ccg Dd Nn rr Slsl": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee Nn rr Slsl": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee Nn Pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Nn pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Nn Pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Nn pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Nn Pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Nn pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee rr Slsl": "Slate Edged Light Red",
"b1b1 Ccg Dd Nn Pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Nn pnpn rr": "Pencilled Slate Edged Light Red",

// SLATE EDGED LIGHT RED with Spsp
"b1b1 Ccg Dd rr Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee rr Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Nn rr Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd rr Slsl Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Pnpn rr Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd pnpn rr Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Nn rr Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Nn rr Slsl Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee Nn rr Slsl Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee Nn Pnpn rr Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Nn pnpn rr Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Nn Pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Nn pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Nn Pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Nn pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Pnpn rr Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee pnpn rr Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee rr Slsl Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Nn Pnpn rr Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Nn pnpn rr Spsp": "Pencilled Slate Edged Light Red",

// SLATE EDGED LIGHT RED with Fdfd
"b1b1 Ccg Dd Fdfd rr": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd rr": "Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Nn rr": "Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd rr Slsl": "Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Nn rr": "Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Nn rr Slsl": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Nn rr Slsl": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Nn Pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Nn pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Nn Pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Nn pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Nn Pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Nn pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd rr Slsl": "Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Nn Pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Nn pnpn rr": "Pencilled Slate Edged Light Red",
// SLATE EDGED LIGHT RED with Fdfd and Spsp
"b1b1 Ccg Dd Fdfd rr Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd rr Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Nn rr Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd rr Slsl Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Pnpn rr Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd pnpn rr Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Nn rr Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Nn rr Slsl Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Nn rr Slsl Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Nn Pnpn rr Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Nn pnpn rr Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Nn Pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Nn pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Nn Pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Nn pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd Pnpn rr Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd pnpn rr Slsl Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd pnpn rr Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee Fdfd rr Slsl Spsp": "Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Nn Pnpn rr Spsp": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Fdfd Nn pnpn rr Spsp": "Pencilled Slate Edged Light Red",

// SLATE EDGED LIGHT RED with fdfd
"b1b1 Ccg Dd fdfd rr": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee fdfd rr": "Slate Edged Light Red",
"b1b1 Ccg Dd fdfd Nn rr": "Slate Edged Light Red",
"b1b1 Ccg Dd fdfd rr Slsl": "Slate Edged Light Red",
"b1b1 Ccg Dd fdfd Pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd fdfd pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee fdfd Nn rr": "Slate Edged Light Red",
"b1b1 Ccg Dd fdfd Nn rr Slsl": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee fdfd Nn rr Slsl": "Slate Edged Light Red",
"b1b1 Ccg Dd Ee fdfd Nn Pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee fdfd Nn pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd fdfd Nn Pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd fdfd Nn pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd fdfd Pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd fdfd pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee fdfd Nn Pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee fdfd Nn pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee fdfd Pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee fdfd Pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee fdfd pnpn rr Slsl": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee fdfd pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd Ee fdfd rr Slsl": "Slate Edged Light Red",
"b1b1 Ccg Dd fdfd Nn Pnpn rr": "Pencilled Slate Edged Light Red",
"b1b1 Ccg Dd fdfd Nn pnpn rr": "Pencilled Slate Edged Light Red",


// b1b1 cgcg PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd nn pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee nn pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd nn pnpn rr Slsl": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee nn pnpn rr Slsl": "Pencilled Slate Edged Red Palm",


// b1b1 cgcg Spsp PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd nn pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee nn pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd nn pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee nn pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",


// b1b1 cgcg Fdfd PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd Fdfd nn pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee Fdfd nn pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Fdfd nn pnpn rr Slsl": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee Fdfd nn pnpn rr Slsl": "Pencilled Slate Edged Red Palm",


// b1b1 cgcg fdfd PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd fdfd nn pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee fdfd nn pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd fdfd nn pnpn rr Slsl": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee fdfd nn pnpn rr Slsl": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg Fdfd Spsp PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd Fdfd nn pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee Fdfd nn pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Fdfd nn pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee Fdfd nn pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",


// b1b1 cgcg fdfd Spsp PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd fdfd nn pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee fdfd nn pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd fdfd nn pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee fdfd nn pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",


// b1b1 cgcg PENCILLED SLATE EDGED RED PALM females
"b1b1 cgcg Dd n- pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd n- pnpn rr Slsl": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg Spsp PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd n- pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd n- pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg Fdfd PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd Fdfd n- pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Fdfd n- pnpn rr Slsl": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg fdfd PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd fdfd n- pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd fdfd n- pnpn rr Slsl": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg Fdfd Spsp PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd Fdfd n- pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Fdfd n- pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg fdfd Spsp PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd fdfd n- pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd fdfd n- pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",

// Pnpn
// b1b1 cgcg PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd nn Pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee nn Pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd nn Pnpn rr Slsl": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee nn Pnpn rr Slsl": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg Spsp PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd nn Pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee nn Pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd nn Pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee nn Pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg Fdfd PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd Fdfd nn Pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee Fdfd nn Pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Fdfd nn Pnpn rr Slsl": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee Fdfd nn Pnpn rr Slsl": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg fdfd PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd fdfd nn Pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee fdfd nn Pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd fdfd nn Pnpn rr Slsl": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee fdfd nn Pnpn rr Slsl": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg Fdfd Spsp PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd Fdfd nn Pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee Fdfd nn Pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Fdfd nn Pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee Fdfd nn Pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg fdfd Spsp PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd fdfd nn Pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee fdfd nn Pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd fdfd nn Pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Ee fdfd nn Pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",


// b1b1 cgcg PENCILLED SLATE EDGED RED PALM females
"b1b1 cgcg Dd n- Pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd n- Pnpn rr Slsl": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg Spsp PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd n- Pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd n- Pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg Fdfd PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd Fdfd n- Pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Fdfd n- Pnpn rr Slsl": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg fdfd PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd fdfd n- Pnpn rr": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd fdfd n- Pnpn rr Slsl": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg Fdfd Spsp PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd Fdfd n- Pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd Fdfd n- Pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",

// b1b1 cgcg fdfd Spsp PENCILLED SLATE EDGED RED PALM
"b1b1 cgcg Dd fdfd n- Pnpn rr Spsp": "Pencilled Slate Edged Red Palm",
"b1b1 cgcg Dd fdfd n- Pnpn rr Slsl Spsp": "Pencilled Slate Edged Red Palm",



// SLATE EDGED RED PALM
"b1b1 cgcg Dd nn rr": "Slate Edged Red Palm",
"b1b1 cgc Dd nn rr": "Slate Edged Red Palm",
"b1b1 cgcg Dd Ee nn rr": "Slate Edged Red Palm",
"b1b1 cgc Dd Ee nn rr": "Slate Edged Red Palm",
"b1b1 cgcg Dd nn rr Slsl": "Slate Edged Red Palm",
"b1b1 cgc Dd nn rr Slsl": "Slate Edged Red Palm",
"b1b1 cgcg Dd Ee nn rr Slsl": "Slate Edged Red Palm",
"b1b1 cgc Dd Ee nn rr Slsl": "Slate Edged Red Palm",
"b1b1 cgcm Dd nn rr": "Slate Edged Red Palm",
"b1b1 cgcm Dd nn rr Slsl": "Slate Edged Red Palm",
"b1b1 cgcg Dd n- rr": "Slate Edged Red Palm",
"b1b1 cgc Dd n- rr": "Slate Edged Red Palm",
"b1b1 cgcg Dd n- rr Slsl": "Slate Edged Red Palm",
"b1b1 cgc Dd n- rr Slsl": "Slate Edged Red Palm",
"b1b1 cgcm Dd n- rr": "Slate Edged Red Palm",
"b1b1 cgcm Dd n- rr Slsl": "Slate Edged Red Palm",

// SLATE EDGED RED SWEETGRASS
"b1b1 cgcg Dd rr": "Slate Edged Red Sweetgrass",
"b1b1 cgcg Dd Ee rr": "Slate Edged Red Sweetgrass",
"b1b1 cgcg Dd Nn rr": "Slate Edged Red Sweetgrass",
"b1b1 cgcg Dd rr Slsl": "Slate Edged Red Sweetgrass",
"b1b1 cgcg Dd Ee Nn rr": "Slate Edged Red Sweetgrass",
"b1b1 cgcg Dd Nn rr Slsl": "Slate Edged Red Sweetgrass",
"b1b1 cgcg Dd Ee Nn rr Slsl": "Slate Edged Red Sweetgrass",
"b1b1 cgcm Dd rr": "Slate Edged Red Sweetgrass",
"b1b1 cgcm Dd Ee rr": "Slate Edged Red Sweetgrass",
"b1b1 cgcm Dd Nn rr": "Slate Edged Red Sweetgrass",
"b1b1 cgcm Dd rr Slsl": "Slate Edged Red Sweetgrass",
"b1b1 cgcm Dd Ee Nn rr": "Slate Edged Red Sweetgrass",
"b1b1 cgcm Dd Nn rr Slsl": "Slate Edged Red Sweetgrass",
"b1b1 cgcm Dd Ee Nn rr Slsl": "Slate Edged Red Sweetgrass",
"b1b1 cgc Dd rr": "Slate Edged Red Sweetgrass",
"b1b1 cgc Dd Ee rr": "Slate Edged Red Sweetgrass",
"b1b1 cgc Dd Nn rr": "Slate Edged Red Sweetgrass",
"b1b1 cgc Dd rr Slsl": "Slate Edged Red Sweetgrass",
"b1b1 cgc Dd Ee Nn rr": "Slate Edged Red Sweetgrass",
"b1b1 cgc Dd Nn rr Slsl": "Slate Edged Red Sweetgrass",
"b1b1 cgc Dd Ee Nn rr Slsl": "Slate Edged Red Sweetgrass",


// SLATE EDGED REGAL RED
"b1b1 Dd rr": "Slate Edged Regal Red",
"b1b1 Dd Ee rr": "Slate Edged Regal Red",
"b1b1 Dd Nn rr": "Slate Edged Regal Red",
"b1b1 Dd rr Slsl": "Slate Edged Regal Red",
"b1b1 Dd Pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Nn rr": "Slate Edged Regal Red",
"b1b1 Dd Nn rr Slsl": "Slate Edged Regal Red",
"b1b1 Dd Ee Nn rr Slsl": "Slate Edged Regal Red",
"b1b1 Dd Ee Nn Pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Nn pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Nn Pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Nn pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Nn Pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Nn pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee rr Slsl": "Slate Edged Regal Red",
"b1b1 Dd Nn Pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Nn pnpn rr": "Pencilled Slate Edged Regal Red",

// SLATE EDGED REGAL RED with Spsp
"b1b1 Dd rr Spsp": "Slate Edged Regal Red",
"b1b1 Dd Ee rr Spsp": "Slate Edged Regal Red",
"b1b1 Dd Nn rr Spsp": "Slate Edged Regal Red",
"b1b1 Dd rr Slsl Spsp": "Slate Edged Regal Red",
"b1b1 Dd Pnpn rr Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd pnpn rr Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Nn rr Spsp": "Slate Edged Regal Red",
"b1b1 Dd Nn rr Slsl Spsp": "Slate Edged Regal Red",
"b1b1 Dd Ee Nn rr Slsl Spsp": "Slate Edged Regal Red",
"b1b1 Dd Ee Nn Pnpn rr Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Nn pnpn rr Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Nn Pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Nn pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Nn Pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Nn pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Pnpn rr Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee pnpn rr Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee rr Slsl Spsp": "Slate Edged Regal Red",
"b1b1 Dd Nn Pnpn rr Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Nn pnpn rr Spsp": "Pencilled Slate Edged Regal Red",

// SLATE EDGED REGAL RED with Fdfd
"b1b1 Dd Fdfd rr": "Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd rr": "Slate Edged Regal Red",
"b1b1 Dd Fdfd Nn rr": "Slate Edged Regal Red",
"b1b1 Dd Fdfd rr Slsl": "Slate Edged Regal Red",
"b1b1 Dd Fdfd Pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Fdfd pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Nn rr": "Slate Edged Regal Red",
"b1b1 Dd Fdfd Nn rr Slsl": "Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Nn rr Slsl": "Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Nn Pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Nn pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Fdfd Nn Pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Fdfd Nn pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Fdfd Pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Fdfd pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Nn Pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Nn pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd rr Slsl": "Slate Edged Regal Red",
"b1b1 Dd Fdfd Nn Pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Fdfd Nn pnpn rr": "Pencilled Slate Edged Regal Red",


// SLATE EDGED REGAL RED with Fdfd and Spsp
"b1b1 Dd Fdfd rr Spsp": "Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd rr Spsp": "Slate Edged Regal Red",
"b1b1 Dd Fdfd Nn rr Spsp": "Slate Edged Regal Red",
"b1b1 Dd Fdfd rr Slsl Spsp": "Slate Edged Regal Red",
"b1b1 Dd Fdfd Pnpn rr Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Fdfd pnpn rr Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Nn rr Spsp": "Slate Edged Regal Red",
"b1b1 Dd Fdfd Nn rr Slsl Spsp": "Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Nn rr Slsl Spsp": "Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Nn Pnpn rr Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Nn pnpn rr Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Fdfd Nn Pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Fdfd Nn pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Fdfd Pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Fdfd pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Nn Pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Nn pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd Pnpn rr Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd pnpn rr Slsl Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd pnpn rr Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee Fdfd rr Slsl Spsp": "Slate Edged Regal Red",
"b1b1 Dd Fdfd Nn Pnpn rr Spsp": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Fdfd Nn pnpn rr Spsp": "Pencilled Slate Edged Regal Red",

// SLATE EDGED REGAL RED with fdfd
"b1b1 Dd fdfd rr": "Slate Edged Regal Red",
"b1b1 Dd Ee fdfd rr": "Slate Edged Regal Red",
"b1b1 Dd fdfd Nn rr": "Slate Edged Regal Red",
"b1b1 Dd fdfd rr Slsl": "Slate Edged Regal Red",
"b1b1 Dd fdfd Pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd fdfd pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee fdfd Nn rr": "Slate Edged Regal Red",
"b1b1 Dd fdfd Nn rr Slsl": "Slate Edged Regal Red",
"b1b1 Dd Ee fdfd Nn rr Slsl": "Slate Edged Regal Red",
"b1b1 Dd Ee fdfd Nn Pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee fdfd Nn pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd fdfd Nn Pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd fdfd Nn pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd fdfd Pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd fdfd pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee fdfd Nn Pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee fdfd Nn pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee fdfd Pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee fdfd Pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee fdfd pnpn rr Slsl": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee fdfd pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd Ee fdfd rr Slsl": "Slate Edged Regal Red",
"b1b1 Dd fdfd Nn Pnpn rr": "Pencilled Slate Edged Regal Red",
"b1b1 Dd fdfd Nn pnpn rr": "Pencilled Slate Edged Regal Red",


 
  
    
// cgc LIGHT SWEETGRASS, done
"b1b1 cgc": "Light Sweetgrass",
"b1b1 cgc Ee": "Light Sweetgrass",
"b1b1 cgc Nn": "Light Sweetgrass",
"b1b1 cgc Slsl": "Light Sweetgrass",
"b1b1 cgc Ee Nn": "Light Sweetgrass",
"b1b1 cgc Ee Slsl": "Light Sweetgrass",
"b1b1 cgc Nn Slsl": "Light Sweetgrass",
"b1b1 cgc Ee Nn Slsl": "Light Sweetgrass",
"b1b1 cgc Spsp": "Light Sweetgrass",
"b1b1 cgc Ee Spsp": "Light Sweetgrass",
"b1b1 cgc Nn Spsp": "Light Sweetgrass",
"b1b1 cgc Slsl Spsp": "Light Sweetgrass",
"b1b1 cgc Ee Nn Spsp": "Light Sweetgrass",
"b1b1 cgc Ee Slsl Spsp": "Light Sweetgrass",
"b1b1 cgc Nn Slsl Spsp": "Light Sweetgrass",
"b1b1 cgc Ee Nn Slsl Spsp": "Light Sweetgrass",

// b1b1 cgc fdfd LIGHT SWEETGRASS, done
"b1b1 cgc fdfd": "Light Sweetgrass",
"b1b1 cgc Ee fdfd": "Light Sweetgrass",
"b1b1 cgc fdfd Nn": "Light Sweetgrass",
"b1b1 cgc fdfd Slsl": "Light Sweetgrass",
"b1b1 cgc Ee fdfd Nn": "Light Sweetgrass",
"b1b1 cgc Ee fdfd Slsl": "Light Sweetgrass",
"b1b1 cgc fdfd Nn Slsl": "Light Sweetgrass",
"b1b1 cgc Ee fdfd Nn Slsl": "Light Sweetgrass",
"b1b1 cgc fdfd Spsp": "Light Sweetgrass",
"b1b1 cgc Ee fdfd Spsp": "Light Sweetgrass",
"b1b1 cgc fdfd Nn Spsp": "Light Sweetgrass",
"b1b1 cgc fdfd Slsl Spsp": "Light Sweetgrass",
"b1b1 cgc Ee fdfd Nn Spsp": "Light Sweetgrass",
"b1b1 cgc Ee fdfd Slsl Spsp": "Light Sweetgrass",
"b1b1 cgc fdfd Nn Slsl Spsp": "Light Sweetgrass",
"b1b1 cgc Ee fdfd Nn Slsl Spsp": "Light Sweetgrass",

// b1b1 cgc Fdfd LIGHT SWEETGRASS, done
"b1b1 cgc Fdfd": "Light Sweetgrass",
"b1b1 cgc Ee Fdfd": "Light Sweetgrass",
"b1b1 cgc Fdfd Nn": "Light Sweetgrass",
"b1b1 cgc Fdfd Slsl": "Light Sweetgrass",
"b1b1 cgc Ee Fdfd Nn": "Light Sweetgrass",
"b1b1 cgc Ee Fdfd Slsl": "Light Sweetgrass",
"b1b1 cgc Fdfd Nn Slsl": "Light Sweetgrass",
"b1b1 cgc Ee Fdfd Nn Slsl": "Light Sweetgrass",
"b1b1 cgc Fdfd Spsp": "Light Sweetgrass",
"b1b1 cgc Ee Fdfd Spsp": "Light Sweetgrass",
"b1b1 cgc Fdfd Nn Spsp": "Light Sweetgrass",
"b1b1 cgc Fdfd Slsl Spsp": "Light Sweetgrass",
"b1b1 cgc Ee Fdfd Nn Spsp": "Light Sweetgrass",
"b1b1 cgc Ee Fdfd Slsl Spsp": "Light Sweetgrass",
"b1b1 cgc Fdfd Nn Slsl Spsp": "Light Sweetgrass",
"b1b1 cgc Ee Fdfd Nn Slsl Spsp": "Light Sweetgrass",



// cgcg SWEETGRASS, done
"b1b1 cgcg": "Sweetgrass",
"b1b1 cgcg Ee": "Sweetgrass",
"b1b1 cgcg Nn": "Sweetgrass",
"b1b1 cgcg Slsl": "Sweetgrass",
"b1b1 cgcg Ee Nn": "Sweetgrass",
"b1b1 cgcg Ee Slsl": "Sweetgrass",
"b1b1 cgcg Nn Slsl": "Sweetgrass",
"b1b1 cgcg Ee Nn Slsl": "Sweetgrass",
"b1b1 cgcg Spsp": "Sweetgrass",
"b1b1 cgcg Ee Spsp": "Sweetgrass",
"b1b1 cgcg Nn Spsp": "Sweetgrass",
"b1b1 cgcg Slsl Spsp": "Sweetgrass",
"b1b1 cgcg Ee Nn Spsp": "Sweetgrass",
"b1b1 cgcg Ee Slsl Spsp": "Sweetgrass",
"b1b1 cgcg Nn Slsl Spsp": "Sweetgrass",
"b1b1 cgcg Ee Nn Slsl Spsp": "Sweetgrass",

// b1b1 cgcg fdfd SWEETGRASS, done
"b1b1 cgcg fdfd": "Sweetgrass",
"b1b1 cgcg Ee fdfd": "Sweetgrass",
"b1b1 cgcg fdfd Nn": "Sweetgrass",
"b1b1 cgcg fdfd Slsl": "Sweetgrass",
"b1b1 cgcg Ee fdfd Nn": "Sweetgrass",
"b1b1 cgcg Ee fdfd Slsl": "Sweetgrass",
"b1b1 cgcg fdfd Nn Slsl": "Sweetgrass",
"b1b1 cgcg Ee fdfd Nn Slsl": "Sweetgrass",
"b1b1 cgcg fdfd Spsp": "Sweetgrass",
"b1b1 cgcg Ee fdfd Spsp": "Sweetgrass",
"b1b1 cgcg fdfd Nn Spsp": "Sweetgrass",
"b1b1 cgcg fdfd Slsl Spsp": "Sweetgrass",
"b1b1 cgcg Ee fdfd Nn Spsp": "Sweetgrass",
"b1b1 cgcg Ee fdfd Slsl Spsp": "Sweetgrass",
"b1b1 cgcg fdfd Nn Slsl Spsp": "Sweetgrass",
"b1b1 cgcg Ee fdfd Nn Slsl Spsp": "Sweetgrass",

// b1b1 cgcg Fdfd SWEETGRASS, done
"b1b1 cgcg Fdfd": "Sweetgrass",
"b1b1 cgcg Ee Fdfd": "Sweetgrass",
"b1b1 cgcg Fdfd Nn": "Sweetgrass",
"b1b1 cgcg Fdfd Slsl": "Sweetgrass",
"b1b1 cgcg Ee Fdfd Nn": "Sweetgrass",
"b1b1 cgcg Ee Fdfd Slsl": "Sweetgrass",
"b1b1 cgcg Fdfd Nn Slsl": "Sweetgrass",
"b1b1 cgcg Ee Fdfd Nn Slsl": "Sweetgrass",
"b1b1 cgcg Fdfd Spsp": "Sweetgrass",
"b1b1 cgcg Ee Fdfd Spsp": "Sweetgrass",
"b1b1 cgcg Fdfd Nn Spsp": "Sweetgrass",
"b1b1 cgcg Fdfd Slsl Spsp": "Sweetgrass",
"b1b1 cgcg Ee Fdfd Nn Spsp": "Sweetgrass",
"b1b1 cgcg Ee Fdfd Slsl Spsp": "Sweetgrass",
"b1b1 cgcg Fdfd Nn Slsl Spsp": "Sweetgrass",
"b1b1 cgcg Ee Fdfd Nn Slsl Spsp": "Sweetgrass",
    
    
 // b1b1 cgcm SWEETGRASS, done
"b1b1 cgcm": "Sweetgrass",
"b1b1 cgcm Ee": "Sweetgrass",
"b1b1 cgcm Nn": "Sweetgrass",
"b1b1 cgcm Slsl": "Sweetgrass",
"b1b1 cgcm Ee Nn": "Sweetgrass",
"b1b1 cgcm Ee Slsl": "Sweetgrass",
"b1b1 cgcm Nn Slsl": "Sweetgrass",
"b1b1 cgcm Ee Nn Slsl": "Sweetgrass",
"b1b1 cgcm Spsp": "Sweetgrass",
"b1b1 cgcm Ee Spsp": "Sweetgrass",
"b1b1 cgcm Nn Spsp": "Sweetgrass",
"b1b1 cgcm Slsl Spsp": "Sweetgrass",
"b1b1 cgcm Ee Nn Spsp": "Sweetgrass",
"b1b1 cgcm Ee Slsl Spsp": "Sweetgrass",
"b1b1 cgcm Nn Slsl Spsp": "Sweetgrass",
"b1b1 cgcm Ee Nn Slsl Spsp": "Sweetgrass",

// b1b1 cgcm fdfd SWEETGRASS, done
"b1b1 cgcm fdfd": "Sweetgrass",
"b1b1 cgcm Ee fdfd": "Sweetgrass",
"b1b1 cgcm fdfd Nn": "Sweetgrass",
"b1b1 cgcm fdfd Slsl": "Sweetgrass",
"b1b1 cgcm Ee fdfd Nn": "Sweetgrass",
"b1b1 cgcm Ee fdfd Slsl": "Sweetgrass",
"b1b1 cgcm fdfd Nn Slsl": "Sweetgrass",
"b1b1 cgcm Ee fdfd Nn Slsl": "Sweetgrass",
"b1b1 cgcm fdfd Spsp": "Sweetgrass",
"b1b1 cgcm Ee fdfd Spsp": "Sweetgrass",
"b1b1 cgcm fdfd Nn Spsp": "Sweetgrass",
"b1b1 cgcm fdfd Slsl Spsp": "Sweetgrass",
"b1b1 cgcm Ee fdfd Nn Spsp": "Sweetgrass",
"b1b1 cgcm Ee fdfd Slsl Spsp": "Sweetgrass",
"b1b1 cgcm fdfd Nn Slsl Spsp": "Sweetgrass",
"b1b1 cgcm Ee fdfd Nn Slsl Spsp": "Sweetgrass",

// b1b1 cgcm Fdfd SWEETGRASS, done
"b1b1 cgcm Fdfd": "Sweetgrass",
"b1b1 cgcm Ee Fdfd": "Sweetgrass",
"b1b1 cgcm Fdfd Nn": "Sweetgrass",
"b1b1 cgcm Fdfd Slsl": "Sweetgrass",
"b1b1 cgcm Ee Fdfd Nn": "Sweetgrass",
"b1b1 cgcm Ee Fdfd Slsl": "Sweetgrass",
"b1b1 cgcm Fdfd Nn Slsl": "Sweetgrass",
"b1b1 cgcm Ee Fdfd Nn Slsl": "Sweetgrass",
"b1b1 cgcm Fdfd Spsp": "Sweetgrass",
"b1b1 cgcm Ee Fdfd Spsp": "Sweetgrass",
"b1b1 cgcm Fdfd Nn Spsp": "Sweetgrass",
"b1b1 cgcm Fdfd Slsl Spsp": "Sweetgrass",
"b1b1 cgcm Ee Fdfd Nn Spsp": "Sweetgrass",
"b1b1 cgcm Ee Fdfd Slsl Spsp": "Sweetgrass",
"b1b1 cgcm Fdfd Nn Slsl Spsp": "Sweetgrass",
"b1b1 cgcm Ee Fdfd Nn Slsl Spsp": "Sweetgrass",
 



};
