// LRBN - M CD
const phenotypeMapping5 = {
  // LAVENDER RED BRONZE
"bb DD Rr": "Lavender Red Bronze",
"bb DD Ee Rr": "Lavender Red Bronze",
"bb DD Nn Rr": "Lavender Red Bronze",
"bb DD Rr Slsl": "Lavender Red Bronze",
"bb DD Pnpn Rr": "Lavender Red Bronze",
"bb DD pnpn Rr": "Lavender Red Bronze",
"bb DD Ee Nn Rr": "Lavender Red Bronze",
"bb DD Nn Rr Slsl": "Lavender Red Bronze",
"bb DD Ee Nn Rr Slsl": "Lavender Red Bronze",
"bb DD Ee Nn Pnpn Rr": "Lavender Red Bronze",
"bb DD Ee Nn pnpn Rr": "Lavender Red Bronze",
"bb DD Nn Pnpn Rr Slsl": "Lavender Red Bronze",
"bb DD Nn pnpn Rr Slsl": "Lavender Red Bronze",
"bb DD Pnpn Rr Slsl": "Lavender Red Bronze",
"bb DD pnpn Rr Slsl": "Lavender Red Bronze",
"bb Ccg DD Rr": "Lavender Red Bronze",
"bb Ccg DD Ee Rr": "Lavender Red Bronze",
"bb Ccg DD Nn Rr": "Lavender Red Bronze",
"bb Ccg DD Rr Slsl": "Lavender Red Bronze",
"bb Ccg DD Pnpn Rr": "Lavender Red Bronze",
"bb Ccg DD pnpn Rr": "Lavender Red Bronze",
"bb Ccg DD Ee Nn Rr": "Lavender Red Bronze",
"bb Ccg DD Nn Rr Slsl": "Lavender Red Bronze",
"bb Ccg DD Ee Nn Rr Slsl": "Lavender Red Bronze",
"bb Ccg DD Ee Nn Pnpn Rr": "Lavender Red Bronze",
"bb Ccg DD Ee Nn pnpn Rr": "Lavender Red Bronze",
"bb Ccg DD Nn Pnpn Rr Slsl": "Lavender Red Bronze",
"bb Ccg DD Nn pnpn Rr Slsl": "Lavender Red Bronze",
"bb Ccg DD Pnpn Rr Slsl": "Lavender Red Bronze",
"bb Ccg DD pnpn Rr Slsl": "Lavender Red Bronze",
"bb Ccm DD Rr": "Lavender Red Bronze",
"bb Ccm DD Ee Rr": "Lavender Red Bronze",
"bb Ccm DD Nn Rr": "Lavender Red Bronze",
"bb Ccm DD Rr Slsl": "Lavender Red Bronze",
"bb Ccm DD Pnpn Rr": "Lavender Red Bronze",
"bb Ccm DD pnpn Rr": "Lavender Red Bronze",
"bb Ccm DD Ee Nn Rr": "Lavender Red Bronze",
"bb Ccm DD Nn Rr Slsl": "Lavender Red Bronze",
"bb Ccm DD Ee Nn Rr Slsl": "Lavender Red Bronze",
"bb Ccm DD Ee Nn Pnpn Rr": "Lavender Red Bronze",
"bb Ccm DD Ee Nn pnpn Rr": "Lavender Red Bronze",
"bb Ccm DD Nn Pnpn Rr Slsl": "Lavender Red Bronze",
"bb Ccm DD Nn pnpn Rr Slsl": "Lavender Red Bronze",
"bb Ccm DD Pnpn Rr Slsl": "Lavender Red Bronze",
"bb Ccm DD pnpn Rr Slsl": "Lavender Red Bronze",
"bb Cc DD Rr": "Lavender Red Bronze",
"bb Cc DD Ee Rr": "Lavender Red Bronze",
"bb Cc DD Nn Rr": "Lavender Red Bronze",
"bb Cc DD Rr Slsl": "Lavender Red Bronze",
"bb Cc DD Pnpn Rr": "Lavender Red Bronze",
"bb Cc DD pnpn Rr": "Lavender Red Bronze",
"bb Cc DD Ee Nn Rr": "Lavender Red Bronze",
"bb Cc DD Nn Rr Slsl": "Lavender Red Bronze",
"bb Cc DD Ee Nn Rr Slsl": "Lavender Red Bronze",
"bb Cc DD Ee Nn Pnpn Rr": "Lavender Red Bronze",
"bb Cc DD Ee Nn pnpn Rr": "Lavender Red Bronze",
"bb Cc DD Nn Pnpn Rr Slsl": "Lavender Red Bronze",
"bb Cc DD Nn pnpn Rr Slsl": "Lavender Red Bronze",
"bb Cc DD Pnpn Rr Slsl": "Lavender Red Bronze",
"bb Cc DD pnpn Rr Slsl": "Lavender Red Bronze",
"bb cgcg DD Rr": "Lavender Red Bronze",
"bb cgcg DD Ee Rr": "Lavender Red Bronze",
"bb cgcg DD Nn Rr": "Lavender Red Bronze",
"bb cgcg DD Rr Slsl": "Lavender Red Bronze",
"bb cgcg DD Pnpn Rr": "Lavender Red Bronze",
"bb cgcg DD pnpn Rr": "Lavender Red Bronze",
"bb cgcg DD Ee Nn Rr": "Lavender Red Bronze",
"bb cgcg DD Nn Rr Slsl": "Lavender Red Bronze",
"bb cgcg DD Ee Nn Rr Slsl": "Lavender Red Bronze",
"bb cgcg DD Ee Nn Pnpn Rr": "Lavender Red Bronze",
"bb cgcg DD Ee Nn pnpn Rr": "Lavender Red Bronze",
"bb cgcg DD Nn Pnpn Rr Slsl": "Lavender Red Bronze",
"bb cgcg DD Nn pnpn Rr Slsl": "Lavender Red Bronze",
"bb cgcg DD Pnpn Rr Slsl": "Lavender Red Bronze",
"bb cgcg DD pnpn Rr Slsl": "Lavender Red Bronze",
"bb cgcm DD Rr": "Lavender Red Bronze",
"bb cgcm DD Ee Rr": "Lavender Red Bronze",
"bb cgcm DD Nn Rr": "Lavender Red Bronze",
"bb cgcm DD Rr Slsl": "Lavender Red Bronze",
"bb cgcm DD Pnpn Rr": "Lavender Red Bronze",
"bb cgcm DD pnpn Rr": "Lavender Red Bronze",
"bb cgcm DD Ee Nn Rr": "Lavender Red Bronze",
"bb cgcm DD Nn Rr Slsl": "Lavender Red Bronze",
"bb cgcm DD Ee Nn Rr Slsl": "Lavender Red Bronze",
"bb cgcm DD Ee Nn Pnpn Rr": "Lavender Red Bronze",
"bb cgcm DD Ee Nn pnpn Rr": "Lavender Red Bronze",
"bb cgcm DD Nn Pnpn Rr Slsl": "Lavender Red Bronze",
"bb cgcm DD Nn pnpn Rr Slsl": "Lavender Red Bronze",
"bb cgcm DD Pnpn Rr Slsl": "Lavender Red Bronze",
"bb cgcm DD pnpn Rr Slsl": "Lavender Red Bronze",
"bb cgc DD Rr": "Lavender Red Bronze",
"bb cgc DD Ee Rr": "Lavender Red Bronze",
"bb cgc DD Nn Rr": "Lavender Red Bronze",
"bb cgc DD Rr Slsl": "Lavender Red Bronze",
"bb cgc DD Pnpn Rr": "Lavender Red Bronze",
"bb cgc DD pnpn Rr": "Lavender Red Bronze",
"bb cgc DD Ee Nn Rr": "Lavender Red Bronze",
"bb cgc DD Nn Rr Slsl": "Lavender Red Bronze",
"bb cgc DD Ee Nn Rr Slsl": "Lavender Red Bronze",
"bb cgc DD Ee Nn Pnpn Rr": "Lavender Red Bronze",
"bb cgc DD Ee Nn pnpn Rr": "Lavender Red Bronze",
"bb cgc DD Nn Pnpn Rr Slsl": "Lavender Red Bronze",
"bb cgc DD Nn pnpn Rr Slsl": "Lavender Red Bronze",
"bb cgc DD Pnpn Rr Slsl": "Lavender Red Bronze",
"bb cgc DD pnpn Rr Slsl": "Lavender Red Bronze",
 // bb1 LAVENDER RED BRONZE
"bb1 DD Rr": "Lavender Red Bronze",
"bb1 DD Ee Rr": "Lavender Red Bronze",
"bb1 DD Nn Rr": "Lavender Red Bronze",
"bb1 DD Rr Slsl": "Lavender Red Bronze",
"bb1 DD Pnpn Rr": "Lavender Red Bronze",
"bb1 DD pnpn Rr": "Lavender Red Bronze",
"bb1 DD Ee Nn Rr": "Lavender Red Bronze",
"bb1 DD Nn Rr Slsl": "Lavender Red Bronze",
"bb1 DD Ee Nn Rr Slsl": "Lavender Red Bronze",
"bb1 DD Ee Nn Pnpn Rr": "Lavender Red Bronze",
"bb1 DD Ee Nn pnpn Rr": "Lavender Red Bronze",
"bb1 DD Nn Pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 DD Nn pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 DD Pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 DD pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 Ccg DD Rr": "Lavender Red Bronze",
"bb1 Ccg DD Ee Rr": "Lavender Red Bronze",
"bb1 Ccg DD Nn Rr": "Lavender Red Bronze",
"bb1 Ccg Rr Slsl DD Rr": "Lavender Red Bronze",
"bb1 Ccg DD Pnpn Rr": "Lavender Red Bronze",
"bb1 Ccg DD pnpn Rr": "Lavender Red Bronze",
"bb1 Ccg DD Ee Nn Rr": "Lavender Red Bronze",
"bb1 Ccg DD Nn Rr Slsl": "Lavender Red Bronze",
"bb1 Ccg DD Ee Nn Rr Slsl": "Lavender Red Bronze",
"bb1 Ccg DD Ee Nn Pnpn Rr": "Lavender Red Bronze",
"bb1 Ccg DD Ee Nn pnpn Rr": "Lavender Red Bronze",
"bb1 Ccg DD Nn Pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 Ccg DD Nn pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 Ccg DD Pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 Ccg DD pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 Ccm DD Rr": "Lavender Red Bronze",
"bb1 Ccm DD Ee Rr": "Lavender Red Bronze",
"bb1 Ccm DD Nn Rr": "Lavender Red Bronze",
"bb1 Ccm DD Rr Slsl": "Lavender Red Bronze",
"bb1 Ccm DD Pnpn Rr": "Lavender Red Bronze",
"bb1 Ccm DD pnpn Rr": "Lavender Red Bronze",
"bb1 Ccm DD Ee Nn Rr": "Lavender Red Bronze",
"bb1 Ccm DD Nn Rr Slsl": "Lavender Red Bronze",
"bb1 Ccm DD Ee Nn Rr Slsl": "Lavender Red Bronze",
"bb1 Ccm DD Ee Nn Pnpn Rr": "Lavender Red Bronze",
"bb1 Ccm DD Ee Nn pnpn Rr": "Lavender Red Bronze",
"bb1 Ccm DD Nn Pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 Ccm DD Nn pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 Ccm DD Pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 Ccm DD pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 Cc DD Rr": "Lavender Red Bronze",
"bb1 Cc DD Ee Rr": "Lavender Red Bronze",
"bb1 Cc DD Nn Rr": "Lavender Red Bronze",
"bb1 Cc DD Rr Slsl": "Lavender Red Bronze",
"bb1 Cc DD Pnpn Rr": "Lavender Red Bronze",
"bb1 Cc DD pnpn Rr": "Lavender Red Bronze",
"bb1 Cc DD Ee Nn Rr": "Lavender Red Bronze",
"bb1 Cc DD Nn Rr Slsl": "Lavender Red Bronze",
"bb1 Cc DD Ee Nn Rr Slsl": "Lavender Red Bronze",
"bb1 Cc DD Ee Nn Pnpn Rr": "Lavender Red Bronze",
"bb1 Cc DD Ee Nn pnpn Rr": "Lavender Red Bronze",
"bb1 Cc DD Nn Pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 Cc DD Nn pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 Cc DD Pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 Cc DD pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 cgcg DD Rr": "Lavender Red Bronze",
"bb1 cgcg DD Ee Rr": "Lavender Red Bronze",
"bb1 cgcg DD Nn Rr": "Lavender Red Bronze",
"bb1 cgcg DD Rr Slsl": "Lavender Red Bronze",
"bb1 cgcg DD Pnpn Rr": "Lavender Red Bronze",
"bb1 cgcg DD pnpn Rr": "Lavender Red Bronze",
"bb1 cgcg DD Ee Nn Rr": "Lavender Red Bronze",
"bb1 cgcg DD Nn Rr Slsl": "Lavender Red Bronze",
"bb1 cgcg DD Ee Nn Rr Slsl": "Lavender Red Bronze",
"bb1 cgcg DD Ee Nn Pnpn Rr": "Lavender Red Bronze",
"bb1 cgcg DD Ee Nn pnpn Rr": "Lavender Red Bronze",
"bb1 cgcg DD Nn Pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 cgcg DD Nn pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 cgcg DD Pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 cgcg DD pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 cgcm DD Rr": "Lavender Red Bronze",
"bb1 cgcm DD Ee Rr": "Lavender Red Bronze",
"bb1 cgcm DD Nn Rr": "Lavender Red Bronze",
"bb1 cgcm DD Rr Slsl": "Lavender Red Bronze",
"bb1 cgcm DD Pnpn Rr": "Lavender Red Bronze",
"bb1 cgcm DD pnpn Rr": "Lavender Red Bronze",
"bb1 cgcm DD Ee Nn Rr": "Lavender Red Bronze",
"bb1 cgcm DD Nn Rr Slsl": "Lavender Red Bronze",
"bb1 cgcm DD Ee Nn Rr Slsl": "Lavender Red Bronze",
"bb1 cgcm DD Ee Nn Pnpn Rr": "Lavender Red Bronze",
"bb1 cgcm DD Ee Nn pnpn Rr": "Lavender Red Bronze",
"bb1 cgcm DD Nn Pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 cgcm DD Nn pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 cgcm DD Pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 cgcm DD pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 cgc DD Rr": "Lavender Red Bronze",
"bb1 cgc DD Ee Rr": "Lavender Red Bronze",
"bb1 cgc DD Nn Rr": "Lavender Red Bronze",
"bb1 cgc DD Rr Slsl": "Lavender Red Bronze",
"bb1 cgc DD Pnpn Rr": "Lavender Red Bronze",
"bb1 cgc DD pnpn Rr": "Lavender Red Bronze",
"bb1 cgc DD Ee Nn Rr": "Lavender Red Bronze",
"bb1 cgc DD Nn Rr Slsl": "Lavender Red Bronze",
"bb1 cgc DD Ee Nn Rr Slsl": "Lavender Red Bronze",
"bb1 cgc DD Ee Nn Pnpn Rr": "Lavender Red Bronze",
"bb1 cgc DD Ee Nn pnpn Rr": "Lavender Red Bronze",
"bb1 cgc DD Nn Pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 cgc DD Nn pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 cgc DD Pnpn Rr Slsl": "Lavender Red Bronze",
"bb1 cgc DD pnpn Rr Slsl": "Lavender Red Bronze",

// LAVENDER RED NARRAGANSETT
"bb DD nn Rr": "Lavender Red Narragansett",
"bb DD Ee nn Rr": "Lavender Red Narragansett",
"bb DD nn Rr Slsl": "Lavender Red Narragansett",
"bb DD nn Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb DD nn pnpn Rr Slsl": "Lavender Red Narragansett",
"bb DD Ee nn Rr Slsl": "Lavender Red Narragansett",
"bb DD Ee nn Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Ccg DD nn Rr": "Lavender Red Narragansett",
"bb Ccg DD Ee nn Rr": "Lavender Red Narragansett",
"bb Ccg DD nn Rr Slsl": "Lavender Red Narragansett",
"bb Ccg DD nn Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Ccg DD nn pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Ccg DD Ee nn Rr Slsl": "Lavender Red Narragansett",
"bb Ccg DD Ee nn Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Ccm DD nn Rr": "Lavender Red Narragansett",
"bb Ccm DD Ee nn Rr": "Lavender Red Narragansett",
"bb Ccm DD nn Rr Slsl": "Lavender Red Narragansett",
"bb Ccm DD nn Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Ccm DD nn pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Ccm DD Ee nn Rr Slsl": "Lavender Red Narragansett",
"bb Ccm DD Ee nn Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Cc DD nn Rr": "Lavender Red Narragansett",
"bb Cc DD Ee nn Rr": "Lavender Red Narragansett",
"bb Cc DD nn Rr Slsl": "Lavender Red Narragansett",
"bb Cc DD nn Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Cc DD nn pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Cc DD Ee nn Rr Slsl": "Lavender Red Narragansett",
"bb Cc DD Ee nn Pnpn Rr Slsl": "Lavender Red Narragansett",

// LAVENDER RED NARRAGANSETT FEMALES
"bb DD n- Rr": "Lavender Red Narragansett",
"bb DD n- Pnpn Rr": "Lavender Red Narragansett",
"bb DD n- pnpn Rr": "Lavender Red Narragansett",
"bb DD n- Rr Slsl": "Lavender Red Narragansett",
"bb DD n- Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb DD n- pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Ccg DD n- Rr": "Lavender Red Narragansett",
"bb Ccg DD n- Pnpn Rr": "Lavender Red Narragansett",
"bb Ccg DD n- pnpn Rr": "Lavender Red Narragansett",
"bb Ccg DD n- Rr Slsl": "Lavender Red Narragansett",
"bb Ccg DD n- Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Ccg DD n- pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Ccm DD n- Rr": "Lavender Red Narragansett",
"bb Ccm DD n- Pnpn Rr": "Lavender Red Narragansett",
"bb Ccm DD n- pnpn Rr": "Lavender Red Narragansett",
"bb Ccm DD n- Rr Slsl": "Lavender Red Narragansett",
"bb Ccm DD n- Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Ccm DD n- pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Cc DD n- Rr": "Lavender Red Narragansett",
"bb Cc DD n- Pnpn Rr": "Lavender Red Narragansett",
"bb Cc DD n- pnpn Rr": "Lavender Red Narragansett",
"bb Cc DD n- Rr Slsl": "Lavender Red Narragansett",
"bb Cc DD n- Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb Cc DD n- pnpn Rr Slsl": "Lavender Red Narragansett",

// bb1 LAVENDER RED NARRAGANSETT
"bb1 DD nn Rr": "Lavender Red Narragansett",
"bb1 DD Ee nn Rr": "Lavender Red Narragansett",
"bb1 DD nn Rr Slsl": "Lavender Red Narragansett",
"bb1 DD nn Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 DD nn pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 DD Ee nn Rr Slsl": "Lavender Red Narragansett",
"bb1 DD Ee nn Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccg DD nn Rr": "Lavender Red Narragansett",
"bb1 Ccg DD Ee nn Rr": "Lavender Red Narragansett",
"bb1 Ccg DD nn Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccg DD nn Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccg DD nn pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccg DD Ee nn Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccg DD Ee nn Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccm DD nn Rr": "Lavender Red Narragansett",
"bb1 Ccm DD Ee nn Rr": "Lavender Red Narragansett",
"bb1 Ccm DD nn Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccm DD nn Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccm DD nn pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccm DD Ee nn Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccm DD Ee nn Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Cc DD nn Rr": "Lavender Red Narragansett",
"bb1 Cc DD Ee nn Rr": "Lavender Red Narragansett",
"bb1 Cc DD nn Rr Slsl": "Lavender Red Narragansett",
"bb1 Cc DD nn Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Cc DD nn pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Cc DD Ee nn Rr Slsl": "Lavender Red Narragansett",
"bb1 Cc DD Ee nn Pnpn Rr Slsl": "Lavender Red Narragansett",

// bb1 LAVENDER RED NARRAGANSETT FEMALES
"bb1 DD n- Rr": "Lavender Red Narragansett",
"bb1 DD n- Pnpn Rr": "Lavender Red Narragansett",
"bb1 DD n- pnpn Rr": "Lavender Red Narragansett",
"bb1 DD n- Rr Slsl": "Lavender Red Narragansett",
"bb1 DD n- Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 DD n- pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccg DD n- Rr": "Lavender Red Narragansett",
"bb1 Ccg DD n- Pnpn Rr": "Lavender Red Narragansett",
"bb1 Ccg DD n- pnpn Rr": "Lavender Red Narragansett",
"bb1 Ccg DD n- Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccg DD n- Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccg DD n- pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccm DD n- Rr": "Lavender Red Narragansett",
"bb1 Ccm DD n- Pnpn Rr": "Lavender Red Narragansett",
"bb1 Ccm DD n- pnpn Rr": "Lavender Red Narragansett",
"bb1 Ccm DD n- Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccm DD n- Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Ccm DD n- pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Cc DD n- Rr": "Lavender Red Narragansett",
"bb1 Cc DD n- Pnpn Rr": "Lavender Red Narragansett",
"bb1 Cc DD n- pnpn Rr": "Lavender Red Narragansett",
"bb1 Cc DD n- Rr Slsl": "Lavender Red Narragansett",
"bb1 Cc DD n- Pnpn Rr Slsl": "Lavender Red Narragansett",
"bb1 Cc DD n- pnpn Rr Slsl": "Lavender Red Narragansett",






// LAVENDER RED PHOENIX
"b1b1 Ccg DD Rr": "Lavender Red Phoenix",
"b1b1 Ccg DD Ee Rr": "Lavender Red Phoenix",
"b1b1 Ccg DD Nn Rr": "Lavender Red Phoenix",
"b1b1 Ccg DD Rr Slsl": "Lavender Red Phoenix",
"b1b1 Ccg DD Ee Nn Rr": "Lavender Red Phoenix",
"b1b1 Ccg DD Nn Rr Slsl": "Lavender Red Phoenix",
"b1b1 Ccg DD Ee Nn Rr Slsl": "Lavender Red Phoenix",
// LAVENDER SWEETGRASS
"b1b1 cgcg DD": "Lavender Sweetgrass",
"b1b1 cgcg DD Ee": "Lavender Sweetgrass",
"b1b1 cgcg DD Nn": "Lavender Sweetgrass",
"b1b1 cgcg DD Slsl": "Lavender Sweetgrass",
"b1b1 cgcg DD Ee Nn": "Lavender Sweetgrass",
"b1b1 cgcg DD Nn Slsl": "Lavender Sweetgrass",
"b1b1 cgcg DD Ee Nn Slsl": "Lavender Sweetgrass",
"b1b1 cgcm DD": "Lavender Sweetgrass",
"b1b1 cgcm DD Ee": "Lavender Sweetgrass",
"b1b1 cgcm DD Nn": "Lavender Sweetgrass",
"b1b1 cgcm DD Slsl": "Lavender Sweetgrass",
"b1b1 cgcm DD Ee Nn": "Lavender Sweetgrass",
"b1b1 cgcm DD Nn Slsl": "Lavender Sweetgrass",
"b1b1 cgcm DD Ee Nn Slsl": "Lavender Sweetgrass",
"b1b1 cgc DD": "Lavender Sweetgrass",
"b1b1 cgc DD Ee": "Lavender Sweetgrass",
"b1b1 cgc DD Nn": "Lavender Sweetgrass",
"b1b1 cgc DD Slsl": "Lavender Sweetgrass",
"b1b1 cgc DD Ee Nn": "Lavender Sweetgrass",
"b1b1 cgc DD Nn Slsl": "Lavender Sweetgrass",
"b1b1 cgc DD Ee Nn Slsl": "Lavender Sweetgrass",
// LIGHT BUFF
"b1b1 nn rr": "Light Buff",
"b1b1 Ee nn rr": "Light Buff",
"b1b1 nn rr Slsl": "Light Buff",
"b1b1 Ee nn rr Slsl": "Light Buff",
"b1b1 Ccg nn rr": "Light Buff",
"b1b1 Ccg Ee nn rr": "Light Buff",
"b1b1 Ccg nn rr Slsl": "Light Buff",
"b1b1 Ccg Ee nn rr Slsl": "Light Buff",
"b1b1 Ccm nn rr": "Light Buff",
"b1b1 Ccm Ee nn rr": "Light Buff",
"b1b1 Ccm nn rr Slsl": "Light Buff",
"b1b1 Ccm Ee nn rr Slsl": "Light Buff",
"b1b1 Cc nn rr": "Light Buff",
"b1b1 Cc Ee nn rr": "Light Buff",
"b1b1 Cc nn rr Slsl": "Light Buff",
"b1b1 Cc Ee nn rr Slsl": "Light Buff",
"b1b1 n- rr": "Light Buff",
"b1b1 n- rr Slsl": "Light Buff",
"b1b1 Ccg n- rr": "Light Buff",
"b1b1 Ccg n- rr Slsl": "Light Buff",
"b1b1 Ccm n- rr": "Light Buff",
"b1b1 Ccm n- rr Slsl": "Light Buff",
"b1b1 Cc n- rr": "Light Buff",
"b1b1 Cc n- rr Slsl": "Light Buff",
// LILAC
"bb DD": "Lilac",
"bb DD Slsl": "Lilac",
"bb DD Ee Slsl": "Lilac",
"bb DD Ee pnpn Slsl": "Lilac",
"bb DD Ee Pnpn Slsl": "Lilac",
"bb DD Ee": "Lilac",
"bb DD Ee Nn": "Lilac",
"bb DD Ee Nn Slsl": "Lilac",
"bb DD Nn": "Lilac",
"bb DD Nn Pnpn Slsl": "Lilac",
"bb DD Nn Slsl": "Lilac",
"bb DD Nn pnpn Slsl": "Lilac",
"bb DD Pnpn": "Lilac",
"bb DD Pnpn Slsl": "Lilac",
"bb DD pnpn": "Lilac",
"bb DD pnpn Slsl": "Lilac",
"bb Ccg DD": "Lilac",
"bb Ccg DD Slsl": "Lilac",
"bb Ccg DD Ee Slsl": "Lilac",
"bb Ccg DD Ee pnpn Slsl": "Lilac",
"bb Ccg DD Ee Pnpn Slsl": "Lilac",
"bb Ccg DD Ee": "Lilac",
"bb Ccg DD Ee Nn": "Lilac",
"bb Ccg DD Ee Nn Pnpn": "Lilac",
"bb Ccg DD Ee Nn Slsl": "Lilac",
"bb Ccg DD Ee Nn pnpn": "Lilac",
"bb Ccg DD Nn": "Lilac",
"bb Ccg DD Nn Pnpn Slsl": "Lilac",
"bb Ccg DD Nn Slsl": "Lilac",
"bb Ccg DD Nn pnpn Slsl": "Lilac",
"bb Ccg DD Pnpn": "Lilac",
"bb Ccg DD Pnpn Slsl": "Lilac",
"bb Ccg DD pnpn": "Lilac",
"bb Ccg DD pnpn Slsl": "Lilac",
"bb Ccm DD": "Lilac",
"bb Ccm DD Ee": "Lilac",
"bb Ccm DD Slsl": "Lilac",
"bb Ccm DD Ee Slsl": "Lilac",
"bb Ccm DD Ee pnpn Slsl": "Lilac",
"bb Ccm DD Ee Pnpn Slsl": "Lilac",
"bb Ccm DD Ee Nn": "Lilac",
"bb Ccm DD Ee Nn Pnpn": "Lilac",
"bb Ccm DD Ee Nn Slsl": "Lilac",
"bb Ccm DD Ee Nn pnpn": "Lilac",
"bb Ccm DD Nn": "Lilac",
"bb Ccm DD Nn Pnpn Slsl": "Lilac",
"bb Ccm DD Nn Slsl": "Lilac",
"bb Ccm DD Nn pnpn Slsl": "Lilac",
"bb Ccm DD Pnpn": "Lilac",
"bb Ccm DD Pnpn Slsl": "Lilac",
"bb Ccm DD pnpn": "Lilac",
"bb Ccm DD pnpn Slsl": "Lilac",
"bb Cc DD": "Lilac",
"bb Cc DD Slsl": "Lilac",
"bb Cc DD Ee Slsl": "Lilac",
"bb Cc DD Ee pnpn Slsl": "Lilac",
"bb Cc DD Ee Pnpn Slsl": "Lilac",
"bb Cc DD Ee": "Lilac",
"bb Cc DD Ee Nn": "Lilac",
"bb Cc DD Ee Nn Pnpn": "Lilac",
"bb Cc DD Ee Nn Slsl": "Lilac",
"bb Cc DD Ee Nn pnpn": "Lilac",
"bb Cc DD Nn": "Lilac",
"bb Cc DD Nn Pnpn Slsl": "Lilac",
"bb Cc DD Nn Slsl": "Lilac",
"bb Cc DD Nn pnpn Slsl": "Lilac",
"bb Cc DD Pnpn": "Lilac",
"bb Cc DD Pnpn Slsl": "Lilac",
"bb Cc DD pnpn": "Lilac",
"bb Cc DD pnpn Slsl": "Lilac",
"bb cgcg DD": "Lilac",
"bb cgcg DD Slsl": "Lilac",
"bb cgcg DD Ee Slsl": "Lilac",
"bb cgcg DD Ee pnpn Slsl": "Lilac",
"bb cgcg DD Ee Pnpn Slsl": "Lilac",
"bb cgcg DD Ee": "Lilac",
"bb cgcg DD Ee Nn": "Lilac",
"bb cgcg DD Ee Nn Pnpn": "Lilac",
"bb cgcg DD Ee Nn Slsl": "Lilac",
"bb cgcg DD Ee Nn pnpn": "Lilac",
"bb cgcg DD Nn": "Lilac",
"bb cgcg DD Nn Pnpn Slsl": "Lilac",
"bb cgcg DD Nn Slsl": "Lilac",
"bb cgcg DD Nn pnpn Slsl": "Lilac",
"bb cgcg DD Pnpn": "Lilac",
"bb cgcg DD Pnpn Slsl": "Lilac",
"bb cgcg DD pnpn": "Lilac",
"bb cgcg DD pnpn Slsl": "Lilac",
"bb cgcm DD": "Lilac",
"bb cgcm DD Slsl": "Lilac",
"bb cgcm DD Ee Slsl": "Lilac",
"bb cgcm DD Ee pnpn Slsl": "Lilac",
"bb cgcm DD Ee Pnpn Slsl": "Lilac",
"bb cgcm DD Ee": "Lilac",
"bb cgcm DD Ee Nn": "Lilac",
"bb cgcm DD Ee Nn Pnpn": "Lilac",
"bb cgcm DD Ee Nn Slsl": "Lilac",
"bb cgcm DD Ee Nn pnpn": "Lilac",
"bb cgcm DD Nn": "Lilac",
"bb cgcm DD Nn Pnpn Slsl": "Lilac",
"bb cgcm DD Nn Slsl": "Lilac",
"bb cgcm DD Nn pnpn Slsl": "Lilac",
"bb cgcm DD Pnpn": "Lilac",
"bb cgcm DD Pnpn Slsl": "Lilac",
"bb cgcm DD pnpn": "Lilac",
"bb cgcm DD pnpn Slsl": "Lilac",
"bb cgc DD": "Lilac",
"bb cgc DD Slsl": "Lilac",
"bb cgc DD Ee Slsl": "Lilac",
"bb cgc DD Ee pnpn Slsl": "Lilac",
"bb cgc DD Ee Pnpn Slsl": "Lilac",
"bb cgc DD Ee": "Lilac",
"bb cgc DD Ee Nn": "Lilac",
"bb cgc DD Ee Nn Pnpn": "Lilac",
"bb cgc DD Ee Nn Slsl": "Lilac",
"bb cgc DD Ee Nn pnpn": "Lilac",
"bb cgc DD Nn": "Lilac",
"bb cgc DD Nn Pnpn Slsl": "Lilac",
"bb cgc DD Nn Slsl": "Lilac",
"bb cgc DD Nn pnpn Slsl": "Lilac",
"bb cgc DD Pnpn": "Lilac",
"bb cgc DD Pnpn Slsl": "Lilac",
"bb cgc DD pnpn": "Lilac",
"bb cgc DD pnpn Slsl": "Lilac",
// bb1 LILAC
"bb1 DD": "Lilac",
"bb1 DD Slsl": "Lilac",
"bb1 DD Ee Slsl": "Lilac",
"bb1 DD Ee pnpn Slsl": "Lilac",
"bb1 DD Ee Pnpn Slsl": "Lilac",
"bb1 DD Ee": "Lilac",
"bb1 DD Ee Nn": "Lilac",
"bb1 DD Ee Nn Slsl": "Lilac",
"bb1 DD Nn": "Lilac",
"bb1 DD Nn Pnpn Slsl": "Lilac",
"bb1 DD Nn Slsl": "Lilac",
"bb1 DD Nn pnpn Slsl": "Lilac",
"bb1 DD Pnpn": "Lilac",
"bb1 DD Pnpn Slsl": "Lilac",
"bb1 DD pnpn": "Lilac",
"bb1 DD pnpn Slsl": "Lilac",
"bb1 Ccg DD": "Lilac",
"bb1 Ccg DD Slsl": "Lilac",
"bb1 Ccg DD Ee Slsl": "Lilac",
"bb1 Ccg DD Ee pnpn Slsl": "Lilac",
"bb1 Ccg DD Ee Pnpn Slsl": "Lilac",
"bb1 Ccg DD Ee": "Lilac",
"bb1 Ccg DD Ee Nn": "Lilac",
"bb1 Ccg DD Ee Nn Pnpn": "Lilac",
"bb1 Ccg DD Ee Nn Slsl": "Lilac",
"bb1 Ccg DD Ee Nn pnpn": "Lilac",
"bb1 Ccg DD Nn": "Lilac",
"bb1 Ccg DD Nn Pnpn Slsl": "Lilac",
"bb1 Ccg DD Nn Slsl": "Lilac",
"bb1 Ccg DD Nn pnpn Slsl": "Lilac",
"bb1 Ccg DD Pnpn": "Lilac",
"bb1 Ccg DD Pnpn Slsl": "Lilac",
"bb1 Ccg DD pnpn": "Lilac",
"bb1 Ccg DD pnpn Slsl": "Lilac",
"bb1 Ccm DD": "Lilac",
"bb1 Ccm DD Slsl": "Lilac",
"bb1 Ccm DD Ee Slsl": "Lilac",
"bb1 Ccm DD Ee pnpn Slsl": "Lilac",
"bb1 Ccm DD Ee Pnpn Slsl": "Lilac",
"bb1 Ccm DD Ee": "Lilac",
"bb1 Ccm DD Ee Nn": "Lilac",
"bb1 Ccm DD Ee Nn Pnpn": "Lilac",
"bb1 Ccm DD Ee Nn Slsl": "Lilac",
"bb1 Ccm DD Ee Nn pnpn": "Lilac",
"bb1 Ccm DD Nn": "Lilac",
"bb1 Ccm DD Nn Pnpn Slsl": "Lilac",
"bb1 Ccm DD Nn Slsl": "Lilac",
"bb1 Ccm DD Nn pnpn Slsl": "Lilac",
"bb1 Ccm DD Pnpn": "Lilac",
"bb1 Ccm DD Pnpn Slsl": "Lilac",
"bb1 Ccm DD pnpn": "Lilac",
"bb1 Ccm DD pnpn Slsl": "Lilac",
"bb1 Cc DD": "Lilac",
"bb1 Cc DD Slsl": "Lilac",
"bb1 Cc DD Ee Slsl": "Lilac",
"bb1 Cc DD Ee pnpn Slsl": "Lilac",
"bb1 Cc DD Ee Pnpn Slsl": "Lilac",
"bb1 Cc DD Ee": "Lilac",
"bb1 Cc DD Ee Nn": "Lilac",
"bb1 Cc DD Ee Nn Pnpn": "Lilac",
"bb1 Cc DD Ee Nn Slsl": "Lilac",
"bb1 Cc DD Ee Nn pnpn": "Lilac",
"bb1 Cc DD Nn": "Lilac",
"bb1 Cc DD Nn Pnpn Slsl": "Lilac",
"bb1 Cc DD Nn Slsl": "Lilac",
"bb1 Cc DD Nn pnpn Slsl": "Lilac",
"bb1 Cc DD Pnpn": "Lilac",
"bb1 Cc DD Pnpn Slsl": "Lilac",
"bb1 Cc DD pnpn": "Lilac",
"bb1 Cc DD pnpn Slsl": "Lilac",
"bb1 cgcg DD": "Lilac",
"bb1 cgcg DD Slsl": "Lilac",
"bb1 cgcg DD Ee Slsl": "Lilac",
"bb1 cgcg DD Ee pnpn Slsl": "Lilac",
"bb1 cgcg DD Ee Pnpn Slsl": "Lilac",
"bb1 cgcg DD Ee": "Lilac",
"bb1 cgcg DD Ee Nn": "Lilac",
"bb1 cgcg DD Ee Nn Pnpn": "Lilac",
"bb1 cgcg DD Ee Nn Slsl": "Lilac",
"bb1 cgcg DD Ee Nn pnpn": "Lilac",
"bb1 cgcg DD Nn": "Lilac",
"bb1 cgcg DD Nn Pnpn Slsl": "Lilac",
"bb1 cgcg DD Nn Slsl": "Lilac",
"bb1 cgcg DD Nn pnpn Slsl": "Lilac",
"bb1 cgcg DD Pnpn": "Lilac",
"bb1 cgcg DD Pnpn Slsl": "Lilac",
"bb1 cgcg DD pnpn": "Lilac",
"bb1 cgcg DD pnpn Slsl": "Lilac",
"bb1 cgcm DD": "Lilac",
"bb1 cgcm DD Slsl": "Lilac",
"bb1 cgcm DD Ee Slsl": "Lilac",
"bb1 cgcm DD Ee pnpn Slsl": "Lilac",
"bb1 cgcm DD Ee Pnpn Slsl": "Lilac",
"bb1 cgcm DD Ee": "Lilac",
"bb1 cgcm DD Ee Nn": "Lilac",
"bb1 cgcm DD Ee Nn Pnpn": "Lilac",
"bb1 cgcm DD Ee Nn Slsl": "Lilac",
"bb1 cgcm DD Ee Nn pnpn": "Lilac",
"bb1 cgcm DD Nn": "Lilac",
"bb1 cgcm DD Nn Pnpn Slsl": "Lilac",
"bb1 cgcm DD Nn Slsl": "Lilac",
"bb1 cgcm DD Nn pnpn Slsl": "Lilac",
"bb1 cgcm DD Pnpn": "Lilac",
"bb1 cgcm DD Pnpn Slsl": "Lilac",
"bb1 cgcm DD pnpn": "Lilac",
"bb1 cgcm DD pnpn Slsl": "Lilac",
"bb1 cgc DD": "Lilac",
"bb1 cgc DD Slsl": "Lilac",
"bb1 cgc DD Ee Slsl": "Lilac",
"bb1 cgc DD Ee pnpn Slsl": "Lilac",
"bb1 cgc DD Ee Pnpn Slsl": "Lilac",
"bb1 cgc DD Ee": "Lilac",
"bb1 cgc DD Ee Nn": "Lilac",
"bb1 cgc DD Ee Nn Pnpn": "Lilac",
"bb1 cgc DD Ee Nn Slsl": "Lilac",
"bb1 cgc DD Ee Nn pnpn": "Lilac",
"bb1 cgc DD Nn": "Lilac",
"bb1 cgc DD Nn Pnpn Slsl": "Lilac",
"bb1 cgc DD Nn Slsl": "Lilac",
"bb1 cgc DD Nn pnpn Slsl": "Lilac",
"bb1 cgc DD Pnpn": "Lilac",
"bb1 cgc DD Pnpn Slsl": "Lilac",
"bb1 cgc DD pnpn": "Lilac",
"bb1 cgc DD pnpn Slsl": "Lilac",

    // MARBLED BLACK
    "BB cgcg nn": "Marbled Black",
    "BB cgcg Ee nn": "Marbled Black",
    "BB cgcg nn Slsl": "Marbled Black",
    "BB cgcg nn Pnpn": "Marbled Black",
    "BB cgcg nn pnpn": "Marbled Black",
    "BB cgcg Ee nn Slsl": "Marbled Black",
    "BB cgcg Ee nn Pnpn": "Marbled Black",
    "BB cgcg Ee nn pnpn": "Marbled Black",
    "BB cgcg nn Pnpn Slsl": "Marbled Black",
    "BB cgcg nn pnpn Slsl": "Marbled Black",
    "BB cgcg Ee nn Pnpn Slsl": "Marbled Black",
    "BB cgcg Ee nn pnpn Slsl": "Marbled Black",
    "BB cgcm nn": "Marbled Black",
    "BB cgcm Ee nn": "Marbled Black",
    "BB cgcm nn Slsl": "Marbled Black",
    "BB cgcm nn Pnpn": "Marbled Black",
    "BB cgcm nn pnpn": "Marbled Black",
    "BB cgcm Ee nn Slsl": "Marbled Black",
    "BB cgcm Ee nn Pnpn": "Marbled Black",
    "BB cgcm Ee nn pnpn": "Marbled Black",
    "BB cgcm Ee nn Pnpn Slsl": "Marbled Black",
    "BB cgcm Ee nn pnpn Slsl": "Marbled Black",
    "BB cgcm nn Pnpn Slsl": "Marbled Black",
    "BB cgcm nn pnpn Slsl": "Marbled Black",
"BB cgcg n-": "Marbled Black",
"BB cgcg n- Slsl": "Marbled Black",
"BB cgcg n- Pnpn": "Marbled Black",
"BB cgcg n- pnpn": "Marbled Black",
"BB cgcg n- Pnpn Slsl": "Marbled Black",
"BB cgcg n- pnpn Slsl": "Marbled Black",
"BB cgcm n-": "Marbled Black",
"BB cgcm n- Slsl": "Marbled Black",
"BB cgcm n- Pnpn": "Marbled Black",
"BB cgcm n- pnpn": "Marbled Black",
"BB cgcm n- Pnpn Slsl": "Marbled Black",
"BB cgcm n- pnpn Slsl": "Marbled Black",
// MARBLED CHOCOLATE
"BB cgcg ee nn": "Marbled Chocolate",
"BB cgcg ee nn Slsl": "Marbled Chocolate",
"BB cgcg ee nn Pnpn": "Marbled Chocolate",
"BB cgcg ee nn pnpn": "Marbled Chocolate",
"BB cgcg ee nn Pnpn Slsl": "Marbled Chocolate",
"BB cgcg ee nn pnpn Slsl": "Marbled Chocolate",
"BB cgcg e- n-": "Marbled Chocolate",
"BB cgcg e- n- Slsl": "Marbled Chocolate",
"BB cgcg e- n- Pnpn": "Marbled Chocolate",
"BB cgcg e- n- pnpn": "Marbled Chocolate",
"BB cgcg e- n- Pnpn Slsl": "Marbled Chocolate",
"BB cgcg e- n- pnpn Slsl": "Marbled Chocolate",
"BB cgcm ee nn": "Marbled Chocolate",
"BB cgcm ee nn Slsl": "Marbled Chocolate",
"BB cgcm ee nn Pnpn": "Marbled Chocolate",
"BB cgcm ee nn pnpn": "Marbled Chocolate",
"BB cgcm ee nn Pnpn Slsl": "Marbled Chocolate",
"BB cgcm ee nn pnpn Slsl": "Marbled Chocolate",
"BB cgcm e- n-": "Marbled Chocolate",
"BB cgcm e- n- Slsl": "Marbled Chocolate",
"BB cgcm e- n- Pnpn": "Marbled Chocolate",
"BB cgcm e- n- pnpn": "Marbled Chocolate",
"BB cgcm e- n- Pnpn Slsl": "Marbled Chocolate",
"BB cgcm e- n- pnpn Slsl": "Marbled Chocolate",
"BB cgc ee nn": "Marbled Chocolate",
"BB cgc ee nn Slsl": "Marbled Chocolate",
"BB cgc ee nn Pnpn": "Marbled Chocolate",
"BB cgc ee nn pnpn": "Marbled Chocolate",
"BB cgc ee nn Pnpn Slsl": "Marbled Chocolate",
"BB cgc ee nn pnpn Slsl": "Marbled Chocolate",
"BB cgc e- n-": "Marbled Chocolate",
"BB cgc e- n- Slsl": "Marbled Chocolate",
"BB cgc e- n- Pnpn": "Marbled Chocolate",
"BB cgc e- n- pnpn": "Marbled Chocolate",
"BB cgc e- n- Pnpn Slsl": "Marbled Chocolate",
"BB cgc e- n- pnpn Slsl": "Marbled Chocolate",
// MARBLED LAVENDER
"BB cgcg DD nn": "Marbled Lavender",
"BB cgcg DD Ee nn": "Marbled Lavender",
"BB cgcg DD nn Slsl": "Marbled Lavender",
"BB cgcg DD nn Pnpn": "Marbled Lavender",
"BB cgcg DD nn pnpn": "Marbled Lavender",
"BB cgcg DD Ee nn Slsl": "Marbled Lavender",
"BB cgcg DD Ee nn Pnpn": "Marbled Lavender",
"BB cgcg DD Ee nn pnpn": "Marbled Lavender",
"BB cgcg DD nn Pnpn Slsl": "Marbled Lavender",
"BB cgcg DD nn pnpn Slsl": "Marbled Lavender",
"BB cgcg DD Ee nn Pnpn Slsl": "Marbled Lavender",
"BB cgcg DD Ee nn pnpn Slsl": "Marbled Lavender",
"BB cgcg DD n-": "Marbled Lavender",
"BB cgcg DD n- Slsl": "Marbled Lavender",
"BB cgcg DD n- Pnpn": "Marbled Lavender",
"BB cgcg DD n- pnpn": "Marbled Lavender",
"BB cgcg DD n- Pnpn Slsl": "Marbled Lavender",
"BB cgcg DD n- pnpn Slsl": "Marbled Lavender",
"BB cgcm DD nn": "Marbled Lavender",
"BB cgcm DD Ee nn": "Marbled Lavender",
"BB cgcm DD nn Slsl": "Marbled Lavender",
"BB cgcm DD nn Pnpn": "Marbled Lavender",
"BB cgcm DD nn pnpn": "Marbled Lavender",
"BB cgcm DD Ee nn Slsl": "Marbled Lavender",
"BB cgcm DD Ee nn Pnpn": "Marbled Lavender",
"BB cgcm DD Ee nn pnpn": "Marbled Lavender",
"BB cgcm DD nn Pnpn Slsl": "Marbled Lavender",
"BB cgcm DD nn pnpn Slsl": "Marbled Lavender",
"BB cgcm DD Ee nn Pnpn Slsl": "Marbled Lavender",
"BB cgcm DD Ee nn pnpn Slsl": "Marbled Lavender",
"BB cgcm DD n-": "Marbled Lavender",
"BB cgcm DD n- Slsl": "Marbled Lavender",
"BB cgcm DD n- Pnpn": "Marbled Lavender",
"BB cgcm DD n- pnpn": "Marbled Lavender",
"BB cgcm DD n- Pnpn Slsl": "Marbled Lavender",
"BB cgcm DD n- pnpn Slsl": "Marbled Lavender",
"BB cgc DD nn": "Marbled Lavender",
"BB cgc DD Ee nn": "Marbled Lavender",
"BB cgc DD nn Slsl": "Marbled Lavender",
"BB cgc DD nn Pnpn": "Marbled Lavender",
"BB cgc DD nn pnpn": "Marbled Lavender",
"BB cgc DD Ee nn Slsl": "Marbled Lavender",
"BB cgc DD Ee nn Pnpn": "Marbled Lavender",
"BB cgc DD Ee nn pnpn": "Marbled Lavender",
"BB cgc DD nn Pnpn Slsl": "Marbled Lavender",
"BB cgc DD nn pnpn Slsl": "Marbled Lavender",
"BB cgc DD Ee nn Pnpn Slsl": "Marbled Lavender",
"BB cgc DD Ee nn pnpn Slsl": "Marbled Lavender",
"BB cgc DD n-": "Marbled Lavender",
"BB cgc DD n- Slsl": "Marbled Lavender",
"BB cgc DD n- Pnpn": "Marbled Lavender",
"BB cgc DD n- pnpn": "Marbled Lavender",
"BB cgc DD n- Pnpn Slsl": "Marbled Lavender",
"BB cgc DD n- pnpn Slsl": "Marbled Lavender",
// MARBLED SILVER
"BB cgc nn": "Marbled Silver",
"BB cgc Ee nn": "Marbled Silver",
"BB cgc nn Slsl": "Marbled Silver",
"BB cgc nn Pnpn": "Marbled Silver",
"BB cgc nn pnpn": "Marbled Silver",
"BB cgc Ee nn Slsl": "Marbled Silver",
"BB cgc Ee nn Pnpn": "Marbled Silver",
"BB cgc Ee nn pnpn": "Marbled Silver",
"BB cgc Ee nn Pnpn Slsl": "Marbled Silver",
"BB cgc Ee nn pnpn Slsl": "Marbled Silver",
"BB cgc nn Pnpn Slsl": "Marbled Silver",
"BB cgc nn pnpn Slsl": "Marbled Silver",
"BB cgc n-": "Marbled Silver",
"BB cgc n- Slsl": "Marbled Silver",
"BB cgc n- Pnpn Slsl": "Marbled Silver",
"BB cgc n- pnpn Slsl": "Marbled Silver",
// MARBLED SLATE
"BB cgcg Dd nn": "Marbled Slate",
"BB cgcg Dd Ee nn": "Marbled Slate",
"BB cgcg Dd nn Slsl": "Marbled Slate",
"BB cgcg Dd nn Pnpn": "Marbled Slate",
"BB cgcg Dd nn pnpn": "Marbled Slate",
"BB cgcg Dd Ee nn Slsl": "Marbled Slate",
"BB cgcg Dd Ee nn Pnpn": "Marbled Slate",
"BB cgcg Dd Ee nn pnpn": "Marbled Slate",
"BB cgcg Dd nn Pnpn Slsl": "Marbled Slate",
"BB cgcg Dd nn pnpn Slsl": "Marbled Slate",
"BB cgcg Dd Ee nn Pnpn Slsl": "Marbled Slate",
"BB cgcg Dd Ee nn pnpn Slsl": "Marbled Slate",
"BB cgcg Dd n-": "Marbled Slate",
"BB cgcg Dd n- Slsl": "Marbled Slate",
"BB cgcg Dd n- Pnpn": "Marbled Slate",
"BB cgcg Dd n- pnpn": "Marbled Slate",
"BB cgcg Dd n- Pnpn Slsl": "Marbled Slate",
"BB cgcg Dd n- pnpn Slsl": "Marbled Slate",
"BB cgcm Dd nn": "Marbled Slate",
"BB cgcm Dd Ee nn": "Marbled Slate",
"BB cgcm Dd nn Slsl": "Marbled Slate",
"BB cgcm Dd nn Pnpn": "Marbled Slate",
"BB cgcm Dd nn pnpn": "Marbled Slate",
"BB cgcm Dd Ee nn Slsl": "Marbled Slate",
"BB cgcm Dd Ee nn Pnpn": "Marbled Slate",
"BB cgcm Dd Ee nn pnpn": "Marbled Slate",
"BB cgcm Dd nn Pnpn Slsl": "Marbled Slate",
"BB cgcm Dd nn pnpn Slsl": "Marbled Slate",
"BB cgcm Dd Ee nn Pnpn Slsl": "Marbled Slate",
"BB cgcm Dd Ee nn pnpn Slsl": "Marbled Slate",
"BB cgcm Dd n-": "Marbled Slate",
"BB cgcm Dd n- Slsl": "Marbled Slate",
"BB cgcm Dd n- Pnpn": "Marbled Slate",
"BB cgcm Dd n- pnpn": "Marbled Slate",
"BB cgcm Dd n- Pnpn Slsl": "Marbled Slate",
"BB cgcm Dd n- pnpn Slsl": "Marbled Slate",
"BB cgc Dd nn": "Marbled Slate",
"BB cgc Dd Ee nn": "Marbled Slate",
"BB cgc Dd nn Slsl": "Marbled Slate",
"BB cgc Dd nn Pnpn": "Marbled Slate",
"BB cgc Dd nn pnpn": "Marbled Slate",
"BB cgc Dd Ee nn Slsl": "Marbled Slate",
"BB cgc Dd Ee nn Pnpn": "Marbled Slate",
"BB cgc Dd Ee nn pnpn": "Marbled Slate",
"BB cgc Dd nn Pnpn Slsl": "Marbled Slate",
"BB cgc Dd nn pnpn Slsl": "Marbled Slate",
"BB cgc Dd Ee nn Pnpn Slsl": "Marbled Slate",
"BB cgc Dd Ee nn pnpn Slsl": "Marbled Slate",
"BB cgc Dd n-": "Marbled Slate",
"BB cgc Dd n- Slsl": "Marbled Slate",
"BB cgc Dd n- Pnpn": "Marbled Slate",
"BB cgc Dd n- pnpn": "Marbled Slate",
"BB cgc Dd n- Pnpn Slsl": "Marbled Slate",
"BB cgc Dd n- pnpn Slsl": "Marbled Slate",

//  cgcg MOTTLED BLACK,  Done ***
"Bb1 cgcg nn": "Mottled Black",
"Bb1 cgcg Ee nn": "Mottled Black",
"Bb1 cgcg nn Slsl": "Mottled Black",
"Bb1 cgcg Ee nn Slsl": "Mottled Black",
"Bb1 cgcg nn Pnpn": "Mottled Black",
"Bb1 cgcg Ee nn Pnpn": "Mottled Black",
"Bb1 cgcg nn pnpn": "Mottled Black",
"Bb1 cgcg Ee nn pnpn": "Mottled Black",
"Bb1 cgcg nn Pnpn Slsl": "Mottled Black",
"Bb1 cgcg Ee nn Pnpn Slsl": "Mottled Black",
"Bb1 cgcg nn pnpn Slsl": "Mottled Black",
"Bb1 cgcg Ee nn pnpn Slsl": "Mottled Black",
"Bb1 cgcg nn Spsp": "Mottled Black",
"Bb1 cgcg Ee nn Spsp": "Mottled Black",
"Bb1 cgcg nn Slsl Spsp": "Mottled Black",
"Bb1 cgcg Ee nn Slsl Spsp": "Mottled Black",
"Bb1 cgcg nn Pnpn Spsp": "Mottled Black",
"Bb1 cgcg Ee nn Pnpn Spsp": "Mottled Black",
"Bb1 cgcg nn pnpn Spsp": "Mottled Black",
"Bb1 cgcg Ee nn pnpn Spsp": "Mottled Black",
"Bb1 cgcg nn Pnpn Slsl Spsp": "Mottled Black",
"Bb1 cgcg Ee nn Pnpn Slsl Spsp": "Mottled Black",
"Bb1 cgcg nn pnpn Slsl Spsp": "Mottled Black",
"Bb1 cgcg Ee nn pnpn Slsl Spsp": "Mottled Black",

// cgcm
"Bb1 cgcm nn": "Mottled Black",
"Bb1 cgcm Ee nn": "Mottled Black",
"Bb1 cgcm nn Slsl": "Mottled Black",
"Bb1 cgcm Ee nn Slsl": "Mottled Black",
"Bb1 cgcm nn Pnpn": "Mottled Black",
"Bb1 cgcm Ee nn Pnpn": "Mottled Black",
"Bb1 cgcm nn pnpn": "Mottled Black",
"Bb1 cgcm Ee nn pnpn": "Mottled Black",
"Bb1 cgcm nn Pnpn Slsl": "Mottled Black",
"Bb1 cgcm Ee nn Pnpn Slsl": "Mottled Black",
"Bb1 cgcm nn pnpn Slsl": "Mottled Black",
"Bb1 cgcm Ee nn pnpn Slsl": "Mottled Black",
"Bb1 cgcm nn Spsp": "Mottled Black",
"Bb1 cgcm Ee nn Spsp": "Mottled Black",
"Bb1 cgcm nn Slsl Spsp": "Mottled Black",
"Bb1 cgcm Ee nn Slsl Spsp": "Mottled Black",
"Bb1 cgcm nn Pnpn Spsp": "Mottled Black",
"Bb1 cgcm Ee nn Pnpn Spsp": "Mottled Black",
"Bb1 cgcm nn pnpn Spsp": "Mottled Black",
"Bb1 cgcm Ee nn pnpn Spsp": "Mottled Black",
"Bb1 cgcm nn Pnpn Slsl Spsp": "Mottled Black",
"Bb1 cgcm Ee nn Pnpn Slsl Spsp": "Mottled Black",
"Bb1 cgcm nn pnpn Slsl Spsp": "Mottled Black",
"Bb1 cgcm Ee nn pnpn Slsl Spsp": "Mottled Black",

  
// Ccg 
"Bb1 Ccg nn": "Mottled Black.",
"Bb1 Ccg Ee nn": "Mottled Black.",
"Bb1 Ccg nn Slsl": "Mottled Black.",
"Bb1 Ccg Ee nn Slsl": "Mottled Black.",
"Bb1 Ccg nn Pnpn": "Mottled Black.",
"Bb1 Ccg Ee nn Pnpn": "Mottled Black.",
"Bb1 Ccg nn pnpn": "Mottled Black.",
"Bb1 Ccg Ee nn pnpn": "Mottled Black.",
"Bb1 Ccg nn Pnpn Slsl": "Mottled Black.",
"Bb1 Ccg Ee nn Pnpn Slsl": "Mottled Black.",
"Bb1 Ccg nn pnpn Slsl": "Mottled Black.",
"Bb1 Ccg Ee nn pnpn Slsl": "Mottled Black.",
"Bb1 Ccg nn Spsp": "Mottled Black.",
"Bb1 Ccg Ee nn Spsp": "Mottled Black.",
"Bb1 Ccg nn Slsl Spsp": "Mottled Black.",
"Bb1 Ccg Ee nn Slsl Spsp": "Mottled Black.",
"Bb1 Ccg nn Pnpn Spsp": "Mottled Black.",
"Bb1 Ccg Ee nn Pnpn Spsp": "Mottled Black.",
"Bb1 Ccg nn pnpn Spsp": "Mottled Black.",
"Bb1 Ccg Ee nn pnpn Spsp": "Mottled Black.",
"Bb1 Ccg nn Pnpn Slsl Spsp": "Mottled Black.",
"Bb1 Ccg Ee nn Pnpn Slsl Spsp": "Mottled Black.",
"Bb1 Ccg nn pnpn Slsl Spsp": "Mottled Black.",
"Bb1 Ccg Ee nn pnpn Slsl Spsp": "Mottled Black.",

    
  // FEMALES
"Bb1 cgcg n-": "Mottled Black",
"Bb1 cgcg n- Slsl": "Mottled Black",
"Bb1 cgcg n- Pnpn": "Mottled Black",
"Bb1 cgcg n- pnpn": "Mottled Black",
"Bb1 cgcg n- Pnpn Slsl": "Mottled Black",
"Bb1 cgcg n- pnpn Slsl": "Mottled Black",
"Bb1 cgcg n- Spsp": "Mottled Black",
"Bb1 cgcg n- Slsl Spsp": "Mottled Black",
"Bb1 cgcg n- Pnpn Spsp": "Mottled Black",
"Bb1 cgcg n- pnpn Spsp": "Mottled Black",
"Bb1 cgcg n- Pnpn Slsl Spsp": "Mottled Black",
"Bb1 cgcg n- pnpn Slsl Spsp": "Mottled Black",


"Bb1 cgcm n-": "Mottled Black",
"Bb1 cgcm n- Slsl": "Mottled Black",
"Bb1 cgcm n- Pnpn": "Mottled Black",
"Bb1 cgcm n- pnpn": "Mottled Black",
"Bb1 cgcm n- Pnpn Slsl": "Mottled Black",
"Bb1 cgcm n- pnpn Slsl": "Mottled Black",
"Bb1 cgcm n- Spsp": "Mottled Black",
"Bb1 cgcm n- Slsl Spsp": "Mottled Black",
"Bb1 cgcm n- Pnpn Spsp": "Mottled Black",
"Bb1 cgcm n- pnpn Spsp": "Mottled Black",
"Bb1 cgcm n- Pnpn Slsl Spsp": "Mottled Black",
"Bb1 cgcm n- pnpn Slsl Spsp": "Mottled Black",


"Bb1 Ccg n-": "Mottled Black.",
"Bb1 Ccg n- Slsl": "Mottled Black.",
"Bb1 Ccg n- Pnpn": "Mottled Black.",
"Bb1 Ccg n- pnpn": "Mottled Black.",
"Bb1 Ccg n- Pnpn Slsl": "Mottled Black.",
"Bb1 Ccg n- pnpn Slsl": "Mottled Black.",
"Bb1 Ccg n- Spsp": "Mottled Black.",
"Bb1 Ccg n- Slsl Spsp": "Mottled Black.",
"Bb1 Ccg n- Pnpn Spsp": "Mottled Black.",
"Bb1 Ccg n- pnpn Spsp": "Mottled Black.",
"Bb1 Ccg n- Pnpn Slsl Spsp": "Mottled Black.",
"Bb1 Ccg n- pnpn Slsl Spsp": "Mottled Black.",

    
    
    
    
// MOTTLED CHOCOLATE
"Bb1 Ccg ee nn": "Mottled Chocolate",
"Bb1 Ccg ee nn Slsl": "Mottled Chocolate",
"Bb1 Ccg ee nn Pnpn": "Mottled Chocolate",
"Bb1 Ccg ee nn pnpn": "Mottled Chocolate",
"Bb1 Ccg ee nn Pnpn Slsl": "Mottled Chocolate",
"Bb1 Ccg ee nn pnpn Slsl": "Mottled Chocolate",
"Bb1 Ccg e- n-": "Mottled Chocolate",
"Bb1 Ccg e- n- Slsl": "Mottled Chocolate",
"Bb1 Ccg e- n- Pnpn": "Mottled Chocolate",
"Bb1 Ccg e- n- pnpn": "Mottled Chocolate",
"Bb1 Ccg e- n- Pnpn Slsl": "Mottled Chocolate",
"Bb1 Ccg e- n- pnpn Slsl": "Mottled Chocolate",
"Bb1 cgcg ee nn": "Mottled Chocolate",
"Bb1 cgcg ee nn Slsl": "Mottled Chocolate",
"Bb1 cgcg ee nn Pnpn": "Mottled Chocolate",
"Bb1 cgcg ee nn pnpn": "Mottled Chocolate",
"Bb1 cgcg ee nn Pnpn Slsl": "Mottled Chocolate",
"Bb1 cgcg ee nn pnpn Slsl": "Mottled Chocolate",
"Bb1 cgcg e- n-": "Mottled Chocolate",
"Bb1 cgcg e- n- Slsl": "Mottled Chocolate",
"Bb1 cgcg e- n- Pnpn": "Mottled Chocolate",
"Bb1 cgcg e- n- pnpn": "Mottled Chocolate",
"Bb1 cgcg e- n- Pnpn Slsl": "Mottled Chocolate",
"Bb1 cgcg e- n- pnpn Slsl": "Mottled Chocolate",
"Bb1 cgcm ee nn": "Mottled Chocolate",
"Bb1 cgcm ee nn Slsl": "Mottled Chocolate",
"Bb1 cgcm ee nn Pnpn": "Mottled Chocolate",
"Bb1 cgcm ee nn pnpn": "Mottled Chocolate",
"Bb1 cgcm ee nn Pnpn Slsl": "Mottled Chocolate",
"Bb1 cgcm ee nn pnpn Slsl": "Mottled Chocolate",
"Bb1 cgcm e- n-": "Mottled Chocolate",
"Bb1 cgcm e- n- Slsl": "Mottled Chocolate",
"Bb1 cgcm e- n- Pnpn": "Mottled Chocolate",
"Bb1 cgcm e- n- pnpn": "Mottled Chocolate",
"Bb1 cgcm e- n- Pnpn Slsl": "Mottled Chocolate",
"Bb1 cgcm e- n- pnpn Slsl": "Mottled Chocolate",
// MOTTLED CHOCOLATE DAPPLE
"Bb1 cgc ee nn": "Mottled Chocolate Dapple",
"Bb1 cgc ee nn Slsl": "Mottled Chocolate Dapple",
"Bb1 cgc ee nn Pnpn": "Mottled Chocolate Dapple",
"Bb1 cgc ee nn pnpn": "Mottled Chocolate Dapple",
"Bb1 cgc ee nn Pnpn Slsl": "Mottled Chocolate Dapple",
"Bb1 cgc ee nn pnpn Slsl": "Mottled Chocolate Dapple",
"Bb1 cgc e- n-": "Mottled Chocolate Dapple",
"Bb1 cgc e- n- Slsl": "Mottled Chocolate Dapple",
"Bb1 cgc e- n- Pnpn": "Mottled Chocolate Dapple",
"Bb1 cgc e- n- pnpn": "Mottled Chocolate Dapple",
"Bb1 cgc e- n- Pnpn Slsl": "Mottled Chocolate Dapple",
"Bb1 cgc e- n- pnpn Slsl": "Mottled Chocolate Dapple",
  
  
  
  
  
  
  
};
