const phenotypeMapping15 = {
  
  
  
  ///////////////////    Completed cm varieties at end   ///////////////////////   

"BB cmc DD ee": "Grizzled Chocolate Lavender Painted",
"BB cmc DD e-": "Grizzled Chocolate Lavender Painted",
"BB cmc Dd ee": "Grizzled Chocolate Slate Painted",
"BB cmc Dd e-": "Grizzled Chocolate Slate Painted",
"BB cmc nn": "Grizzled Dilute Black Painted",
"BB cmc n-": "Grizzled Dilute Black Painted",



"BB cmc DD nn": "Grizzled Dilute Lavender Painted",
"BB cmc DD n-": "Grizzled Dilute Lavender Painted",
"BB cmc Dd nn": "Grizzled Dilute Slate Painted",
"BB cmc Dd n-": "Grizzled Dilute Slate Painted",
"BB cmc DD ee nn": "Grizzled Dilute Chocolate Lavender Painted",
"BB cmc DD e- n-": "Grizzled Dilute Chocolate Lavender Painted",
"BB cmc Dd ee nn": "Grizzled Dilute Chocolate Slate Painted",
"BB cmc Dd e- n-": "Grizzled Dilute Chocolate Slate Painted",
"BB cmc DD Rr": "Grizzled Rusty Lavender Painted",
"BB cmc Dd Rr": "Grizzled Rusty Slate Painted",
"BB cmc DD ee Rr": "Grizzled Rusty Brown Lavender Painted",
"BB cmc DD e- Rr": "Grizzled Rusty Brown Lavender Painted",
"BB cmc Dd ee Rr": "Grizzled Rusty Brown Slate Painted",
"BB cmc Dd e- Rr": "Grizzled Rusty Brown Slate Painted",
"BB cmc ee Rr": "Grizzled Rusty Brown Painted",
"BB cmc e- Rr": "Grizzled Rusty Brown Painted",
"BB cmc ee rr": "Grizzled Chocolate Red Painted",
"BB cmc e- rr": "Grizzled Chocolate Red Painted",
"BB cmc DD nn Rr": "Grizzled Dilute Rusty Lavender Painted",
"BB cmc DD n- Rr": "Grizzled Dilute Rusty Lavender Painted",
"BB cmc Dd nn Rr": "Grizzled Dilute Rusty Slate Painted",
"BB cmc Dd n- Rr": "Grizzled Dilute Rusty Slate Painted",
"BB cmc DD ee nn Rr": "Grizzled Dilute Rusty Brown Lavender Painted",
"BB cmc DD e- n- Rr": "Grizzled Dilute Rusty Brown Lavender Painted",
"BB cmc Dd ee nn Rr": "Grizzled Dilute Rusty Brown Dominant Slate Painted",
"BB cmc Dd e- n- Rr": "Grizzled Dilute Rusty Brown Dominant Slate Painted",
"BB cmc ee nn Rr": "Grizzled Dilute Rusty Brown Painted",
"BB cmc e- n- Rr": "Grizzled Dilute Rusty Brown Painted",
"BB cmc ee nn rr": "Grizzled Chocolate Buff Painted",
"BB cmc e- n- rr": "Grizzled Chocolate Buff Painted",
"BB cmc nn rr": "Grizzled Buff Painted",
"BB cmc n- rr": "Grizzled Buff Painted",

"BB cmc DD ee pnpn": "Grizzled Chocolate Lavender Painted",
"BB cmc DD e- pnpn": "Grizzled Chocolate Lavender Painted",
"BB cmc Dd ee pnpn": "Grizzled Chocolate Slate Painted",
"BB cmc Dd e- pnpn": "Grizzled Chocolate Slate Painted",


"BB cmc nn pnpn": "Grizzled Dilute Black Painted",
"BB cmc n- pnpn": "Grizzled Dilute Black Painted",



"BB cmc DD nn pnpn": "Grizzled Dilute Lavender Painted",
"BB cmc DD n- pnpn": "Grizzled Dilute Lavender Painted",
"BB cmc Dd nn pnpn": "Grizzled Dilute Slate Painted",
"BB cmc Dd n- pnpn": "Grizzled Dilute Slate Painted",
"BB cmc DD ee nn pnpn": "Grizzled Dilute Chocolate Lavender Painted",
"BB cmc DD e- n- pnpn": "Grizzled Dilute Chocolate Lavender Painted",
"BB cmc Dd ee nn pnpn": "Grizzled Dilute Chocolate Slate Painted",
"BB cmc Dd e- n- pnpn": "Grizzled Dilute Chocolate Slate Painted",
"BB cmc DD pnpn Rr": "Grizzled Rusty Lavender Painted",
"BB cmc Dd pnpn Rr": "Grizzled Rusty Slate Painted",
"BB cmc DD ee pnpn Rr": "Grizzled Rusty Brown Lavender Painted",
"BB cmc DD e- pnpn Rr": "Grizzled Rusty Brown Lavender Painted",
"BB cmc Dd ee pnpn Rr": "Grizzled Rusty Brown Slate Painted",
"BB cmc Dd e- pnpn Rr": "Grizzled Rusty Brown Slate Painted",
"BB cmc ee pnpn Rr": "Grizzled Rusty Brown Painted",
"BB cmc e- pnpn Rr": "Grizzled Rusty Brown Painted",
"BB cmc ee pnpn rr": "Grizzled Chocolate Red Painted",
"BB cmc e- pnpn rr": "Grizzled Chocolate Red Painted",
"BB cmc DD nn pnpn Rr": "Grizzled Dilute Rusty Lavender Painted",
"BB cmc DD n- pnpn Rr": "Grizzled Dilute Rusty Lavender Painted",
"BB cmc Dd nn pnpn Rr": "Grizzled Dilute Rusty Slate Painted",
"BB cmc Dd n- pnpn Rr": "Grizzled Dilute Rusty Slate Painted",
"BB cmc DD ee nn pnpn Rr": "Grizzled Dilute Rusty Brown Lavender Painted",
"BB cmc DD e- n- pnpn Rr": "Grizzled Dilute Rusty Brown Lavender Painted",
"BB cmc Dd ee nn pnpn Rr": "Grizzled Dilute Rusty Brown Dominant Slate Painted",
"BB cmc Dd e- n- pnpn Rr": "Grizzled Dilute Rusty Brown Dominant Slate Painted",
"BB cmc ee nn pnpn Rr": "Grizzled Dilute Rusty Brown Painted",
"BB cmc e- n- pnpn Rr": "Grizzled Dilute Rusty Brown Painted",
"BB cmc ee nn pnpn rr": "Grizzled Chocolate Buff Painted",
"BB cmc e- n- pnpn rr": "Grizzled Chocolate Buff Painted",
"BB cmc nn pnpn rr": "Grizzled Buff Painted",
"BB cmc n- pnpn rr": "Grizzled Buff Painted",

"BB cmc DD ee Pnpn": "Grizzled Chocolate Lavender Painted",
"BB cmc DD e- Pnpn": "Grizzled Chocolate Lavender Painted",
"BB cmc Dd ee Pnpn": "Grizzled Chocolate Slate Painted",
"BB cmc Dd e- Pnpn": "Grizzled Chocolate Slate Painted",
"BB cmc nn Pnpn": "Grizzled Dilute Black Painted",
"BB cmc n- Pnpn": "Grizzled Dilute Black Painted",



"BB cmc DD nn Pnpn": "Grizzled Dilute Lavender Painted",
"BB cmc DD n- Pnpn": "Grizzled Dilute Lavender Painted",
"BB cmc Dd nn Pnpn": "Grizzled Dilute Slate Painted",
"BB cmc Dd n- Pnpn": "Grizzled Dilute Slate Painted",
"BB cmc DD ee nn Pnpn": "Grizzled Dilute Chocolate Lavender Painted",
"BB cmc DD e- n- Pnpn": "Grizzled Dilute Chocolate Lavender Painted",
"BB cmc Dd ee nn Pnpn": "Grizzled Dilute Chocolate Slate Painted",
"BB cmc Dd e- n- Pnpn": "Grizzled Dilute Chocolate Slate Painted",
"BB cmc DD Pnpn Rr": "Grizzled Rusty Lavender Painted",
"BB cmc Dd Pnpn Rr": "Grizzled Rusty Slate Painted",
"BB cmc DD ee Pnpn Rr": "Grizzled Rusty Brown Lavender Painted",
"BB cmc DD e- Pnpn Rr": "Grizzled Rusty Brown Lavender Painted",
"BB cmc Dd ee Pnpn Rr": "Grizzled Rusty Brown Slate Painted",
"BB cmc Dd e- Pnpn Rr": "Grizzled Rusty Brown Slate Painted",
"BB cmc ee Pnpn Rr": "Grizzled Rusty Brown Painted",
"BB cmc e- Pnpn Rr": "Grizzled Rusty Brown Painted",
"BB cmc ee Pnpn rr": "Grizzled Chocolate Red Painted",
"BB cmc e- Pnpn rr": "Grizzled Chocolate Red Painted",
"BB cmc DD nn Pnpn Rr": "Grizzled Dilute Rusty Lavender Painted",
"BB cmc DD n- Pnpn Rr": "Grizzled Dilute Rusty Lavender Painted",
"BB cmc Dd nn Pnpn Rr": "Grizzled Dilute Rusty Slate Painted",
"BB cmc Dd n- Pnpn Rr": "Grizzled Dilute Rusty Slate Painted",
"BB cmc DD ee nn Pnpn Rr": "Grizzled Dilute Rusty Brown Lavender Painted",
"BB cmc DD e- n- Pnpn Rr": "Grizzled Dilute Rusty Brown Lavender Painted",
"BB cmc Dd ee nn Pnpn Rr": "Grizzled Dilute Rusty Brown Slate Painted",
"BB cmc Dd e- n- Pnpn Rr": "Grizzled Dilute Rusty Brown Slate Painted",
"BB cmc ee nn Pnpn Rr": "Grizzled Dilute Rusty Brown Painted",
"BB cmc e- nn Pnpn Rr": "Grizzled Dilute Rusty Brown Painted",
"BB cmc ee nn Pnpn rr": "Grizzled Chocolate Buff Painted",
"BB cmc e- nn Pnpn rr": "Grizzled Chocolate Buff Painted",
"BB cmc nn Pnpn rr": "Grizzled Buff Painted",
"BB cmc n- Pnpn rr": "Grizzled Buff Painted",
// Bb PAINTED
"Bb cmc DD": "Lavender Painted-",
"Bb cmc Dd": "Slate Painted-",
"Bb cmc Dd Nn": "Slate Painted-",
"Bb cmc Dd Ee": "Slate Painted-",
"Bb cmc Dd Ee Nn": "Slate Painted-",
"Bb cmc DD ee": "Chocolate Lavender Painted",
"Bb cmc DD e-": "Chocolate Lavender Painted",
"Bb cmc Dd ee": "Chocolate Slate Painted-",
"Bb cmc Dd e-": "Chocolate Slate Painted-",

"Bb cmc nn": "Dilute Painted",
"Bb cmc n-": "Dilute Painted",

"Bb cmc rr": "Red Painted",
"Bb cmc slsl": "Recessive Blue Painted",
"Bb cmc DD nn": "Dilute Lavender Painted",
"Bb cmc DD n-": "Dilute Lavender Painted",
"Bb cmc Dd nn": "Dilute Dominant Slate Painted",
"Bb cmc Dd n-": "Dilute Dominant Slate Painted",
"Bb cmc DD ee nn": "Dilute Chocolate Lavender Painted",
"Bb cmc DD e- n-": "Dilute Chocolate Lavender Painted",
"Bb cmc Dd ee nn": "Dilute Chocolate Slate Painted",
"Bb cmc Dd e- n-": "Dilute Chocolate Slate Painted",
"Bb cmc DD Rr": "Rusty Lavender Painted",
"Bb cmc Dd Rr": "Rusty Slate Painted",
 "Bb cmc DD ee Rr": "Rusty Chocolate Lavender Painted",
 "Bb cmc DD e- Rr": "Rusty Chocolate Lavender Painted",
 "Bb cmc Dd ee Rr": "Rusty Brown Slate Painted",
 "Bb cmc Dd e- Rr": "Rusty Brown Slate Painted",
 "Bb cmc ee Rr": "Rusty Brown Painted",
 "Bb cmc e- Rr": "Rusty Brown Painted",
 "Bb cmc ee rr": "Chocolate Red Painted",
 "Bb cmc e- rr": "Chocolate Red Painted",
 "Bb cmc DD nn Rr": "Dilute Rusty Lavender Painted",
 "Bb cmc DD n- Rr": "Dilute Rusty Lavender Painted",
 "Bb cmc Dd nn Rr": "Dilute Rusty Slate Painted",
 "Bb cmc Dd n- Rr": "Dilute Rusty Slate Painted",
 "Bb cmc DD ee nn Rr": "Dilute Rusty Chocolate Lavender Painted",
 "Bb cmc DD e- n- Rr": "Dilute Rusty Chocolate Lavender Painted",
 "Bb cmc Dd ee nn Rr": "Dilute Rusty Brown Slate Painted",
 "Bb cmc Dd e- n- Rr": "Dilute Rusty Brown Slate Painted",
 "Bb cmc ee nn Rr": "Dilute Rusty Brown Painted",
 "Bb cmc e- n- Rr": "Dilute Rusty Brown Painted",
 "Bb cmc ee nn rr": "Chocolate Buff Painted",
 "Bb cmc e- n- rr": "Chocolate Buff Painted",
 "Bb cmc nn rr": "Buff Painted",
 "Bb cmc n- rr": "Buff Painted",
"Bb cmc DD pnpn": "Lavender Painted",
"Bb cmc Dd pnpn": "Slate Painted",
"Bb cmc DD ee pnpn": "Chocolate Lavender Painted",
"Bb cmc DD e- pnpn": "Chocolate Lavender Painted",
"Bb cmc Dd ee pnpn": "Chocolate Slate Painted",
"Bb cmc Dd e- pnpn": "Chocolate Slate Painted",


"Bb cmc nn pnpn": "Dilute Black Painted",
"Bb cmc n- pnpn": "Dilute Black Painted",

"Bb cmc pnpn rr": "Red Painted",
"Bb cmc pnpn slsl": "Recessive Blue Painted",
"Bb cmc DD nn pnpn": "Dilute Lavender Painted",
"Bb cmc DD n- pnpn": "Dilute Lavender Painted",
"Bb cmc Dd nn pnpn": "Dilute Slate Painted",
"Bb cmc Dd n- pnpn": "Dilute Slate Painted",
"Bb cmc DD ee nn pnpn": "Dilute Chocolate Lavender Painted",
"Bb cmc DD e- n- pnpn": "Dilute Chocolate Lavender Painted",
"Bb cmc Dd ee nn pnpn": "Dilute Chocolate Slate Painted",
"Bb cmc Dd e- n- pnpn": "Dilute Chocolate Slate Painted",
"Bb cmc DD pnpn Rr": "Rusty Lavender Painted",
"Bb cmc Dd pnpn Rr": "Rusty Slate Painted",
"Bb cmc DD ee pnpn Rr": "Rusty Brown Lavender Painted",
"Bb cmc DD e- pnpn Rr": "Rusty Brown Lavender Painted",
"Bb cmc Dd ee pnpn Rr": "Rusty Brown Slate Painted",
"Bb cmc Dd e- pnpn Rr": "Rusty Brown Slate Painted",
"Bb cmc ee pnpn Rr": "Rusty Brown Painted",
"Bb cmc e- pnpn Rr": "Rusty Brown Painted",
"Bb cmc ee pnpn rr": "Chocolate Red Painted",
"Bb cmc e- pnpn rr": "Chocolate Red Painted",
"Bb cmc DD nn pnpn Rr": "Dilute Rusty Lavender Painted",
"Bb cmc DD n- pnpn Rr": "Dilute Rusty Lavender Painted",
"Bb cmc Dd nn pnpn Rr": "Dilute Rusty Slate Painted",
"Bb cmc Dd n- pnpn Rr": "Dilute Rusty Slate Painted",
"Bb cmc DD ee nn pnpn Rr": "Dilute Rusty Brown Lavender Painted",
"Bb cmc DD e- n- pnpn Rr": "Dilute Rusty Brown Lavender Painted",
"Bb cmc Dd ee nn pnpn Rr": "Dilute Rusty Brown Slate Painted",
"Bb cmc Dd e- n- pnpn Rr": "Dilute Rusty Brown Slate Painted",
"Bb cmc ee nn pnpn Rr": "Dilute Rusty Brown Painted",
"Bb cmc e- n- pnpn Rr": "Dilute Rusty Brown Painted",
"Bb cmc ee nn pnpn rr": "Chocolate Buff Painted",
"Bb cmc e- n- pnpn rr": "Chocolate Buff Painted",
"Bb cmc nn pnpn rr": "Buff Painted",
"Bb cmc n- pnpn rr": "Buff Painted",
// Bb1 PAINTED
"Bb1 cmc DD": "Lavender Painted",
"Bb1 cmc Dd": "Slate Painted",
"Bb1 cmc Dd Ee": "Slate Painted",
"Bb1 cmc Dd Nn": "Slate Painted",
"Bb1 cmc Dd Ee Nn": "Slate Painted",
"Bb1 cmc DD ee": "Chocolate Lavender Painted",
"Bb1 cmc DD e-": "Chocolate Lavender Painted",
"Bb1 cmc Dd ee": "Chocolate Slate Painted",
"Bb1 cmc Dd e-": "Chocolate Slate Painted",

"Bb1 cmc nn": "Dilute Painted",
"Bb1 cmc n-": "Dilute Painted",

"Bb1 cmc rr": "Red Painted",
"Bb1 cmc slsl": "Recessive Blue Painted",
"Bb1 cmc DD nn": "Dilute Lavender Painted",
"Bb1 cmc DD n-": "Dilute Lavender Painted",
"Bb1 cmc Dd nn": "Dilute Dominant Slate Painted",
"Bb1 cmc Dd n-": "Dilute Dominant Slate Painted",
"Bb1 cmc DD ee nn": "Dilute Chocolate Lavender Painted",
"Bb1 cmc DD e- n-": "Dilute Chocolate Lavender Painted",
"Bb1 cmc Dd ee nn": "Dilute Chocolate Slate Painted",
"Bb1 cmc Dd e- n-": "Dilute Chocolate Slate Painted",
"Bb1 cmc DD Rr": "Rusty Lavender Painted",
"Bb1 cmc Dd Rr": "Rusty Slate Painted",
"Bb1 cmc DD ee Rr": "Rusty Chocolate Lavender Painted",
"Bb1 cmc DD e- Rr": "Rusty Chocolate Lavender Painted",
"Bb1 cmc Dd ee Rr": "Rusty Brown Slate Painted",
"Bb1 cmc Dd e- Rr": "Rusty Brown Slate Painted",
"Bb1 cmc ee Rr": "Rusty Brown Painted",
"Bb1 cmc e- Rr": "Rusty Brown Painted",
"Bb1 cmc ee rr": "Chocolate Red Painted",
"Bb1 cmc e- rr": "Chocolate Red Painted",
"Bb1 cmc DD nn Rr": "Dilute Rusty Lavender Painted",
"Bb1 cmc DD n- Rr": "Dilute Rusty Lavender Painted",
"Bb1 cmc Dd nn Rr": "Dilute Rusty Slate Painted",
"Bb1 cmc Dd n- Rr": "Dilute Rusty Slate Painted",
"Bb1 cmc DD ee nn Rr": "Dilute Rusty Chocolate Lavender Painted",
"Bb1 cmc DD e- n- Rr": "Dilute Rusty Chocolate Lavender Painted",
"Bb1 cmc Dd ee nn Rr": "Dilute Rusty Brown Slate Painted",
"Bb1 cmc Dd e- n- Rr": "Dilute Rusty Brown Slate Painted",
"Bb1 cmc ee nn Rr": "Dilute Rusty Brown Painted",
"Bb1 cmc e- n- Rr": "Dilute Rusty Brown Painted",
"Bb1 cmc ee nn rr": "Chocolate Buff Painted",
"Bb1 cmc e- n- rr": "Chocolate Buff Painted",
"Bb1 cmc nn rr": "Buff Painted",
"Bb1 cmc n- rr": "Buff Painted",
"Bb1 cmc DD pnpn": "Lavender Painted",
"Bb1 cmc Dd pnpn": "Slate Painted",
"Bb1 cmc DD ee pnpn": "Chocolate Lavender Painted",
"Bb1 cmc DD e- pnpn": "Chocolate Lavender Painted",
"Bb1 cmc Dd ee pnpn": "Chocolate Slate Painted",
"Bb1 cmc Dd e- pnpn": "Chocolate Slate Painted",

"Bb1 cmc nn pnpn": "Dilute Black Painted",
"Bb1 cmc n- pnpn": "Dilute Black Painted",

"Bb1 cmc pnpn rr": "Red Painted",
"Bb1 cmc pnpn slsl": "Recessive Blue Painted",
"Bb1 cmc DD nn pnpn": "Dilute Lavender Painted",
"Bb1 cmc DD n- pnpn": "Dilute Lavender Painted",
"Bb1 cmc Dd nn pnpn": "Dilute Slate Painted",
"Bb1 cmc Dd n- pnpn": "Dilute Slate Painted",
"Bb1 cmc DD ee nn pnpn": "Dilute Chocolate Lavender Painted",
"Bb1 cmc DD e- n- pnpn": "Dilute Chocolate Lavender Painted",
"Bb1 cmc Dd ee nn pnpn": "Dilute Chocolate Slate Painted",
"Bb1 cmc Dd e- n- pnpn": "Dilute Chocolate Slate Painted",
"Bb1 cmc DD pnpn Rr": "Rusty Lavender Painted",
"Bb1 cmc Dd pnpn Rr": "Rusty Slate Painted",
"Bb1 cmc DD ee pnpn Rr": "Rusty Brown Lavender Painted",
"Bb1 cmc DD e- pnpn Rr": "Rusty Brown Lavender Painted",
"Bb1 cmc Dd ee pnpn Rr": "Rusty Brown Slate Painted",
"Bb1 cmc Dd e- pnpn Rr": "Rusty Brown Slate Painted",
"Bb1 cmc ee pnpn Rr": "Rusty Brown Painted",
"Bb1 cmc e- pnpn Rr": "Rusty Brown Painted",
"Bb1 cmc ee pnpn rr": "Chocolate Red Painted",
"Bb1 cmc e- pnpn rr": "Chocolate Red Painted",
"Bb1 cmc DD nn pnpn Rr": "Dilute Rusty Lavender Painted",
"Bb1 cmc DD n- pnpn Rr": "Dilute Rusty Lavender Painted",
"Bb1 cmc Dd nn pnpn Rr": "Dilute Rusty Slate Painted",
"Bb1 cmc Dd n- pnpn Rr": "Dilute Rusty Slate Painted",
"Bb1 cmc DD ee nn pnpn Rr": "Dilute Rusty Brown Lavender Painted",
"Bb1 cmc DD e- n- pnpn Rr": "Dilute Rusty Brown Lavender Painted",
"Bb1 cmc Dd ee nn pnpn Rr": "Dilute Rusty Brown Slate Painted",
"Bb1 cmc Dd e- n- pnpn Rr": "Dilute Rusty Brown Slate Painted",
"Bb1 cmc ee nn pnpn Rr": "Dilute Rusty Brown Painted",
"Bb1 cmc e- n- pnpn Rr": "Dilute Rusty Brown Painted",
"Bb1 cmc ee nn pnpn rr": "Chocolate Buff Painted",
"Bb1 cmc e- n- pnpn rr": "Chocolate Buff Painted",
"Bb1 cmc nn pnpn rr": "Buff Painted",
"Bb1 cmc n- pnpn rr": "Buff Painted",
// BB TUXEDO

"BB cmcm DD": "Lavender Tuxedo",
"BB cmcm Dd": "Slate Tuxedo",
"BB cmcm Dd Ee": "Slate Tuxedo",
"BB cmcm Dd Nn": "Slate Tuxedo",
"BB cmcm Dd Ee Nn": "Slate Tuxedo",
"BB cmcm DD ee": "Chocolate Lavender Tuxedo",
"BB cmcm DD e-": "Chocolate Lavender Tuxedo",
"BB cmcm Dd ee": "Chocolate Slate Tuxedo",
"BB cmcm Dd e-": "Chocolate Slate Tuxedo",

"BB cmcm nn": "Silver Tipped Black Tuxedo",
"BB cmcm n-": "Silver Tipped Black Tuxedo",
"BB cmcm Rr": "Rusty Tuxedo",
"BB cmcm rr": "Red Tuxedo",
"BB cmcm slsl": "Recessive Blue Tuxedo",
"BB cmcm DD nn": "Silver Tipped Lavender Tuxedo",
"BB cmcm DD n-": " Silver Tipped Lavender Tuxedo",
"BB cmcm Dd nn": "Silver Tipped Slate Tuxedo",
"BB cmcm Dd n-": "Silver Tipped Slate Tuxedo",
"BB cmcm DD ee nn": "Silver Tipped Chocolate Lavender Tuxedo",
"BB cmcm DD e- n-": "Silver Tipped Chocolate Lavender Tuxedo",
"BB cmcm Dd ee nn": "Silver Tipped Chocolate Slate Tuxedo",
"BB cmcm Dd e- n-": "Silver Tipped Chocolate Slate Tuxedo",
"BB cmcm DD Rr": "Rusty Lavender Tuxedo",
"BB cmcm Dd Rr": "Rusty Slate Tuxedo",
"BB cmcm DD ee Rr": "Rusty Brown Lavender Tuxedo",
"BB cmcm DD e- Rr": "Rusty Brown Lavender Tuxedo",
"BB cmcm Dd ee Rr": "Rusty Brown Slate Tuxedo",
"BB cmcm Dd e- Rr": "Rusty Brown Slate Tuxedo",
"BB cmcm ee Rr": "Rusty Brown Tuxedo",
"BB cmcm e- Rr": "Rusty Brown Tuxedo",
"BB cmcm ee rr": "Rusty Chocolate Red Tuxedo",
"BB cmcm e- rr": "Rusty Chocolate Red Tuxedo",
"BB cmcm DD nn Rr": "Dilute Rusty Lavender Tuxedo",
"BB cmcm DD n- Rr": "Dilute Rusty Lavender Tuxedo",
"BB cmcm Dd nn Rr": "Dilute Rusty Slate Tuxedo",
"BB cmcm Dd n- Rr": "Dilute Rusty Slate Tuxedo",
"BB cmcm DD ee nn Rr": "Dilute Rusty Brown Lavender Tuxedo",
"BB cmcm DD e- n- Rr": "Dilute Rusty Brown Lavender Tuxedo",
"BB cmcm Dd ee nn Rr": "Dilute Rusty Brown Slate Tuxedo",
"BB cmcm Dd e- n- Rr": "Dilute Rusty Brown Slate Tuxedo",
"BB cmcm ee nn Rr": "Dilute Rusty Brown Tuxedo",
"BB cmcm e- n- Rr": "Dilute Rusty Brown Tuxedo",
"BB cmcm ee nn rr": "Chocolate Buff Tuxedo",
"BB cmcm e- n- rr": "Chocolate Buff Tuxedo",
"BB cmcm nn rr": "Buff Tuxedo",
"BB cmcm n- rr": "Buff Tuxedo",
// Bb TUXEDO

"Bb cmcm DD": "Barred Lavender Tuxedo",
"Bb cmcm Dd": "Barred Slate Tuxedo",
"Bb cmcm Dd Ee": "Barred Slate Tuxedo",
"Bb cmcm Dd Nn": "Barred Slate Tuxedo",
"Bb cmcm Dd Ee Nn": "Barred Slate Tuxedo",
"Bb cmcm DD ee": "Barred Chocolate Lavender Tuxedo",
"Bb cmcm DD e-": "Barred Chocolate Lavender Tuxedo",
"Bb cmcm Dd ee": "Barred Chocolate Slate Tuxedo",
"Bb cmcm Dd e-": "Barred Chocolate Slate Tuxedo",
"Bb cmcm ee": "Barred Chocolate Tuxedo",
"Bb cmcm e-": "Barred Chocolate Tuxedo",
"Bb cmcm nn": "Silver Tipped Barred Black Tuxedo",
"Bb cmcm n-": "Silver Tipped Barred Black Tuxedo",
"Bb cmcm Rr": "Rusty-Tuxedo",
"Bb cmcm rr": "Red Tuxedo",
"Bb cmcm slsl": "Barred Recessive Blue Tuxedo",
"Bb cmcm DD nn": "Silver Tipped Barred Lavender Tuxedo",
"Bb cmcm DD n-": "Silver Tipped Barred Lavender Tuxedo",
"Bb cmcm Dd nn": "Silver Tipped Barred Slate Tuxedo",
"Bb cmcm Dd n-": "Silver Tipped Barred Slate Tuxedo",
"Bb cmcm DD ee nn": "Silver Tipped Barred Chocolate Lavender Tuxedo",
"Bb cmcm DD e- n-": "Silver Tipped Barred Chocolate Lavender Tuxedo",
"Bb cmcm Dd ee nn": "Silver Tipped Barred Chocolate Slate Tuxedo",
"Bb cmcm Dd e- n-": "Silver Tipped Barred Chocolate Slate Tuxedo",

"Bb cmcm DD Rr": "Rusty Lavender Tuxedo",
"Bb cmcm Dd Rr": "Rusty Slate Tuxedo",
"Bb cmcm DD ee Rr": "Rusty Brown Lavender Tuxedo",
"Bb cmcm DD e- Rr": "Rusty Brown Lavender Tuxedo",
"Bb cmcm Dd ee Rr": "Rusty Brown Slate Tuxedo",
"Bb cmcm Dd e- Rr": "Rusty Brown Slate Tuxedo",
"Bb cmcm ee Rr": "Rusty Brown Tuxedo",
"Bb cmcm e- Rr": "Rusty Brown Tuxedo",
"Bb cmcm ee rr": "Rusty Chocolate Red Tuxedo",
"Bb cmcm e- rr": "Rusty Chocolate Red Tuxedo",
"Bb cmcm DD nn Rr": "Dilute Rusty Lavender Tuxedo",
"Bb cmcm DD n- Rr": "Dilute Rusty Lavender Tuxedo",
"Bb cmcm Dd nn Rr": "Dilute Rusty Slate Tuxedo",
"Bb cmcm Dd n- Rr": "Dilute Rusty Slate Tuxedo",
"Bb cmcm DD ee nn Rr": "Dilute Rusty Brown Lavender Tuxedo",
"Bb cmcm DD e- n- Rr": "Dilute Rusty Brown Lavender Tuxedo",
"Bb cmcm Dd ee nn Rr": "Dilute Rusty Brown Slate Tuxedo",
"Bb cmcm Dd e- n- Rr": "Dilute Rusty Brown Slate Tuxedo",
"Bb cmcm ee nn Rr": "Dilute Rusty Brown Tuxedo",
"Bb cmcm e- n- Rr": "Dilute Rusty Brown Tuxedo",
"Bb cmcm ee nn rr": "Chocolate Buff Tuxedo",
"Bb cmcm e- n- rr": "Chocolate Buff Tuxedo",
"Bb cmcm nn rr": "Buff Tuxedo",
"Bb cmcm n- rr": "Buff Tuxedo",
// Bb1 TUXEDO

"Bb1 cmcm DD": "Mottled Lavender Tuxedo",
"Bb1 cmcm Dd": "Mottled Slate Tuxedo",
"Bb1 cmcm Dd Ee": "Mottled Slate Tuxedo",
"Bb1 cmcm Dd Nn": "Mottled Slate Tuxedo",
"Bb1 cmcm Dd Ee Nn": "Mottled Slate Tuxedo",
"Bb1 cmcm DD ee": "Mottled Chocolate Lavender Tuxedo",
"Bb1 cmcm DD e-": "Mottled Chocolate Lavender Tuxedo",
"Bb1 cmcm Dd ee": "Mottled Chocolate Slate Tuxedo",
"Bb1 cmcm Dd e-": "Mottled Chocolate Slate Tuxedo",
"Bb1 cmcm ee": "Mottled Chocolate Tuxedo",
"Bb1 cmcm ee Slsl": "Mottled Chocolate Tuxedo",
"Bb1 cmcm e-": "Mottled Chocolate Tuxedo",
"Bb1 cmcm e- Slsl": "Mottled Chocolate Tuxedo",
"Bb1 cmcm nn": "Silver Tipped Mottled Black Tuxedo",
"Bb1 cmcm n-": "Silver Tipped Mottled Black Tuxedo",
"Bb1 cmcm Rr": "Mottled Rusty Tuxedo",
"Bb1 cmcm Rr Slsl": "Mottled Rusty Tuxedo",
"Bb1 cmcm rr": "Red Tuxedo",
"Bb1 cmcm slsl": "Mottled Recessive Blue Tuxedo",
"Bb1 cmcm DD nn": "Silver Tipped Mottled Lavender Tuxedo",
"Bb1 cmcm DD n-": "Silver Tipped Mottled Lavender Tuxedo",
"Bb1 cmcm Dd nn": "Silver Tipped Mottled Slate Tuxedo",
"Bb1 cmcm Dd n-": "Silver Tipped Mottled Slate Tuxedo",
"Bb1 cmcm DD ee nn": "Silver Tipped Mottled Chocolate Lavender Tuxedo",
"Bb1 cmcm DD e- n-": "Silver Tipped Mottled Chocolate Lavender Tuxedo",
"Bb1 cmcm Dd ee nn": "Silver Tipped Mottled Chocolate Slate Tuxedo",
"Bb1 cmcm Dd e- n-": "Silver Tipped Mottled Chocolate Slate Tuxedo",

"Bb1 cmcm DD Rr": "Mottled Rusty Lavender Tuxedo",
"Bb1 cmcm Dd Rr": "Mottled Rusty Slate Tuxedo",
"Bb1 cmcm DD ee Rr": "Mottled Rusty Brown Lavender Tuxedo",
"Bb1 cmcm DD e- Rr": "Mottled Rusty Brown Lavender Tuxedo",
"Bb1 cmcm Dd ee Rr": "Mottled Rusty Brown Slate Tuxedo",
"Bb1 cmcm Dd e- Rr": "Mottled Rusty Brown Slate Tuxedo",
"Bb1 cmcm ee Rr": "Mottled Rusty Brown Tuxedo",
"Bb1 cmcm e- Rr": "Mottled Rusty Brown Tuxedo",
"Bb1 cmcm ee rr": "Mottled Rusty Chocolate Red Tuxedo",
"Bb1 cmcm e- rr": "Mottled Rusty Chocolate Red Tuxedo",
"Bb1 cmcm DD nn Rr": "Mottled Dilute Rusty Lavender Tuxedo",
"Bb1 cmcm DD n- Rr": "Mottled Dilute Rusty Lavender Tuxedo",
"Bb1 cmcm Dd nn Rr": "Mottled Dilute Rusty Slate Tuxedo",
"Bb1 cmcm Dd n- Rr": "Mottled Dilute Rusty Slate Tuxedo",
"Bb1 cmcm DD ee nn Rr": "Mottled Dilute Rusty Brown Lavender Tuxedo",
"Bb1 cmcm DD e- n- Rr": "Mottled Dilute Rusty Brown Lavender Tuxedo",
"Bb1 cmcm Dd ee nn Rr": "Mottled Dilute Rusty Brown Slate Tuxedo",
"Bb1 cmcm Dd e- n- Rr": "Mottled Dilute Rusty Brown Slate Tuxedo",
"Bb1 cmcm ee nn Rr": "Mottled Dilute Rusty Brown Tuxedo",
"Bb1 cmcm e- n- Rr": "Mottled Dilute Rusty Brown Tuxedo",
"Bb1 cmcm ee nn rr": "Chocolate Buff Tuxedo",
"Bb1 cmcm e- n- rr": "Chocolate Buff Tuxedo",
"Bb1 cmcm nn rr": "Buff Tuxedo",
"Bb1 cmcm n- rr": "Buff Tuxedo",
// bb FAWN
"bb cmc": "Fawn",
"bb cmc DD": "Lavender Fawn",
"bb cmc Dd": "Slate Fawn",
"bb cmc DD ee": "Chocolate Lavender Fawn",
"bb cmc DD e-": "Chocolate Lavender Fawn",
"bb cmc Dd ee": "Chocolate Slate Fawn",
"bb cmc Dd e-": "Chocolate Slate Fawn",
"bb cmc ee": "Chocolate Fawn",
"bb cmc e-": "Chocolate Fawn",
"bb cmc nn": "Dilute Fawn",
"bb cmc n-": "Dilute Fawn",
"bb cmc Rr": "Rusty Fawn",
"bb cmc rr": "Red Fawn",
"bb cmc slsl": "Recessive Blue Fawn",
"bb cmc DD nn": "Dilute Lavender Fawn",
"bb cmc DD n-": "Dilute Lavender Fawn",
"bb cmc Dd nn": "Dilute Dominant Slate Fawn",
"bb cmc Dd n-": "Dilute Dominant Slate Fawn",
"bb cmc DD ee nn": "Dilute Chocolate Lavender Fawn",
"bb cmc DD e- n-": "Dilute Chocolate Lavender Fawn",
"bb cmc Dd ee nn": "Dilute Chocolate Slate Fawn",
"bb cmc Dd e- n-": "Dilute Chocolate Slate Fawn",
"bb cmc DD Rr": "Rusty Lavender Fawn",
"bb cmc Dd Rr": "Rusty Slate Fawn",
"bb cmc DD ee Rr": "Rusty Chocolate Lavender Fawn",
"bb cmc DD e- Rr": "Rusty Chocolate Lavender Fawn",
"bb cmc Dd ee Rr": "Rusty Brown Slate Fawn",
"bb cmc Dd e- Rr": "Rusty Brown Slate Fawn",
"bb cmc ee Rr": "Rusty Brown Fawn",
"bb cmc e- Rr": "Rusty Brown Fawn",
"bb cmc ee rr": "Chocolate Red Fawn",
"bb cmc e- rr": "Chocolate Red Fawn",
"bb cmc DD nn Rr": "Dilute Rusty Lavender Fawn",
"bb cmc DD n- Rr": "Dilute Rusty Lavender Fawn",
"bb cmc Dd nn Rr": "Dilute Rusty Slate Fawn",
"bb cmc Dd n- Rr": "Dilute Rusty Slate Fawn",
"bb cmc ee nn Rr": "Dilute Rusty Brown Fawn",
"bb cmc e- n- Rr": "Dilute Rusty Brown Fawn",
"bb cmc ee nn rr": "Chocolate Buff Fawn",
"bb cmc e- n- rr": "Chocolate Buff Fawn",
"bb cmc nn rr": "Buff Fawn",
"bb cmc n- rr": "Buff Fawn",
// bb1 FAWN
"bb1 cmc": "Fawn",
"bb1 cmc DD": "Lavender Fawn",
"bb1 cmc Dd": "Slate Fawn",
"bb1 cmc DD ee": "Chocolate Lavender Fawn",
"bb1 cmc DD e-": "Chocolate Lavender Fawn",
"bb1 cmc Dd ee": "Chocolate Slate Fawn",
"bb1 cmc Dd e-": "Chocolate Slate Fawn",
"bb1 cmc ee": "Chocolate Fawn",
"bb1 cmc e-": "Chocolate Fawn",
"bb1 cmc nn": "Dilute Fawn",
"bb1 cmc n-": "Dilute Fawn",
"bb1 cmc Rr": "Rusty Fawn",
"bb1 cmc rr": "Red Fawn",
"bb1 cmc slsl": " Recessive Blue Fawn",
"bb1 cmc DD nn": "Dilute Lavender Fawn",
"bb1 cmc DD n-": "Dilute Lavender Fawn",
"bb1 cmc Dd nn": "Dilute Dominant Slate Fawn",
"bb1 cmc Dd n-": "Dilute Dominant Slate Fawn",
"bb1 cmc DD ee nn": "Dilute Chocolate Lavender Fawn",
"bb1 cmc DD e- n-": "Dilute Chocolate Lavender Fawn",
"bb1 cmc Dd ee nn": "Dilute Chocolate Slate Fawn",
"bb1 cmc Dd e- n-": "Dilute Chocolate Slate Fawn",
"bb1 cmc DD Rr": "Rusty Lavender Fawn",
"bb1 cmc Dd Rr": "Rusty Slate Fawn",
"bb1 cmc DD ee Rr": "Rusty Chocolate Lavender Fawn",
"bb1 cmc DD e- Rr": "Rusty Chocolate Lavender Fawn",
"bb1 cmc Dd ee Rr": "Rusty Brown Slate Fawn",
"bb1 cmc Dd e- Rr": "Rusty Brown Slate Fawn",
"bb1 cmc ee Rr": "Rusty Brown Fawn",
"bb1 cmc e- Rr": "Rusty Brown Fawn",
"bb1 cmc ee rr": "Chocolate Red Fawn",
"bb1 cmc e- rr": "Chocolate Red Fawn",
"bb1 cmc DD nn Rr": "Dilute Rusty Lavender Fawn",
"bb1 cmc DD n- Rr": "Dilute Rusty Lavender Fawn",
"bb1 cmc Dd nn Rr": "Dilute Rusty Slate Fawn",
"bb1 cmc Dd n- Rr": "Dilute Rusty Slate Fawn",
"bb1 cmc ee nn Rr": "Dilute Rusty Brown Fawn",
"bb1 cmc e- n- Rr": "Dilute Rusty Brown Fawn",
"bb1 cmc ee nn rr": "Chocolate Buff Fawn",
"bb1 cmc e- n- rr": "Chocolate Buff Fawn",
"bb1 cmc nn rr": "Buff Fawn",
"bb1 cmc n- rr": "Buff Fawn",
// WHITE WINGED FAWN
"b1b1 cmc": "White Winged Fawn",
"b1b1 cmc DD": "White Winged Lavender Fawn",
"b1b1 cmc Dd": "White Winged Slate Fawn",
"b1b1 cmc DD ee": "White Winged Chocolate Lavender Fawn",
"b1b1 cmc DD e-": "White Winged Chocolate Lavender Fawn",
"b1b1 cmc Dd ee": "White Winged Chocolate Slate Fawn",
"b1b1 cmc Dd e-": "White Winged Chocolate Slate Fawn",
"b1b1 cmc ee": "White Winged Chocolate Fawn",
"b1b1 cmc e-": "White Winged Chocolate Fawn",
"b1b1 cmc nn": "White Winged Dilute Fawn",
"b1b1 cmc n-": "White Winged Dilute Fawn",
"b1b1 cmc Rr": "White Winged Rusty Fawn",
"b1b1 cmc rr": "White Winged Red Fawn",
"b1b1 cmc slsl": "White Winged Recessive Blue Fawn",
"b1b1 cmc DD nn": "White Winged Dilute Lavender Fawn",
"b1b1 cmc DD n-": "White Winged Dilute Lavender Fawn",
"b1b1 cmc Dd nn": "White Winged Dilute Slate Fawn",
"b1b1 cmc Dd n-": "White Winged Dilute Slate Fawn",
"b1b1 cmc DD ee nn": "White Winged Dilute Chocolate Lavender Fawn",
"b1b1 cmc DD e- n-": "White Winged Dilute Chocolate Lavender Fawn",
"b1b1 cmc Dd ee nn": "White Winged Dilute Chocolate Slate Fawn",
"b1b1 cmc Dd e- n-": "White Winged Dilute Chocolate Slate Fawn",
"b1b1 cmc DD Rr": "White Winged Rusty Lavender Fawn",
"b1b1 cmc Dd Rr": "White Winged Rusty Slate Fawn",
"b1b1 cmc DD ee Rr": "White Winged Rusty Chocolate Lavender Fawn",
"b1b1 cmc DD e- Rr": "White Winged Rusty Chocolate Lavender Fawn",
"b1b1 cmc Dd ee Rr": "White Winged Rusty Brown Slate Fawn",
"b1b1 cmc Dd e- Rr": "White Winged Rusty Brown Slate Fawn",
"b1b1 cmc ee Rr": "White Winged Rusty Brown Fawn",
"b1b1 cmc e- Rr": "White Winged Rusty Brown Fawn",
"b1b1 cmc ee rr": "White Winged Chocolate Red Fawn",
"b1b1 cmc e- rr": "White Winged Chocolate Red Fawn",
"b1b1 cmc DD nn Rr": "White Winged Dilute Rusty Lavender Fawn",
"b1b1 cmc DD n- Rr": "White Winged Dilute Rusty Lavender Fawn",
"b1b1 cmc Dd nn Rr": "White Winged Dilute Rusty Slate Fawn",
"b1b1 cmc Dd n- Rr": "White Winged Dilute Rusty Slate Fawn",
"b1b1 cmc ee nn Rr": "White Winged Dilute Rusty Brown Fawn",
"b1b1 cmc e- n- Rr": "White Winged Dilute Rusty Brown Fawn",
"b1b1 cmc ee nn rr": "White Winged Chocolate Buff Fawn",
"b1b1 cmc e- n- rr": "White Winged Chocolate Buff Fawn",
"b1b1 cmc nn rr": "White Winged Buff Fawn",
"b1b1 cmc n- rr": "White Winged Buff Fawn",
// bb MOTTLED 

"bb cmcm DD": "Mottled Lilac",
"bb cmcm Dd": "Mottled Red Slate",
"bb cmcm DD ee": "Mottled Chocolate Lilac",
"bb cmcm DD e-": "Mottled Chocolate Lilac",
"bb cmcm Dd ee": "Mottled Chocolate Red Slate",
"bb cmcm Dd e-": "Mottled Chocolate Red Slate",

"bb cmcm nn": "Mottled Narragansett",
"bb cmcm n-": "Mottled Narragansett",

"bb cmcm rr": "Mottled Red",
"bb cmcm DD nn": "Mottled Lavender Narragansett",
"bb cmcm DD n-": "Mottled Lavender Narragansett",
"bb cmcm Dd nn": "Mottled Blue Narragansett",
"bb cmcm Dd n-": "Mottled Blue Narragansett",
"bb cmcm DD ee nn": "Mottled Chocolate Lavender Narragansett",
"bb cmcm DD e- n-": "Mottled Chocolate Lavender Narragansett",
"bb cmcm Dd ee nn": "Mottled Chocolate Slate Narragansett",
"bb cmcm Dd e- n-": "Mottled Chocolate Slate Narragansett",
"bb cmcm DD Rr": "Mottled Lavender Red Bronze",
"bb cmcm Dd Rr": "Mottled Blue Red Bronze",
"bb cmcm DD ee Rr": "Mottled Chocolate Lavender Red Bronze",
"bb cmcm DD e- Rr": "Mottled Chocolate Lavender Red Bronze",
"bb cmcm Dd ee Rr": "Mottled Blue Red Auburn",
"bb cmcm Dd e- Rr": "Mottled Blue Red Auburn",
"bb cmcm ee Rr": "Mottled Red Auburn",
"bb cmcm e- Rr": "Mottled Red Auburn",
"bb cmcm ee rr": "Mottled Chocolate Red",
"bb cmcm e- rr": "Mottled Chocolate Red",
"bb cmcm DD nn Rr": "Mottled Lavender Red Narragansett",
"bb cmcm DD n- Rr": "Mottled Lavender Red Narragansett",
"bb cmcm Dd nn Rr": "Mottled Blue Red Narragansett",
"bb cmcm Dd n- Rr": "Mottled Blue Red Narragansett",
"bb cmcm ee nn Rr": "Mottled Golden Silver Auburn",
"bb cmcm e- n- Rr": "Mottled Golden Silver Auburn",
"bb cmcm ee nn rr": "Mottled Chocolate Buff",
"bb cmcm e- n- rr": "Mottled Chocolate Buff",
"bb cmcm nn rr": "Mottled Buff",
"bb cmcm n- rr": "Mottled Buff",
// bb1 MOTTLED 

"bb1 cmcm DD": "Mottled Lilac",
"bb1 cmcm Dd": "Mottled Red Slate",
"bb1 cmcm DD ee": "Mottled Chocolate Lilac",
"bb1 cmcm DD e-": "Mottled Chocolate Lilac",
"bb1 cmcm Dd ee": "Mottled Chocolate Red Slate",
"bb1 cmcm Dd e-": "Mottled Chocolate Red Slate",
"bb1 cmcm ee": "Mottled Auburn",
"bb1 cmcm e-": "Mottled Auburn",
"bb1 cmcm nn": "Mottled Narragansett",
"bb1 cmcm n-": "Mottled Narragansett",

"bb1 cmcm rr": "Mottled Red",
"bb1 cmcm DD nn": "Mottled Lavender Narragansett",
"bb1 cmcm DD n-": "Mottled Lavender Narragansett",
"bb1 cmcm Dd nn": "Mottled Blue Narragansett",
"bb1 cmcm Dd n-": "Mottled Blue Narragansett",
"bb1 cmcm DD ee nn": "Mottled Chocolate Lavender Narragansett",
"bb1 cmcm DD e- n-": "Mottled Chocolate Lavender Narragansett",
"bb1 cmcm Dd ee nn": "Mottled Chocolate Slate Narragansett",
"bb1 cmcm Dd e- n-": "Mottled Chocolate Slate Narragansett",
"bb1 cmcm DD Rr": "Mottled Lavender Red Bronze",
"bb1 cmcm Dd Rr": "Mottled Blue Red Bronze",
"bb1 cmcm DD ee Rr": "Mottled Chocolate Lavender Red Bronze",
"bb1 cmcm DD e- Rr": "Mottled Chocolate Lavender Red Bronze",
"bb1 cmcm Dd ee Rr": "Mottled Blue Red Auburn",
"bb1 cmcm Dd e- Rr": "Mottled Blue Red Auburn",
"bb1 cmcm ee Rr": "Mottled Red Auburn",
"bb1 cmcm e- Rr": "Mottled Red Auburn",
"bb1 cmcm ee rr": "Mottled Chocolate Red",
"bb1 cmcm e- rr": "Mottled Chocolate Red",
"bb1 cmcm DD nn Rr": "Mottled Lavender Red Narragansett",
"bb1 cmcm DD n- Rr": "Mottled Lavender Red Narragansett",
"bb1 cmcm Dd nn Rr": "Mottled Blue Red Narragansett",
"bb1 cmcm Dd n- Rr": "Mottled Blue Red Narragansett",
"bb1 cmcm ee nn Rr": "Mottled Golden Silver Auburn",
"bb1 cmcm e- n- Rr": "Mottled Golden Silver Auburn",
"bb1 cmcm ee nn rr": "Mottled Chocolate Buff",
"bb1 cmcm e- n- rr": "Mottled Chocolate Buff",
"bb1 cmcm nn rr": "Mottled Buff",
"bb1 cmcm n- rr": "Mottled Buff",
"b1b1 cmcm": "Mottled Black Winged Bronze",
"b1b1 cmcm Slsl": "Mottled Black Winged Bronze",
"b1b1 cmcm DD": "Mottled Blue Winged Lilac",
"b1b1 cmcm Dd": "Mottled Blue Winged Red Slate",
"b1b1 cmcm DD ee": "Mottled Blue Winged Chocolate Lilac",
"b1b1 cmcm DD e-": "Mottled Blue Winged Chocolate Lilac",
"b1b1 cmcm Dd ee": "Mottled Blue Winged Chocolate Red Slate",
"b1b1 cmcm Dd e-": "Mottled Blue Winged Chocolate Red Slate",
"b1b1 cmcm ee": "Mottled Brown Winged Auburn",
"b1b1 cmcm e-": "Mottled Brown Winged Auburn",
"b1b1 cmcm nn": "Mottled Black Winged Narragansett",
"b1b1 cmcm n-": "Mottled Black Winged Narragansett",
"b1b1 cmcm Rr": "Mottled Harvest Gold",
"b1b1 cmcm rr": "Mottled Regal Red",
"b1b1 cmcm slsl": "Mottled Blue Winged Recessive Slate", 
"b1b1 cmcm DD nn": "Mottled Blue Winged Lavender Narragansett",
"b1b1 cmcm DD n-": "Mottled Blue Winged Lavender Narragansett",
"b1b1 cmcm Dd nn": "Mottled Blue Winged Narragansett",
"b1b1 cmcm Dd n-": "Mottled Blue Winged Narragansett",
"b1b1 cmcm DD ee nn": "Mottled Blue Winged Chocolate Lavender Narragansett",
"b1b1 cmcm DD e- n-": "Mottled Blue Winged Chocolate Lavender Narragansett",
"b1b1 cmcm Dd ee nn": "Mottled Blue Winged Chocolate Slate Narragansett",
"b1b1 cmcm Dd e- n-": "Mottled Blue Winged Chocolate Slate Narragansett",
"b1b1 cmcm DD Rr": "Mottled Blue Winged Lavender Red Bronze",
"b1b1 cmcm Dd Rr": "Mottled Blue Winged Red Bronze",
"b1b1 cmcm DD ee Rr": "Mottled Blue Winged Chocolate Lavender Red Bronze",
"b1b1 cmcm DD e- Rr": "Mottled Blue Winged Chocolate Lavender Red Bronze",
"b1b1 cmcm Dd ee Rr": "Mottled Blue Winged Red Auburn",
"b1b1 cmcm Dd e- Rr": "Mottled Blue Winged Red Auburn",
"b1b1 cmcm ee Rr": "Mottled Brown Winged Red Auburn",
"b1b1 cmcm e- Rr": "Mottled Brown Winged Red Auburn",
"b1b1 cmcm ee rr": "Mottled Chocolate Red",
"b1b1 cmcm e- rr": "Mottled Chocolate Red",
"b1b1 cmcm DD nn Rr": "Mottled Blue Winged Lavender Red Narragansett",
"b1b1 cmcm DD n- Rr": "Mottled Blue Winged Lavender Red Narragansett",
"b1b1 cmcm Dd nn Rr": "Mottled Blue Winged Red Narragansett",
"b1b1 cmcm Dd n- Rr": "Mottled Blue Winged Red Narragansett",
"b1b1 cmcm ee nn Rr": "Mottled Brown Winged Golden Silver Auburn",
"b1b1 cmcm e- n- Rr": "Mottled Brown Winged Golden Silver Auburn",
"b1b1 cmcm ee nn rr": "Mottled Chocolate Buff",
"b1b1 cmcm e- n- rr": "Mottled Chocolate Buff",
"b1b1 cmcm nn rr": "Mottled Buff",
"b1b1 cmcm n- rr": "Mottled Buff",












// MOTTLED AUBURN
"bb cmcm ee": "Mottled Auburn",
"bb cmcm ee Nn": "Mottled Auburn",
"bb cmcm ee Slsl": "Mottled Auburn",
"bb cmcm ee Pnpn": "Mottled Auburn",
"bb cmcm ee pnpn": "Mottled Auburn",
"bb cmcm ee Nn Slsl": "Mottled Auburn",
"bb cmcm ee Nn Pnpn": "Mottled Auburn",
"bb cmcm ee Nn pnpn": "Mottled Auburn",
"bb cmcm ee Nn Pnpn Slsl": "Mottled Auburn",
"bb cmcm ee Nn pnpn Slsl": "Mottled Auburn",
"bb cmcm ee Pnpn Slsl": "Mottled Auburn",
"bb cmcm ee pnpn Slsl": "Mottled Auburn",

// MOTTLED AUBURN FEMALES
"bb cmcm e-": "Mottled Auburn",
"bb cmcm e- Slsl": "Mottled Auburn",
"bb cmcm e- Pnpn": "Mottled Auburn",
"bb cmcm e- pnpn": "Mottled Auburn",
"bb cmcm e- pnpn Slsl": "Mottled Auburn",
"bb cmcm e- Pnpn Slsl": "Mottled Auburn",

// MOTTLED AUBURN â€” Spsp ADDED
"bb cmcm ee Spsp": "Mottled Auburn",
"bb cmcm ee Nn Spsp": "Mottled Auburn",
"bb cmcm ee Slsl Spsp": "Mottled Auburn",
"bb cmcm ee Pnpn Spsp": "Mottled Auburn",
"bb cmcm ee pnpn Spsp": "Mottled Auburn",
"bb cmcm ee Nn Slsl Spsp": "Mottled Auburn",
"bb cmcm ee Nn Pnpn Spsp": "Mottled Auburn",
"bb cmcm ee Nn pnpn Spsp": "Mottled Auburn",
"bb cmcm ee Nn Pnpn Slsl Spsp": "Mottled Auburn",
"bb cmcm ee Nn pnpn Slsl Spsp": "Mottled Auburn",
"bb cmcm ee Pnpn Slsl Spsp": "Mottled Auburn",
"bb cmcm ee pnpn Slsl Spsp": "Mottled Auburn",

// MOTTLED AUBURN FEMALES â€” Spsp ADDED
"bb cmcm e- Spsp": "Mottled Auburn",
"bb cmcm e- Slsl Spsp": "Mottled Auburn",
"bb cmcm e- Pnpn Spsp": "Mottled Auburn",
"bb cmcm e- pnpn Spsp": "Mottled Auburn",
"bb cmcm e- pnpn Slsl Spsp": "Mottled Auburn",
"bb cmcm e- Pnpn Slsl Spsp": "Mottled Auburn",





};
