// Rec Blu-RS
const phenotypeMapping8 = {
// BB RECESSIVE BLUE, All combos done
"BB slsl": "Recessive Blue",
"BB Ee slsl": "Recessive Blue",
"BB Nn slsl": "Recessive Blue",
"BB Pnpn slsl": "Recessive Blue",
"BB pnpn slsl": "Recessive Blue",
"BB Ee Nn slsl": "Recessive Blue",
"BB Ee Pnpn slsl": "Recessive Blue",
"BB Ee pnpn slsl": "Recessive Blue",
"BB Nn Pnpn slsl": "Recessive Blue",
"BB Nn pnpn slsl": "Recessive Blue",
"BB Ee Nn Pnpn slsl": "Recessive Blue",
"BB Ee Nn pnpn slsl": "Recessive Blue",

// C loci variations
"BB Ccg slsl": "Recessive Blue",
"BB Ccg Ee slsl": "Recessive Blue",
"BB Ccg Nn slsl": "Recessive Blue",
"BB Ccg Pnpn slsl": "Recessive Blue",
"BB Ccg pnpn slsl": "Recessive Blue",
"BB Ccg Ee Nn slsl": "Recessive Blue",
"BB Ccg Ee Pnpn slsl": "Recessive Blue",
"BB Ccg Ee pnpn slsl": "Recessive Blue",
"BB Ccg Nn Pnpn slsl": "Recessive Blue",
"BB Ccg Nn pnpn slsl": "Recessive Blue",
"BB Ccg Ee Nn Pnpn slsl": "Recessive Blue",
"BB Ccg Ee Nn pnpn slsl": "Recessive Blue",

"BB Ccm slsl": "Recessive Blue",
"BB Ccm Ee slsl": "Recessive Blue",
"BB Ccm Nn slsl": "Recessive Blue",
"BB Ccm Pnpn slsl": "Recessive Blue",
"BB Ccm pnpn slsl": "Recessive Blue",
"BB Ccm Ee Nn slsl": "Recessive Blue",
"BB Ccm Ee Pnpn slsl": "Recessive Blue",
"BB Ccm Ee pnpn slsl": "Recessive Blue",
"BB Ccm Nn Pnpn slsl": "Recessive Blue",
"BB Ccm Nn pnpn slsl": "Recessive Blue",
"BB Ccm Ee Nn Pnpn slsl": "Recessive Blue",
"BB Ccm Ee Nn pnpn slsl": "Recessive Blue",

"BB Cc slsl": "Recessive Blue",
"BB Cc Ee slsl": "Recessive Blue",
"BB Cc Nn slsl": "Recessive Blue",
"BB Cc Pnpn slsl": "Recessive Blue",
"BB Cc pnpn slsl": "Recessive Blue",
"BB Cc Ee Nn slsl": "Recessive Blue",
"BB Cc Ee Pnpn slsl": "Recessive Blue",
"BB Cc Ee pnpn slsl": "Recessive Blue",
"BB Cc Nn Pnpn slsl": "Recessive Blue",
"BB Cc Nn pnpn slsl": "Recessive Blue",
"BB Cc Ee Nn Pnpn slsl": "Recessive Blue",
"BB Cc Ee Nn pnpn slsl": "Recessive Blue",

"BB cgcg slsl": "Recessive Blue",
"BB cgcg Ee slsl": "Recessive Blue",
"BB cgcg Nn slsl": "Recessive Blue",
"BB cgcg Pnpn slsl": "Recessive Blue",
"BB cgcg pnpn slsl": "Recessive Blue",
"BB cgcg Ee Nn slsl": "Recessive Blue",
"BB cgcg Ee Pnpn slsl": "Recessive Blue",
"BB cgcg Ee pnpn slsl": "Recessive Blue",
"BB cgcg Nn Pnpn slsl": "Recessive Blue",
"BB cgcg Nn pnpn slsl": "Recessive Blue",
"BB cgcg Ee Nn Pnpn slsl": "Recessive Blue",
"BB cgcg Ee Nn pnpn slsl": "Recessive Blue",

"BB cgcm slsl": "Recessive Blue",
"BB cgcm Ee slsl": "Recessive Blue",
"BB cgcm Nn slsl": "Recessive Blue",
"BB cgcm Pnpn slsl": "Recessive Blue",
"BB cgcm pnpn slsl": "Recessive Blue",
"BB cgcm Ee Nn slsl": "Recessive Blue",
"BB cgcm Ee Pnpn slsl": "Recessive Blue",
"BB cgcm Ee pnpn slsl": "Recessive Blue",
"BB cgcm Nn Pnpn slsl": "Recessive Blue",
"BB cgcm Nn pnpn slsl": "Recessive Blue",
"BB cgcm Ee Nn Pnpn slsl": "Recessive Blue",
"BB cgcm Ee Nn pnpn slsl": "Recessive Blue",

"BB cgc slsl": "Recessive Blue",
"BB cgc Ee slsl": "Recessive Blue",
"BB cgc Nn slsl": "Recessive Blue",
"BB cgc Pnpn slsl": "Recessive Blue",
"BB cgc pnpn slsl": "Recessive Blue",
"BB cgc Ee Nn slsl": "Recessive Blue",
"BB cgc Ee Pnpn slsl": "Recessive Blue",
"BB cgc Ee pnpn slsl": "Recessive Blue",
"BB cgc Nn Pnpn slsl": "Recessive Blue",
"BB cgc Nn pnpn slsl": "Recessive Blue",
"BB cgc Ee Nn Pnpn slsl": "Recessive Blue",
"BB cgc Ee Nn pnpn slsl": "Recessive Blue",


 // RECESSIVE BLUE NARRAGANSETT
"bb nn slsl": "Recessive Blue Narragansett",
"bb Ee nn slsl": "Recessive Blue Narragansett",
"bb nn Pnpn slsl": "Recessive Blue Narragansett",
"bb nn pnpn slsl": "Recessive Blue Narragansett",
"bb Ee nn Pnpn slsl": "Recessive Blue Narragansett",
"bb Ee nn pnpn slsl": "Recessive Blue Narragansett",
"bb Ccm nn slsl": "Recessive Blue Narragansett",
"bb Ccm Ee nn slsl": "Recessive Blue Narragansett",
"bb Ccm nn Pnpn slsl": "Recessive Blue Narragansett",
"bb Ccm nn pnpn slsl": "Recessive Blue Narragansett",
"bb Ccm Ee nn Pnpn slsl": "Recessive Blue Narragansett",
"bb Ccm Ee nn pnpn slsl": "Recessive Blue Narragansett",
"bb Ccg nn slsl": "Recessive Blue Narragansett",
"bb Ccg Ee nn slsl": "Recessive Blue Narragansett",
"bb Ccg nn Pnpn slsl": "Recessive Blue Narragansett",
"bb Ccg nn pnpn slsl": "Recessive Blue Narragansett",
"bb Ccg Ee nn Pnpn slsl": "Recessive Blue Narragansett",
"bb Ccg Ee nn pnpn slsl": "Recessive Blue Narragansett",
"bb Cc nn slsl": "Recessive Blue Narragansett",
"bb Cc Ee nn slsl": "Recessive Blue Narragansett",
"bb Cc nn Pnpn slsl": "Recessive Blue Narragansett",
"bb Cc nn pnpn slsl": "Recessive Blue Narragansett",
"bb Cc Ee nn Pnpn slsl": "Recessive Blue Narragansett",
"bb Cc Ee nn pnpn slsl": "Recessive Blue Narragansett",
"bb n- slsl": "Recessive Blue Narragansett",
"bb n- Pnpn slsl": "Recessive Blue Narragansett",
"bb n- pnpn slsl": "Recessive Blue Narragansett",
"bb Ccm n- slsl": "Recessive Blue Narragansett",
"bb Ccm n- Pnpn slsl": "Recessive Blue Narragansett",
"bb Ccm n- pnpn slsl": "Recessive Blue Narragansett",
"bb Ccg n- slsl": "Recessive Blue Narragansett",
"bb Ccg n- Pnpn slsl": "Recessive Blue Narragansett",
"bb Ccg n- pnpn slsl": "Recessive Blue Narragansett",
"bb Cc n- slsl": "Recessive Blue Narragansett",
"bb Cc n- Pnpn slsl": "Recessive Blue Narragansett",
"bb Cc n- pnpn slsl": "Recessive Blue Narragansett",
// RECESSIVE BLUE PALM
"b1b1 cgcg nn slsl": "Recessive Blue Palm",
"b1b1 cgcg Ee nn slsl": "Recessive Blue Palm",
"b1b1 cgcm nn slsl": "Recessive Blue Palm",
"b1b1 cgcm Ee nn slsl": "Recessive Blue Palm",
"b1b1 cgc nn slsl": "Recessive Blue Palm",
"b1b1 cgc Ee nn slsl": "Recessive Blue Palm",
"b1b1 cgcg n- slsl": "Recessive Blue Palm",
"b1b1 cgcm n- slsl": "Recessive Blue Palm",
"b1b1 cgc n- slsl": "Recessive Blue Palm",
// RECESSIVE BLUE CORNISH PALM
"b1b1 Ccg slsl": "Recessive Blue Cornish Palm",
"b1b1 Ccg Ee slsl": "Recessive Blue Cornish Palm",
"b1b1 Ccg Nn slsl": "Recessive Blue Cornish Palm",
"b1b1 Ccg Ee Nn slsl": "Recessive Blue Cornish Palm",
 // RECESSIVE BLUE SWEETGRASS / PENCILLED
"b1b1 cgcg slsl": "Recessive Blue Sweetgrass",
"b1b1 cgcg Ee slsl": "Recessive Blue Sweetgrass",
"b1b1 cgcg Nn slsl": "Recessive Blue Sweetgrass",
"b1b1 cgcg Pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgcg pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgcg Ee Nn slsl": "Recessive Blue Sweetgrass",
"b1b1 cgcg Ee Nn Pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgcg Ee Nn pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgcg Nn Pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgcg Nn pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgcm slsl": "Recessive Blue Sweetgrass",
"b1b1 cgcm Ee slsl": "Recessive Blue Sweetgrass",
"b1b1 cgcm Nn slsl": "Recessive Blue Sweetgrass",
"b1b1 cgcm Pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgcm pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgcm Ee Nn slsl": "Recessive Blue Sweetgrass",
"b1b1 cgcm Ee Nn Pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgcm Ee Nn pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgcm Nn Pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgcm Nn pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgc slsl": "Recessive Blue Sweetgrass",
"b1b1 cgc Ee slsl": "Recessive Blue Sweetgrass",
"b1b1 cgc Nn slsl": "Recessive Blue Sweetgrass",
"b1b1 cgc Pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgc pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgc Ee Nn slsl": "Recessive Blue Sweetgrass",
"b1b1 cgc Ee Nn Pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgc Ee Nn pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgc Nn Pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
"b1b1 cgc Nn pnpn slsl": "Pencilled Recessive Blue Sweetgrass",
// RECESSIVE BLUE WINGED NARRAGANSETT
"b1b1 nn slsl": "Recessive Blue Winged Narragansett",
"b1b1 Ee nn slsl": "Recessive Blue Winged Narragansett",
"b1b1 Ccm nn slsl": "Recessive Blue Winged Narragansett",
"b1b1 Ccm Ee nn slsl": "Recessive Blue Winged Narragansett",
"b1b1 Ccg nn slsl": "Recessive Blue Winged Narragansett",
"b1b1 Ccg Ee nn slsl": "Recessive Blue Winged Narragansett",
"b1b1 Cc nn slsl": "Recessive Blue Winged Narragansett",
"b1b1 Cc Ee nn slsl": "Recessive Blue Winged Narragansett",
"b1b1 n- slsl": "Recessive Blue Winged Narragansett",
"b1b1 Ccm n- slsl": "Recessive Blue Winged Narragansett",
"b1b1 Ccg n- slsl": "Recessive Blue Winged Narragansett",
"b1b1 Cc n- slsl": "Recessive Blue Winged Narragansett",

// RECESSIVE DARK BLUE
"bb cgcg nn slsl": "Recessive Dark Blue",
"bb cgcg Ee nn slsl": "Recessive Dark Blue",
"bb cgcg nn Pnpn slsl": "Recessive Dark Blue",
"bb cgcg nn pnpn slsl": "Recessive Dark Blue",
"bb cgcg Ee nn Pnpn slsl": "Recessive Dark Blue",
"bb cgcg Ee nn pnpn slsl": "Recessive Dark Blue",
"bb cgcm nn slsl": "Recessive Dark Blue",
"bb cgcm Ee nn slsl": "Recessive Dark Blue",
"bb cgcm nn Pnpn slsl": "Recessive Dark Blue",
"bb cgcm nn pnpn slsl": "Recessive Dark Blue",
"bb cgcm Ee nn Pnpn slsl": "Recessive Dark Blue",
"bb cgcm Ee nn pnpn slsl": "Recessive Dark Blue",
"bb cgcg n- slsl": "Recessive Dark Blue" ,
"bb cgcg n- Pnpn slsl": "Recessive Dark Blue" ,
"bb cgcg n- pnpn slsl": "Recessive Dark Blue",
"bb cgcm n- slsl": "Recessive Dark Blue",
"bb cgcm n- Pnpn slsl": "Recessive Dark Blue",
"bb cgcm n- pnpn slsl": "Recessive Dark Blue",
// bb1 RECESSIVE DARK BLUE
"bb1 cgcg nn slsl": "Recessive Dark Blue",
"bb1 cgcg Ee nn slsl": "Recessive Dark Blue",
"bb1 cgcg nn Pnpn slsl": "Recessive Dark Blue",
"bb1 cgcg nn pnpn slsl": "Recessive Dark Blue",
"bb1 cgcg Ee nn Pnpn slsl": "Recessive Dark Blue",
"bb1 cgcg Ee nn pnpn slsl": "Recessive Dark Blue",
"bb1 cgcm nn slsl": "Recessive Dark Blue",
"bb1 cgcm Ee nn slsl": "Recessive Dark Blue",
"bb1 cgcm nn Pnpn slsl": "Recessive Dark Blue",
"bb1 cgcm nn pnpn slsl": "Recessive Dark Blue",
"bb1 cgcm Ee nn Pnpn slsl": "Recessive Dark Blue",
"bb1 cgcm Ee nn pnpn slsl": "Recessive Dark Blue",
"bb1 cgcg n- slsl": "Recessive Dark Blue" ,
"bb1 cgcg n- Pnpn slsl": "Recessive Dark Blue" ,
"bb1 cgcg n- pnpn slsl": "Recessive Dark Blue",
"bb1 cgcm n- slsl": "Recessive Dark Blue",
"bb1 cgcm n- Pnpn slsl": "Recessive Dark Blue",
"bb1 cgcm n- pnpn slsl": "Recessive Dark Blue",
// RECESSIVE LILAC
"bb rr slsl": "Recessive Lilac",
"bb Ee rr slsl": "Recessive Lilac",
"bb Nn rr slsl": "Recessive Lilac",
"bb Pnpn rr slsl": "Recessive Lilac",
"bb pnpn rr slsl": "Recessive Lilac",
"bb Ee Nn rr slsl": "Recessive Lilac",
"bb Nn Pnpn rr slsl": "Recessive Lilac",
"bb Nn pnpn rr slsl": "Recessive Lilac",
"bb Ee Nn Pnpn rr slsl": "Recessive Lilac",
"bb Ee Nn pnpn rr slsl": "Recessive Lilac",
"bb Ccg rr slsl": "Recessive Lilac",
"bb Ccg Ee rr slsl": "Recessive Lilac",
"bb Ccg Nn rr slsl": "Recessive Lilac",
"bb Ccg Pnpn rr slsl": "Recessive Lilac",
"bb Ccg pnpn rr slsl": "Recessive Lilac",
"bb Ccg Ee Nn rr slsl": "Recessive Lilac",
"bb Ccg Nn Pnpn rr slsl": "Recessive Lilac",
"bb Ccg Nn pnpn rr slsl": "Recessive Lilac",
"bb Ccg Ee Nn Pnpn rr slsl": "Recessive Lilac",
"bb Ccg Ee Nn pnpn rr slsl": "Recessive Lilac",
"bb Ccm rr slsl": "Recessive Lilac",
"bb Ccm Ee rr slsl": "Recessive Lilac",
"bb Ccm Nn rr slsl": "Recessive Lilac",
"bb Ccm Pnpn rr slsl": "Recessive Lilac",
"bb Ccm pnpn rr slsl": "Recessive Lilac",
"bb Ccm Ee Nn rr slsl": "Recessive Lilac",
"bb Ccm Nn Pnpn rr slsl": "Recessive Lilac",
"bb Ccm Nn pnpn rr slsl": "Recessive Lilac",
"bb Ccm Ee Nn Pnpn rr slsl": "Recessive Lilac",
"bb Ccm Ee Nn pnpn rr slsl": "Recessive Lilac",
"bb Cc rr slsl": "Recessive Lilac",
"bb Cc Ee rr slsl": "Recessive Lilac",
"bb Cc Nn rr slsl": "Recessive Lilac",
"bb Cc Pnpn rr slsl": "Recessive Lilac",
"bb Cc pnpn rr slsl": "Recessive Lilac",
"bb Cc Ee Nn rr slsl": "Recessive Lilac",
"bb Cc Nn Pnpn rr slsl": "Recessive Lilac",
"bb Cc Nn pnpn rr slsl": "Recessive Lilac",
"bb Cc Ee Nn Pnpn rr slsl": "Recessive Lilac",
"bb Cc Ee Nn pnpn rr slsl": "Recessive Lilac",
"bb cgcg rr slsl": "Recessive Lilac",
"bb cgcg Ee rr slsl": "Recessive Lilac",
"bb cgcg Nn rr slsl": "Recessive Lilac",
"bb cgcg Pnpn rr slsl": "Recessive Lilac",
"bb cgcg pnpn rr slsl": "Recessive Lilac",
"bb cgcg Ee Nn rr slsl": "Recessive Lilac",
"bb cgcg Nn Pnpn rr slsl": "Recessive Lilac",
"bb cgcg Nn pnpn rr slsl": "Recessive Lilac",
"bb cgcg Ee Nn Pnpn rr slsl": "Recessive Lilac",
"bb cgcg Ee Nn pnpn rr slsl": "Recessive Lilac",
"bb cgcm rr slsl": "Recessive Lilac",
"bb cgcm Ee rr slsl": "Recessive Lilac",
"bb cgcm Nn rr slsl": "Recessive Lilac",
"bb cgcm Pnpn rr slsl": "Recessive Lilac",
"bb cgcm pnpn rr slsl": "Recessive Lilac",
"bb cgcm Ee Nn rr slsl": "Recessive Lilac",
"bb cgcm Nn Pnpn rr slsl": "Recessive Lilac",
"bb cgcm Nn pnpn rr slsl": "Recessive Lilac",
"bb cgcm Ee Nn Pnpn rr slsl": "Recessive Lilac",
"bb cgcm Ee Nn pnpn rr slsl": "Recessive Lilac",
"bb cgc rr slsl": "Recessive Lilac",
"bb cgc Ee rr slsl": "Recessive Lilac",
"bb cgc Nn rr slsl": "Recessive Lilac",
"bb cgc Pnpn rr slsl": "Recessive Lilac",
"bb cgc pnpn rr slsl": "Recessive Lilac",
"bb cgc Ee Nn rr slsl": "Recessive Lilac",
"bb cgc Nn Pnpn rr slsl": "Recessive Lilac",
"bb cgc Nn pnpn rr slsl": "Recessive Lilac",
"bb cgc Ee Nn Pnpn rr slsl": "Recessive Lilac",
"bb cgc Ee Nn pnpn rr slsl": "Recessive Lilac",
// bb1 RECESSIVE LILAC
"bb1 rr slsl": "Recessive Lilac",
"bb1 Ee rr slsl": "Recessive Lilac",
"bb1 Nn rr slsl": "Recessive Lilac",
"bb1 Pnpn rr slsl": "Recessive Lilac",
"bb1 pnpn rr slsl": "Recessive Lilac",
"bb1 Ee Nn rr slsl": "Recessive Lilac",
"bb1 Nn Pnpn rr slsl": "Recessive Lilac",
"bb1 Nn pnpn rr slsl": "Recessive Lilac",
"bb1 Ee Nn Pnpn rr slsl": "Recessive Lilac",
"bb1 Ee Nn pnpn rr slsl": "Recessive Lilac",
"bb1 Ccg rr slsl": "Recessive Lilac",
"bb1 Ccg Ee rr slsl": "Recessive Lilac",
"bb1 Ccg Nn rr slsl": "Recessive Lilac",
"bb1 Ccg Pnpn rr slsl": "Recessive Lilac",
"bb1 Ccg pnpn rr slsl": "Recessive Lilac",
"bb1 Ccg Ee Nn rr slsl": "Recessive Lilac",
"bb1 Ccg Nn Pnpn rr slsl": "Recessive Lilac",
"bb1 Ccg Nn pnpn rr slsl": "Recessive Lilac",
"bb1 Ccg Ee Nn Pnpn rr slsl": "Recessive Lilac",
"bb1 Ccg Ee Nn pnpn rr slsl": "Recessive Lilac",
"bb1 Ccm rr slsl": "Recessive Lilac",
"bb1 Ccm Ee rr slsl": "Recessive Lilac",
"bb1 Ccm Nn rr slsl": "Recessive Lilac",
"bb1 Ccm Pnpn rr slsl": "Recessive Lilac",
"bb1 Ccm pnpn rr slsl": "Recessive Lilac",
"bb1 Ccm Ee Nn rr slsl": "Recessive Lilac",
"bb1 Ccm Nn Pnpn rr slsl": "Recessive Lilac",
"bb1 Ccm Nn pnpn rr slsl": "Recessive Lilac",
"bb1 Ccm Ee Nn Pnpn rr slsl": "Recessive Lilac",
"bb1 Ccm Ee Nn pnpn rr slsl": "Recessive Lilac",
"bb1 Cc rr slsl": "Recessive Lilac",
"bb1 Cc Ee rr slsl": "Recessive Lilac",
"bb1 Cc Nn rr slsl": "Recessive Lilac",
"bb1 Cc Pnpn rr slsl": "Recessive Lilac",
"bb1 Cc pnpn rr slsl": "Recessive Lilac",
"bb1 Cc Ee Nn rr slsl": "Recessive Lilac",
"bb1 Cc Nn Pnpn rr slsl": "Recessive Lilac",
"bb1 Cc Nn pnpn rr slsl": "Recessive Lilac",
"bb1 Cc Ee Nn Pnpn rr slsl": "Recessive Lilac",
"bb1 Cc Ee Nn pnpn rr slsl": "Recessive Lilac",
"bb1 cgcg rr slsl": "Recessive Lilac",
"bb1 cgcg Ee rr slsl": "Recessive Lilac",
"bb1 cgcg Nn rr slsl": "Recessive Lilac",
"bb1 cgcg Pnpn rr slsl": "Recessive Lilac",
"bb1 cgcg pnpn rr slsl": "Recessive Lilac",
"bb1 cgcg Ee Nn rr slsl": "Recessive Lilac",
"bb1 cgcg Nn Pnpn rr slsl": "Recessive Lilac",
"bb1 cgcg Nn pnpn rr slsl": "Recessive Lilac",
"bb1 cgcg Ee Nn Pnpn rr slsl": "Recessive Lilac",
"bb1 cgcg Ee Nn pnpn rr slsl": "Recessive Lilac",
"bb1 cgcm rr slsl": "Recessive Lilac",
"bb1 cgcm Ee rr slsl": "Recessive Lilac",
"bb1 cgcm Nn rr slsl": "Recessive Lilac",
"bb1 cgcm Pnpn rr slsl": "Recessive Lilac",
"bb1 cgcm pnpn rr slsl": "Recessive Lilac",
"bb1 cgcm Ee Nn rr slsl": "Recessive Lilac",
"bb1 cgcm Nn Pnpn rr slsl": "Recessive Lilac",
"bb1 cgcm Nn pnpn rr slsl": "Recessive Lilac",
"bb1 cgcm Ee Nn Pnpn rr slsl": "Recessive Lilac",
"bb1 cgcm Ee Nn pnpn rr slsl": "Recessive Lilac",
"bb1 cgc rr slsl": "Recessive Lilac",
"bb1 cgc Ee rr slsl": "Recessive Lilac",
"bb1 cgc Nn rr slsl": "Recessive Lilac",
"bb1 cgc Pnpn rr slsl": "Recessive Lilac",
"bb1 cgc pnpn rr slsl": "Recessive Lilac",
"bb1 cgc Ee Nn rr slsl": "Recessive Lilac",
"bb1 cgc Nn Pnpn rr slsl": "Recessive Lilac",
"bb1 cgc Nn pnpn rr slsl": "Recessive Lilac",
"bb1 cgc Ee Nn Pnpn rr slsl": "Recessive Lilac",
"bb1 cgc Ee Nn pnpn rr slsl": "Recessive Lilac",
// RECESSIVE OREGON BLUE
"bb cgc nn slsl": "Recessive Oregon Blue",
"bb cgc Ee nn slsl": "Recessive Oregon Blue",
"bb cgc nn Pnpn slsl": "Recessive Oregon Blue",
"bb cgc nn pnpn slsl": "Recessive Oregon Blue",
"bb cgc Ee nn Pnpn slsl": "Recessive Oregon Blue",
"bb cgc Ee nn pnpn slsl": "Recessive Oregon Blue",
"bb cgc n- slsl": "Recessive Oregon Blue",
"bb cgc n- Pnpn slsl": "Recessive Oregon Blue",
"bb cgc n- pnpn slsl": "Recessive Oregon Blue",
// bb1 RECESSIVE OREGON BLUE
"bb1 cgc nn slsl": "Recessive Oregon Blue",
"bb1 cgc Ee nn slsl": "Recessive Oregon Blue",
"bb1 cgc nn Pnpn slsl": "Recessive Oregon Blue",
"bb1 cgc nn pnpn slsl": "Recessive Oregon Blue",
"bb1 cgc Ee nn Pnpn slsl": "Recessive Oregon Blue",
"bb1 cgc Ee nn pnpn slsl": "Recessive Oregon Blue",
"bb1 cgc n- slsl": "Recessive Oregon Blue",
"bb1 cgc n- Pnpn slsl": "Recessive Oregon Blue",
"bb1 cgc n- pnpn slsl": "Recessive Oregon Blue",

// bb RECESSIVE SLATE, All combos done
"bb slsl": "Recessive Slate",
"bb Ee slsl": "Recessive Slate",
"bb Nn slsl": "Recessive Slate",
"bb Pnpn slsl": "Recessive Slate",
"bb pnpn slsl": "Recessive Slate",
"bb Ee Nn slsl": "Recessive Slate",
"bb Ee Pnpn slsl": "Recessive Slate",
"bb Ee pnpn slsl": "Recessive Slate",
"bb Nn Pnpn slsl": "Recessive Slate",
"bb Nn pnpn slsl": "Recessive Slate",
"bb Ee Nn Pnpn slsl": "Recessive Slate",
"bb Ee Nn pnpn slsl": "Recessive Slate",

// C loci variations
"bb Ccg slsl": "Recessive Slate",
"bb Ccg Ee slsl": "Recessive Slate",
"bb Ccg Nn slsl": "Recessive Slate",
"bb Ccg Pnpn slsl": "Recessive Slate",
"bb Ccg pnpn slsl": "Recessive Slate",
"bb Ccg Ee Nn slsl": "Recessive Slate",
"bb Ccg Ee Pnpn slsl": "Recessive Slate",
"bb Ccg Ee pnpn slsl": "Recessive Slate",
"bb Ccg Nn Pnpn slsl": "Recessive Slate",
"bb Ccg Nn pnpn slsl": "Recessive Slate",
"bb Ccg Ee Nn Pnpn slsl": "Recessive Slate",
"bb Ccg Ee Nn pnpn slsl": "Recessive Slate",

"bb Ccm slsl": "Recessive Slate",
"bb Ccm Ee slsl": "Recessive Slate",
"bb Ccm Nn slsl": "Recessive Slate",
"bb Ccm Pnpn slsl": "Recessive Slate",
"bb Ccm pnpn slsl": "Recessive Slate",
"bb Ccm Ee Nn slsl": "Recessive Slate",
"bb Ccm Ee Pnpn slsl": "Recessive Slate",
"bb Ccm Ee pnpn slsl": "Recessive Slate",
"bb Ccm Nn Pnpn slsl": "Recessive Slate",
"bb Ccm Nn pnpn slsl": "Recessive Slate",
"bb Ccm Ee Nn Pnpn slsl": "Recessive Slate",
"bb Ccm Ee Nn pnpn slsl": "Recessive Slate",

"bb Cc slsl": "Recessive Slate",
"bb Cc Ee slsl": "Recessive Slate",
"bb Cc Nn slsl": "Recessive Slate",
"bb Cc Pnpn slsl": "Recessive Slate",
"bb Cc pnpn slsl": "Recessive Slate",
"bb Cc Ee Nn slsl": "Recessive Slate",
"bb Cc Ee Pnpn slsl": "Recessive Slate",
"bb Cc Ee pnpn slsl": "Recessive Slate",
"bb Cc Nn Pnpn slsl": "Recessive Slate",
"bb Cc Nn pnpn slsl": "Recessive Slate",
"bb Cc Ee Nn Pnpn slsl": "Recessive Slate",
"bb Cc Ee Nn pnpn slsl": "Recessive Slate",

"bb cgcg slsl": "Recessive Slate",
"bb cgcg Ee slsl": "Recessive Slate",
"bb cgcg Nn slsl": "Recessive Slate",
"bb cgcg Pnpn slsl": "Recessive Slate",
"bb cgcg pnpn slsl": "Recessive Slate",
"bb cgcg Ee Nn slsl": "Recessive Slate",
"bb cgcg Ee Pnpn slsl": "Recessive Slate",
"bb cgcg Ee pnpn slsl": "Recessive Slate",
"bb cgcg Nn Pnpn slsl": "Recessive Slate",
"bb cgcg Nn pnpn slsl": "Recessive Slate",
"bb cgcg Ee Nn Pnpn slsl": "Recessive Slate",
"bb cgcg Ee Nn pnpn slsl": "Recessive Slate",

"bb cgcm slsl": "Recessive Slate",
"bb cgcm Ee slsl": "Recessive Slate",
"bb cgcm Nn slsl": "Recessive Slate",
"bb cgcm Pnpn slsl": "Recessive Slate",
"bb cgcm pnpn slsl": "Recessive Slate",
"bb cgcm Ee Nn slsl": "Recessive Slate",
"bb cgcm Ee Pnpn slsl": "Recessive Slate",
"bb cgcm Ee pnpn slsl": "Recessive Slate",
"bb cgcm Nn Pnpn slsl": "Recessive Slate",
"bb cgcm Nn pnpn slsl": "Recessive Slate",
"bb cgcm Ee Nn Pnpn slsl": "Recessive Slate",
"bb cgcm Ee Nn pnpn slsl": "Recessive Slate",

"bb cgc slsl": "Recessive Slate",
"bb cgc Ee slsl": "Recessive Slate",
"bb cgc Nn slsl": "Recessive Slate",
"bb cgc Pnpn slsl": "Recessive Slate",
"bb cgc pnpn slsl": "Recessive Slate",
"bb cgc Ee Nn slsl": "Recessive Slate",
"bb cgc Ee Pnpn slsl": "Recessive Slate",
"bb cgc Ee pnpn slsl": "Recessive Slate",
"bb cgc Nn Pnpn slsl": "Recessive Slate",
"bb cgc Nn pnpn slsl": "Recessive Slate",
"bb cgc Ee Nn Pnpn slsl": "Recessive Slate",
"bb cgc Ee Nn pnpn slsl": "Recessive Slate",

// bb1

"bb1 slsl": "Recessive Slate.",
"bb1 Ee slsl": "Recessive Slate.",
"bb1 Nn slsl": "Recessive Slate.",
"bb1 Pnpn slsl": "Recessive Slate.",
"bb1 pnpn slsl": "Recessive Slate.",
"bb1 Ee Nn slsl": "Recessive Slate.",
"bb1 Ee Pnpn slsl": "Recessive Slate.",
"bb1 Ee pnpn slsl": "Recessive Slate.",
"bb1 Nn Pnpn slsl": "Recessive Slate.",
"bb1 Nn pnpn slsl": "Recessive Slate.",
"bb1 Ee Nn Pnpn slsl": "Recessive Slate.",
"bb1 Ee Nn pnpn slsl": "Recessive Slate.",

"bb1 Ccg slsl": "Recessive Slate.",
"bb1 Ccg Ee slsl": "Recessive Slate.",
"bb1 Ccg Nn slsl": "Recessive Slate.",
"bb1 Ccg Pnpn slsl": "Recessive Slate.",
"bb1 Ccg pnpn slsl": "Recessive Slate.",
"bb1 Ccg Ee Nn slsl": "Recessive Slate.",
"bb1 Ccg Ee Pnpn slsl": "Recessive Slate.",
"bb1 Ccg Ee pnpn slsl": "Recessive Slate.",
"bb1 Ccg Nn Pnpn slsl": "Recessive Slate.",
"bb1 Ccg Nn pnpn slsl": "Recessive Slate.",
"bb1 Ccg Ee Nn Pnpn slsl": "Recessive Slate.",
"bb1 Ccg Ee Nn pnpn slsl": "Recessive Slate.",

"bb1 Ccm slsl": "Recessive Slate.",
"bb1 Ccm Ee slsl": "Recessive Slate.",
"bb1 Ccm Nn slsl": "Recessive Slate.",
"bb1 Ccm Pnpn slsl": "Recessive Slate.",
"bb1 Ccm pnpn slsl": "Recessive Slate.",
"bb1 Ccm Ee Nn slsl": "Recessive Slate.",
"bb1 Ccm Ee Pnpn slsl": "Recessive Slate.",
"bb1 Ccm Ee pnpn slsl": "Recessive Slate.",
"bb1 Ccm Nn Pnpn slsl": "Recessive Slate.",
"bb1 Ccm Nn pnpn slsl": "Recessive Slate.",
"bb1 Ccm Ee Nn Pnpn slsl": "Recessive Slate.",
"bb1 Ccm Ee Nn pnpn slsl": "Recessive Slate.",

"bb1 Cc slsl": "Recessive Slate.",
"bb1 Cc Ee slsl": "Recessive Slate.",
"bb1 Cc Nn slsl": "Recessive Slate.",
"bb1 Cc Pnpn slsl": "Recessive Slate.",
"bb1 Cc pnpn slsl": "Recessive Slate.",
"bb1 Cc Ee Nn slsl": "Recessive Slate.",
"bb1 Cc Ee Pnpn slsl": "Recessive Slate.",
"bb1 Cc Ee pnpn slsl": "Recessive Slate.",
"bb1 Cc Nn Pnpn slsl": "Recessive Slate.",
"bb1 Cc Nn pnpn slsl": "Recessive Slate.",
"bb1 Cc Ee Nn Pnpn slsl": "Recessive Slate.",
"bb1 Cc Ee Nn pnpn slsl": "Recessive Slate.",

"bb1 cgcg slsl": "Recessive Slate.",
"bb1 cgcg Ee slsl": "Recessive Slate.",
"bb1 cgcg Nn slsl": "Recessive Slate.",
"bb1 cgcg Pnpn slsl": "Recessive Slate.",
"bb1 cgcg pnpn slsl": "Recessive Slate.",
"bb1 cgcg Ee Nn slsl": "Recessive Slate.",
"bb1 cgcg Ee Pnpn slsl": "Recessive Slate.",
"bb1 cgcg Ee pnpn slsl": "Recessive Slate.",
"bb1 cgcg Nn Pnpn slsl": "Recessive Slate.",
"bb1 cgcg Nn pnpn slsl": "Recessive Slate.",
"bb1 cgcg Ee Nn Pnpn slsl": "Recessive Slate.",
"bb1 cgcg Ee Nn pnpn slsl": "Recessive Slate.",

"bb1 cgcm slsl": "Recessive Slate.",
"bb1 cgcm Ee slsl": "Recessive Slate.",
"bb1 cgcm Nn slsl": "Recessive Slate.",
"bb1 cgcm Pnpn slsl": "Recessive Slate.",
"bb1 cgcm pnpn slsl": "Recessive Slate.",
"bb1 cgcm Ee Nn slsl": "Recessive Slate.",
"bb1 cgcm Ee Pnpn slsl": "Recessive Slate.",
"bb1 cgcm Ee pnpn slsl": "Recessive Slate.",
"bb1 cgcm Nn Pnpn slsl": "Recessive Slate.",
"bb1 cgcm Nn pnpn slsl": "Recessive Slate.",
"bb1 cgcm Ee Nn Pnpn slsl": "Recessive Slate.",
"bb1 cgcm Ee Nn pnpn slsl": "Recessive Slate.",

"bb1 cgc slsl": "Recessive Slate.",
"bb1 cgc Ee slsl": "Recessive Slate.",
"bb1 cgc Nn slsl": "Recessive Slate.",
"bb1 cgc Pnpn slsl": "Recessive Slate.",
"bb1 cgc pnpn slsl": "Recessive Slate.",
"bb1 cgc Ee Nn slsl": "Recessive Slate.",
"bb1 cgc Ee Pnpn slsl": "Recessive Slate.",
"bb1 cgc Ee pnpn slsl": "Recessive Slate.",
"bb1 cgc Nn Pnpn slsl": "Recessive Slate.",
"bb1 cgc Nn pnpn slsl": "Recessive Slate.",
"bb1 cgc Ee Nn Pnpn slsl": "Recessive Slate.",
"bb1 cgc Ee Nn pnpn slsl": "Recessive Slate.",

 
  
  
  
  



  
};
