// FADING DOWN VARIATIONS
const phenotypeMapping17 = {


// bb fdfd FADING DOWN BRONZE, done ***
"bb cc fdfd": "Fading Down Bronze",
"bb cc Ee fdfd": "Fading Down Bronze",
"bb cc fdfd Nn": "Fading Down Bronze",
"bb cc fdfd Slsl": "Fading Down Bronze",
"bb cc fdfd Pnpn": "Fading Down Bronze",
"bb cc fdfd pnpn": "Fading Down Bronze",
"bb cc Ee fdfd Nn": "Fading Down Bronze",
"bb cc Ee fdfd Slsl": "Fading Down Bronze",
"bb cc Ee fdfd Pnpn": "Fading Down Bronze",
"bb cc Ee fdfd pnpn": "Fading Down Bronze",
"bb cc fdfd Nn Pnpn": "Fading Down Bronze",
"bb cc fdfd Nn pnpn": "Fading Down Bronze",
"bb cc fdfd Nn Slsl": "Fading Down Bronze",
"bb cc fdfd Nn Pnpn Slsl": "Fading Down Bronze",
"bb cc fdfd Nn pnpn Slsl": "Fading Down Bronze",
"bb cc Ee fdfd Nn Pnpn": "Fading Down Bronze",
"bb cc Ee fdfd Nn Slsl": "Fading Down Bronze",
"bb cc Ee fdfd Nn Pnpn Slsl": "Fading Down Bronze",
"bb cc Ee fdfd Nn pnpn Slsl": "Fading Down Bronze",
"bb cc fdfd Pnpn Slsl": "Fading Down Bronze",
"bb cc fdfd pnpn Slsl": "Fading Down Bronze",
"bb cc fdfd Spsp": "Fading Down Bronze",
"bb cc Ee fdfd Spsp": "Fading Down Bronze",
"bb cc fdfd Nn Spsp": "Fading Down Bronze",
"bb cc fdfd Slsl Spsp": "Fading Down Bronze",
"bb cc fdfd Pnpn Spsp": "Fading Down Bronze",
"bb cc fdfd pnpn Spsp": "Fading Down Bronze",
"bb cc Ee fdfd Nn Spsp": "Fading Down Bronze",
"bb cc Ee fdfd Slsl Spsp": "Fading Down Bronze",
"bb cc Ee fdfd Pnpn Spsp": "Fading Down Bronze",
"bb cc Ee fdfd pnpn Spsp": "Fading Down Bronze",
"bb cc fdfd Nn Pnpn Spsp": "Fading Down Bronze",
"bb cc fdfd Nn pnpn Spsp": "Fading Down Bronze",
"bb cc fdfd Nn Slsl Spsp": "Fading Down Bronze",
"bb cc fdfd Nn Pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc fdfd Nn pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc Ee fdfd Pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc Ee fdfd pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc fdfd Pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc fdfd pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc Ee fdfd Nn Pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc Ee fdfd Nn pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc Ee fdfd Nn Pnpn Spsp": "Fading Down Bronze",
"bb cc Ee fdfd Nn pnpn Spsp": "Fading Down Bronze",
"bb cc Ee fdfd Nn Slsl Spsp": "Fading Down Bronze",
"bb cc Ee fdfd Pnpn Slsl": "Fading Down Bronze",
"bb cc Ee fdfd pnpn Slsl": "Fading Down Bronze",


// bb1 FADING DOWN BRONZE, done ***
"bb1 cc fdfd": "Fading Down Bronze",
"bb1 cc Ee fdfd": "Fading Down Bronze",
"bb1 cc fdfd Nn": "Fading Down Bronze",
"bb1 cc fdfd Slsl": "Fading Down Bronze",
"bb1 cc fdfd Pnpn": "Fading Down Bronze",
"bb1 cc fdfd pnpn": "Fading Down Bronze",
"bb1 cc Ee fdfd Nn": "Fading Down Bronze",
"bb1 cc Ee fdfd Slsl": "Fading Down Bronze",
"bb1 cc Ee fdfd Pnpn": "Fading Down Bronze",
"bb1 cc Ee fdfd pnpn": "Fading Down Bronze",
"bb1 cc fdfd Nn Pnpn": "Fading Down Bronze",
"bb1 cc fdfd Nn pnpn": "Fading Down Bronze",
"bb1 cc fdfd Nn Slsl": "Fading Down Bronze",
"bb1 cc fdfd Nn Pnpn Slsl": "Fading Down Bronze",
"bb1 cc fdfd Nn pnpn Slsl": "Fading Down Bronze",
"bb1 cc Ee fdfd Nn Pnpn": "Fading Down Bronze",
"bb1 cc Ee fdfd Nn Slsl": "Fading Down Bronze",
"bb1 cc Ee fdfd Nn Pnpn Slsl": "Fading Down Bronze",
"bb1 cc Ee fdfd Nn pnpn Slsl": "Fading Down Bronze",
"bb1 cc fdfd Pnpn Slsl": "Fading Down Bronze",
"bb1 cc fdfd pnpn Slsl": "Fading Down Bronze",
"bb1 cc fdfd Spsp": "Fading Down Bronze",
"bb1 cc Ee fdfd Spsp": "Fading Down Bronze",
"bb1 cc fdfd Nn Spsp": "Fading Down Bronze",
"bb1 cc fdfd Slsl Spsp": "Fading Down Bronze",
"bb1 cc fdfd Pnpn Spsp": "Fading Down Bronze",
"bb1 cc fdfd pnpn Spsp": "Fading Down Bronze",
"bb1 cc Ee fdfd Nn Spsp": "Fading Down Bronze",
"bb1 cc Ee fdfd Slsl Spsp": "Fading Down Bronze",
"bb1 cc Ee fdfd Pnpn Spsp": "Fading Down Bronze",
"bb1 cc Ee fdfd pnpn Spsp": "Fading Down Bronze",
"bb1 cc fdfd Nn Pnpn Spsp": "Fading Down Bronze",
"bb1 cc fdfd Nn pnpn Spsp": "Fading Down Bronze",
"bb1 cc fdfd Nn Slsl Spsp": "Fading Down Bronze",
"bb1 cc fdfd Nn Pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc fdfd Nn pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Ee fdfd Pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Ee fdfd pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc fdfd Pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc fdfd pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Ee fdfd Nn Pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Ee fdfd Nn pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Ee fdfd Nn Pnpn Spsp": "Fading Down Bronze",
"bb1 cc Ee fdfd Nn pnpn Spsp": "Fading Down Bronze",
"bb1 cc Ee fdfd Nn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Ee fdfd Pnpn Slsl": "Fading Down Bronze",
"bb1 cc Ee fdfd pnpn Slsl": "Fading Down Bronze",

// bb Fdfd FADING DOWN BRONZE, done ***
"bb cc Fdfd": "Fading Down Bronze",
"bb cc Ee Fdfd": "Fading Down Bronze",
"bb cc Fdfd Nn": "Fading Down Bronze",
"bb cc Fdfd Slsl": "Fading Down Bronze",
"bb cc Fdfd Pnpn": "Fading Down Bronze",
"bb cc Fdfd pnpn": "Fading Down Bronze",
"bb cc Ee Fdfd Nn": "Fading Down Bronze",
"bb cc Ee Fdfd Slsl": "Fading Down Bronze",
"bb cc Ee Fdfd Pnpn": "Fading Down Bronze",
"bb cc Ee Fdfd pnpn": "Fading Down Bronze",
"bb cc Fdfd Nn Pnpn": "Fading Down Bronze",
"bb cc Fdfd Nn pnpn": "Fading Down Bronze",
"bb cc Fdfd Nn Slsl": "Fading Down Bronze",
"bb cc Fdfd Nn Pnpn Slsl": "Fading Down Bronze",
"bb cc Fdfd Nn pnpn Slsl": "Fading Down Bronze",
"bb cc Ee Fdfd Nn Pnpn": "Fading Down Bronze",
"bb cc Ee Fdfd Nn Slsl": "Fading Down Bronze",
"bb cc Ee Fdfd Nn Pnpn Slsl": "Fading Down Bronze",
"bb cc Ee Fdfd Nn pnpn Slsl": "Fading Down Bronze",
"bb cc Fdfd Pnpn Slsl": "Fading Down Bronze",
"bb cc Fdfd pnpn Slsl": "Fading Down Bronze",
"bb cc Fdfd Spsp": "Fading Down Bronze",
"bb cc Ee Fdfd Spsp": "Fading Down Bronze",
"bb cc Fdfd Nn Spsp": "Fading Down Bronze",
"bb cc Fdfd Slsl Spsp": "Fading Down Bronze",
"bb cc Fdfd Pnpn Spsp": "Fading Down Bronze",
"bb cc Fdfd pnpn Spsp": "Fading Down Bronze",
"bb cc Ee Fdfd Nn Spsp": "Fading Down Bronze",
"bb cc Ee Fdfd Slsl Spsp": "Fading Down Bronze",
"bb cc Ee Fdfd Pnpn Spsp": "Fading Down Bronze",
"bb cc Ee Fdfd pnpn Spsp": "Fading Down Bronze",
"bb cc Fdfd Nn Pnpn Spsp": "Fading Down Bronze",
"bb cc Fdfd Nn pnpn Spsp": "Fading Down Bronze",
"bb cc Fdfd Nn Slsl Spsp": "Fading Down Bronze",
"bb cc Fdfd Nn Pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc Fdfd Nn pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc Ee Fdfd Pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc Ee Fdfd pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc Fdfd Pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc Fdfd pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc Ee Fdfd Nn Pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc Ee Fdfd Nn pnpn Slsl Spsp": "Fading Down Bronze",
"bb cc Ee Fdfd Nn Pnpn Spsp": "Fading Down Bronze",
"bb cc Ee Fdfd Nn pnpn Spsp": "Fading Down Bronze",
"bb cc Ee Fdfd Nn Slsl Spsp": "Fading Down Bronze",
"bb cc Ee Fdfd Pnpn Slsl": "Fading Down Bronze",
"bb cc Ee Fdfd pnpn Slsl": "Fading Down Bronze",

// bb1 Fdfd FADING DOWN BRONZE, done ***
"bb1 cc Fdfd": "Fading Down Bronze",
"bb1 cc Ee Fdfd": "Fading Down Bronze",
"bb1 cc Fdfd Nn": "Fading Down Bronze",
"bb1 cc Fdfd Slsl": "Fading Down Bronze",
"bb1 cc Fdfd Pnpn": "Fading Down Bronze",
"bb1 cc Fdfd pnpn": "Fading Down Bronze",
"bb1 cc Ee Fdfd Nn": "Fading Down Bronze",
"bb1 cc Ee Fdfd Slsl": "Fading Down Bronze",
"bb1 cc Ee Fdfd Pnpn": "Fading Down Bronze",
"bb1 cc Ee Fdfd pnpn": "Fading Down Bronze",
"bb1 cc Fdfd Nn Pnpn": "Fading Down Bronze",
"bb1 cc Fdfd Nn pnpn": "Fading Down Bronze",
"bb1 cc Fdfd Nn Slsl": "Fading Down Bronze",
"bb1 cc Fdfd Nn Pnpn Slsl": "Fading Down Bronze",
"bb1 cc Fdfd Nn pnpn Slsl": "Fading Down Bronze",
"bb1 cc Ee Fdfd Nn Pnpn": "Fading Down Bronze",
"bb1 cc Ee Fdfd Nn Slsl": "Fading Down Bronze",
"bb1 cc Ee Fdfd Nn Pnpn Slsl": "Fading Down Bronze",
"bb1 cc Ee Fdfd Nn pnpn Slsl": "Fading Down Bronze",
"bb1 cc Fdfd Pnpn Slsl": "Fading Down Bronze",
"bb1 cc Fdfd pnpn Slsl": "Fading Down Bronze",
"bb1 cc Fdfd Spsp": "Fading Down Bronze",
"bb1 cc Ee Fdfd Spsp": "Fading Down Bronze",
"bb1 cc Fdfd Nn Spsp": "Fading Down Bronze",
"bb1 cc Fdfd Slsl Spsp": "Fading Down Bronze",
"bb1 cc Fdfd Pnpn Spsp": "Fading Down Bronze",
"bb1 cc Fdfd pnpn Spsp": "Fading Down Bronze",
"bb1 cc Ee Fdfd Nn Spsp": "Fading Down Bronze",
"bb1 cc Ee Fdfd Slsl Spsp": "Fading Down Bronze",
"bb1 cc Ee Fdfd Pnpn Spsp": "Fading Down Bronze",
"bb1 cc Ee Fdfd pnpn Spsp": "Fading Down Bronze",
"bb1 cc Fdfd Nn Pnpn Spsp": "Fading Down Bronze",
"bb1 cc Fdfd Nn pnpn Spsp": "Fading Down Bronze",
"bb1 cc Fdfd Nn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Fdfd Nn Pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Fdfd Nn pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Ee Fdfd Pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Ee Fdfd pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Fdfd Pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Fdfd pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Ee Fdfd Nn Pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Ee Fdfd Nn pnpn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Ee Fdfd Nn Pnpn Spsp": "Fading Down Bronze",
"bb1 cc Ee Fdfd Nn pnpn Spsp": "Fading Down Bronze",
"bb1 cc Ee Fdfd Nn Slsl Spsp": "Fading Down Bronze",
"bb1 cc Ee Fdfd Pnpn Slsl": "Fading Down Bronze",
"bb1 cc Ee Fdfd pnpn Slsl": "Fading Down Bronze",




// BB fdfd FADING DOWN BLACK, done ***
"BB cc fdfd": "Fading Down Black",
"BB cc Ee fdfd": "Fading Down Black",
"BB cc fdfd Nn": "Fading Down Black",
"BB cc fdfd Slsl": "Fading Down Black",
"BB cc fdfd Pnpn": "Fading Down Black",
"BB cc fdfd pnpn": "Fading Down Black",
"BB cc Ee fdfd Nn": "Fading Down Black",
"BB cc Ee fdfd Slsl": "Fading Down Black",
"BB cc Ee fdfd Pnpn": "Fading Down Black",
"BB cc Ee fdfd pnpn": "Fading Down Black",
"BB cc fdfd Nn Pnpn": "Fading Down Black",
"BB cc fdfd Nn pnpn": "Fading Down Black",
"BB cc fdfd Nn Slsl": "Fading Down Black",
"BB cc fdfd Nn Pnpn Slsl": "Fading Down Black",
"BB cc fdfd Nn pnpn Slsl": "Fading Down Black",
"BB cc Ee fdfd Nn Pnpn": "Fading Down Black",
"BB cc Ee fdfd Nn Slsl": "Fading Down Black",
"BB cc Ee fdfd Nn Pnpn Slsl": "Fading Down Black",
"BB cc Ee fdfd Nn pnpn Slsl": "Fading Down Black",
"BB cc fdfd Pnpn Slsl": "Fading Down Black",
"BB cc fdfd pnpn Slsl": "Fading Down Black",
"BB cc fdfd Spsp": "Fading Down Black",
"BB cc Ee fdfd Spsp": "Fading Down Black",
"BB cc fdfd Nn Spsp": "Fading Down Black",
"BB cc fdfd Slsl Spsp": "Fading Down Black",
"BB cc fdfd Pnpn Spsp": "Fading Down Black",
"BB cc fdfd pnpn Spsp": "Fading Down Black",
"BB cc Ee fdfd Nn Spsp": "Fading Down Black",
"BB cc Ee fdfd Slsl Spsp": "Fading Down Black",
"BB cc Ee fdfd Pnpn Spsp": "Fading Down Black",
"BB cc Ee fdfd pnpn Spsp": "Fading Down Black",
"BB cc fdfd Nn Pnpn Spsp": "Fading Down Black",
"BB cc fdfd Nn pnpn Spsp": "Fading Down Black",
"BB cc fdfd Nn Slsl Spsp": "Fading Down Black",
"BB cc fdfd Nn Pnpn Slsl Spsp": "Fading Down Black",
"BB cc fdfd Nn pnpn Slsl Spsp": "Fading Down Black",
"BB cc Ee fdfd Pnpn Slsl Spsp": "Fading Down Black",
"BB cc Ee fdfd pnpn Slsl Spsp": "Fading Down Black",
"BB cc fdfd Pnpn Slsl Spsp": "Fading Down Black",
"BB cc fdfd pnpn Slsl Spsp": "Fading Down Black",
"BB cc Ee fdfd Nn Pnpn Slsl Spsp": "Fading Down Black",
"BB cc Ee fdfd Nn pnpn Slsl Spsp": "Fading Down Black",
"BB cc Ee fdfd Nn Pnpn Spsp": "Fading Down Black",
"BB cc Ee fdfd Nn pnpn Spsp": "Fading Down Black",
"BB cc Ee fdfd Nn Slsl Spsp": "Fading Down Black",
"BB cc Ee fdfd Pnpn Slsl": "Fading Down Black",
"BB cc Ee fdfd pnpn Slsl": "Fading Down Black",

// FADING DOWN BWB, DONE
"b1b1 cc fdfd": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Nn": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Slsl": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Pnpn": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd pnpn": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Nn": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Slsl": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Pnpn": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd pnpn": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Nn Pnpn": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Nn pnpn": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Nn Slsl": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Nn Pnpn Slsl": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Nn pnpn Slsl": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Nn Pnpn": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Nn Slsl": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Nn Pnpn Slsl": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Nn pnpn Slsl": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Pnpn Slsl": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd pnpn Slsl": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Nn Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Slsl Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Pnpn Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd pnpn Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Nn Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Slsl Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Pnpn Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd pnpn Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Nn Pnpn Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Nn pnpn Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Nn Slsl Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Nn Pnpn Slsl Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Nn pnpn Slsl Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Pnpn Slsl Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd pnpn Slsl Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd Pnpn Slsl Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc fdfd pnpn Slsl Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Nn Pnpn Slsl Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Nn pnpn Slsl Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Nn Pnpn Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Nn pnpn Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Nn Slsl Spsp": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd Pnpn Slsl": "Fading Down Black Winged Bronze",
"b1b1 cc Ee fdfd pnpn Slsl": "Fading Down Black Winged Bronze",


//  fdfd FADING DOWN bb RED BRONZE, DONE
"bb cc fdfd Rr": "Fading Down Red Bronze",
"bb cc Ee fdfd Rr": "Fading Down Red Bronze",
"bb cc fdfd Nn Rr": "Fading Down Red Bronze",
"bb cc fdfd Rr Slsl": "Fading Down Red Bronze",
"bb cc fdfd Pnpn Rr": "Fading Down Red Bronze",
"bb cc fdfd pnpn Rr": "Fading Down Red Bronze",
"bb cc Ee fdfd Nn Rr": "Fading Down Red Bronze",
"bb cc Ee fdfd Rr Slsl": "Fading Down Red Bronze",
"bb cc Ee fdfd Pnpn Rr": "Fading Down Red Bronze",
"bb cc Ee fdfd pnpn Rr": "Fading Down Red Bronze",
"bb cc fdfd Nn Pnpn Rr": "Fading Down Red Bronze",
"bb cc fdfd Nn pnpn Rr": "Fading Down Red Bronze",
"bb cc fdfd Nn Rr Slsl": "Fading Down Red Bronze",
"bb cc fdfd Nn Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb cc fdfd Nn pnpn Rr Slsl": "Fading Down Red Bronze",
"bb cc Ee fdfd Nn Pnpn Rr": "Fading Down Red Bronze",
"bb cc Ee fdfd Nn Rr Slsl": "Fading Down Red Bronze",
"bb cc Ee fdfd Nn Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb cc Ee fdfd Nn pnpn Rr Slsl": "Fading Down Red Bronze",
"bb cc fdfd Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb cc fdfd pnpn Rr Slsl": "Fading Down Red Bronze",
"bb cc fdfd Rr Spsp": "Fading Down Red Bronze",
"bb cc Ee fdfd Rr Spsp": "Fading Down Red Bronze",
"bb cc fdfd Nn Rr Spsp": "Fading Down Red Bronze",
"bb cc fdfd Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc fdfd Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc fdfd pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc Ee fdfd Nn Rr Spsp": "Fading Down Red Bronze",
"bb cc Ee fdfd Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Ee fdfd Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc Ee fdfd pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc fdfd Nn Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc fdfd Nn pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc fdfd Nn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Ee fdfd Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Ee fdfd pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc fdfd Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc fdfd pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Ee fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Ee fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Ee fdfd Nn Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc Ee fdfd Nn pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc Ee fdfd Nn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Ee fdfd Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb cc Ee fdfd pnpn Rr Slsl": "Fading Down Red Bronze",
 
 // fdfd FADING DOWN  bb1 RED BRONZE, DONE
 "bb1 cc fdfd Rr": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Rr": "Fading Down Red Bronze",
"bb1 cc fdfd Nn Rr": "Fading Down Red Bronze",
"bb1 cc fdfd Rr Slsl": "Fading Down Red Bronze",
"bb1 cc fdfd Pnpn Rr": "Fading Down Red Bronze",
"bb1 cc fdfd pnpn Rr": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Nn Rr": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Pnpn Rr": "Fading Down Red Bronze",
"bb1 cc Ee fdfd pnpn Rr": "Fading Down Red Bronze",
"bb1 cc fdfd Nn Pnpn Rr": "Fading Down Red Bronze",
"bb1 cc fdfd Nn pnpn Rr": "Fading Down Red Bronze",
"bb1 cc fdfd Nn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc fdfd Nn Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc fdfd Nn pnpn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Nn Pnpn Rr": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Nn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Nn Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Nn pnpn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc fdfd Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc fdfd pnpn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc fdfd Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Rr Spsp": "Fading Down Red Bronze",
"bb1 cc fdfd Nn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc fdfd Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc fdfd Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc fdfd pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Nn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Ee fdfd pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc fdfd Nn Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc fdfd Nn pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc fdfd Nn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Ee fdfd pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc fdfd Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc fdfd pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Nn Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Nn pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Nn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Ee fdfd Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Ee fdfd pnpn Rr Slsl": "Fading Down Red Bronze",


// Fdfd FADING DOWN bb RED BRONZE, DONE
"bb cc Fdfd Rr": "Fading Down Red Bronze",
"bb cc Ee Fdfd Rr": "Fading Down Red Bronze",
"bb cc Fdfd Nn Rr": "Fading Down Red Bronze",
"bb cc Fdfd Rr Slsl": "Fading Down Red Bronze",
"bb cc Fdfd Pnpn Rr": "Fading Down Red Bronze",
"bb cc Fdfd pnpn Rr": "Fading Down Red Bronze",
"bb cc Ee Fdfd Nn Rr": "Fading Down Red Bronze",
"bb cc Ee Fdfd Rr Slsl": "Fading Down Red Bronze",
"bb cc Ee Fdfd Pnpn Rr": "Fading Down Red Bronze",
"bb cc Ee Fdfd pnpn Rr": "Fading Down Red Bronze",
"bb cc Fdfd Nn Pnpn Rr": "Fading Down Red Bronze",
"bb cc Fdfd Nn pnpn Rr": "Fading Down Red Bronze",
"bb cc Fdfd Nn Rr Slsl": "Fading Down Red Bronze",
"bb cc Fdfd Nn Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb cc Fdfd Nn pnpn Rr Slsl": "Fading Down Red Bronze",
"bb cc Ee Fdfd Nn Pnpn Rr": "Fading Down Red Bronze",
"bb cc Ee Fdfd Nn Rr Slsl": "Fading Down Red Bronze",
"bb cc Ee Fdfd Nn Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb cc Ee Fdfd Nn pnpn Rr Slsl": "Fading Down Red Bronze",
"bb cc Fdfd Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb cc Fdfd pnpn Rr Slsl": "Fading Down Red Bronze",
"bb cc Fdfd Rr Spsp": "Fading Down Red Bronze",
"bb cc Ee Fdfd Rr Spsp": "Fading Down Red Bronze",
"bb cc Fdfd Nn Rr Spsp": "Fading Down Red Bronze",
"bb cc Fdfd Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Fdfd Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc Fdfd pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc Ee Fdfd Nn Rr Spsp": "Fading Down Red Bronze",
"bb cc Ee Fdfd Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Ee Fdfd Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc Ee Fdfd pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc Fdfd Nn Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc Fdfd Nn pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc Fdfd Nn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Ee Fdfd Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Ee Fdfd pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Fdfd Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Fdfd pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Ee Fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Ee Fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Ee Fdfd Nn Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc Ee Fdfd Nn pnpn Rr Spsp": "Fading Down Red Bronze",
"bb cc Ee Fdfd Nn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb cc Ee Fdfd Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb cc Ee Fdfd pnpn Rr Slsl": "Fading Down Red Bronze",

//  Fdfd FADING DOWN bb1 RED BRONZE, DONE
"bb1 cc Fdfd Rr": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Rr": "Fading Down Red Bronze",
"bb1 cc Fdfd Nn Rr": "Fading Down Red Bronze",
"bb1 cc Fdfd Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Fdfd Pnpn Rr": "Fading Down Red Bronze",
"bb1 cc Fdfd pnpn Rr": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Nn Rr": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Pnpn Rr": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd pnpn Rr": "Fading Down Red Bronze",
"bb1 cc Fdfd Nn Pnpn Rr": "Fading Down Red Bronze",
"bb1 cc Fdfd Nn pnpn Rr": "Fading Down Red Bronze",
"bb1 cc Fdfd Nn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Fdfd Nn Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Fdfd Nn pnpn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Nn Pnpn Rr": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Nn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Nn Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Nn pnpn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Fdfd Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Fdfd pnpn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Fdfd Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Fdfd Nn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Fdfd Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Fdfd Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Fdfd pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Nn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Fdfd Nn Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Fdfd Nn pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Fdfd Nn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Fdfd Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Fdfd pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Nn Pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Nn pnpn Rr Spsp": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Nn Rr Slsl Spsp": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd Pnpn Rr Slsl": "Fading Down Red Bronze",
"bb1 cc Ee Fdfd pnpn Rr Slsl": "Fading Down Red Bronze",




// BB fdfd FADING DOWN RUSTY BLACK, done ***
"BB cc fdfd Rr": "Fading Down Rusty Black",
"BB cc Ee fdfd Rr": "Fading Down Rusty Black",
"BB cc fdfd Nn Rr": "Fading Down Rusty Black",
"BB cc fdfd Rr Slsl": "Fading Down Rusty Black",
"BB cc fdfd Pnpn Rr": "Fading Down Rusty Black",
"BB cc fdfd pnpn Rr": "Fading Down Rusty Black",
"BB cc Ee fdfd Nn Rr": "Fading Down Rusty Black",
"BB cc Ee fdfd Rr Slsl": "Fading Down Rusty Black",
"BB cc Ee fdfd Pnpn Rr": "Fading Down Rusty Black",
"BB cc Ee fdfd pnpn Rr": "Fading Down Rusty Black",
"BB cc fdfd Nn Pnpn Rr": "Fading Down Rusty Black",
"BB cc fdfd Nn pnpn Rr": "Fading Down Rusty Black",
"BB cc fdfd Nn Rr Slsl": "Fading Down Rusty Black",
"BB cc fdfd Nn Pnpn Rr Slsl": "Fading Down Rusty Black",
"BB cc fdfd Nn pnpn Rr Slsl": "Fading Down Rusty Black",
"BB cc Ee fdfd Nn Pnpn Rr": "Fading Down Rusty Black",
"BB cc Ee fdfd Nn Rr Slsl": "Fading Down Rusty Black",
"BB cc Ee fdfd Nn Pnpn Rr Slsl": "Fading Down Rusty Black",
"BB cc Ee fdfd Nn pnpn Rr Slsl": "Fading Down Rusty Black",
"BB cc fdfd Pnpn Rr Slsl": "Fading Down Rusty Black",
"BB cc fdfd pnpn Rr Slsl": "Fading Down Rusty Black",
"BB cc fdfd Rr Spsp": "Fading Down Rusty Black",
"BB cc Ee fdfd Rr Spsp": "Fading Down Rusty Black",
"BB cc fdfd Nn Rr Spsp": "Fading Down Rusty Black",
"BB cc fdfd Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc fdfd Pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc fdfd pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc Ee fdfd Nn Rr Spsp": "Fading Down Rusty Black",
"BB cc Ee fdfd Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Ee fdfd Pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc Ee fdfd pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc fdfd Nn Pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc fdfd Nn pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc fdfd Nn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Ee fdfd Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Ee fdfd pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc fdfd Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc fdfd pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Ee fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Ee fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Ee fdfd Nn Pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc Ee fdfd Nn pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc Ee fdfd Nn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Ee fdfd Pnpn Rr Slsl": "Fading Down Rusty Black",
"BB cc Ee fdfd pnpn Rr Slsl": "Fading Down Rusty Black",

// Bb fdfd FADING DOWN RUSTY BLACK, done ***
"Bb cc fdfd Rr": "Fading Down Rusty Black",
"Bb cc Ee fdfd Rr": "Fading Down Rusty Black",
"Bb cc fdfd Nn Rr": "Fading Down Rusty Black",
"Bb cc fdfd Rr Slsl": "Fading Down Rusty Black",
"Bb cc fdfd Pnpn Rr": "Fading Down Rusty Black",
"Bb cc fdfd pnpn Rr": "Fading Down Rusty Black",
"Bb cc Ee fdfd Nn Rr": "Fading Down Rusty Black",
"Bb cc Ee fdfd Rr Slsl": "Fading Down Rusty Black",
"Bb cc Ee fdfd Pnpn Rr": "Fading Down Rusty Black",
"Bb cc Ee fdfd pnpn Rr": "Fading Down Rusty Black",
"Bb cc fdfd Nn Pnpn Rr": "Fading Down Rusty Black",
"Bb cc fdfd Nn pnpn Rr": "Fading Down Rusty Black",
"Bb cc fdfd Nn Rr Slsl": "Fading Down Rusty Black",
"Bb cc fdfd Nn Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb cc fdfd Nn pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb cc Ee fdfd Nn Pnpn Rr": "Fading Down Rusty Black",
"Bb cc Ee fdfd Nn Rr Slsl": "Fading Down Rusty Black",
"Bb cc Ee fdfd Nn Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb cc Ee fdfd Nn pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb cc fdfd Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb cc fdfd pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb cc fdfd Rr Spsp": "Fading Down Rusty Black",
"Bb cc Ee fdfd Rr Spsp": "Fading Down Rusty Black",
"Bb cc fdfd Nn Rr Spsp": "Fading Down Rusty Black",
"Bb cc fdfd Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc fdfd Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc fdfd pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Ee fdfd Nn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Ee fdfd Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Ee fdfd Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Ee fdfd pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc fdfd Nn Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc fdfd Nn pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc fdfd Nn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Ee fdfd Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Ee fdfd pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc fdfd Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc fdfd pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Ee fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Ee fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Ee fdfd Nn Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Ee fdfd Nn pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Ee fdfd Nn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Ee fdfd Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb cc Ee fdfd pnpn Rr Slsl": "Fading Down Rusty Black",

// BB Fdfd FADING DOWN RUSTY BLACK, done ***
"BB cc Fdfd Rr": "Fading Down Rusty Black",
"BB cc Ee Fdfd Rr": "Fading Down Rusty Black",
"BB cc Fdfd Nn Rr": "Fading Down Rusty Black",
"BB cc Fdfd Rr Slsl": "Fading Down Rusty Black",
"BB cc Fdfd Pnpn Rr": "Fading Down Rusty Black",
"BB cc Fdfd pnpn Rr": "Fading Down Rusty Black",
"BB cc Ee Fdfd Nn Rr": "Fading Down Rusty Black",
"BB cc Ee Fdfd Rr Slsl": "Fading Down Rusty Black",
"BB cc Ee Fdfd Pnpn Rr": "Fading Down Rusty Black",
"BB cc Ee Fdfd pnpn Rr": "Fading Down Rusty Black",
"BB cc Fdfd Nn Pnpn Rr": "Fading Down Rusty Black",
"BB cc Fdfd Nn pnpn Rr": "Fading Down Rusty Black",
"BB cc Fdfd Nn Rr Slsl": "Fading Down Rusty Black",
"BB cc Fdfd Nn Pnpn Rr Slsl": "Fading Down Rusty Black",
"BB cc Fdfd Nn pnpn Rr Slsl": "Fading Down Rusty Black",
"BB cc Ee Fdfd Nn Pnpn Rr": "Fading Down Rusty Black",
"BB cc Ee Fdfd Nn Rr Slsl": "Fading Down Rusty Black",
"BB cc Ee Fdfd Nn Pnpn Rr Slsl": "Fading Down Rusty Black",
"BB cc Ee Fdfd Nn pnpn Rr Slsl": "Fading Down Rusty Black",
"BB cc Fdfd Pnpn Rr Slsl": "Fading Down Rusty Black",
"BB cc Fdfd pnpn Rr Slsl": "Fading Down Rusty Black",
"BB cc Fdfd Rr Spsp": "Fading Down Rusty Black",
"BB cc Ee Fdfd Rr Spsp": "Fading Down Rusty Black",
"BB cc Fdfd Nn Rr Spsp": "Fading Down Rusty Black",
"BB cc Fdfd Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Fdfd Pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc Fdfd pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc Ee Fdfd Nn Rr Spsp": "Fading Down Rusty Black",
"BB cc Ee Fdfd Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Ee Fdfd Pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc Ee Fdfd pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc Fdfd Nn Pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc Fdfd Nn pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc Fdfd Nn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Ee Fdfd Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Ee Fdfd pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Fdfd Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Fdfd pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Ee Fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Ee Fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Ee Fdfd Nn Pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc Ee Fdfd Nn pnpn Rr Spsp": "Fading Down Rusty Black",
"BB cc Ee Fdfd Nn Rr Slsl Spsp": "Fading Down Rusty Black",
"BB cc Ee Fdfd Pnpn Rr Slsl": "Fading Down Rusty Black",
"BB cc Ee Fdfd pnpn Rr Slsl": "Fading Down Rusty Black",

// Bb Fdfd FADING DOWN RUSTY BLACK, done ***
"Bb cc Fdfd Rr": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Rr": "Fading Down Rusty Black",
"Bb cc Fdfd Nn Rr": "Fading Down Rusty Black",
"Bb cc Fdfd Rr Slsl": "Fading Down Rusty Black",
"Bb cc Fdfd Pnpn Rr": "Fading Down Rusty Black",
"Bb cc Fdfd pnpn Rr": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Nn Rr": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Rr Slsl": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Pnpn Rr": "Fading Down Rusty Black",
"Bb cc Ee Fdfd pnpn Rr": "Fading Down Rusty Black",
"Bb cc Fdfd Nn Pnpn Rr": "Fading Down Rusty Black",
"Bb cc Fdfd Nn pnpn Rr": "Fading Down Rusty Black",
"Bb cc Fdfd Nn Rr Slsl": "Fading Down Rusty Black",
"Bb cc Fdfd Nn Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb cc Fdfd Nn pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Nn Pnpn Rr": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Nn Rr Slsl": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Nn Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Nn pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb cc Fdfd Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb cc Fdfd pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb cc Fdfd Rr Spsp": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Rr Spsp": "Fading Down Rusty Black",
"Bb cc Fdfd Nn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Fdfd Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Fdfd Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Fdfd pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Nn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Ee Fdfd pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Fdfd Nn Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Fdfd Nn pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Fdfd Nn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Ee Fdfd pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Fdfd Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Fdfd pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Nn Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Nn pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Nn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb cc Ee Fdfd Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb cc Ee Fdfd pnpn Rr Slsl": "Fading Down Rusty Black",




// Bb1 fdfd FADING DOWN RUSTY BLACK, done ***
"Bb1 cc fdfd Rr": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Rr": "Fading Down Rusty Black",
"Bb1 cc fdfd Nn Rr": "Fading Down Rusty Black",
"Bb1 cc fdfd Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc fdfd Pnpn Rr": "Fading Down Rusty Black",
"Bb1 cc fdfd pnpn Rr": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Nn Rr": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Pnpn Rr": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd pnpn Rr": "Fading Down Rusty Black",
"Bb1 cc fdfd Nn Pnpn Rr": "Fading Down Rusty Black",
"Bb1 cc fdfd Nn pnpn Rr": "Fading Down Rusty Black",
"Bb1 cc fdfd Nn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc fdfd Nn Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc fdfd Nn pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Nn Pnpn Rr": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Nn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Nn Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Nn pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc fdfd Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc fdfd pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc fdfd Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc fdfd Nn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc fdfd Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc fdfd Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc fdfd pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Nn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc fdfd Nn Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc fdfd Nn pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc fdfd Nn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc fdfd Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc fdfd pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Nn Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Nn pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Nn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Ee fdfd pnpn Rr Slsl": "Fading Down Rusty Black",


// Bb1 Fdfd FADING DOWN RUSTY BLACK, done ***
"Bb1 cc Fdfd Rr": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Rr": "Fading Down Rusty Black",
"Bb1 cc Fdfd Nn Rr": "Fading Down Rusty Black",
"Bb1 cc Fdfd Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Fdfd Pnpn Rr": "Fading Down Rusty Black",
"Bb1 cc Fdfd pnpn Rr": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Nn Rr": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Pnpn Rr": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd pnpn Rr": "Fading Down Rusty Black",
"Bb1 cc Fdfd Nn Pnpn Rr": "Fading Down Rusty Black",
"Bb1 cc Fdfd Nn pnpn Rr": "Fading Down Rusty Black",
"Bb1 cc Fdfd Nn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Fdfd Nn Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Fdfd Nn pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Nn Pnpn Rr": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Nn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Nn Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Nn pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Fdfd Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Fdfd pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Fdfd Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Fdfd Nn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Fdfd Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Fdfd Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Fdfd pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Nn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Fdfd Nn Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Fdfd Nn pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Fdfd Nn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Fdfd Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Fdfd pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Nn Pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Nn pnpn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Nn Pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Nn pnpn Rr Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Nn Rr Slsl Spsp": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd Pnpn Rr Slsl": "Fading Down Rusty Black",
"Bb1 cc Ee Fdfd pnpn Rr Slsl": "Fading Down Rusty Black",




};
