// CH-Dil JB
const phenotypeMapping3 = { 
 // CHOCOLATE
  "BB ee": "Chocolate",
  "BB ee Nn": "Chocolate",
  "BB ee Slsl": "Chocolate",
  "BB ee Pnpn": "Chocolate",
  "BB ee pnpn": "Chocolate",
  "BB ee Pnpn Slsl": "Chocolate",
  "BB ee pnpn Slsl": "Chocolate",
  "BB ee Nn Slsl": "Chocolate",
  "BB ee Nn Pnpn": "Chocolate",
  "BB ee Nn pnpn": "Chocolate",
  "BB ee Nn Pnpn Slsl": "Chocolate",
  "BB ee Nn pnpn Slsl": "Chocolate",
  "BB Ccg ee": "Chocolate",
  "BB Ccg ee Nn": "Chocolate",
  "BB Ccg ee Slsl": "Chocolate",
  "BB Ccg ee Pnpn": "Chocolate",
  "BB Ccg ee pnpn": "Chocolate",
  "BB Ccg ee Pnpn Slsl": "Chocolate",
  "BB Ccg ee pnpn Slsl": "Chocolate",
  "BB Ccg ee Nn Slsl": "Chocolate",
  "BB Ccg ee Nn Pnpn": "Chocolate",
  "BB Ccg ee Nn pnpn": "Chocolate",
  "BB Ccg ee Nn Pnpn Slsl": "Chocolate",
  "BB Ccg ee Nn pnpn Slsl": "Chocolate",
  "BB Ccm ee": "Chocolate",
  "BB Ccm ee Nn": "Chocolate",
  "BB Ccm ee Slsl": "Chocolate",
  "BB Ccm ee Pnpn": "Chocolate",
  "BB Ccm ee pnpn Slsl": "Chocolate",
  "BB Ccm ee Pnpn Slsl": "Chocolate",
  "BB Ccm ee pnpn": "Chocolate",
  "BB Ccm ee Nn Slsl": "Chocolate",
  "BB Ccm ee Nn Pnpn": "Chocolate",
  "BB Ccm ee Nn pnpn": "Chocolate",
  "BB Ccm ee Nn Pnpn Slsl": "Chocolate",
  "BB Ccm ee Nn pnpn Slsl": "Chocolate",
  "BB Cc ee": "Chocolate",
  "BB Cc ee Nn": "Chocolate",
  "BB Cc ee Slsl": "Chocolate",
  "BB Cc ee Pnpn": "Chocolate",
  "BB Cc ee pnpn Slsl": "Chocolate",
  "BB Cc ee Pnpn Slsl": "Chocolate",
  "BB Cc ee pnpn": "Chocolate",
  "BB Cc ee Nn Slsl": "Chocolate",
  "BB Cc ee Nn Pnpn": "Chocolate",
  "BB Cc ee Nn pnpn": "Chocolate",
  "BB Cc ee Nn Pnpn Slsl": "Chocolate",
  "BB Cc ee Nn pnpn Slsl": "Chocolate",
  "BB cgcg ee": "Chocolate",
  "BB cgcg ee Nn": "Chocolate",
  "BB cgcg ee Slsl": "Chocolate",
  "BB cgcg ee Pnpn": "Chocolate",
  "BB cgcg ee pnpn": "Chocolate",
  "BB cgcg ee Pnpn Slsl": "Chocolate",
  "BB cgcg ee pnpn Slsl": "Chocolate",
  "BB cgcg ee Nn Slsl": "Chocolate",
  "BB cgcg ee Nn Pnpn": "Chocolate",
  "BB cgcg ee Nn pnpn": "Chocolate",
  "BB cgcg ee Nn pnpn Slsl": "Chocolate",
  "BB cgcm ee": "Chocolate",
  "BB cgcm ee Nn": "Chocolate",
  "BB cgcm ee Slsl": "Chocolate",
  "BB cgcm ee Pnpn": "Chocolate",
  "BB cgcm ee pnpn": "Chocolate",
  "BB cgcm ee Pnpn Slsl": "Chocolate",
  "BB cgcm ee pnpn Slsl": "Chocolate",
  "BB cgcm ee Nn Slsl": "Chocolate",
  "BB cgcm ee Nn Pnpn": "Chocolate",
  "BB cgcm ee Nn pnpn": "Chocolate",
  "BB cgcm ee Nn pnpn Slsl": "Chocolate",
  "BB cgc ee": "Chocolate",
  "BB cgc ee Nn": "Chocolate",
  "BB cgc ee Slsl": "Chocolate",
  "BB cgc ee Pnpn": "Chocolate",
  "BB cgc ee pnpn": "Chocolate",
  "BB cgc ee Pnpn Slsl": "Chocolate",
  "BB cgc ee pnpn Slsl": "Chocolate",
  "BB cgc ee Nn Slsl": "Chocolate",
  "BB cgc ee Nn Pnpn": "Chocolate",
  "BB cgc ee Nn pnpn": "Chocolate",
  "BB cgc ee Nn pnpn Slsl": "Chocolate",
  // CHOCOLATE FEMALES
  "BB e-": "Chocolate",
  "BB e- Slsl": "Chocolate",
  "BB e- Pnpn": "Chocolate",
  "BB e- pnpn": "Chocolate",
  "BB e- Pnpn Slsl": "Chocolate",
  "BB e- pnpn Slsl": "Chocolate",
  "BB Ccg e-": "Chocolate",
  "BB Ccg e- Slsl": "Chocolate",
  "BB Ccg e- Pnpn": "Chocolate",
  "BB Ccg e- pnpn": "Chocolate",
  "BB Ccg e- Pnpn Slsl": "Chocolate",
  "BB Ccg e- pnpn Slsl": "Chocolate",
  "BB Ccm e-": "Chocolate",
  "BB Ccm e- Slsl": "Chocolate",
  "BB Ccm e- Pnpn": "Chocolate",
  "BB Ccm e- pnpn": "Chocolate",
  "BB Ccm e- pnpn Slsl": "Chocolate",
  "BB Ccm e- Pnpn Slsl": "Chocolate",
  "BB Cc e-": "Chocolate",
  "BB Cc e- Slsl": "Chocolate",
  "BB Cc e- Pnpn": "Chocolate",
  "BB Cc e- pnpn": "Chocolate",
  "BB Cc e- Pnpn Slsl": "Chocolate",
  "BB Cc e- pnpn Slsl": "Chocolate",
  "BB cgcg e-": "Chocolate",
  "BB cgcg e- Slsl": "Chocolate",
  "BB cgcg e- Pnpn": "Chocolate",
  "BB cgcg e- pnpn": "Chocolate",
  "BB cgcg e- Pnpn Slsl": "Chocolate",
  "BB cgcg e- pnpn Slsl": "Chocolate",
  "BB cgcm e-": "Chocolate",
  "BB cgcm e- Slsl": "Chocolate",
  "BB cgcm e- Pnpn": "Chocolate",
  "BB cgcm e- pnpn": "Chocolate",
  "BB cgcm e- Pnpn Slsl": "Chocolate",
  "BB cgcm e- pnpn Slsl": "Chocolate",
  "BB cgc e-": "Chocolate",
  "BB cgc e- Slsl": "Chocolate",
  "BB cgc e- Pnpn": "Chocolate",
  "BB cgc e- pnpn": "Chocolate",
  "BB cgc e- Pnpn Slsl": "Chocolate",
  "BB cgc e- pnpn Slsl": "Chocolate",
  
  
  // CHOCOLATE BLUE RED BRONZE
"bb Dd ee Rr": "Chocolate Blue Red Bronze",
"bb Dd ee Nn Rr": "Chocolate Blue Red Bronze",
"bb Dd ee Rr Slsl": "Chocolate Blue Red Bronze",
"bb Dd ee Pnpn Rr": "Chocolate Blue Red Bronze",
"bb Dd ee pnpn Rr": "Chocolate Blue Red Bronze",
"bb Dd ee Nn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Dd ee Nn Pnpn": "Chocolate Blue Red Bronze",
"bb Dd ee Nn pnpn": "Chocolate Blue Red Bronze",
"bb Dd ee Nn Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Dd ee Nn pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Dd ee Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Dd ee pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccg Dd ee Rr": "Chocolate Blue Red Bronze",
"bb Ccg Dd ee Nn Rr": "Chocolate Blue Red Bronze",
"bb Ccg Dd ee Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccg Dd ee Pnpn Rr": "Chocolate Blue Red Bronze",
"bb Ccg Dd ee pnpn Rr": "Chocolate Blue Red Bronze",
"bb Ccg Dd ee Nn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccg Dd ee Nn Pnpn Rr": "Chocolate Blue Red Bronze",
"bb Ccg Dd ee Nn pnpn Rr": "Chocolate Blue Red Bronze",
"bb Ccg Dd ee Nn Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccg Dd ee Nn pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccg Dd ee Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccg Dd ee pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccm Dd ee Rr": "Chocolate Blue Red Bronze",
"bb Ccm Dd ee Nn Rr": "Chocolate Blue Red Bronze",
"bb Ccm Dd ee Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccm Dd ee Pnpn Rr": "Chocolate Blue Red Bronze",
"bb Ccm Dd ee pnpn Rr": "Chocolate Blue Red Bronze",
"bb Ccm Dd ee Nn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccm Dd ee Nn Pnpn Rr": "Chocolate Blue Red Bronze",
"bb Ccm Dd ee Nn pnpn Rr": "Chocolate Blue Red Bronze",
"bb Ccm Dd ee Nn Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccm Dd ee Nn pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccm Dd ee Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccm Dd ee pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Cc Dd ee Rr": "Chocolate Blue Red Bronze",
"bb Cc Dd ee Nn Rr": "Chocolate Blue Red Bronze",
"bb Cc Dd ee Rr Slsl": "Chocolate Blue Red Bronze",
"bb Cc Dd ee Pnpn Rr": "Chocolate Blue Red Bronze",
"bb Cc Dd ee pnpn Rr": "Chocolate Blue Red Bronze",
"bb Cc Dd ee Nn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Cc Dd ee Nn Pnpn Rr": "Chocolate Blue Red Bronze",
"bb Cc Dd ee Nn pnpn Rr": "Chocolate Blue Red Bronze",
"bb Cc Dd ee Nn Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Cc Dd ee Nn pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Cc Dd ee Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Cc Dd ee pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcg Dd ee Rr": "Chocolate Blue Red Bronze",
"bb cgcg Dd ee Nn Rr": "Chocolate Blue Red Bronze",
"bb cgcg Dd ee Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcg Dd ee Pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgcg Dd ee pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgcg Dd ee Nn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcg Dd ee Nn Pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgcg Dd ee Nn pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgcg Dd ee Nn Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcg Dd ee Nn pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcg Dd ee Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcg Dd ee pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcm Dd ee Rr": "Chocolate Blue Red Bronze",
"bb cgcm Dd ee Nn Rr": "Chocolate Blue Red Bronze",
"bb cgcm Dd ee Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcm Dd ee Pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgcm Dd ee pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgcm Dd ee Nn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcm Dd ee Nn Pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgcm Dd ee Nn pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgcm Dd ee Nn Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcm Dd ee Nn pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcm Dd ee Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcm Dd ee pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgc Dd ee Rr": "Chocolate Blue Red Bronze",
"bb cgc Dd ee Nn Rr": "Chocolate Blue Red Bronze",
"bb cgc Dd ee Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgc Dd ee Pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgc Dd ee pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgc Dd ee Nn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgc Dd ee Nn Pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgc Dd ee Nn pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgc Dd ee Nn Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgc Dd ee Nn pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgc Dd ee Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgc Dd ee pnpn Rr Slsl": "Chocolate Blue Red Bronze",
// bb1
"bb1 Dd ee Rr": "Chocolate Blue Red Bronze",
"bb1 Dd ee Nn Rr": "Chocolate Blue Red Bronze",
"bb1 Dd ee Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Dd ee Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Dd ee pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Dd ee Nn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Dd ee Nn Pnpn": "Chocolate Blue Red Bronze",
"bb1 Dd ee Nn pnpn": "Chocolate Blue Red Bronze",
"bb1 Dd ee Nn Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Dd ee Nn pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Dd ee Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Dd ee pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd ee Rr": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd ee Nn Rr": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd ee Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd ee Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd ee pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd ee Nn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd ee Nn Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd ee Nn pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd ee Nn Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd ee Nn pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd ee Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd ee pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd ee Rr": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd ee Nn Rr": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd ee Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd ee Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd ee pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd ee Nn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd ee Nn Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd ee Nn pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd ee Nn Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd ee Nn pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd ee Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd ee pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Cc Dd ee Rr": "Chocolate Blue Red Bronze",
"bb1 Cc Dd ee Nn Rr": "Chocolate Blue Red Bronze",
"bb1 Cc Dd ee Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Cc Dd ee Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Cc Dd ee pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Cc Dd ee Nn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Cc Dd ee Nn Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Cc Dd ee Nn pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Cc Dd ee Nn Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Cc Dd ee Nn pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Cc Dd ee Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Cc Dd ee pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd ee Rr": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd ee Nn Rr": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd ee Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd ee Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd ee pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd ee Nn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd ee Nn Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd ee Nn pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd ee Nn Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd ee Nn pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd ee Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd ee pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd ee Rr": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd ee Nn Rr": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd ee Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd ee Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd ee pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd ee Nn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd ee Nn Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd ee Nn pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd ee Nn Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd ee Nn pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd ee Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd ee pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgc Dd ee Rr": "Chocolate Blue Red Bronze",
"bb1 cgc Dd ee Nn Rr": "Chocolate Blue Red Bronze",
"bb1 cgc Dd ee Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgc Dd ee Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgc Dd ee pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgc Dd ee Nn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgc Dd ee Nn Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgc Dd ee Nn pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgc Dd ee Nn Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgc Dd ee Nn pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgc Dd ee Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgc Dd ee pnpn Rr Slsl": "Chocolate Blue Red Bronze",

// CHOCOLATE BLUE RED BRONZE FEMALES
"bb Dd e- Rr": "Chocolate Blue Red Bronze",
"bb Dd e- Rr Slsl": "Chocolate Blue Red Bronze",
"bb Dd e- Pnpn Rr": "Chocolate Blue Red Bronze",
"bb Dd e- pnpn Rr": "Chocolate Blue Red Bronze",
"bb Dd e- Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Dd e- pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccg Dd e- Rr": "Chocolate Blue Red Bronze",
"bb Ccg Dd e- Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccg Dd e- Pnpn Rr": "Chocolate Blue Red Bronze",
"bb Ccg Dd e- pnpn Rr": "Chocolate Blue Red Bronze",
"bb Ccg Dd e- Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccg Dd e- pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccm Dd e- Rr": "Chocolate Blue Red Bronze",
"bb Ccm Dd e- Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccm Dd e- Pnpn Rr": "Chocolate Blue Red Bronze",
"bb Ccm Dd e- pnpn Rr": "Chocolate Blue Red Bronze",
"bb Ccm Dd e- Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Ccm Dd e- pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Cc Dd e- Rr": "Chocolate Blue Red Bronze",
"bb Cc Dd e- Rr Slsl": "Chocolate Blue Red Bronze",
"bb Cc Dd e- Pnpn Rr": "Chocolate Blue Red Bronze",
"bb Cc Dd e- pnpn Rr": "Chocolate Blue Red Bronze",
"bb Cc Dd e- Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb Cc Dd e- pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcg Dd e- Rr": "Chocolate Blue Red Bronze",
"bb cgcg Dd e- Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcg Dd e- Pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgcg Dd e- pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgcg Dd e- Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcg Dd e- pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcm Dd e- Rr": "Chocolate Blue Red Bronze",
"bb cgcm Dd e- Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcm Dd e- Pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgcm Dd e- pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgcm Dd e- Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgcm Dd e- pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgc Dd e- Rr": "Chocolate Blue Red Bronze",
"bb cgc Dd e- Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgc Dd e- Pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgc Dd e- pnpn Rr": "Chocolate Blue Red Bronze",
"bb cgc Dd e- Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb cgc Dd e- pnpn Rr Slsl": "Chocolate Blue Red Bronze",
// bb1
"bb1 Dd e- Rr": "Chocolate Blue Red Bronze",
"bb1 Dd e- Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Dd e- Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Dd e- pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Dd e- Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Dd e- pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd e- Rr": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd e- Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd e- Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd e- pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd e- Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccg Dd e- pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd e- Rr": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd e- Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd e- Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd e- pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd e- Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Ccm Dd e- pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Cc Dd e- Rr": "Chocolate Blue Red Bronze",
"bb1 Cc Dd e- Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Cc Dd e- Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Cc Dd e- pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 Cc Dd e- Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 Cc Dd e- pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd e- Rr": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd e- Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd e- Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd e- pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd e- Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcg Dd e- pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd e- Rr": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd e- Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd e- Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd e- pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd e- Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgcm Dd e- pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgc Dd e- Rr": "Chocolate Blue Red Bronze",
"bb1 cgc Dd e- Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgc Dd e- Pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgc Dd e- pnpn Rr": "Chocolate Blue Red Bronze",
"bb1 cgc Dd e- Pnpn Rr Slsl": "Chocolate Blue Red Bronze",
"bb1 cgc Dd e- pnpn Rr Slsl": "Chocolate Blue Red Bronze",


  // CHOCOLATE CALICO
  "b1b1 cgcg ee nn Rr": "Chocolate Calico",
  "b1b1 cgcg ee nn Rr Slsl": "Chocolate Calico",
  "b1b1 cgcg e- n- Rr": "Chocolate Calico",
  "b1b1 cgcg e- n- Rr Slsl": "Chocolate Calico",
  "b1b1 cgcm ee nn Rr": "Chocolate Calico",
  "b1b1 cgcm e- n- Rr": "Chocolate Calico",
  "b1b1 cgcm e- n- Rr Slsl": "Chocolate Calico",
  "b1b1 cgc ee nn Rr": "Chocolate Calico",
  "b1b1 cgc ee nn Rr Slsl": "Chocolate Calico",
  "b1b1 cgc e- n- Rr": "Chocolate Calico",
  "b1b1 cgc e- n- Rr Slsl": "Chocolate Calico",
 // CHOCOLATE DAPPLE
"Bb cgc ee nn": "Chocolate Dapple",
"Bb cgc ee nn Slsl": "Chocolate Dapple",
"Bb cgc ee nn Pnpn": "Chocolate Dapple",
"Bb cgc ee nn pnpn": "Chocolate Dapple",
"Bb cgc ee nn Pnpn Slsl": "Chocolate Dapple",
"Bb cgc ee nn pnpn Slsl": "Chocolate Dapple",
 // CHOCOLATE DAPPLE FEMALES
"Bb cgc e- n-": "Chocolate Dapple",
"Bb cgc e- n- Slsl": "Chocolate Dapple",
"Bb cgc e- n- Pnpn": "Chocolate Dapple",
"Bb cgc e- n- pnpn": "Chocolate Dapple",
"Bb cgc e- n- Pnpn Slsl": "Chocolate Dapple",
"Bb cgc e- n- pnpn Slsl": "Chocolate Dapple",

// CHOCOLATE FALL FIRE
"b1b1 cgcg ee Rr": "Chocolate Fall Fire",
"b1b1 cgcg ee Rr Slsl": "Chocolate Fall Fire",
"b1b1 cgcg ee Nn Rr": "Chocolate Fall Fire",
"b1b1 cgcg ee Nn Rr Slsl": "Chocolate Fall Fire",
"b1b1 cgcm ee Rr": "Chocolate Fall Fire",
"b1b1 cgcm ee Rr Slsl": "Chocolate Fall Fire",
"b1b1 cgcm ee Nn Rr": "Chocolate Fall Fire",
"b1b1 cgcm ee Nn Rr Slsl": "Chocolate Fall Fire",
"b1b1 cgc ee Rr": "Chocolate Fall Fire",
"b1b1 cgc ee Rr Slsl": "Chocolate Fall Fire",
"b1b1 cgc ee Nn Rr": "Chocolate Fall Fire",
"b1b1 cgc ee Nn Rr Slsl": "Chocolate Fall Fire",
// Female
"b1b1 cgcg e- Rr": "Chocolate Fall Fire",
"b1b1 cgcg e- Rr Slsl": "Chocolate Fall Fire",
"b1b1 cgcm e- Rr": "Chocolate Fall Fire",
"b1b1 cgcm e- Rr Slsl": "Chocolate Fall Fire",
"b1b1 cgc e- Rr": "Chocolate Fall Fire",
"b1b1 cgc e- Rr Slsl": "Chocolate Fall Fire",


  // CHOCOLATE LAVENDER
    "BB DD ee": "Chocolate Lavender",
    "BB DD ee Nn": "Chocolate Lavender",
    "BB DD ee Nn Pnpn": "Chocolate Lavender",
    "BB DD ee Nn Slsl": "Chocolate Lavender",
    "BB DD ee Nn pnpn": "Chocolate Lavender",
    "BB DD ee Pnpn": "Chocolate Lavender",
    "BB DD ee Pnpn Slsl": "Chocolate Lavender",
    "BB DD ee pnpn": "Chocolate Lavender",
    "BB DD ee pnpn Slsl": "Chocolate Lavender",
    "BB Ccg DD ee": "Chocolate Lavender",
    "BB Ccg DD ee Nn": "Chocolate Lavender",
    "BB Ccg DD ee Nn Pnpn": "Chocolate Lavender",
    "BB Ccg DD ee Nn Slsl": "Chocolate Lavender",
    "BB Ccg DD ee Nn pnpn": "Chocolate Lavender",
    "BB Ccg DD ee Pnpn": "Chocolate Lavender",
    "BB Ccg DD ee Pnpn Slsl": "Chocolate Lavender",
    "BB Ccg DD ee pnpn": "Chocolate Lavender",
    "BB Ccg DD ee pnpn Slsl": "Chocolate Lavender",
    "BB Ccm DD ee": "Chocolate Lavender",
    "BB Ccm DD ee Nn": "Chocolate Lavender",
    "BB Ccm DD ee Nn Pnpn": "Chocolate Lavender",
    "BB Ccm DD ee Nn Slsl": "Chocolate Lavender",
    "BB Ccm DD ee Nn pnpn": "Chocolate Lavender",
    "BB Ccm DD ee Pnpn": "Chocolate Lavender",
    "BB Ccm DD ee Pnpn Slsl": "Chocolate Lavender",
    "BB Ccm DD ee pnpn": "Chocolate Lavender",
    "BB Ccm DD ee pnpn Slsl": "Chocolate Lavender",
    "BB Cc DD ee": "Chocolate Lavender",
    "BB Cc DD ee Nn": "Chocolate Lavender",
    "BB Cc DD ee Nn Pnpn": "Chocolate Lavender",
    "BB Cc DD ee Nn Slsl": "Chocolate Lavender",
    "BB Cc DD ee Nn pnpn": "Chocolate Lavender",
    "BB Cc DD ee Pnpn": "Chocolate Lavender",
    "BB Cc DD ee Pnpn Slsl": "Chocolate Lavender",
    "BB Cc DD ee pnpn": "Chocolate Lavender",
    "BB Cc DD ee pnpn Slsl": "Chocolate Lavender",
    "BB cgcg DD ee": "Chocolate Lavender",
    "BB cgcg DD ee Nn": "Chocolate Lavender",
    "BB cgcg DD ee Nn Pnpn": "Chocolate Lavender",
    "BB cgcg DD ee Nn Slsl": "Chocolate Lavender",
    "BB cgcg DD ee Nn pnpn": "Chocolate Lavender",
    "BB cgcg DD ee Pnpn": "Chocolate Lavender",
    "BB cgcg DD ee Pnpn Slsl": "Chocolate Lavender",
    "BB cgcg DD ee pnpn": "Chocolate Lavender",
    "BB cgcg DD ee pnpn Slsl": "Chocolate Lavender",
    "BB cgcm DD ee": "Chocolate Lavender",
    "BB cgcm DD ee Nn": "Chocolate Lavender",
    "BB cgcm DD ee Nn Pnpn": "Chocolate Lavender",
    "BB cgcm DD ee Nn Slsl": "Chocolate Lavender",
    "BB cgcm DD ee Nn pnpn": "Chocolate Lavender",
    "BB cgcm DD ee Pnpn": "Chocolate Lavender",
    "BB cgcm DD ee Pnpn Slsl": "Chocolate Lavender",
    "BB cgcm DD ee pnpn": "Chocolate Lavender",
    "BB cgcm DD ee pnpn Slsl": "Chocolate Lavender",
    "BB cgc DD ee": "Chocolate Lavender",
    "BB cgc DD ee Nn": "Chocolate Lavender",
    "BB cgc DD ee Nn Pnpn": "Chocolate Lavender",
    "BB cgc DD ee Nn Slsl": "Chocolate Lavender",
    "BB cgc DD ee Nn pnpn": "Chocolate Lavender",
    "BB cgc DD ee Pnpn": "Chocolate Lavender",
    "BB cgc DD ee Pnpn Slsl": "Chocolate Lavender",
    "BB cgc DD ee pnpn": "Chocolate Lavender",
    "BB cgc DD ee pnpn Slsl": "Chocolate Lavender",
    "BB DD e-": "Chocolate Lavender",
    "BB DD e- Slsl": "Chocolate Lavender",
    "BB DD e- Pnpn": "Chocolate Lavender",
    "BB DD e- pnpn": "Chocolate Lavender",
    "BB DD e- Pnpn Slsl": "Chocolate Lavender",
    "BB DD e- pnpn Slsl": "Chocolate Lavender",
    "BB Ccg DD e-": "Chocolate Lavender",
    "BB Ccg DD e- Slsl": "Chocolate Lavender",
    "BB Ccg DD e- Pnpn": "Chocolate Lavender",
    "BB Ccg DD e- pnpn": "Chocolate Lavender",
    "BB Ccg DD e- Pnpn Slsl": "Chocolate Lavender",
    "BB Ccg DD e- pnpn Slsl": "Chocolate Lavender",
    "BB Ccm DD e-": "Chocolate Lavender",
    "BB Ccm DD e- Slsl": "Chocolate Lavender",
    "BB Ccm DD e- Pnpn": "Chocolate Lavender",
    "BB Ccm DD e- pnpn": "Chocolate Lavender",
    "BB Ccm DD e- pnpn Slsl": "Chocolate Lavender",
    "BB Ccm DD e- Pnpn Slsl": "Chocolate Lavender",
    "BB Cc DD e-": "Chocolate Lavender",
    "BB Cc DD e- Slsl": "Chocolate Lavender",
    "BB Cc DD e- Pnpn": "Chocolate Lavender",
    "BB Cc DD e- pnpn": "Chocolate Lavender",
    "BB Cc DD e- Pnpn Slsl": "Chocolate Lavender",
    "BB Cc DD e- pnpn Slsl": "Chocolate Lavender",
    "BB cgcg DD e-": "Chocolate Lavender",
    "BB cgcg DD e- Slsl": "Chocolate Lavender",
    "BB cgcg DD e- Pnpn": "Chocolate Lavender",
    "BB cgcg DD e- pnpn": "Chocolate Lavender",
    "BB cgcg DD e- Pnpn Slsl": "Chocolate Lavender",
    "BB cgcg DD e- pnpn Slsl": "Chocolate Lavender",
    "BB cgcm DD e-": "Chocolate Lavender",
    "BB cgcm DD e- Slsl": "Chocolate Lavender",
    "BB cgcm DD e- Pnpn": "Chocolate Lavender",
    "BB cgcm DD e- pnpn": "Chocolate Lavender",
    "BB cgcm DD e- Pnpn Slsl": "Chocolate Lavender",
    "BB cgcm DD e- pnpn Slsl": "Chocolate Lavender",
    "BB cgc DD e-": "Chocolate Lavender",
    "BB cgc DD e- Slsl": "Chocolate Lavender",
    "BB cgc DD e- Pnpn": "Chocolate Lavender",
    "BB cgc DD e- pnpn": "Chocolate Lavender",
    "BB cgc DD e- Pnpn Slsl": "Chocolate Lavender",
    "BB cgc DD e- pnpn Slsl": "Chocolate Lavender",
 // CHOCOLATE PALM
"b1b1 cgcg ee nn": "Chocolate Palm",
"b1b1 cgcg ee nn Slsl": "Chocolate Palm",
"b1b1 cgcm ee nn": "Chocolate Palm",
"b1b1 cgcm ee nn Slsl": "Chocolate Palm",
"b1b1 cgc ee nn": "Chocolate Palm",
"b1b1 cgc ee nn Slsl": "Chocolate Palm",
// CP FEMALES
"b1b1 cgcg e- n-": "Chocolate Palm",
"b1b1 cgc e- n-": "Chocolate Palm",
"b1b1 cgc e- n- Slsl": "Chocolate Palm",
"b1b1 cgcg e- n- Slsl": "Chocolate Palm",
"b1b1 cgcm e- n-": "Chocolate Palm",
"b1b1 cgcm e- n- Slsl": "Chocolate Palm",
// CHOCOLATE RED SLATE
"bb Dd ee": "Chocolate Red Slate",
"bb Dd ee Nn": "Chocolate Red Slate",
"bb Dd ee Nn Slsl": "Chocolate Red Slate",
"bb Dd ee Pnpn": "Chocolate Red Slate",
"bb Dd ee Pnpn Slsl": "Chocolate Red Slate",
"bb Dd ee pnpn": "Chocolate Red Slate",
"bb Dd ee pnpn Slsl": "Chocolate Red Slate",
"bb Ccg Dd ee": "Chocolate Red Slate",
"bb Ccg Dd ee Nn": "Chocolate Red Slate",
"bb Ccg Dd ee Nn Pnpn": "Chocolate Red Slate",
"bb Ccg Dd ee Nn Slsl": "Chocolate Red Slate",
"bb Ccg Dd ee Nn pnpn": "Chocolate Red Slate",
"bb Ccg Dd ee Pnpn": "Chocolate Red Slate",
"bb Ccg Dd ee Pnpn Slsl": "Chocolate Red Slate",
"bb Ccg Dd ee pnpn": "Chocolate Red Slate",
"bb Ccg Dd ee pnpn Slsl": "Chocolate Red Slate",
"bb Ccm Dd ee": "Chocolate Red Slate",
"bb Ccm Dd ee Nn": "Chocolate Red Slate",
"bb Ccm Dd ee Nn Pnpn": "Chocolate Red Slate",
"bb Ccm Dd ee Nn Slsl": "Chocolate Red Slate",
"bb Ccm Dd ee Nn pnpn": "Chocolate Red Slate",
"bb Ccm Dd ee Pnpn": "Chocolate Red Slate",
"bb Ccm Dd ee Pnpn Slsl": "Chocolate Red Slate",
"bb Ccm Dd ee pnpn": "Chocolate Red Slate",
"bb Ccm Dd ee pnpn Slsl": "Chocolate Red Slate",
"bb Cc Dd ee": "Chocolate Red Slate",
"bb Cc Dd ee Nn": "Chocolate Red Slate",
"bb Cc Dd ee Nn Pnpn": "Chocolate Red Slate",
"bb Cc Dd ee Nn Slsl": "Chocolate Red Slate",
"bb Cc Dd ee Nn pnpn": "Chocolate Red Slate",
"bb Cc Dd ee Pnpn": "Chocolate Red Slate",
"bb Cc Dd ee Pnpn Slsl": "Chocolate Red Slate",
"bb Cc Dd ee pnpn": "Chocolate Red Slate",
"bb Cc Dd ee pnpn Slsl": "Chocolate Red Slate",
"bb cgcg Dd ee": "Chocolate Red Slate",
"bb cgcg Dd ee Nn": "Chocolate Red Slate",
"bb cgcg Dd ee Nn Pnpn": "Chocolate Red Slate",
"bb cgcg Dd ee Nn Slsl": "Chocolate Red Slate",
"bb cgcg Dd ee Nn pnpn": "Chocolate Red Slate",
"bb cgcg Dd ee Pnpn": "Chocolate Red Slate",
"bb cgcg Dd ee Pnpn Slsl": "Chocolate Red Slate",
"bb cgcg Dd ee pnpn": "Chocolate Red Slate",
"bb cgcg Dd ee pnpn Slsl": "Chocolate Red Slate",
"bb cgcm Dd ee": "Chocolate Red Slate",
"bb cgcm Dd ee Nn": "Chocolate Red Slate",
"bb cgcm Dd ee Nn Pnpn": "Chocolate Red Slate",
"bb cgcm Dd ee Nn Slsl": "Chocolate Red Slate",
"bb cgcm Dd ee Nn pnpn": "Chocolate Red Slate",
"bb cgcm Dd ee Pnpn": "Chocolate Red Slate",
"bb cgcm Dd ee Pnpn Slsl": "Chocolate Red Slate",
"bb cgcm Dd ee pnpn": "Chocolate Red Slate",
"bb cgcm Dd ee pnpn Slsl": "Chocolate Red Slate",
"bb cgc Dd ee": "Chocolate Red Slate",
"bb cgc Dd ee Nn": "Chocolate Red Slate",
"bb cgc Dd ee Nn Pnpn": "Chocolate Red Slate",
"bb cgc Dd ee Nn Slsl": "Chocolate Red Slate",
"bb cgc Dd ee Nn pnpn": "Chocolate Red Slate",
"bb cgc Dd ee Pnpn": "Chocolate Red Slate",
"bb cgc Dd ee Pnpn Slsl": "Chocolate Red Slate",
"bb cgc Dd ee pnpn": "Chocolate Red Slate",
"bb cgc Dd ee pnpn Slsl": "Chocolate Red Slate",
"bb Dd e-": "Chocolate Red Slate",
"bb Dd e- Slsl": "Chocolate Red Slate",
"bb Dd e- Pnpn": "Chocolate Red Slate",
"bb Dd e- pnpn": "Chocolate Red Slate",
"bb Dd e- Pnpn Slsl": "Chocolate Red Slate",
"bb Dd e- pnpn Slsl": "Chocolate Red Slate",
"bb Ccg Dd e-": "Chocolate Red Slate",
"bb Ccg Dd e- Slsl": "Chocolate Red Slate",
"bb Ccg Dd e- Pnpn": "Chocolate Red Slate",
"bb Ccg Dd e- pnpn": "Chocolate Red Slate",
"bb Ccg Dd e- Pnpn Slsl": "Chocolate Red Slate",
"bb Ccg Dd e- pnpn Slsl": "Chocolate Red Slate",
"bb Ccm Dd e-": "Chocolate Red Slate",
"bb Ccm Dd e- Slsl": "Chocolate Red Slate",
"bb Ccm Dd e- Pnpn": "Chocolate Red Slate",
"bb Ccm Dd e- pnpn": "Chocolate Red Slate",
"bb Ccm Dd e- pnpn Slsl": "Chocolate Red Slate",
"bb Ccm Dd e- Pnpn Slsl": "Chocolate Red Slate",
"bb Cc Dd e-": "Chocolate Red Slate",
"bb Cc Dd e- Slsl": "Chocolate Red Slate",
"bb Cc Dd e- Pnpn": "Chocolate Red Slate",
"bb Cc Dd e- pnpn": "Chocolate Red Slate",
"bb Cc Dd e- Pnpn Slsl": "Chocolate Red Slate",
"bb Cc Dd e- pnpn Slsl": "Chocolate Red Slate",
"bb cgcg Dd e-": "Chocolate Red Slate",
"bb cgcg Dd e- Slsl": "Chocolate Red Slate",
"bb cgcg Dd e- Pnpn": "Chocolate Red Slate",
"bb cgcg Dd e- pnpn": "Chocolate Red Slate",
"bb cgcg Dd e- Pnpn Slsl": "Chocolate Red Slate",
"bb cgcg Dd e- pnpn Slsl": "Chocolate Red Slate",
"bb cgcm Dd e-": "Chocolate Red Slate",
"bb cgcm Dd e- Slsl": "Chocolate Red Slate",
"bb cgcm Dd e- Pnpn": "Chocolate Red Slate",
"bb cgcm Dd e- pnpn": "Chocolate Red Slate",
"bb cgcm Dd e- Pnpn Slsl": "Chocolate Red Slate",
"bb cgcm Dd e- pnpn Slsl": "Chocolate Red Slate",
"bb cgc Dd e-": "Chocolate Red Slate",
"bb cgc Dd e- Slsl": "Chocolate Red Slate",
"bb cgc Dd e- Pnpn": "Chocolate Red Slate",
"bb cgc Dd e- pnpn": "Chocolate Red Slate",
"bb cgc Dd e- Pnpn Slsl": "Chocolate Red Slate",
"bb cgc Dd e- pnpn Slsl": "Chocolate Red Slate",

// bb1
"bb1 Dd ee": "Chocolate Red Slate",
"bb1 Dd ee Nn": "Chocolate Red Slate",
"bb1 Dd ee Slsl": "Chocolate Red Slate",
"bb1 Dd ee Pnpn": "Chocolate Red Slate",
"bb1 Dd ee pnpn": "Chocolate Red Slate",
"bb1 Dd ee Nn Slsl": "Chocolate Red Slate",
"bb1 Dd ee Nn Pnpn Slsl": "Chocolate Red Slate",
"bb1 Dd ee Nn pnpn Slsl": "Chocolate Red Slate",
"bb1 Dd ee Pnpn Slsl": "Chocolate Red Slate",
"bb1 Dd ee pnpn Slsl": "Chocolate Red Slate",
"bb1 Ccg Dd ee": "Chocolate Red Slate",
"bb1 Ccg Dd ee Nn": "Chocolate Red Slate",
"bb1 Ccg Dd ee Slsl": "Chocolate Red Slate",
"bb1 Ccg Dd ee Pnpn": "Chocolate Red Slate",
"bb1 Ccg Dd ee pnpn": "Chocolate Red Slate",
"bb1 Ccg Dd ee Nn Slsl": "Chocolate Red Slate",
"bb1 Ccg Dd ee Nn Pnpn": "Chocolate Red Slate",
"bb1 Ccg Dd ee Nn pnpn": "Chocolate Red Slate",
"bb1 Ccg Dd ee Nn Pnpn Slsl": "Chocolate Red Slate",
"bb1 Ccg Dd ee Nn pnpn Slsl": "Chocolate Red Slate",
"bb1 Ccg Dd ee Pnpn Slsl": "Chocolate Red Slate",
"bb1 Ccg Dd ee pnpn Slsl": "Chocolate Red Slate",
"bb1 Ccm Dd ee": "Chocolate Red Slate",
"bb1 Ccm Dd ee Nn": "Chocolate Red Slate",
"bb1 Ccm Dd ee Slsl": "Chocolate Red Slate",
"bb1 Ccm Dd ee Pnpn": "Chocolate Red Slate",
"bb1 Ccm Dd ee pnpn": "Chocolate Red Slate",
"bb1 Ccm Dd ee Nn Slsl": "Chocolate Red Slate",
"bb1 Ccm Dd ee Nn Pnpn": "Chocolate Red Slate",
"bb1 Ccm Dd ee Nn pnpn": "Chocolate Red Slate",
"bb1 Ccm Dd ee Nn Pnpn Slsl": "Chocolate Red Slate",
"bb1 Ccm Dd ee Nn pnpn Slsl": "Chocolate Red Slate",
"bb1 Ccm Dd ee Pnpn Slsl": "Chocolate Red Slate",
"bb1 Ccm Dd ee pnpn Slsl": "Chocolate Red Slate",
"bb1 Cc Dd ee": "Chocolate Red Slate",
"bb1 Cc Dd ee Nn": "Chocolate Red Slate",
"bb1 Cc Dd ee Slsl": "Chocolate Red Slate",
"bb1 Cc Dd ee Pnpn": "Chocolate Red Slate",
"bb1 Cc Dd ee pnpn": "Chocolate Red Slate",
"bb1 Cc Dd ee Nn Slsl": "Chocolate Red Slate",
"bb1 Cc Dd ee Nn Pnpn": "Chocolate Red Slate",
"bb1 Cc Dd ee Nn pnpn": "Chocolate Red Slate",
"bb1 Cc Dd ee Nn Pnpn Slsl": "Chocolate Red Slate",
"bb1 Cc Dd ee Nn pnpn Slsl": "Chocolate Red Slate",
"bb1 Cc Dd ee Pnpn Slsl": "Chocolate Red Slate",
"bb1 Cc Dd ee pnpn Slsl": "Chocolate Red Slate",
"bb1 cgcg Dd ee": "Chocolate Red Slate",
"bb1 cgcg Dd ee Nn": "Chocolate Red Slate",
"bb1 cgcg Dd ee Slsl": "Chocolate Red Slate",
"bb1 cgcg Dd ee Pnpn": "Chocolate Red Slate",
"bb1 cgcg Dd ee pnpn": "Chocolate Red Slate",
"bb1 cgcg Dd ee Nn Slsl": "Chocolate Red Slate",
"bb1 cgcg Dd ee Nn Pnpn": "Chocolate Red Slate",
"bb1 cgcg Dd ee Nn pnpn": "Chocolate Red Slate",
"bb1 cgcg Dd ee Nn Pnpn Slsl": "Chocolate Red Slate",
"bb1 cgcg Dd ee Nn pnpn Slsl": "Chocolate Red Slate",
"bb1 cgcg Dd ee Pnpn Slsl": "Chocolate Red Slate",
"bb1 cgcg Dd ee pnpn Slsl": "Chocolate Red Slate",
"bb1 cgcm Dd ee": "Chocolate Red Slate",
"bb1 cgcm Dd ee Nn": "Chocolate Red Slate",
"bb1 cgcm Dd ee Slsl": "Chocolate Red Slate",
"bb1 cgcm Dd ee Pnpn": "Chocolate Red Slate",
"bb1 cgcm Dd ee pnpn": "Chocolate Red Slate",
"bb1 cgcm Dd ee Nn Slsl": "Chocolate Red Slate",
"bb1 cgcm Dd ee Nn Pnpn": "Chocolate Red Slate",
"bb1 cgcm Dd ee Nn pnpn": "Chocolate Red Slate",
"bb1 cgcm Dd ee Nn Pnpn Slsl": "Chocolate Red Slate",
"bb1 cgcm Dd ee Nn pnpn Slsl": "Chocolate Red Slate",
"bb1 cgcm Dd ee Pnpn Slsl": "Chocolate Red Slate",
"bb1 cgcm Dd ee pnpn Slsl": "Chocolate Red Slate",
"bb1 cgc Dd ee": "Chocolate Red Slate",
"bb1 cgc Dd ee Nn": "Chocolate Red Slate",
"bb1 cgc Dd ee Slsl": "Chocolate Red Slate",
"bb1 cgc Dd ee Pnpn": "Chocolate Red Slate",
"bb1 cgc Dd ee pnpn": "Chocolate Red Slate",
"bb1 cgc Dd ee Nn Slsl": "Chocolate Red Slate",
"bb1 cgc Dd ee Nn Pnpn": "Chocolate Red Slate",
"bb1 cgc Dd ee Nn pnpn": "Chocolate Red Slate",
"bb1 cgc Dd ee Nn Pnpn Slsl": "Chocolate Red Slate",
"bb1 cgc Dd ee Nn pnpn Slsl": "Chocolate Red Slate",
"bb1 cgc Dd ee Pnpn Slsl": "Chocolate Red Slate",
"bb1 cgc Dd ee pnpn Slsl": "Chocolate Red Slate",

// bb1
"bb1 Dd e-": "Chocolate Red Slate",
"bb1 Dd e- Slsl": "Chocolate Red Slate",
"bb1 Dd e- Pnpn": "Chocolate Red Slate",
"bb1 Dd e- pnpn": "Chocolate Red Slate",
"bb1 Dd e- Pnpn Slsl": "Chocolate Red Slate",
"bb1 Dd e- pnpn Slsl": "Chocolate Red Slate",
"bb1 Ccg Dd e-": "Chocolate Red Slate",
"bb1 Ccg Dd e- Slsl": "Chocolate Red Slate",
"bb1 Ccg Dd e- Pnpn": "Chocolate Red Slate",
"bb1 Ccg Dd e- pnpn": "Chocolate Red Slate",
"bb1 Ccg Dd e- Pnpn Slsl": "Chocolate Red Slate",
"bb1 Ccg Dd e- pnpn Slsl": "Chocolate Red Slate",
"bb1 Ccm Dd e-": "Chocolate Red Slate",
"bb1 Ccm Dd e- Slsl": "Chocolate Red Slate",
"bb1 Ccm Dd e- Pnpn": "Chocolate Red Slate",
"bb1 Ccm Dd e- pnpn": "Chocolate Red Slate",
"bb1 Ccm Dd e- Pnpn Slsl": "Chocolate Red Slate",
"bb1 Ccm Dd e- pnpn Slsl": "Chocolate Red Slate",
"bb1 Cc Dd e-": "Chocolate Red Slate",
"bb1 Cc Dd e- Slsl": "Chocolate Red Slate",
"bb1 Cc Dd e- Pnpn": "Chocolate Red Slate",
"bb1 Cc Dd e- pnpn": "Chocolate Red Slate",
"bb1 Cc Dd e- Pnpn Slsl": "Chocolate Red Slate",
"bb1 Cc Dd e- pnpn Slsl": "Chocolate Red Slate",
"bb1 cgcg Dd e-": "Chocolate Red Slate",
"bb1 cgcg Dd e- Slsl": "Chocolate Red Slate",
"bb1 cgcg Dd e- Pnpn": "Chocolate Red Slate",
"bb1 cgcg Dd e- pnpn": "Chocolate Red Slate",
"bb1 cgcg Dd e- Pnpn Slsl": "Chocolate Red Slate",
"bb1 cgcg Dd e- pnpn Slsl": "Chocolate Red Slate",
"bb1 cgcm Dd e-": "Chocolate Red Slate",
"bb1 cgcm Dd e- Slsl": "Chocolate Red Slate",
"bb1 cgcm Dd e- Pnpn": "Chocolate Red Slate",
"bb1 cgcm Dd e- pnpn": "Chocolate Red Slate",
"bb1 cgcm Dd e- Pnpn Slsl": "Chocolate Red Slate",
"bb1 cgcm Dd e- pnpn Slsl": "Chocolate Red Slate",
"bb1 cgc Dd e-": "Chocolate Red Slate",
"bb1 cgc Dd e- Slsl": "Chocolate Red Slate",
"bb1 cgc Dd e- Pnpn": "Chocolate Red Slate",
"bb1 cgc Dd e- pnpn": "Chocolate Red Slate",
"bb1 cgc Dd e- Pnpn Slsl": "Chocolate Red Slate",
"bb1 cgc Dd e- pnpn Slsl": "Chocolate Red Slate",


    // CHOCOLATE SLATE
    "BB Dd ee": "Chocolate Slate",
    "BB Dd ee Nn": "Chocolate Slate",
    "BB Dd ee Nn Pnpn": "Chocolate Slate",
    "BB Dd ee Nn Slsl": "Chocolate Slate",
    "BB Dd ee Nn pnpn": "Chocolate Slate",
    "BB Dd ee Pnpn": "Chocolate Slate",
    "BB Dd ee Pnpn Slsl": "Chocolate Slate",
    "BB Dd ee pnpn": "Chocolate Slate",
    "BB Dd ee pnpn Slsl": "Chocolate Slate",
    "BB Ccg Dd ee": "Chocolate Slate",
    "BB Ccg Dd ee Nn": "Chocolate Slate",
    "BB Ccg Dd ee Nn Pnpn": "Chocolate Slate",
    "BB Ccg Dd ee Nn Slsl": "Chocolate Slate",
    "BB Ccg Dd ee Nn pnpn": "Chocolate Slate",
    "BB Ccg Dd ee Pnpn": "Chocolate Slate",
    "BB Ccg Dd ee Pnpn Slsl": "Chocolate Slate",
    "BB Ccg Dd ee pnpn": "Chocolate Slate",
    "BB Ccg Dd ee pnpn Slsl": "Chocolate Slate",
    "BB Ccm Dd ee": "Chocolate Slate",
    "BB Ccm Dd ee Nn": "Chocolate Slate",
    "BB Ccm Dd ee Nn Pnpn": "Chocolate Slate",
    "BB Ccm Dd ee Nn Slsl": "Chocolate Slate",
    "BB Ccm Dd ee Nn pnpn": "Chocolate Slate",
    "BB Ccm Dd ee Pnpn": "Chocolate Slate",
    "BB Ccm Dd ee Pnpn Slsl": "Chocolate Slate",
    "BB Ccm Dd ee pnpn": "Chocolate Slate",
    "BB Ccm Dd ee pnpn Slsl": "Chocolate Slate",
    "BB Cc Dd ee": "Chocolate Slate",
    "BB Cc Dd ee Nn": "Chocolate Slate",
    "BB Cc Dd ee Nn Pnpn": "Chocolate Slate",
    "BB Cc Dd ee Nn Slsl": "Chocolate Slate",
    "BB Cc Dd ee Nn pnpn": "Chocolate Slate",
    "BB Cc Dd ee Pnpn": "Chocolate Slate",
    "BB Cc Dd ee Pnpn Slsl": "Chocolate Slate",
    "BB Cc Dd ee pnpn": "Chocolate Slate",
    "BB Cc Dd ee pnpn Slsl": "Chocolate Slate",
    "BB cgcg Dd ee": "Chocolate Slate",
    "BB cgcg Dd ee Nn": "Chocolate Slate",
    "BB cgcg Dd ee Nn Pnpn": "Chocolate Slate",
    "BB cgcg Dd ee Nn Slsl": "Chocolate Slate",
    "BB cgcg Dd ee Nn pnpn": "Chocolate Slate",
    "BB cgcg Dd ee Pnpn": "Chocolate Slate",
    "BB cgcg Dd ee Pnpn Slsl": "Chocolate Slate",
    "BB cgcg Dd ee pnpn": "Chocolate Slate",
    "BB cgcg Dd ee pnpn Slsl": "Chocolate Slate",
    "BB cgcm Dd ee": "Chocolate Slate",
    "BB cgcm Dd ee Nn": "Chocolate Slate",
    "BB cgcm Dd ee Nn Pnpn": "Chocolate Slate",
    "BB cgcm Dd ee Nn Slsl": "Chocolate Slate",
    "BB cgcm Dd ee Nn pnpn": "Chocolate Slate",
    "BB cgcm Dd ee Pnpn": "Chocolate Slate",
    "BB cgcm Dd ee Pnpn Slsl": "Chocolate Slate",
    "BB cgcm Dd ee pnpn": "Chocolate Slate",
    "BB cgcm Dd ee pnpn Slsl": "Chocolate Slate",
    "BB cgc Dd ee": "Chocolate Slate",
    "BB cgc Dd ee Nn": "Chocolate Slate",
    "BB cgc Dd ee Nn Pnpn": "Chocolate Slate",
    "BB cgc Dd ee Nn Slsl": "Chocolate Slate",
    "BB cgc Dd ee Nn pnpn": "Chocolate Slate",
    "BB cgc Dd ee Pnpn": "Chocolate Slate",
    "BB cgc Dd ee Pnpn Slsl": "Chocolate Slate",
    "BB cgc Dd ee pnpn": "Chocolate Slate",
    "BB cgc Dd ee pnpn Slsl": "Chocolate Slate",
    "BB Dd e-": "Chocolate Slate",
    "BB Dd e- Slsl": "Chocolate Slate",
    "BB Dd e- Pnpn": "Chocolate Slate",
    "BB Dd e- pnpn": "Chocolate Slate",
    "BB Dd e- Pnpn Slsl": "Chocolate Slate",
    "BB Dd e- pnpn Slsl": "Chocolate Slate",
    "BB Ccg Dd e-": "Chocolate Slate",
    "BB Ccg Dd e- Slsl": "Chocolate Slate",
    "BB Ccg Dd e- Pnpn": "Chocolate Slate",
    "BB Ccg Dd e- pnpn": "Chocolate Slate",
    "BB Ccg Dd e- Pnpn Slsl": "Chocolate Slate",
    "BB Ccg Dd e- pnpn Slsl": "Chocolate Slate",
    "BB Ccm Dd e-": "Chocolate Slate",
    "BB Ccm Dd e- Slsl": "Chocolate Slate",
    "BB Ccm Dd e- Pnpn": "Chocolate Slate",
    "BB Ccm Dd e- pnpn": "Chocolate Slate",
    "BB Ccm Dd e- pnpn Slsl": "Chocolate Slate",
    "BB Ccm Dd e- Pnpn Slsl": "Chocolate Slate",
    "BB Cc Dd e-": "Chocolate Slate",
    "BB Cc Dd e- Slsl": "Chocolate Slate",
    "BB Cc Dd e- Pnpn": "Chocolate Slate",
    "BB Cc Dd e- pnpn": "Chocolate Slate",
    "BB Cc Dd e- Pnpn Slsl": "Chocolate Slate",
    "BB Cc Dd e- pnpn Slsl": "Chocolate Slate",
    "BB cgcg Dd e-": "Chocolate Slate",
    "BB cgcg Dd e- Slsl": "Chocolate Slate",
    "BB cgcg Dd e- Pnpn": "Chocolate Slate",
    "BB cgcg Dd e- pnpn": "Chocolate Slate",
    "BB cgcg Dd e- Pnpn Slsl": "Chocolate Slate",
    "BB cgcg Dd e- pnpn Slsl": "Chocolate Slate",
    "BB cgcm Dd e-": "Chocolate Slate",
    "BB cgcm Dd e- Slsl": "Chocolate Slate",
    "BB cgcm Dd e- Pnpn": "Chocolate Slate",
    "BB cgcm Dd e- pnpn": "Chocolate Slate",
    "BB cgcm Dd e- Pnpn Slsl": "Chocolate Slate",
    "BB cgcm Dd e- pnpn Slsl": "Chocolate Slate",
    "BB cgc Dd e-": "Chocolate Slate",
    "BB cgc Dd e- Slsl": "Chocolate Slate",
    "BB cgc Dd e- Pnpn": "Chocolate Slate",
    "BB cgc Dd e- pnpn": "Chocolate Slate",
    "BB cgc Dd e- Pnpn Slsl": "Chocolate Slate",
    "BB cgc Dd e- pnpn Slsl": "Chocolate Slate",
    
    // CHOCOLATE SLATE SWEETGRASS
"b1b1 cgcg Dd ee": "Chocolate Slate Sweetgrass",
"b1b1 cgcg Dd ee Nn": "Chocolate Slate Sweetgrass",
"b1b1 cgcg Dd ee Slsl": "Chocolate Slate Sweetgrass",
"b1b1 cgcg Dd ee Nn Slsl": "Chocolate Slate Sweetgrass",

"b1b1 cgcm Dd ee": "Chocolate Slate Sweetgrass",
"b1b1 cgcm Dd ee Nn": "Chocolate Slate Sweetgrass",
"b1b1 cgcm Dd ee Slsl": "Chocolate Slate Sweetgrass",
"b1b1 cgcm Dd ee Nn Slsl": "Chocolate Slate Sweetgrass",

"b1b1 cgc Dd ee": "Chocolate Slate Sweetgrass",
"b1b1 cgc Dd ee Nn": "Chocolate Slate Sweetgrass",
"b1b1 cgc Dd ee Slsl": "Chocolate Slate Sweetgrass",
"b1b1 cgc Dd ee Nn Slsl": "Chocolate Slate Sweetgrass",

"b1b1 cgcg Dd e-": "Chocolate Slate Sweetgrass",
"b1b1 cgcg Dd e- Slsl": "Chocolate Slate Sweetgrass",

"b1b1 cgcm Dd e-": "Chocolate Slate Sweetgrass",
"b1b1 cgcm Dd e- Slsl": "Chocolate Slate Sweetgrass",

"b1b1 cgc Dd e-": "Chocolate Slate Sweetgrass",
"b1b1 cgc Dd e- Slsl": "Chocolate Slate Sweetgrass",

    
 // CHOCOLATE SWEETGRASS
"b1b1 cgcg ee": "Chocolate Sweetgrass",
"b1b1 cgcg ee Nn": "Chocolate Sweetgrass",
"b1b1 cgcg ee Slsl": "Chocolate Sweetgrass",
"b1b1 cgcg ee Nn Slsl": "Chocolate Sweetgrass",
"b1b1 cgcm ee": "Chocolate Sweetgrass",
"b1b1 cgcm ee Nn": "Chocolate Sweetgrass",
"b1b1 cgcm ee Slsl": "Chocolate Sweetgrass",
"b1b1 cgcm ee Nn Slsl": "Chocolate Sweetgrass",
"b1b1 cgc ee": "Chocolate Sweetgrass",
"b1b1 cgc ee Nn": "Chocolate Sweetgrass",
"b1b1 cgc ee Slsl": "Chocolate Sweetgrass",
"b1b1 cgc ee Nn Slsl": "Chocolate Sweetgrass",
"b1b1 cgcg e-": "Chocolate Sweetgrass",
"b1b1 cgcg e- Slsl": "Chocolate Sweetgrass",
"b1b1 cgcm e-": "Chocolate Sweetgrass",
"b1b1 cgcm e- Slsl": "Chocolate Sweetgrass",
"b1b1 cgc e-": "Chocolate Sweetgrass",
"b1b1 cgc e- Slsl": "Chocolate Sweetgrass",
 // CORNISH PALM
"b1b1 Ccg": "Cornish Palm",
"b1b1 Ccg Ee": "Cornish Palm",
"b1b1 Ccg Ee Nn": "Cornish Palm",
"b1b1 Ccg Nn": "Cornish Palm",
"b1b1 Ccg Ee Slsl": "Cornish Palm",
"b1b1 Ccg Nn Slsl": "Cornish Palm",
"b1b1 Ccg Ee Nn Slsl": "Cornish Palm",
"b1b1 Ccg Slsl": "Cornish Palm",
// DARK BLUE
"bb cgcg Dd nn": "Dark Blue",
"bb cgcg Dd Ee nn": "Dark Blue",
"bb cgcg Dd nn Slsl": "Dark Blue",
"bb cgcg Dd nn Pnpn": "Dark Blue",
"bb cgcg Dd nn pnpn": "Dark Blue",
"bb cgcg Dd Ee nn Slsl": "Dark Blue",
"bb cgcg Dd Ee nn Pnpn": "Dark Blue",
"bb cgcg Dd Ee nn pnpn": "Dark Blue",
"bb cgcg Dd nn Pnpn Slsl": "Dark Blue",
"bb cgcg Dd nn pnpn Slsl": "Dark Blue",
"bb cgcg Dd Ee nn Pnpn Slsl": "Dark Blue",
"bb cgcg Dd Ee nn pnpn Slsl": "Dark Blue",
"bb cgcm Dd nn": "Dark Blue",
"bb cgcm Dd Ee nn": "Dark Blue",
"bb cgcm Dd nn Slsl": "Dark Blue",
"bb cgcm Dd nn Pnpn": "Dark Blue",
"bb cgcm Dd nn pnpn": "Dark Blue",
"bb cgcm Dd Ee nn Slsl": "Dark Blue",
"bb cgcm Dd Ee nn Pnpn": "Dark Blue",
"bb cgcm Dd Ee nn pnpn": "Dark Blue",
"bb cgcm Dd Ee nn Pnpn Slsl": "Dark Blue",
"bb cgcm Dd Ee nn pnpn Slsl": "Dark Blue",
"bb cgcm Dd nn Pnpn Slsl": "Dark Blue",
"bb cgcm Dd nn pnpn Slsl": "Dark Blue",
  // bb1 DARK BLUE
  "bb1 cgcg Dd nn": "Dark Blue.",
  "bb1 cgcg Dd Ee nn": "Dark Blue.",
  "bb1 cgcg Dd nn Slsl": "Dark Blue.",
  "bb1 cgcg Dd nn Pnpn": "Dark Blue.",
  "bb1 cgcg Dd nn pnpn": "Dark Blue.",
  "bb1 cgcg Dd Ee nn Slsl": "Dark Blue.",
  "bb1 cgcg Dd Ee nn Pnpn": "Dark Blue.",
  "bb1 cgcg Dd Ee nn pnpn": "Dark Blue.",
  "bb1 cgcg Dd nn Pnpn Slsl": "Dark Blue.",
  "bb1 cgcg Dd nn pnpn Slsl": "Dark Blue.",
  "bb1 cgcg Dd Ee nn Pnpn Slsl": "Dark Blue.",
  "bb1 cgcg Dd Ee nn pnpn Slsl": "Dark Blue.",
  "bb1 cgcm Dd nn": "Dark Blue.",
  "bb1 cgcm Dd Ee nn": "Dark Blue.",
  "bb1 cgcm Dd nn Slsl": "Dark Blue.",
  "bb1 cgcm Dd nn Pnpn": "Dark Blue.",
  "bb1 cgcm Dd nn pnpn": "Dark Blue.",
  "bb1 cgcm Dd Ee nn Slsl": "Dark Blue.",
  "bb1 cgcm Dd Ee nn Pnpn": "Dark Blue.",
  "bb1 cgcm Dd Ee nn pnpn": "Dark Blue.",
  "bb1 cgcm Dd Ee nn Pnpn Slsl": "Dark Blue.",
  "bb1 cgcm Dd Ee nn pnpn Slsl": "Dark Blue.",
  "bb1 cgcm Dd nn Pnpn Slsl": "Dark Blue.",
  "bb1 cgcm Dd nn pnpn Slsl": "Dark Blue.",
 // bb DARK BLUE FEMALES
"bb cgcg Dd n-": "Dark Blue",
"bb cgcg Dd n- Slsl": "Dark Blue",
"bb cgcg Dd n- Pnpn": "Dark Blue",
"bb cgcg Dd n- pnpn": "Dark Blue",
"bb cgcg Dd n- Pnpn Slsl": "Dark Blue",
"bb cgcg Dd n- pnpn Slsl": "Dark Blue",
"bb cgcm Dd n-": "Dark Blue",
"bb cgcm Dd n- Slsl": "Dark Blue",
"bb cgcm Dd n- Pnpn": "Dark Blue",
"bb cgcm Dd n- pnpn": "Dark Blue",
"bb cgcm Dd n- Pnpn Slsl": "Dark Blue",
"bb cgcm Dd n- pnpn Slsl": "Dark Blue",
 // bb1 DARK BLUE FEMALES
"bb1 cgcg Dd n-": "Dark Blue.",
"bb1 cgcg Dd n- Slsl": "Dark Blue.",
"bb1 cgcg Dd n- Pnpn": "Dark Blue.",
"bb1 cgcg Dd n- pnpn": "Dark Blue.",
"bb1 cgcg Dd n- Pnpn Slsl": "Dark Blue.",
"bb1 cgcg Dd n- pnpn Slsl": "Dark Blue.",
"bb1 cgcm Dd n-": "Dark Blue.",
"bb1 cgcm Dd n- Slsl": "Dark Blue.",
"bb1 cgcm Dd n- Pnpn": "Dark Blue.",
"bb1 cgcm Dd n- pnpn": "Dark Blue.",
"bb1 cgcm Dd n- Pnpn Slsl": "Dark Blue.",
"bb1 cgcm Dd n- pnpn Slsl": "Dark Blue.",
 // DARK BROWN
"bb cgcg ee nn": "Dark Brown",
"bb cgcg ee nn Slsl": "Dark Brown",
"bb cgcg ee nn Pnpn": "Dark Brown",
"bb cgcg ee nn pnpn": "Dark Brown",
"bb cgcg ee nn Pnpn Slsl": "Dark Brown",
"bb cgcg ee nn pnpn Slsl": "Dark Brown",
"bb cgcm ee nn": "Dark Brown",
"bb cgcm ee nn Slsl": "Dark Brown",
"bb cgcm ee nn Pnpn": "Dark Brown",
"bb cgcm ee nn pnpn": "Dark Brown",
"bb cgcm ee nn Pnpn Slsl": "Dark Brown",
"bb cgcm ee nn pnpn Slsl": "Dark Brown",
"bb1 cgcg ee nn": "Dark Brown",
"bb1 cgcg ee nn Slsl": "Dark Brown",
"bb1 cgcg ee nn Pnpn": "Dark Brown",
"bb1 cgcg ee nn pnpn": "Dark Brown",
"bb1 cgcg ee nn Pnpn Slsl": "Dark Brown",
"bb1 cgcg ee nn pnpn Slsl": "Dark Brown",
"bb1 cgcm ee nn": "Dark Brown",
"bb1 cgcm ee nn Slsl": "Dark Brown",
"bb1 cgcm ee nn Pnpn": "Dark Brown",
"bb1 cgcm ee nn pnpn": "Dark Brown",
"bb1 cgcm ee nn Pnpn Slsl": "Dark Brown",
"bb1 cgcm ee nn pnpn Slsl": "Dark Brown",
 // DARK BROWN FEMALES
"bb cgcg e- n-": "Dark Brown",
"bb cgcg e- n- Slsl": "Dark Brown",
"bb cgcg e- n- Pnpn": "Dark Brown",
"bb cgcg e- n- pnpn": "Dark Brown",
"bb cgcg e- n- Pnpn Slsl": "Dark Brown",
"bb cgcg e- n- pnpn Slsl": "Dark Brown",
"bb cgcm e- n-": "Dark Brown",
"bb cgcm e- n- Slsl": "Dark Brown",
"bb cgcm e- n- Pnpn": "Dark Brown",
"bb cgcm e- n- pnpn": "Dark Brown",
"bb cgcm e- n- Pnpn Slsl": "Dark Brown",
"bb cgcm e- n- pnpn Slsl": "Dark Brown",
"bb1 cgcg e- n-": "Dark Brown",
"bb1 cgcg e- n- Slsl": "Dark Brown",
"bb1 cgcg e- n- Pnpn": "Dark Brown",
"bb1 cgcg e- n- pnpn": "Dark Brown",
"bb1 cgcg e- n- Pnpn Slsl": "Dark Brown",
"bb1 cgcg e- n- pnpn Slsl": "Dark Brown",
"bb1 cgcm e- n-": "Dark Brown",
"bb1 cgcm e- n- Slsl": "Dark Brown",
"bb1 cgcm e- n- Pnpn": "Dark Brown",
"bb1 cgcm e- n- pnpn": "Dark Brown",
"bb1 cgcm e- n- Pnpn Slsl": "Dark Brown",
"bb1 cgcm e- n- pnpn Slsl": "Dark Brown",
 // bb DARK GRAY
"bb cgcg nn": "Dark Gray",
"bb cgcg Ee nn": "Dark Gray",
"bb cgcg nn Slsl": "Dark Gray",
"bb cgcg nn Pnpn": "Dark Gray",
"bb cgcg nn pnpn": "Dark Gray",
"bb cgcg Ee nn Slsl": "Dark Gray",
"bb cgcg Ee nn Pnpn": "Dark Gray",
"bb cgcg Ee nn pnpn": "Dark Gray",
"bb cgcg nn Pnpn Slsl": "Dark Gray",
"bb cgcg nn pnpn Slsl": "Dark Gray",
"bb cgcg Ee nn Pnpn Slsl": "Dark Gray",
"bb cgcg Ee nn pnpn Slsl": "Dark Gray",
"bb cgcm nn": "Dark Gray",
"bb cgcm Ee nn": "Dark Gray",
"bb cgcm nn Slsl": "Dark Gray",
"bb cgcm nn Pnpn": "Dark Gray",
"bb cgcm nn pnpn": "Dark Gray",
"bb cgcm Ee nn Slsl": "Dark Gray",
"bb cgcm Ee nn Pnpn": "Dark Gray",
"bb cgcm Ee nn pnpn": "Dark Gray",
"bb cgcm Ee nn Pnpn Slsl": "Dark Gray",
"bb cgcm Ee nn pnpn Slsl": "Dark Gray",
"bb cgcm nn Pnpn Slsl": "Dark Gray",
"bb cgcm nn pnpn Slsl": "Dark Gray",
 // bb1 DARK GRAY
"bb1 cgcg nn": "Dark Gray",
"bb1 cgcg Ee nn": "Dark Gray",
"bb1 cgcg nn Slsl": "Dark Gray",
"bb1 cgcg nn Pnpn": "Dark Gray",
"bb1 cgcg nn pnpn": "Dark Gray",
"bb1 cgcg Ee nn Slsl": "Dark Gray",
"bb1 cgcg Ee nn Pnpn": "Dark Gray",
"bb1 cgcg Ee nn pnpn": "Dark Gray",
"bb1 cgcg nn Pnpn Slsl": "Dark Gray",
"bb1 cgcg nn pnpn Slsl": "Dark Gray",
"bb1 cgcg Ee nn Pnpn Slsl": "Dark Gray",
"bb1 cgcg Ee nn pnpn Slsl": "Dark Gray",
"bb1 cgcm nn": "Dark Gray",
"bb1 cgcm Ee nn": "Dark Gray",
"bb1 cgcm nn Slsl": "Dark Gray",
"bb1 cgcm nn Pnpn": "Dark Gray",
"bb1 cgcm nn pnpn": "Dark Gray",
"bb1 cgcm Ee nn Slsl": "Dark Gray",
"bb1 cgcm Ee nn Pnpn": "Dark Gray",
"bb1 cgcm Ee nn pnpn": "Dark Gray",
"bb1 cgcm Ee nn Pnpn Slsl": "Dark Gray",
"bb1 cgcm Ee nn pnpn Slsl": "Dark Gray",
"bb1 cgcm nn Pnpn Slsl": "Dark Gray",
"bb1 cgcm nn pnpn Slsl": "Dark Gray",
 // DARK GRAY FEMALES
"bb cgcg n-": "Dark Gray",
"bb cgcg n- Slsl": "Dark Gray",
"bb cgcg n- Pnpn": "Dark Gray",
"bb cgcg n- pnpn": "Dark Gray",
"bb cgcg n- Pnpn Slsl": "Dark Gray",
"bb cgcg n- pnpn Slsl": "Dark Gray",
"bb cgcm n-": "Dark Gray",
"bb cgcm n- Slsl": "Dark Gray",
"bb cgcm n- Pnpn": "Dark Gray",
"bb cgcm n- pnpn": "Dark Gray",
"bb cgcm n- Pnpn Slsl": "Dark Gray",
"bb cgcm n- pnpn Slsl": "Dark Gray",
"bb1 cgcg n-": "Dark Gray",
"bb1 cgcg n- Slsl": "Dark Gray",
"bb1 cgcg n- Pnpn": "Dark Gray",
"bb1 cgcg n- pnpn": "Dark Gray",
"bb1 cgcg n- Pnpn Slsl": "Dark Gray",
"bb1 cgcg n- pnpn Slsl": "Dark Gray",
"bb1 cgcm n-": "Dark Gray",
"bb1 cgcm n- Slsl": "Dark Gray",
"bb1 cgcm n- Pnpn": "Dark Gray",
"bb1 cgcm n- pnpn": "Dark Gray",
"bb1 cgcm n- Pnpn Slsl": "Dark Gray",
"bb1 cgcm n- pnpn Slsl": "Dark Gray",
// DARK LAVENDER BLUE
"bb cgcg DD nn": "Dark Lavender Blue",
"bb cgcg DD Ee nn": "Dark Lavender Blue",
"bb cgcg DD nn Slsl": "Dark Lavender Blue",
"bb cgcg DD nn Pnpn": "Dark Lavender Blue",
"bb cgcg DD nn pnpn": "Dark Lavender Blue",
"bb cgcg DD Ee nn Slsl": "Dark Lavender Blue",
"bb cgcg DD Ee nn Pnpn": "Dark Lavender Blue",
"bb cgcg DD Ee nn pnpn": "Dark Lavender Blue",
"bb cgcg DD nn Pnpn Slsl": "Dark Lavender Blue",
"bb cgcg DD nn pnpn Slsl": "Dark Lavender Blue",
"bb cgcg DD Ee nn Pnpn Slsl": "Dark Lavender Blue",
"bb cgcg DD Ee nn pnpn Slsl": "Dark Lavender Blue",
"bb cgcm DD nn": "Dark Lavender Blue",
"bb cgcm DD Ee nn": "Dark Lavender Blue",
"bb cgcm DD nn Slsl": "Dark Lavender Blue",
"bb cgcm DD nn Pnpn": "Dark Lavender Blue",
"bb cgcm DD nn pnpn": "Dark Lavender Blue",
"bb cgcm DD Ee nn Slsl": "Dark Lavender Blue",
"bb cgcm DD Ee nn Pnpn": "Dark Lavender Blue",
"bb cgcm DD Ee nn pnpn": "Dark Lavender Blue",
"bb cgcm DD Ee nn Pnpn Slsl": "Dark Lavender Blue",
"bb cgcm DD Ee nn pnpn Slsl": "Dark Lavender Blue",
"bb cgcm DD nn Pnpn Slsl": "Dark Lavender Blue",
"bb cgcm DD nn pnpn Slsl": "Dark Lavender Blue",
// bb1 DARK LAVENDER BLUE
"bb1 cgcg DD nn": "Dark Lavender Blue",
"bb1 cgcg DD Ee nn": "Dark Lavender Blue",
"bb1 cgcg DD nn Slsl": "Dark Lavender Blue",
"bb1 cgcg DD nn Pnpn": "Dark Lavender Blue",
"bb1 cgcg DD nn pnpn": "Dark Lavender Blue",
"bb1 cgcg DD Ee nn Slsl": "Dark Lavender Blue",
"bb1 cgcg DD Ee nn Pnpn": "Dark Lavender Blue",
"bb1 cgcg DD Ee nn pnpn": "Dark Lavender Blue",
"bb1 cgcg DD nn Pnpn Slsl": "Dark Lavender Blue",
"bb1 cgcg DD nn pnpn Slsl": "Dark Lavender Blue",
"bb1 cgcg DD Ee nn Pnpn Slsl": "Dark Lavender Blue",
"bb1 cgcg DD Ee nn pnpn Slsl": "Dark Lavender Blue",
"bb1 cgcm DD nn": "Dark Lavender Blue",
"bb1 cgcm DD Ee nn": "Dark Lavender Blue",
"bb1 cgcm DD nn Slsl": "Dark Lavender Blue",
"bb1 cgcm DD nn Pnpn": "Dark Lavender Blue",
"bb1 cgcm DD nn pnpn": "Dark Lavender Blue",
"bb1 cgcm DD Ee nn Slsl": "Dark Lavender Blue",
"bb1 cgcm DD Ee nn Pnpn": "Dark Lavender Blue",
"bb1 cgcm DD Ee nn pnpn": "Dark Lavender Blue",
"bb1 cgcm DD Ee nn Pnpn Slsl": "Dark Lavender Blue",
"bb1 cgcm DD Ee nn pnpn Slsl": "Dark Lavender Blue",
"bb1 cgcm DD nn Pnpn Slsl": "Dark Lavender Blue",
"bb1 cgcm DD nn pnpn Slsl": "Dark Lavender Blue",
// bb DARK LAVENDER BLUE FEMALES
"bb cgcg DD n-": "Dark Lavender Blue",
"bb cgcg DD n- Slsl": "Dark Lavender Blue",
"bb cgcg DD n- Pnpn": "Dark Lavender Blue",
"bb cgcg DD n- pnpn": "Dark Lavender Blue",
"bb cgcg DD n- Pnpn Slsl": "Dark Lavender Blue",
"bb cgcg DD n- pnpn Slsl": "Dark Lavender Blue",
"bb cgcm DD n-": "Dark Lavender Blue",
"bb cgcm DD n- Slsl": "Dark Lavender Blue",
"bb cgcm DD n- Pnpn": "Dark Lavender Blue",
"bb cgcm DD n- pnpn": "Dark Lavender Blue",
"bb cgcm DD n- Pnpn Slsl": "Dark Lavender Blue",
"bb cgcm DD n- pnpn Slsl": "Dark Lavender Blue",
// bb1 DARK LAVENDER BLUE FEMALES
"bb1 cgcg DD n-": "Dark Lavender Blue",
"bb1 cgcg DD n- Slsl": "Dark Lavender Blue",
"bb1 cgcg DD n- Pnpn": "Dark Lavender Blue",
"bb1 cgcg DD n- pnpn": "Dark Lavender Blue",
"bb1 cgcg DD n- Pnpn Slsl": "Dark Lavender Blue",
"bb1 cgcg DD n- pnpn Slsl": "Dark Lavender Blue",
"bb1 cgcm DD n-": "Dark Lavender Blue",
"bb1 cgcm DD n- Slsl": "Dark Lavender Blue",
"bb1 cgcm DD n- Pnpn": "Dark Lavender Blue",
"bb1 cgcm DD n- pnpn": "Dark Lavender Blue",
"bb1 cgcm DD n- Pnpn Slsl": "Dark Lavender Blue",
"bb1 cgcm DD n- pnpn Slsl": "Dark Lavender Blue",
 // bb DARK RED
"bb cgcg nn rr": "Dark Red",
"bb cgcg Ee nn rr": "Dark Red",
"bb cgcg nn rr Slsl": "Dark Red",
"bb cgcg nn Pnpn rr Slsl": "Dark Red",
"bb cgcg nn pnpn rr Slsl": "Dark Red",
"bb cgcg Ee nn rr Slsl": "Dark Red",
"bb cgcg Ee nn Pnpn rr Slsl": "Dark Red",
"bb cgcg Ee nn pnpn rr Slsl": "Dark Red",
"bb cgcm nn rr": "Dark Red",
"bb cgcm Ee nn rr": "Dark Red",
"bb cgcm nn rr Slsl": "Dark Red",
"bb cgcm nn Pnpn rr Slsl": "Dark Red",
"bb cgcm nn pnpn rr Slsl": "Dark Red",
"bb cgcm Ee nn rr Slsl": "Dark Red",
"bb cgcm Ee nn Pnpn rr Slsl": "Dark Red",
"bb cgcm Ee nn pnpn rr Slsl": "Dark Red",
 // bb1 DARK RED
"bb1 cgcg nn rr": "Dark Red",
"bb1 cgcg Ee nn rr": "Dark Red",
"bb1 cgcg nn rr Slsl": "Dark Red",
"bb1 cgcg nn Pnpn rr Slsl": "Dark Red",
"bb1 cgcg nn pnpn rr Slsl": "Dark Red",
"bb1 cgcg Ee nn rr Slsl": "Dark Red",
"bb1 cgcg Ee nn Pnpn rr Slsl": "Dark Red",
"bb1 cgcg Ee nn pnpn rr Slsl": "Dark Red",
"bb1 cgcm nn rr": "Dark Red",
"bb1 cgcm Ee nn rr": "Dark Red",
"bb1 cgcm nn rr Slsl": "Dark Red",
"bb1 cgcm nn Pnpn rr Slsl": "Dark Red",
"bb1 cgcm nn pnpn rr Slsl": "Dark Red",
"bb1 cgcm Ee nn rr Slsl": "Dark Red",
"bb1 cgcm Ee nn Pnpn rr Slsl": "Dark Red",
"bb1 cgcm Ee nn pnpn rr Slsl": "Dark Red",
 // DARK RED FEMALES
"bb1 cgcg n- rr": "Dark Red",
"bb1 cgcg n- rr Slsl": "Dark Red",
"bb1 cgcg n- Pnpn rr Slsl": "Dark Red",
"bb1 cgcg n- pnpn rr Slsl": "Dark Red",
"bb cgcg n- rr": "Dark Red",
"bb cgcg n- rr Slsl": "Dark Red",
"bb cgcg n- Pnpn rr Slsl": "Dark Red",
"bb cgcg n- pnpn rr Slsl": "Dark Red",
"bb cgcm n- rr": "Dark Red",
"bb cgcm n- rr Slsl": "Dark Red",
"bb cgcm n- Pnpn rr Slsl": "Dark Red",
"bb cgcm n- pnpn rr Slsl": "Dark Red",
"bb1 cgcm n- rr": "Dark Red",
"bb1 cgcm n- rr Slsl": "Dark Red",
"bb1 cgcm n- Pnpn rr Slsl": "Dark Red",
"bb1 cgcm n- pnpn rr Slsl": "Dark Red",
// DILUTE BLUE CORNISH PALM
"b1b1 Ccg Dd nn": "Dilute Blue Cornish Palm",
"b1b1 Ccg Dd Ee nn": "Dilute Blue Cornish Palm",
"b1b1 Ccg Dd nn Slsl": "Dilute Blue Cornish Palm",
"b1b1 Ccg Dd Ee nn Slsl": "Dilute Blue Cornish Palm",
"b1b1 Ccg Dd n-": "Dilute Blue Cornish Palm",
"b1b1 Ccg Dd n- Slsl": "Dilute Blue Cornish Palm",
// DILUTE CORNISH PALM
"b1b1 Ccg nn": "Dilute Cornish Palm",
"b1b1 Ccg Ee nn": "Dilute Cornish Palm",
"b1b1 Ccg nn Slsl": "Dilute Cornish Palm",
"b1b1 Ccg Ee nn Slsl": "Dilute Cornish Palm",
"b1b1 Ccg n-": "Dilute Cornish Palm",
"b1b1 Ccg n- Slsl": "Dilute Cornish Palm",
// DILUTE LAVENDER CORNISH PALM
"b1b1 Ccg DD nn": "Dilute Lavender Cornish Palm",
"b1b1 Ccg DD Ee nn": "Dilute Lavender Cornish Palm",
"b1b1 Ccg DD nn Slsl": "Dilute Lavender Cornish Palm",
"b1b1 Ccg DD Ee nn Slsl": "Dilute Lavender Cornish Palm",
"b1b1 Ccg DD n-": "Dilute Lavender Cornish Palm",
"b1b1 Ccg DD n- Slsl": "Dilute Lavender Cornish Palm",
// DILUTE JERSEY BUFF
"BB nn rr": "Dilute Jersey Buff",
"BB Ee nn rr": "Dilute Jersey Buff",
"BB nn rr Slsl": "Dilute Jersey Buff",
"BB nn Pnpn rr Slsl": "Dilute Jersey Buff",
"BB nn pnpn rr Slsl": "Dilute Jersey Buff",
"BB Ee nn rr Slsl": "Dilute Jersey Buff",
"BB Ee nn Pnpn rr Slsl": "Dilute Jersey Buff",
"BB Ccg nn rr": "Dilute Jersey Buff",
"BB Ccg Ee nn rr": "Dilute Jersey Buff",
"BB Ccg nn rr Slsl": "Dilute Jersey Buff",
"BB Ccg nn Pnpn rr Slsl": "Dilute Jersey Buff",
"BB Ccg nn pnpn rr Slsl": "Dilute Jersey Buff",
"BB Ccg Ee nn rr Slsl": "Dilute Jersey Buff",
"BB Ccg Ee nn Pnpn rr Slsl": "Dilute Jersey Buff",
"BB Ccm nn rr": "Dilute Jersey Buff",
"BB Ccm Ee nn rr": "Dilute Jersey Buff",
"BB Ccm nn rr Slsl": "Dilute Jersey Buff",
"BB Ccm nn Pnpn rr Slsl": "Dilute Jersey Buff",
"BB Ccm nn pnpn rr Slsl": "Dilute Jersey Buff",
"BB Ccm Ee nn rr Slsl": "Dilute Jersey Buff",
"BB Ccm Ee nn Pnpn rr Slsl": "Dilute Jersey Buff",
"BB Cc nn rr": "Dilute Jersey Buff",
"BB Cc Ee nn rr": "Dilute Jersey Buff",
"BB Cc nn rr Slsl": "Dilute Jersey Buff",
"BB Cc nn Pnpn rr Slsl": "Dilute Jersey Buff",
"BB Cc nn pnpn rr Slsl": "Dilute Jersey Buff",
"BB Cc Ee nn rr Slsl": "Dilute Jersey Buff",
"BB Cc Ee nn Pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgcg nn rr": "Dilute Jersey Buff",
"BB cgcg Ee nn rr": "Dilute Jersey Buff",
"BB cgcg nn rr Slsl": "Dilute Jersey Buff",
"BB cgcg nn Pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgcg nn pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgcg Ee nn rr Slsl": "Dilute Jersey Buff",
"BB cgcg Ee nn Pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgcm nn rr": "Dilute Jersey Buff",
"BB cgcm Ee nn rr": "Dilute Jersey Buff",
"BB cgcm nn rr Slsl": "Dilute Jersey Buff",
"BB cgcm nn Pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgcm nn pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgcm Ee nn rr Slsl": "Dilute Jersey Buff",
"BB cgcm Ee nn Pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgc nn rr": "Dilute Jersey Buff",
"BB cgc Ee nn rr": "Dilute Jersey Buff",
"BB cgc nn rr Slsl": "Dilute Jersey Buff",
"BB cgc nn Pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgc nn pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgc Ee nn rr Slsl": "Dilute Jersey Buff",
"BB cgc Ee nn Pnpn rr Slsl": "Dilute Jersey Buff",
// BB DILUTE JERSEY BUFF FEMALES
"BB n- rr": "Dilute Jersey Buff",
"BB n- Pnpn rr": "Dilute Jersey Buff",
"BB n- pnpn rr": "Dilute Jersey Buff",
"BB n- rr Slsl": "Dilute Jersey Buff",
"BB n- Pnpn rr Slsl": "Dilute Jersey Buff",
"BB n- pnpn rr Slsl": "Dilute Jersey Buff",
"BB Ccg n- rr": "Dilute Jersey Buff",
"BB Ccg n- Pnpn rr": "Dilute Jersey Buff",
"BB Ccg n- pnpn rr": "Dilute Jersey Buff",
"BB Ccg n- rr Slsl": "Dilute Jersey Buff",
"BB Ccg n- Pnpn rr Slsl": "Dilute Jersey Buff",
"BB Ccg n- pnpn rr Slsl": "Dilute Jersey Buff",
"BB Ccm n- rr": "Dilute Jersey Buff",
"BB Ccm n- Pnpn rr": "Dilute Jersey Buff",
"BB Ccm n- pnpn rr": "Dilute Jersey Buff",
"BB Ccm n- rr Slsl": "Dilute Jersey Buff",
"BB Ccm n- Pnpn rr Slsl": "Dilute Jersey Buff",
"BB Ccm n- pnpn rr Slsl": "Dilute Jersey Buff",
"BB Cc n- rr": "Dilute Jersey Buff",
"BB Cc n- Pnpn rr": "Dilute Jersey Buff",
"BB Cc n- pnpn rr": "Dilute Jersey Buff",
"BB Cc n- rr Slsl": "Dilute Jersey Buff",
"BB Cc n- Pnpn rr Slsl": "Dilute Jersey Buff",
"BB Cc n- pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgcg n- rr": "Dilute Jersey Buff",
"BB cgcg n- Pnpn rr": "Dilute Jersey Buff",
"BB cgcg n- pnpn rr": "Dilute Jersey Buff",
"BB cgcg n- rr Slsl": "Dilute Jersey Buff",
"BB cgcg n- Pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgcg n- pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgcm n- rr": "Dilute Jersey Buff",
"BB cgcm n- Pnpn rr": "Dilute Jersey Buff",
"BB cgcm n- pnpn rr": "Dilute Jersey Buff",
"BB cgcm n- rr Slsl": "Dilute Jersey Buff",
"BB cgcm n- Pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgcm n- pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgc n- rr": "Dilute Jersey Buff",
"BB cgc n- Pnpn rr": "Dilute Jersey Buff",
"BB cgc n- pnpn rr": "Dilute Jersey Buff",
"BB cgc n- rr Slsl": "Dilute Jersey Buff",
"BB cgc n- Pnpn rr Slsl": "Dilute Jersey Buff",
"BB cgc n- pnpn rr Slsl": "Dilute Jersey Buff",

// bb DILUTE RECESSIVE LILAC, all combos done
"bb nn rr slsl": "Dilute Recessive Lilac",
"bb Ee nn rr slsl": "Dilute Recessive Lilac",
"bb nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb nn pnpn rr slsl": "Dilute Recessive Lilac",
"bb Ee nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb Ee nn pnpn rr slsl": "Dilute Recessive Lilac",

// C loci variations
"bb Ccg nn rr slsl": "Dilute Recessive Lilac",
"bb Ccg Ee nn rr slsl": "Dilute Recessive Lilac",
"bb Ccg nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb Ccg nn pnpn rr slsl": "Dilute Recessive Lilac",
"bb Ccg Ee nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb Ccg Ee nn pnpn rr slsl": "Dilute Recessive Lilac",

"bb Ccm nn rr slsl": "Dilute Recessive Lilac",
"bb Ccm Ee nn rr slsl": "Dilute Recessive Lilac",
"bb Ccm nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb Ccm nn pnpn rr slsl": "Dilute Recessive Lilac",
"bb Ccm Ee nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb Ccm Ee nn pnpn rr slsl": "Dilute Recessive Lilac",

"bb Cc nn rr slsl": "Dilute Recessive Lilac",
"bb Cc Ee nn rr slsl": "Dilute Recessive Lilac",
"bb Cc nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb Cc nn pnpn rr slsl": "Dilute Recessive Lilac",
"bb Cc Ee nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb Cc Ee nn pnpn rr slsl": "Dilute Recessive Lilac",

"bb cgcg nn rr slsl": "Dilute Recessive Lilac",
"bb cgcg Ee nn rr slsl": "Dilute Recessive Lilac",
"bb cgcg nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb cgcg nn pnpn rr slsl": "Dilute Recessive Lilac",
"bb cgcg Ee nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb cgcg Ee nn pnpn rr slsl": "Dilute Recessive Lilac",

"bb cgcm nn rr slsl": "Dilute Recessive Lilac",
"bb cgcm Ee nn rr slsl": "Dilute Recessive Lilac",
"bb cgcm nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb cgcm nn pnpn rr slsl": "Dilute Recessive Lilac",
"bb cgcm Ee nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb cgcm Ee nn pnpn rr slsl": "Dilute Recessive Lilac",

"bb cgc nn rr slsl": "Dilute Recessive Lilac",
"bb cgc Ee nn rr slsl": "Dilute Recessive Lilac",
"bb cgc nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb cgc nn pnpn rr slsl": "Dilute Recessive Lilac",
"bb cgc Ee nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb cgc Ee nn pnpn rr slsl": "Dilute Recessive Lilac",

// bb DILUTE RECESSIVE LILAC FEMALES
"bb n- rr slsl": "Dilute Recessive Lilac",
"bb n- Pnpn rr slsl": "Dilute Recessive Lilac",
"bb n- pnpn rr slsl": "Dilute Recessive Lilac",

// C loci variations
"bb Ccg n- rr slsl": "Dilute Recessive Lilac",
"bb Ccg n- Pnpn rr slsl": "Dilute Recessive Lilac",
"bb Ccg n- pnpn rr slsl": "Dilute Recessive Lilac",

"bb Ccm n- rr slsl": "Dilute Recessive Lilac",
"bb Ccm n- Pnpn rr slsl": "Dilute Recessive Lilac",
"bb Ccm n- pnpn rr slsl": "Dilute Recessive Lilac",

"bb Cc n- rr slsl": "Dilute Recessive Lilac",
"bb Cc n- Pnpn rr slsl": "Dilute Recessive Lilac",
"bb Cc n- pnpn rr slsl": "Dilute Recessive Lilac",

"bb cgcg n- rr slsl": "Dilute Recessive Lilac",
"bb cgcg n- Pnpn rr slsl": "Dilute Recessive Lilac",
"bb cgcg n- pnpn rr slsl": "Dilute Recessive Lilac",

"bb cgcm n- rr slsl": "Dilute Recessive Lilac",
"bb cgcm n- Pnpn rr slsl": "Dilute Recessive Lilac",
"bb cgcm n- pnpn rr slsl": "Dilute Recessive Lilac",

"bb cgc n- rr slsl": "Dilute Recessive Lilac",
"bb cgc n- Pnpn rr slsl": "Dilute Recessive Lilac",
"bb cgc n- pnpn rr slsl": "Dilute Recessive Lilac",


// bb1 DILUTE RECESSIVE LILAC,all combos done
"bb1 nn rr slsl": "Dilute Recessive Lilac",
"bb1 Ee nn rr slsl": "Dilute Recessive Lilac",
"bb1 nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 nn pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 Ee nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 Ee nn pnpn rr slsl": "Dilute Recessive Lilac",

// C loci variations
"bb1 Ccg nn rr slsl": "Dilute Recessive Lilac",
"bb1 Ccg Ee nn rr slsl": "Dilute Recessive Lilac",
"bb1 Ccg nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 Ccg nn pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 Ccg Ee nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 Ccg Ee nn pnpn rr slsl": "Dilute Recessive Lilac",

"bb1 Ccm nn rr slsl": "Dilute Recessive Lilac",
"bb1 Ccm Ee nn rr slsl": "Dilute Recessive Lilac",
"bb1 Ccm nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 Ccm nn pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 Ccm Ee nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 Ccm Ee nn pnpn rr slsl": "Dilute Recessive Lilac",

"bb1 Cc nn rr slsl": "Dilute Recessive Lilac",
"bb1 Cc Ee nn rr slsl": "Dilute Recessive Lilac",
"bb1 Cc nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 Cc nn pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 Cc Ee nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 Cc Ee nn pnpn rr slsl": "Dilute Recessive Lilac",

"bb1 cgcg nn rr slsl": "Dilute Recessive Lilac",
"bb1 cgcg Ee nn rr slsl": "Dilute Recessive Lilac",
"bb1 cgcg nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 cgcg nn pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 cgcg Ee nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 cgcg Ee nn pnpn rr slsl": "Dilute Recessive Lilac",

"bb1 cgcm nn rr slsl": "Dilute Recessive Lilac",
"bb1 cgcm Ee nn rr slsl": "Dilute Recessive Lilac",
"bb1 cgcm nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 cgcm nn pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 cgcm Ee nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 cgcm Ee nn pnpn rr slsl": "Dilute Recessive Lilac",

"bb1 cgc nn rr slsl": "Dilute Recessive Lilac",
"bb1 cgc Ee nn rr slsl": "Dilute Recessive Lilac",
"bb1 cgc nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 cgc nn pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 cgc Ee nn Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 cgc Ee nn pnpn rr slsl": "Dilute Recessive Lilac",

// bb1 DILUTE RECESSIVE LILAC FEMALES
"bb1 n- rr slsl": "Dilute Recessive Lilac",
"bb1 n- Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 n- pnpn rr slsl": "Dilute Recessive Lilac",

// C loci variations
"bb1 Ccg n- rr slsl": "Dilute Recessive Lilac",
"bb1 Ccg n- Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 Ccg n- pnpn rr slsl": "Dilute Recessive Lilac",

"bb1 Ccm n- rr slsl": "Dilute Recessive Lilac",
"bb1 Ccm n- Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 Ccm n- pnpn rr slsl": "Dilute Recessive Lilac",

"bb1 Cc n- rr slsl": "Dilute Recessive Lilac",
"bb1 Cc n- Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 Cc n- pnpn rr slsl": "Dilute Recessive Lilac",

"bb1 cgcg n- rr slsl": "Dilute Recessive Lilac",
"bb1 cgcg n- Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 cgcg n- pnpn rr slsl": "Dilute Recessive Lilac",

"bb1 cgcm n- rr slsl": "Dilute Recessive Lilac",
"bb1 cgcm n- Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 cgcm n- pnpn rr slsl": "Dilute Recessive Lilac",

"bb1 cgc n- rr slsl": "Dilute Recessive Lilac",
"bb1 cgc n- Pnpn rr slsl": "Dilute Recessive Lilac",
"bb1 cgc n- pnpn rr slsl": "Dilute Recessive Lilac",





};
